### ISSUE TITLE
Store history.txt in central location

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#100]
Right now, it's possible for history.txt to appear in different parts of the file system depending on when and where you use nu. Would be nice if this history was part of config, or generally lived in a central location.

**Comment by wycats** [comment]
It seems like this could be in config, and default to the system paths we already get from the directories crate.

In order to move it into the config, we'd need to make sure that we refresh the config often enough to avoid it feeling broken.

Possible options:

- update the config after invoking `config`
- update the config before every line in the shell (seems too slow at first glance)
- watch the config using FS watching

**Comment by wycats** [comment]
Making it default to the directories we're already using seems like a good first issue.

**Comment by makarchuk** [comment]
The code in question (save `history.txt` area) seems to be recently updated (https://github.com/nushell/nushell/commit/df7a3a48636fb02e01f2933e9f27020ea898df72), and not it's stored in user home, so should this be closed?

**Comment by jonathandturner** [comment]
@makarchuk - I think we can close this and track related questions separate.
