### ISSUE TITLE
Implicit single-argument closure parameter name

### ISSUE THREAD

**Issue by Jethril** [nushell/nushell#10217]
### Related problem

I find `each` commands a bit verbose. For beginners, I would argue that providing both a parameter name and a variable name is less attractive; especially when you see the simplicity of the `where` statement.
- One solution is to make `each` look like `where`, e.g `ls | each $"($name) of size ($size)"`, but this seems akward to me and much harder to get the value itself without being forced to use it as if its fields were in the current scope.
- Another one would be to simplify single-argument closures, which is what I propose here.

### Describe the solution you'd like

We could imagine the single-arguments closures could be written without the parameter name, like Kotlin does:

```nu
ls | each { $'($it.name) of size ($it.size)' }
```

This makes the statement much easier to write (especially with european keyboards :) ).
Of course, multiple-argument closures would be forced to have explicit names.

### Describe alternatives you've considered

Already explained in "related problem".

### Additional context and details

None.

**Comment by fdncred** [comment]
Maybe this is a not well known, but have you tried this?
```nushell
ls | each { $'($in.name) of size ($in.size)' }
```

**Comment by Jethril** [comment]
It works very well... I didn't know about that, maybe it could be added to the book!

**Comment by mvx-io** [comment]
when we want to write multiple lines of code in a closure, we have to reassign the variable $in to something else like
`let original_value = $in;`
and the pipelines depend on $in anyways.
so I guess the proposed variable $it works perfectly within single line and multi-line closures alike.

(sorry if you don't like my comment since this is my first comment ever on a issue on github)
