### ISSUE TITLE
Back-grounding the Rust Amp editor leaves you with a black screen

### ISSUE THREAD

**Issue by sjmackenzie** [nushell/nushell#1038]
**Describe the bug**
After back-grounding the rust `amp` editor one expects to pop into nushell, instead a black screen appears leaving the user stranded with only a ctl-z as an exit.

**To Reproduce**
1. type `amp` to enter into the `amp` editor
2. press `z` to background `amp`
3. note the black screen

**Expected behavior**
After pressing `z` in `amp` we should enter `nushell`. Then typing `fg` we should pop back into `amp`

**Configuration (please complete the following information):**
 - OS: linux (nixos)

**Comment by thegedge** [comment]
I just tried this with `vim`, and didn't have a similar issue. Is this still a problem with the latest release?

**Comment by arnau** [comment]
Not sure if it's related but with nu 0.21.0 if I open vim and `ctrl-z`, the `nu` process is the one that gets suspended, not vim. If the I do `fg` (I have zsh as a login shell) nu comes back with vim as it was. I would expect vim to get suspended and nu to be kept there.

I'm using MacOS 10.15.7 in case it helps.

**Comment by OvermindDL1** [comment]
Same on linux as with @arnau, hitting Ctrl+z while in vim/nano/whatever suspends the program *and* nushell, going back to my main shell of zsh, then `fg` resumes nushell and the program all.

**Comment by OvermindDL1** [comment]
It's still an issue, `Stale` tag should be removed?

**Comment by dmgolembiowski** [comment]
> I just tried this with `vim`, and didn't have a similar issue. Is this still a problem with the latest release?

It appears we lose some part of the PTY session when running:

```sh
/home/david> ps -l | vim -
```

#### _Demo:_
![Pipes](https://s6.gifyu.com/images/pipe2.gif)

**Comment by arnau** [comment]
When using:

- bash
- nu
- vim

a `Ctrl-z` suspends vim and keeps nu.

When using:

- zsh
- nu
- vim

A `Ctrl-z` suspends nu.

---
OS: MacOS 11.4
nu: 0.33
rustc: 1.53
zsh: 5.8
vim: 8.2
bash: GNU Bash 3.2

**Comment by arnau** [comment]
When using:

- bash
- nu
- vim

a `Ctrl-z` suspends nu. `fg` recovers nu AND vim.

When using:

- zsh
- nu
- vim

A `Ctrl-z` suspends nu. `fg` recovers nu AND vim.


The expected behaviour would be **only** suspending vim.

---
OS: MacOS 11.6
nu: 0.38
rustc: 1.55
zsh: 5.8
vim: 8.2
bash: GNU Bash 3.2

**Comment by kubouch** [comment]
The problem is that Nushell does not support backgrounding. If you run Nushell as a default shell, Ctrl-Z does not work at all. So the fact that it backgrounds both nu and vim makes sense.

The real issue here is adding a support for background tasks to Nushell. Basic blocks for that has been laid out in the upcoming engine-q.

**Comment by arnau** [comment]
Thanks for the explanation @kubouch, this makes much more sense :)
