### ISSUE TITLE
Per-directory history?

### ISSUE THREAD

**Issue by agoodfellow123** [nushell/nushell#10445]
### Related problem

Hello, I'm aware this is not a really conventional way but I like to use my history per directory, which means when I press up I don't want to see everything written in the entirety of my sessions but I just want to see the things I wrote in that directory. Can this be done?

### Describe the solution you'd like

Maybe create a single text file in .config/nushell for every different location nushell been used for dynamically and instead of keeping history for everything keep them per folder.

**Comment by fdncred** [comment]
You may be able to hack something together if you're using the sqlite history format because for each history entry it has a cwd, that you could base such a query off of. You'd probably have to create a script using the `history` command and redefine the up arrow to that command. I'm not sure it would work but you could play around with it.

**Comment by sholderbach** [comment]
Related to https://github.com/nushell/nushell/issues/8883

**Comment by sholderbach** [comment]
Closing this one for now as I don't really see us implementing individual text files while we have the option to use sqlite.
Keeping track of the demand for the per-directory completion and viewing of history in #8883
