### ISSUE TITLE
omitting `-r` when copying a directory with `ucp` gives unhelpful error

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10537]
### Describe the bug

as in the title :yum: 

### How to reproduce

1. create a directory with a file in it
```nushell
mkdir foo
"foo" | save foo/foo.foo
```
2. try to copy the directory without `-r`
```nushell
> ucp foo/ bar
-nu: omitting directory '/whatever/foo'
```

### Expected behavior

i expected something more like the builtin `cp` command :yum:
```nushell
> core cp foo/ bar
Error:   × Directories must be copied using "--recursive"
   ╭─[entry #10:1:1]
 1 │ core cp foo/ bar
   ·         ──┬─
   ·           ╰── resolves to a directory (not copied)
   ╰────
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | main                                     |
| commit_hash        | 8f4ea69c22dc9d2d1b86499330f095a76c8c569d |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-09-27 18:45:31 +02:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | gstat, nu_plugin_explore                 |

**Comment by fdncred** [comment]
@dmatos2012 Do you have time to look into this?

**Comment by dmatos2012** [comment]
Hi, yes maybe sometime during the weekend that I am back. :)

**Comment by dmatos2012** [comment]
The problem is that this is the default GNU behavior, and therefore this error bubbles up from `uutils` with the `omitting directory` error.  

Specifically, the error shows up in [copy_source](https://github.com/uutils/coreutils/blob/main/src/uu/cp/src/cp.rs#L1179-L1203), and since its a `Non Fatal Error`, it sets the error type to `Error::NotAllFilesCopied`, which then does **not** allow us to get the error string to maybe do a

 ```
 if error_string.contains("omitting directory") {return ShellError::GenericError{}...}
 ```
 to remap the error. 

Is it an option to optionally change `Error::NotAllFilesCopied` to `Error::NotAllfilesCopied(err: string)`? Or if someone else has other ideas, feel free to chime in :).

 Maybe @tertsdiepraam has better ideas  as well!

**Comment by tertsdiepraam** [comment]
Tricky! I wonder if there's anything we can do on the `UResult` side of things, because this is gonna be a recurring problem.

There's several possible solutions:
1. What @dmatos2012 suggests: feels a bit hacky, but might be the easiest thing to do.
2. Somehow allow `UResult` to collect multiple errors.
3. Give `cp` an iterator interface like what I've been working on for `rm`, which is simpler here. It would yield `ControlFlow<UResult<()>` or something like it. I think that could work.

**Comment by dmatos2012** [comment]
I was reading over your PR @tertsdiepraam  for [rm](https://github.com/uutils/coreutils/pull/5344), and I like it because as you mention if we have access to the `UResult<()>` then we can decide what to do with it, so it gives us way more flexibility. 

I think option `3` seems like the way to go as that would handle future scenarios where we might need to modify the result.  I would like to give this a try but reading that PR, it does not seem super straightforward for me, so I cant promise anything fast at all, so if anyone else wants to give it a try, feel free. 

What do you think about option 3 @fdncred ?

**Comment by fdncred** [comment]
In my perfect world, number 3 would be the way to go. I like it because it potentially paves a way for us to proceed down this vein with other commands as well and kind of have one solution fits all, if I'm understanding correctly.

I can live with number 1 until we get number 3 off the ground though, because it sounds like it could take some fairly significant effort. I still want to make `ucp` our `cp` in our next release if possible.

**Comment by tertsdiepraam** [comment]
@dmatos2012 would you like to give option 3 a shot?
