### ISSUE TITLE
std: modules are available without the "std" namespace

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10676]
**Describe the bug or feature**
it's quite simple
- users can run either `use std assert` or `use assert` and get the same results
- `use assert` should be impossible imo

**Comment by kubouch** [comment]
Yeah, you can see it in `scope modules` as well.

That's weird because I don't see `assert` being exported from `std` or imported in the stdlib prelude. Not sure where it's coming from...

**Comment by amtoine** [comment]
yeah i don't see it being exported anywhere before the user runs `use` :eyes: 
there is something fishy there...

**Comment by CAD97** [comment]
I believe the culprit is the handling of `export-env`:

[^1]: Potentially relevant: ["We need to evaluate the module in order to run the `export-env` blocks."]()

```nushell
> let baseline = (help modules | sort-by module_id | get name)
> mkdir oops
> "export-env { print 'pwned'; use surprise.nu }" | save oops/mod.nu
> "" | save oops/surprise.nu
> use oops []
pwned
> help modules | sort-by module_id | get name | filter { $in not-in $baseline }
╭───┬──────────╮
│ 0 │ surprise │
│ 1 │ oops     │
╰───┴──────────╯
```

Maybe relevant comment:

https://github.com/nushell/nushell/blob/c925537c48ffa2bd927dd33f30af462483fea657/crates/nu-std/src/lib.rs#L93

Since modules do this but `def` items don't, it's something that differs between how naming is handled for the two.

**Comment by kubouch** [comment]
Interesting, thanks for the investigation! `export-env` shouldn't leak scope, not sure what's going on. But it definitely looks like a bug.

**Comment by NotTheDr01ds** [comment]
I cannot reproduce this on 0.94.2.  Neither:

* `use assert` now fails as expected
* The `export-env` scope leak demonsrated [here](https://github.com/nushell/nushell/issues/10676#issuecomment-1758890942) by @CAD97 is not reproducible and only returns the expected `oops` module, not the unexpected/leaked `surprise`.

Also:

* The other issue that was mentioned by @suimong [here](https://github.com/nushell/nushell/issues/10676#issuecomment-1842472941) has been fixed in the `README.md` by #11244

Recommend closing if someone can corroborate.

**Comment by amtoine** [comment]
@NotTheDr01ds good catch :ok_hand: 

according to the following command, 156232fe082c684ccc3eb036edf38bdd6afa86c7 fixed it, which kinda makes sense :pray: 
```nushell
gm repo bisect --good 0.86.0 --bad 0.94.0 {
    cargo run -- -n -c "use assert"
}
```
