### ISSUE TITLE
`$env` and `$nu` "not found" in `metadata`

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11198]
### Describe the bug

I was trying to determine where `$in`, `$nu`, and `$env` are defined, and tried calling `metadata`.  This threw a `variable_not_found` error.

### How to reproduce

`metadata $env` or `metadata $nu`

### Expected behavior

Give another error or give some metadata like it does for `$in`.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.86.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2023-10-22 21:58:37 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by amtoine** [comment]
imo they should give better errors :+1: 

having a span for `$in` makes sense so that, if you have an incorrect `$in`, you can throw an `error make`.
however, i'd say it does not make as much sense for `$env` and `$nu` because they are like hidden variables that probably don't have a span :thinking: 

having said that and playing with `$in`, i'm not even sure anymore it shouldn't throw an error...
because `$in` is consumed whenever you use it, you need to either
- only use `$in` in `error make`, once
- put it in a variable to reuse it, but then the span is the one of the variable you put `$in` in, not the input of the command

**Comment by KAAtheWiseGit** [comment]
@amtoine the thing about `$in`, is that its span is always `(0, 0)`, meaning its span can't currently used.

**Comment by amtoine** [comment]
> @amtoine the thing about `$in`, is that its span is always `(0, 0)`, meaning its span can't currently used.
>
exactly, this is why i'm starting to think it should probably give an error.
and because anyway you can't both use it for real and get it's span in an error afaik as i say above, right?

**Comment by KAAtheWiseGit** [comment]
@amtoine yeah.  I wanted to make a PR, but I can't find the place those variables are defined.

**Comment by KAAtheWiseGit** [comment]
This was fixed with #11228.
