### ISSUE TITLE
winget package: Reduce scope to "per-user"

### ISSUE THREAD

**Issue by starthal** [nushell/nushell#11240]
### Related problem

I'd like to install Nushell on my work machine, but policy only allows me to install packages at user scope.

In short,
```
winget install --scope user -e --id Nushell.Nushell --version 0.87.1
```
doesn't work ("No applicable installer found"). 
Installing without `--scope user` is disallowed in my environment.

### Describe the solution you'd like

Nushell should be a per-user package if it's feasible.

### Describe alternatives you've considered

I have the Rust toolchain installed so I can always `cargo install nu`. But the package is more convenient and easier to keep up-to-date.

### Additional context and details

I'm aware of #9514 , which implies that the package contains necessary per-machine components, but I can't tell what those are.

I could make this PR if it's feasible and desired.

**Comment by fdncred** [comment]
the per-machine package is the windows terminal fragment that automatically puts nushell in the Windows Terminal drop down. I'm super reluctant to make any changes because changes are so problematic to troubleshoot.

**Comment by starthal** [comment]
@youk thanks for the info.

In that case I'll close this in favor of #13719.

**Comment by fdncred** [comment]
I don't believe we ever did file type association. Not sure what the point is about PATH. It should be Path on Windows. Winget has been a pain to maintain, so much so that we have considered removing it completely.

**Comment by fdncred** [comment]
> I didn't say Nushell did file type association. I said the installer broke the manually created association for .nu because the location of nu.exe has changed.

Oh, ya. Very true That would happen.

> For some reason I didn't have such PITA with other packages.

Those apps probably had people dedicated to Windows and that understand Wix. I understand Windows very well and wrote the winget stuff, the people fixed it in later PRs. I do not understand wix and that's been most of the problems. There aren't a lot of people willing to chip in and help when things go wrong with Wix. There are some kind folks who have helped straighten it out and I think it's in pretty good shape now. I understand how changing paths could break things but since the winget-pkgs repo is such a pain to deal with, we had to change it where permissions wouldn't be a problem.

**Comment by fdncred** [comment]
i've talked with the winget-pkgs ci people a few times and no one has volunteered to create the release.

**Comment by hustcer** [comment]
> i've talked with the winget-pkgs ci people a few times and no one has volunteered to create the release.

If we don't publish nu to winget-pkgs any more will they do it later? Just as `homebrew` does

**Comment by fdncred** [comment]
I can't predict what people will do, unfortunately. I doubt the winget-pkgs people would do it. It would probably have to be a critical application to Windows. Some other 3rd party who uses nushell may do it though.
