### ISSUE TITLE
`to xml` outputs an empty string instead of an error

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11264]
When `to xml` is given an invalid record (i.e. `ls | get 0 | to xml`), it returns an empty string instead of an error.

**Comment by KAAtheWiseGit** [comment]
@amtoine `to xml` uses its own record format with defined fields (sort of like `error make` does).

**Comment by NotLebedev** [comment]
There is a mistake in code [here](https://github.com/nushell/nushell/blob/f2095ed0cce04acd61381df1e76ebf6a7b3918b8/crates/nu-command/src/formats/to/xml.rs#L147) Instead of creating error when a record does not match any type of valid tag `Ok(())` is returned. Also no check is in place to ensure that columns with unknown names are not present. Already fixing this!
