### ISSUE TITLE
Enable system package manager to install modules such as completions in system managed paths

### ISSUE THREAD

**Issue by alerque** [nushell/nushell#11337]
### Question

More and more projects are shipping with Nushell completion support (especially Rust based projects because of the pervasive use of Clap which generates Nushell completions). As a distro packager, where should these files get installed to a system such that Nushell will find and use them?

For examples from other shells, completions for foo would be in files:

```bash
#bash 
/usr/share/bash-completion/completions/foo

#zsh
/usr/share/zsh/site-functions/_foo

#fish
/usr/share/fish/vendor_completions.d/foo.fish

#elvish
/usr/share/elvish/lib/foo.elv
```

Where would a similar file go for Nushell?

**Comment by alerque** [comment]
No I was thinking about the ones provided directly by other projects for their own CLIs. As a random example [watchexec](https://github.com/watchexec/watchexec/blob/main/completions/nu), but there are many more out there. As a packager for `watchexec` where should I be placing that file such that Nushell users will benefit from the completions?

**Comment by amtoine** [comment]
aah ok i see :+1: 

well Nushell will not go get the completions by default, users will have to change their configs for that.
so a package manager could place them anywhere, as long as the location is consistent and user s know where to find them :yum: 

e.g. `watchexec` could put them in `/usr/share/nushell-completions/watchexec/` and tell users to add something like
```nushell
use /usr/share/nushell-completions/watchexec/ *
```
to their configs

**Comment by alerque** [comment]
Is there a system config file that the distro's Nushell package could put this `use ...` statement in my default to load all the completions supplied by the system package manager? For example bash loads `etc/bash.bashrc` and zsh loads `/etc/zsh/zprofile`. Is there an equivalent we can setup for Nushell?

**Comment by amtoine** [comment]
depends on how the completion module / sourceable script is setup, that would likely be a per-project thing to look at :thinking:

**Comment by fdncred** [comment]
Since we need to be cross platform, I think the most logical place to put completions consistently is somewhere specified by `$env.NU_LIB_DIRS`.

**Comment by bew** [comment]
To auto-load completions we could (like many projects) use `$XDG_DATA_DIRS`, cycle through that and load somehow all the completion folders/scripts found under `nushell-completions/` in each xdg data dirs.

Having to add a line for all the tools we use just to get their completion seems overkill, and easy to break once I uninstall some package..

---
Something a bit wonky maybe, could be in `env.nu` find all completion scripts in xdg data dirs, and generate a nu file to load them, and that file would be loaded in `config.nu`..
Not sure if there's a better way

**Comment by alerque** [comment]
Using `$env.NU_LIB_DIRS` as it exists now won't work for this because it only has a $HOME based path. With the exception of Nix, no distro package manager I know of can or is allowed to install anything in a *user's* home directory. The issue here is the *system* package manager wanting to install completions. 

Expanding this to include `$XDG_DATA_DIRS` such that a global system initialization file could be run and/or a common directory scanned for possible completion modules would solve this.

**Comment by alerque** [comment]
It appears the answer to my question is "you can't", hence this is now a feature request not a question.

**Comment by fdncred** [comment]
We've been down the `XDG_blah` rabbit hole before and I'm not anxious to traverse it again. Suffice it to say that some core-team members are not fans of the XDG spec (but some are), so, I'm guessing we probably won't be supporting any XDG stuff. The paramount thing here is we have to be cross platform and saying that Windows and MacOS users can just create XDG_SOME_THING isn't a workable solution.

**Comment by IanManske** [comment]
Would a hard-coded system level config work? E.g., `/etc/nushell/` for *nix and `%PROGRAMDATA%\nushell\` for Windows? Completions could be loaded there, and it could also set `XDG` variables.

**Comment by alerque** [comment]
Hard coded is fine, but properly it should be something that is configurable at *build* time. It doesn't have to be run-time configurable so the final value can just be baked in, but some while many/most systems could deal with a hard coded `/etc/nushell/rc` or whatever, there are some (e.g. Nix) that take radically different approaches to system paths. Worst case a single hard coded path is something distros can patch, but making it a build time option is generally appreciated. This is what the `--prefix` and plethora of `--sysconfdir`, `--datadir`, and similar options serve in GNU Autotools builds for example.

**Comment by KAAtheWiseGit** [comment]
To chip in with my opinion, support for external completions is super important for a shell.  Many Linux users, myself included, install most packages using the distro's package manager.  In my case it's `apk` of Alpine Linux.  It automatically installs `fish`/`zsh`/`bash` completions when I install my packages, and those work out of the box, no config changes needed.

From what I saw, "just works" quality of `fish` is one most common ones, when people justify choosing it over a POSIX-compatible shell.  And I think Nushell should provide a similar experience to have mass appeal similar to that of `fish`.

**Comment by jcgruenhage** [comment]
To weigh in as another package maintainer: Hi, I've been maintaining the nushell package and a bunch of rust utils that *could* provide nushell completions for a while now. To be a bit more specific, I've been shipping `nu` for Void Linux since 0.6.1 / 2019. For a lot of the rust tools I ship, I go out of my way to make sure I ship completions generated by clap, in some cases even patching the tools so that they can make use of this.

I'm in the middle of another attempt to switch to `nu` as a daily driver at the moment, and I'm quite happy with it *except* for this bit. Not having completions is kind-of a deal-breaker for me. I can't manually maintain a config that contains all the completions for all the tools I use. I install them using my package manager, and they should work out of the box.

As for how to proceed here: I'd suggest going with what @alerque suggested: Having a hard coded path, with an option to override it during build time or even run time with a special env var or something like that. I'd say that out of the examples brought up so far, the path chosen by `fish` is the most reasonable one, and going for `/usr/share/nushell/vendor_completions.d/foo.nu` is going to be a good thing. Making `nu` source all files in that directory can't be too hard, so if people are alright with that direction, I'd like to take a stab at this and come up with a PR in the coming days.

**Comment by jcgruenhage** [comment]
> Also in the example you gave what would the actual filename be? And could the wildcard be used to handle multiple / all available files not just one specific one?

It seems that this can't be done in `nu` scripts btw, otherwise I could look over this for now and would just ship the completions in a place I deem fit for now:

```

nushell on  main is 📦 v0.88.2 via 🦀 v1.72.1 took 59s 
❯ ls /usr/share/nushell/vendor_completions.d/ | each {|file| source $file}
Error:   × Error: nu::shell::not_a_constant
  │ 
  │   × Not a constant.
  │    ╭─[entry #48:1:1]
  │  1 │ ls /usr/share/nushell/vendor_completions.d/ | each {|file| source $file}
  │    ·                                                                   ──┬──
  │    ·                                                                     ╰── Value is not a parse-time constant
  │    ╰────
  │   help: Only a subset of expressions are allowed constants during parsing. Try using the 'const' command or typing the value literally.
  │ 
   ╭─[entry #48:1:1]
 1 │ ls /usr/share/nushell/vendor_completions.d/ | each {|file| source $file}
   ·                                                                   ──┬──
   ·                                                                     ╰── Encountered error during parse-time evaluation
   ╰────


nushell on  main is 📦 v0.88.2 via 🦀 v1.72.1 
❯ ls /usr/share/nushell/vendor_completions.d/ | each {|file| use $file *}
Error:   × Error: nu::shell::not_a_constant
  │ 
  │   × Not a constant.
  │    ╭─[entry #49:1:1]
  │  1 │ ls /usr/share/nushell/vendor_completions.d/ | each {|file| use $file *}
  │    ·                                                                ──┬──
  │    ·                                                                  ╰── Value is not a parse-time constant
  │    ╰────
  │   help: Only a subset of expressions are allowed constants during parsing. Try using the 'const' command or typing the value literally.
  │ 
   ╭─[entry #49:1:1]
 1 │ ls /usr/share/nushell/vendor_completions.d/ | each {|file| use $file *}
   ·                                                                ───┬───
   ·                                                                   ╰── Encountered error during parse-time evaluation
   ╰────


nushell on  main is 📦 v0.88.2 via 🦀 v1.72.1 
❯ ls /usr/share/nushell/vendor_completions.d/ | each {|file| overlay use $file}
Error:   × Error: nu::shell::not_a_constant
  │ 
  │   × Not a constant.
  │    ╭─[entry #50:1:1]
  │  1 │ ls /usr/share/nushell/vendor_completions.d/ | each {|file| overlay use $file}
  │    ·                                                                        ──┬──
  │    ·                                                                          ╰── Value is not a parse-time constant
  │    ╰────
  │   help: Only a subset of expressions are allowed constants during parsing. Try using the 'const' command or typing the value literally.
  │ 
   ╭─[entry #50:1:1]
 1 │ ls /usr/share/nushell/vendor_completions.d/ | each {|file| overlay use $file}
   ·                                                            ────────┬────────
   ·                                                                    ╰── Encountered error during parse-time evaluation
   ╰────
   ```
   
   Any reason that `source` for example doesn't work with variables inside a closure?

**Comment by fdncred** [comment]
The diff seems reasonable except that it's not cross platform.

**Comment by jcgruenhage** [comment]
Any suggestions where completions should live on Windows? I think for macOS and Linux, the patch is fine as-is, and without a proper place for these to live on Windows, just not exposing that feature is also cross platform. I'd say it wouldn't be cross platform if it just tried to use the unix path on Windows.

**Comment by alerque** [comment]
Why would nushell need write permissions? For the Linux senario myself and @jcgruenhage have suggest the system package manager is responsible for placing things there and nushell would only need *read* access. In fact in most Linux cases it would explicitly *not* have write access. I don't understand why the equivalent directory would need to be writable on the Windows side.

**Comment by fdncred** [comment]
It doesn't have to have permissions but if we wanted to build in some that get extracted and placed at runtime, it would need permission.

**Comment by alerque** [comment]
Two things:

* If you wanted to build some it, they should probably come *with* and be installed with whatever installs nushell.
* Runtime is a strange time to place **system** files. That would be more appropriate perhaps for a **user** location of some sort (personally I do think there should be a system directory and a user directory that is scanned). Unless running with root/SysAdmin permissions though the runtime shouldn't be writing to a system location.

**Comment by jcgruenhage** [comment]
> IMO, excluding windows for things that are supported on Windows is not in keeping with the nushell cross-platform principle.

I said that if there are equivalent paths for Windows, that I'd be happy to include them, but that I'm not aware of any such paths and that I'm open to suggestions here.

> If we don't want a folder based off of a user directory, then we'd want to use a [known folder location](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid) that nushell will have permission to write to. I'm not sure which one it should be off the top of my head.

This is about system package managers, and nushell should *not* have write access to that directory. It might make sense to *also* have such a folder additionally, something in the user directory, but the system path should just be consumed by nushell.

Looking at the known folder thing, the only thing in there that looks like a fit to me would be FOLDERID_ProgramData. I don't know anything about Windows though, so I'd appreciate it if I could just contribute my patch and someone with more knowledge on the matter could add proper Windows support to it later.

**Comment by jcgruenhage** [comment]
Really not a man of my word when it comes to this: I've opened a PR that contains *some* amount of windows compatibility as well, just using `C:\ProgramData\nushell\vendor_completions.d`, and while I was at changing my patch, I also added support for local user vendor completions in `AppData/Roaming` / `~/.local/share`. I should really get on with something else now though, I really don't have more time to spend on this...

**Comment by kubouch** [comment]
There is nothing special in Nushell about completions, they're just definitions that you can add to modules like any other definitions. There is no need to special-case completions. So, the question is how to allow third-party tools to add Nushell modules _without the user having to touch anything_. We currently do not support it, but here is my idea:

* We'd have `$env.NU_AUTOLOAD_DIRS`, similar to `$env.NU_LIB_DIRS`.
* We'd have `autoload` command that loads all modules in directories specified by `$env.NU_AUTOLOAD_DIRS`
* We'd add `autoload` to the default config file
* Package maintainers would set `$env.NU_AUTOLOAD_DIRS` to whatever path they use to distribute completions. This assumes that package maintainers can set some system-wide environment variables on package installations, not sure if that's the case.

The `NU_AUTOLOAD_DIRS` could have a similar syntax as `PATH`: a list of paths separated by `char newline` converted by default into a list using `$env.ENV_CONVERSIONS` (see `env.nu` for an example). `autoload` would be equivalent to going through directories in `$env.NU_AUTOLOAD_DIRS` and calling `use` on every module inside each directory (module = .nu file or a directory containing a mod.nu file).

The advantage of this method is that it's cross-platform, does not hard-code any paths into Nushell, and lets the user provide their own autoload-directories for autoloading some extra completions or whatever. The `autoload` is there to avoid restarting Nushell when you install new completions (you just call `autoload` in the REPL), and you can comment it out from the config to avoid autoloading anything if you don't want it (e.g., security concerns).

**Comment by KAAtheWiseGit** [comment]
@kubouch I like this approach, it is very elegant and allows for easy packaging of programs written in Nushell (unlike for most other interpreted programming languages, where it's usually quite a struggle). 

As for the compile time patching, it's a common practice.  Alpine Linux version of Nushell, for example, contains [this patch](https://git.alpinelinux.org/aports/tree/community/nushell/system-deps.patch) fixing some `musl` issues, I think.

For both issues, the most important aspect is clear documentation, which is discoverable by all of the maintainers across distributions.  Something like a `DISTRIBUTION.md` file linked to from the README (Hare, for example, has [this](https://harelang.org/distributions/).

**Comment by jcgruenhage** [comment]
@kubouch That sounds like a very good compromise, I like it!

**Comment by alerque** [comment]
> As pointed out by @jcgruenhage, apparently it is difficult to ensure that Nushell is spawned with some environment variable. (Note that Nushell inherits the environment from whatever process spawned it.)

This is correct, it is very difficult to configure something like a shell with a runtime env variable because end uses simply don't have control over this is all cases. Also the thing we're trying to configure here is something that should work out of the box and shouldn't require the end user to jump through hoops to get something setup.

> To me, compile-time configuration sounds hacky, as I explained in the PR, but I've never maintained a Linux package myself. Is that a common thing to do?

Yes, absolutely common, even **the norm**. The vast majority of projects out there work this way, and most build systems have built in accommodation for this (Autotools, CMake, Meson, Ninja, Python setup, Python PEP517 installers, etc.). This doesn't just go for Linux either, this is one of the primary ways cross platform projects are setup to have one code base that can be built and run on many platforms using those platforms "norms". E.g. if you install bash on Linux vs. BSD vs. macOS vs. Windows the default system RC file location will be different and where it looks for user RC files (e.g. what the home directory pattern) will be different, but it all cases it will be appropriate for the system. This is typically port of compile-time configuration (i.e. build time).

The location of a directory of system stuff to autoload **should** be a build time configuration.

**Comment by kubouch** [comment]
OK, thanks, TIL. The `$nu.vendor` record could be used for build-time package modifications in general to encapsulate them into one place, if there ever is a need to add something else apart from the autoload path.

We'll need to discuss with the rest of the core team to make sure we're all on board. The `autoload` command would also need to be a parser keyword, which is a language modification. There might be a better way to do this, e.g., add a flag to `use`.

The NU_AUTOLOAD_DIRS might have to be `const` instead of `$env` to make it in line with `NU_LIB_DIRS` (we're kind of half-way moved away from `$env.NU_LIB_DIRS` to `const NU_LIB_DIRS`). This would mean that you wouldn't be able to pass it as an env var, so the built-time configurable `$nu.vendor...` constant would be better in this sense.

There are design details like this that still need to be sorted out.

**Comment by jcgruenhage** [comment]
@kubouch Just to make sure: I'll be closing my PR then? In any upcoming PR regarding this, I'd like to be tagged for review, considering I've spent quite some time on the different areas around that problem and want to make sure the acquired knowledge wasn't for nothing.

**Comment by kubouch** [comment]
Yes, you can close it, and whoever decides to implement it (once we greenlight it), please tag @jcgruenhage to ensure the approach works for package maintainers.

**Comment by jcgruenhage** [comment]
Considering this might still take a while, I'd have two questions:
 - Would you be okay with distros shipping the patch I provided for the time being, until a proper solution is upstream?
 - If so, would you already be willing to commit to a path that distro maintainers can put the modules for autoloading once a proper solution is upstream? `/usr/share/nushell/autoload` on linux/macos? Because then we could already start shipping completions to improve the user experience of those who want to use nushell as a shell daily driver right now.
 
Unrelated to those questions: I'll assume that there is no ETA on this and no one is working on it yet or in the near future, right?

**Comment by KAAtheWiseGit** [comment]
I think that if Void does that, I'll reach out to Alpine's Nushell maintainer and also ask to include the patch

**Comment by fdncred** [comment]
Windows has to be included in any solution here. I'm fine with `%PROGRAMDATA%\nushell\autoload` assuming Windows users have write permissions there as a system level folder unrelated to users. Otherwise, either `~\AppData\Roaming\nushell\autoload` or `~\AppData\Local\nushell\autoload` would suffice.

**Comment by KAAtheWiseGit** [comment]
Unsure how distribution on Windows work, but a lot of tools have fallback paths for both system-wide and user-wide installs.  So picking both might be an option

**Comment by jcgruenhage** [comment]
@KAAtheWiseGit there's package managers for windows that work in similar ways to how linux distributions work, chocolatey and winget for example, so it mostly maps as is, with the difference that the paths they install to are very different.

@fdncred my patch was already including windows stuff, so that'd also be in there.

**Comment by alerque** [comment]
@jcgruenhage If Void and potentially Alpine are going to be in on shipping this even before it lands in a release then I can probably make it happen in Arch Linux too.

And upstream maintainers ... please just move forward with this because they more downstream monkey business we have to do to make things work out of the box for our users the more chance their is of things not working "as expected" when each distro handles it a little differently.

**Comment by jcgruenhage** [comment]
I want to ship this in Void, but that doesn't mean it'll happen. That depends on what upstream says here and the Void committers say, just to make sure this isn't misunderstood. I can't make that decision myself, I can only do the work and open PRs there.

**Comment by jcgruenhage** [comment]
@kubouch that's really helpful, because that is a scope I'm willing and able to contribute myself. Will update my patchset with that feedback and open a new PR.

**Comment by jcgruenhage** [comment]
Before reopening my PR, I've got a few questions:
 - `parse_module_file_or_dir` requires a bunch of args I don't have while I'm in `read_config_file`. Any suggestions where I should do the autoloading instead to ensure I actually do have the required options to use `parse_module_file_or_dir`? Alternatively, any suggestions on what method I could use except for `parse_module_file_or_dir`?
 - Any pointers to how env var access should look like? With the env conversion magic happening like in https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_env.nu#L77-L86, how should I load the env var properly after it might've been modified by the config or something like that? Just using `std::env::var` is probably not going to cut it, right?

**Comment by seomwan** [comment]
Where does external completers like `carapace` come in?

I've been using `carapace` as suggested by the config and nushell docs. In some ways this is better. The experience is that I have to configure `carapace` once (albeit maybe a tiny bit more work) instead of each utility every time. *Most* of the time. Also it's more performant in some cases due to lazy loading and caching. Also sometimes more features than usually provided by completions, via the carapace macros.

The only problem arises when there aren't completions, and no relevant bridges are installed. Haven't quite figured out bridges tbh.

My point being, I've found it useful enough to maybe include in a completions workflow, and it should be complementary to this. Or possibly even replace this as an out of box default, although, I don't know the right balance to strike here.
In any case, I do agree completions should be an out of box experience

**Comment by kubouch** [comment]
We just added autoloading functionality https://github.com/nushell/nushell/pull/13217. We'll see how it works, and we can still adjust the design if necessary, this is just the first implementation.

**Comment by jcgruenhage** [comment]
I think this can now be considered done, so we could close this? Do you agree @alerque?

**Comment by boomshroom** [comment]
I think the main benefit of having distinct autoload and completion paths is that the latter would only need to be read on-demand. Nushell could start-up faster by delaying the loading of completion files until the user actually tries to complete the programs they're for. This is important when you have hundreds of packages with completions generated at install-time.

Since the autoload directory is `$XDG_DATA_DIRS/nushell/vendor/autoload`, the natural place to put lazily loaded completions would be `$XDG_DATA_DIRS/nushell/vendor/completions`. Files under `autoload` would always load when the shell initialises (if it loads any files), while files under `completions` would only load on-demand as completions are requested.

This wouldn't be as important if nushell is particularly fast at parsing the files, but it could still be beneficial on slower filesystems where it would take a significant amount of time even just to read each file from disk. Reading the directories entries and caching the path to each file should still be fairly cheap though. The caveat to this would be that each file would need the same name as the program it's providing completions for, since otherwise the shell wouldn't know which file to load.
