### ISSUE TITLE
Support for disabling automatic escaping in `to xml`

### ISSUE THREAD

**Issue by jameschensmith** [nushell/nushell#11525]
### Related problem

As a C# developer, I deal with a fair share of XML files. There is quite a bit of single quote usage in the attributes of these XML files ([example](https://github.com/dotnet/sdk/blob/f25fbc3368f4c9d3320875c2722abe3e86256800/Directory.Build.targets)). When making changes to these files with Nushell, these single quotes get escaped.

### Describe the solution you'd like

Because escaping single quotes in this case is optional (you only really need it if your attribute value is surrounded in single quotes instead of double quotes), it would be nice if `to xml` had a flag which could disable automatic escaping. This would give me greater control of these escape usage instances.

A quick-and-dirty solution to this might be to not escape single quotes in attributes in `to xml`. Because `to xml` outputs attribute values surrounded in double quotes, this would always be safe.

### Describe alternatives you've considered

While I don't like this alternative, because I was certain that the single quotes were only in the attributes I ended up doing a quick find-and-replace:
```sh
sed -i "s/&apos;/'/g" Directory.Build.targets
```

**Comment by NotLebedev** [comment]
It seems like this is possible to do, but `quick_xml` does not accommodate this very well.
When converting [from string to attribute](https://docs.rs/quick-xml/latest/quick_xml/events/attributes/struct.Attribute.html#method.from-2) everything is escaped and there is no apparent way to escape less. However when converting [from raw bytes](https://docs.rs/quick-xml/latest/quick_xml/events/attributes/struct.Attribute.html#method.from) no conversion is done. This way it is possible to do escaping manually. Unfortunately [escape::partial_escape](https://docs.rs/quick-xml/latest/quick_xml/escape/fn.partial_escape.html) provided by the library does not help, because it is used for text, not attributes and does not escape `"` (double quotation marks). This means that also escaping needs to be done by hand.

It seems like quick_xml will [add better control for escaping in future update](https://github.com/tafia/quick-xml/pull/685) but control over escaping in attributes is currently unimplemented, it seems.

I will create a PR with changes I described in first paragraph and put them under some flag and also raise an issue in quick_xml to add better control over escaping in attributes later.

**Comment by fdncred** [comment]
closed by https://github.com/nushell/nushell/pull/11536
