### ISSUE TITLE
Allow potentially non-functional options to ease nu learning curve

### ISSUE THREAD

**Issue by djc** [nushell/nushell#1155]
**Is your feature request related to a problem? Please describe.**
In today's shells (bash or zsh for me), I almost always type `ls -l` to get a file listing. nu doesn't accept the `-l` argument (because it outputs the equivalent information by default), but instead errors out saying it doesn't understand the `-l` shorthand option.

**Describe the solution you'd like**
I'd like to be able to use nu without immediately retraining all of my muscle memory. Realistically, I might have other machines that don't have nu (yet) or don't want to retrain my habits because I've not committed to using nu yet, but still feel my way around.

**Describe alternatives you've considered**
One option would be silently accepting `-l`, swallowing it without changing anything else. This is not a great option because it means the `-l` option will be forever prevented from being used for something useful. Another option would be allowing users to configure these types of non-functional options so that different users can retrain at their own speed. Potentially, you might want to print a warning before or after the actual command output to help the user retrain in a more gradual way.

**Comment by djc** [comment]
Any progress on a design for this? All the Twitter activity has reminded me that I'd like to start using nu more, but this is still a blocker for me? I'm happy to do some implementation work if there is an agreed upon design.

**Comment by jonathandturner** [comment]
@djc - There are a few steps ahead of this one. Allowing short-hand commands is still a work-in-progress.

I doubt we'd add flags that don't do anything.  What we might do here is to allow you to create your own flags and extend commands, but we'd need to design how that'd work.

**Comment by klausi** [comment]
I use `ls -l` quite a lot to check if a file is executable. The `-l` option does not exist in the nu version, so for my purposes I would be completely happy to alias `ls -l` to `ls -f` which just gives you the full output.

I think this issue is a bit more general, so maybe I should open a new one for the concrete `-l` option alias suggestion? Or do you want to do it here?

Hm, I also use `ls -` to check for symlink targets, so maybe aliasing it to `--full` and `--with-symlink-targets`?

**Comment by thegedge** [comment]
I really feel like aliases and proper scripting support will get us a lot of the way here. Here's what I can imagine, once we have full scripting support:

- Having a script `ls` that overrides the builtin.
- Script defines a switch `--long` = `-l`
- Script consumes that to set a `--full` flag on the builtin `ls`

Voila! Once we have that, we can build up a "transition" profile. Not sure if this would be part of nushell itself, or something you'd install from another repo, but it would have a lot of these scripts that make a lot of the builtin commands have flags and switches similar to the posix utilities. When one is ready to transition, simply check out the script to understand the mapping and simply remove the script to start training yourself, one command at a time.

Full scripting support is still a little ways out, so maybe overriding signatures in config would be something that could be tackled sooner.

**Comment by djc** [comment]
Some kind of aliasing configuration makes sense to me.

**Comment by thegedge** [comment]
We have aliases now (not quite documented). I'm going to close this issue, but if you think there's still something to do here, do open a new issue with the specifics 🙂

```
❯ alias lsl [path] { ls --full $path }
❯ lsl
...
❯ lsl crates/nu-cli
...
```

One thing to note about nushell aliases is that, unlike other shells, arguments have to be explicitly called out, rather than being a shorthand that you can add arbitrary things to. For example, this won't work:

```
❯ lsl --all --short-names crates/nu-cli
```

That's a separate issue though 🙂

**Comment by djc** [comment]
Thanks! Currently trying to figure out https://github.com/starship/starship/issues/1133.
