### ISSUE TITLE
shift + navigation should highlight

### ISSUE THREAD

**Issue by steveklabnik** [nushell/nushell#1171]
**Is your feature request related to a problem? Please describe.**

Sort of, this is more of a "I'm used to this behavior from other shells."

I was psyched when I saw control left / control right move by words in nu 0.8. I tend to use this in cooperation with shift in order to higlight and delete things, but holding shift does not do this. In fact, it doesn't with arrow keys either.

**Describe the solution you'd like**

It would be cool if I could hold shift to select a portion of the command.

**Describe alternatives you've considered**

Maybe this isn't the way nu wants to be used, or there's some better way of doing this I'm not used to.

**Comment by Tastaturtaste** [comment]
This still doesn't work and I would also very much like to be able to select what I want from the current command using shift + arrow left/right. What would be keywords to look out for in the codebase for selecting text from commands in that way? I would maybe try to implement this myself, if someone can point me where to look.

**Comment by Tastaturtaste** [comment]
Thanks for the lightning-fast response. 
I have my editor set to vscode, which I prefer for most workloads but is certainly overkill to just copy some command.
While looking at the issues of reedline I found [this](https://github.com/nushell/reedline/issues/380#issue-1193597871), which seems to be exactly what I had in mind. Sadly nobody has started work on this feature until now.

**Comment by fdncred** [comment]
@Tastaturtaste it would be great if someone added this funcitonality to reedline. I saw [this recently](https://github.com/AmrDeveloper/Lineeditor), that was inspired by reedline, that support this type of selection. Maybe you can learn something from it and port it over to reedline?

**Comment by Tastaturtaste** [comment]
I started to work on a solution for this problem, see draft PR https://github.com/nushell/reedline/pull/689 and issue https://github.com/nushell/reedline/issues/380. As mentioned in my comment in the issue, I would also like for nushell to enable feature `system_clipboard` from `reedline`. Otherwise integration with all other tools is more difficult and the behaviour is surprising (at least for me). Maybe a distinction is necessary between edit commands that work only with a local buffer and cut/copy/paste commands that always use the system clipboard.

**Comment by fdncred** [comment]
I'm not sure why we'd be opposed to adding the system_clipboard feature.
