### ISSUE TITLE
Stepped ranges incorrectly calculate `contains`

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11769]
### Describe the bug

A range with gaps will report any value between its ends as being inside it, even if it has steps.

### How to reproduce

```Nushell
~> 2 in 1..10..100
true
```

### Expected behavior

The above returning false.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.89.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2024-01-13 03:02:49 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

I encountered it on the `HEAD`, though.

**Comment by IanManske** [comment]
Yep, I'm not surprised lol.

I think we can keep this open, but some related issues:
- #11521
- #11086 (thanks for starting that discussion!)

**Comment by KAAtheWiseGit** [comment]
@IanManske what a coincidence, I was just going through my old issues and closing outdated ones, and as I was in #11086 Your message came!

I feel like the problem is that `Range` has its fields public, so a number of different commands have to do the same logic each time, in subtly different ways.

```Rust
/* drop nth */
                // check for equality to isize::MAX because for some reason,
                // the parser returns isize::MAX when we provide a range without upper bound (e.g., 5.. )
                let mut to = to as usize;
                let from = from as usize;
```

**Comment by IanManske** [comment]
Yeah, that is for sure one reason. In many commands, argument ranges are used to signify a slice range. Places like `nu_cmd_base::util::process_range` assume this and ignore the step value. I'm sure other places handle ranges differently like you showed. So, I think the other reason is simply that people forget ranges can have a step value.

It would be really nice if `Range` was something like:
```rust
enum Range {
    Int(Bound<i64>, Bound<i64>)
    Float(Bound<f64>, Bound<f64>)
}
```

Currently, the `to`, `from`, and `step` fields have type `Value` which I think discourages people from handling all cases fully.

**Comment by KAAtheWiseGit** [comment]
@IanManske I could try coding up something like that.  Along with `step: Option<T>`, maybe.

One question is mixed types.  Technically something like `9_223_372_036_854_775_807..10000000000000000000.0` is valid.  So does it mean integers need to be converted to floats?

**Comment by KAAtheWiseGit** [comment]
```Nushell
~> nan..null..
Error: nu::shell::type_mismatch

  × Type mismatch during operation.
   ╭─[entry #71:1:1]
 1 │ nan..null..
   · ─────┬─────┬┬
   ·      │     │╰── type mismatch for operator
   ·      │     ╰── float
   ·      ╰── int
   ╰────
```

**Comment by IanManske** [comment]
@KAAtheWiseGit if you want to, then yeah thanks!

I hastily rebased some [old code](https://github.com/IanManske/nushell/tree/number-range) in case you find it helpful. Ignore that I made `start` type `T` instead of `Bound<T>` or `Option<T>` for some reason.

> Along with step: Option\<T\>, maybe.

Probably for now to keep the old behavior.

> So does it mean integers need to be converted to floats?

I think so. For example, in a Range iterator, the integer would need to be converted anyways to do float addition.

**Comment by KAAtheWiseGit** [comment]
@IanManske thanks!  I'll take a look and give it a try

**Comment by KAAtheWiseGit** [comment]
I have a bold proposal: what if we banned float ranges?

I'm looking at #11773, #11774, #11776, #11777, #11778 and thinking that maybe trying to fix all of the edge cases is more trouble than it's worth?

If someone needs to manipulate float sequences, `seq` can create a fine pipeline stream.  And the shorthand notation itself is primarily used for filter commands and iterations, where floats don't make semantic sense anyways.

**Comment by IanManske** [comment]
Yeah, I had considered this as well. I'm currently on the fence about it.

On one hand, the issues you linked shouldn't be too hard to solve. For example, the old code I linked I think fixes of all them? For infinite streams due to precision issues (e.g., a small step value), ~~this could be detected in the float range iterator when `prev_iter_val == this_iter_val` and then maybe throw an error?~~ Looks like I instead made it so that the iterator keeps track of the current iteration number, `i`, and uses the formula `start + i * step` to avoid accumulating error.

But I generally agree that float ranges usually don't make sense and can be covered by the `seq` command. One place that might make sense is for `random float` which takes a float range to generate a number within it. But, this could be replaced with two separate args like how `seq` currently works. (Maybe `inf` or even `null` could be used to signify an unbounded end?).
