### ISSUE TITLE
Request: from-md-table to convert markdown table to nushell table

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#1183]
**Is your feature request related to a problem? Please describe.**
I want to convert the following markdown codes into a table:

```markdown
| no. | name        | email                    |
|-----|-------------|--------------------------|
| 1   | John Doe    | john-doe@gmail.com       |
| 2   | Peter Smith | petersmith22@outlook.com |
| 3   | Julia Jones | jjones778@gmail.com      |
```

```markdown
 no. | name        | email                    
-----|-------------|--------------------------
 1   | John Doe    | john-doe@gmail.com       
 2   | Peter Smith | petersmith22@outlook.com 
 3   | Julia Jones | jjones778@gmail.com      
```

**Describe the solution you'd like**
Provide a `from-*` command.

**Describe alternatives you've considered**

**Additional context**

**Comment by notryanb** [comment]
Awesome! Having `to-md` or some similar named command for outputting a markdown table would also be really helpful. Writing markdown tables out by hand is tedious.

**Comment by KSXGitHub** [comment]
If possible, I would prefer a `from-text-table` that can parse not only markdown table but also other formats of text table as well, such as the following:

```
+-----+-------------+--------------------------+
| no. | name        | email                    |
+-----+-------------+--------------------------+
| 1   | John Doe    | john-doe@gmail.com       |
+-----+-------------+--------------------------+
| 2   | Peter Smith | petersmith22@outlook.com |
+-----+-------------+--------------------------+
| 3   | Julia Jones | jjones778@gmail.com      |
+-----+-------------+--------------------------+
```

```
╔═════╦═════════════╦══════════════════════════╗
║ no. ║ name        ║ email                    ║
╠═════╬═════════════╬══════════════════════════╣
║ 1   ║ John Doe    ║ john-doe@gmail.com       ║
╠═════╬═════════════╬══════════════════════════╣
║ 2   ║ Peter Smith ║ petersmith22@outlook.com ║
╠═════╬═════════════╬══════════════════════════╣
║ 3   ║ Julia Jones ║ jjones778@gmail.com      ║
╚═════╩═════════════╩══════════════════════════╝
```

etc.

**Comment by thegedge** [comment]
I'm going to close this as a duplicate of https://github.com/nushell/nushell/issues/1270, since implementing a full `from-md` would mean that you could simply pipe in _just_ the table and get the same result.

**Comment by waldyrious** [comment]
@thegedge I think it would be desirable to keep this as a separate issue, since full-fledged `from-md` is a much more complex endeavor that may take a while to implement (and indeed #1270 has been closed as stale), whereas markdown tables are much more straightforward to parse.

Besides, rather than a mere `from-md-table` command, I think a more general `from-text-table` would be preferable, in that it would also support non-markdown ASCII/Unicode table markup (see some examples [here](https://github.com/ozh/ascii-tables), [here](https://ronisbr.github.io/PrettyTables.jl/stable/man/text_backend/#Text-table-formats) and [here](https://github.com/astanin/python-tabulate#table-format)), as mentioned [above](https://github.com/nushell/nushell/issues/1183#issuecomment-573052143). Furthermore, [there's no single markdown table syntax](https://talk.commonmark.org/t/tables-in-pure-markdown/81/166) anyway (although it can be granted that [gfm's tables](https://github.github.com/gfm/#tables-extension-) seems to be the most popular).

This feature, along with `from ssv` and `detect columns` (#4127), would help lay the groundwork towards automatic detection of tabular content in pipelines (similar to how `open` already auto-detects and converts formats it recognizes), which is the subject of #1608.

**Comment by mattmc3** [comment]
This might not be what you were hoping for, but utilities like `pandoc` are pretty capable when it comes to parsing markdown into other formats. You can pretty easily pipe through pandoc to get XHTML output, which you can then treat like XML like so:

```nu
# Get your markdown from an `http get` or an `open file` or just string it up:
let mdstr = "
| no. | name        | email                    |
|-----|-------------|--------------------------|
| 1   | John Doe    | john-doe@gmail.com       |
| 2   | Peter Smith | petersmith22@outlook.com |
| 3   | Julia Jones | jjones778@gmail.com      |
"

# We're going to use XML, so let's get a helper library
use std/xml

# Now use pandoc to make your markdown into XML
$mdstr
| pandoc --standalone -f markdown -t html4
| from xml --allow-dtd
| xml xaccess [html body table 0]
```

Since pandoc uses LaTeX, you may need to vary your statement to account for escaping, depending on your data: `$mdstr | pandoc -s -f markdown-tex_math_dollars -t html4 | from xml --allow-dtd`. XML handling in nushell is still pretty anemic, so you'll have to write your own functions from there to make the table useful since `from xml` just gives you deeply nested tag/attributes/content tables, but it's not too bad with `xml xaccess`.
