### ISSUE TITLE
Alternative views other than table

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#1190]
**Is your feature request related to a problem? Please describe.**
When a particular table does not fill the terminal, it becomes harder to read. For example:
![image](https://user-images.githubusercontent.com/11488886/72198903-35604980-3467-11ea-8948-6748dca91be3.png)

**Describe the solution you'd like**
Allow user to set `autoview` to non-table view. Such as "Cards":

```
----------------------------------------------------------------------------------------------------
10. projects
    type: Directory    created: 5 days ago    accessed: 5 days ago    modified: 5 days ago
----------------------------------------------------------------------------------------------------
11. tasks.txt
     type: File    size: 12KB    created: 2 days ago    accessed: 2 days ago    modified: 2 days ago
----------------------------------------------------------------------------------------------------
```

**Describe alternatives you've considered**

**Additional context**

**Comment by thegedge** [comment]
👍 I was actually thinking about something like this lately, and `\G` in `mysql` was what came to mind. It's similar to the "cards" you mention, but would be a little more vertical:

```
  ...

  ---
  name: projects
  type: Directory
  created: 5 days ago
  accessed: 5 days ago
  modified: 5 days ago
  ---
  name: tasks.txt
  type: File
  size: 12KB
  created: 2 days ago
  accessed: 2 days ago
  modified: 2 days ago
  ---
  ...
```

**Comment by KSXGitHub** [comment]
The "more vertical" version would be harder to read if there are many more columns per row. The "card" version means to hide titles of well-known/obvious fields (`name: foo` -> `foo`; `size: 5KB` -> `5KB`)

**Comment by thegedge** [comment]
> The "more vertical" version would be harder to read if there are many more columns per row.

This will unfortunately be a problem no matter if we go vertical or horizontal 🙂

Personally, I think with good coloring and formatting, the format I described would actually be far easier to read than the card format you described (mostly because I don't like horizontal scrolling). I'm not saying we should disregard the format you presented, I just want to highlight the subjectivity of the issue.

> The "card" version means to hide titles of well-known/obvious fields (name: foo -> foo; size: 5KB -> 5KB)

I like where you're coming from, but "obvious" and "well-known" are also subjective, which is why I'd rather be verbose by default. If we wanted to introduce the card format, I think we should think about two things:

1) Given the subjective nature of what is "well-known" or "obvious" for some output, it should likely be configurable, or there should be an easy way to opt-in or opt-out of this.
2) How can output streams tell the output formatter what's "obvious"? How do we carry this metadata through the pipeline? How much mutation of a column and/or its values will result in dropping this metadata?

The questions in (2) makes me think this will be a non-trivial thing to do.

**Comment by KSXGitHub** [comment]
> The questions in (2) makes me think this will be a non-trivial thing to do.

Is there already an issue about this? If not, we must create one. I think this feature alone is very useful and essential to plugins. If we want to be able to customize autoview, this feature is required.

For now however, I think [your suggestion](https://github.com/nushell/nushell/issues/1190#issuecomment-586624501) is good enough. But I also think that a YAML array would serve the same purpose better.

**Comment by thegedge** [comment]
> But I also think that a YAML array (with syntax highlight) would serve the same purpose better.

Agree that it's essentially the same (minus the ability to colour column names), and we already have `to-yaml` 🙂

> Is there already an issue about this? If not, we must create one. I think this feature alone is very useful and essential to plugins. If we want to be able to customize autoview, this feature is required.

I think the discussion in this issue is good. It's relevant to the feature request, so keeping it here makes it much easier to come back later and gain context. If you have thoughts on the questions in point (2) above, please do include them here.

**Comment by KSXGitHub** [comment]
> Agree that it's essentially the same (minus the ability to colour column names), and we already have `to-yaml`

I suggest dimming all field titles and highlighting field values according to its type (e.g. strings be white, numbers should be green, file size would be red, etc.)

**Comment by thegedge** [comment]
👍 I'll create an issue for that specifically. Thanks for your input 🙂

**Comment by KSXGitHub** [comment]
As for question (2),

The metadata should contain a **"tag"** (usually a URL to a JSON schema) for each column that an autoview plugin can read into and decide how to best display their values. Some commands (such as `pick`) preserve the tags while others (such as the hypothetical `format`) don't.

**Comment by thegedge** [comment]
In your original example, the `name` column has no title, instead we only see the value. You also mention that the `size` title could potentially be discarded too. Where does this information come from?

**Comment by thegedge** [comment]
Or wait, I think I may understand what you're saying now. We tag the column with its source, so the `name` column in `ls` would be identified as coming from `ls`. The `cards` display would then have some kind of configuration where it knows that `ls name` is the card title?

**Comment by KSXGitHub** [comment]
> Or wait, I think I may understand what you're saying now. We tag the column with its source, so the `name` column in `ls` would be identified as coming from `ls`? The `cards` display would then have some kind of configuration where it knows that "`name` from `ls`" is the card title.

That precisely what I wanted.

**Comment by thegedge** [comment]
Sorry for taking so long to get on the same page 😅 

We do already tag things in a way that may allow doing this, but now my thoughts are mostly on how we scale this to many commands and aliases? Maybe we accept that we can't capture everything and just capture the common cases? Or well, this probably makes sense as configuration, so we can initialize with some defaults, and the user could add additional config for new commands.

**Comment by KSXGitHub** [comment]
What do you mean by "many commands and aliases"? Are they independent commands that are not invoked together? Are they multiple commands in a pipeline? In a script?

Anyway, in my mind, tag metadata are provided by process that spawned them (i.e. part of the data/stream/output/schema), not by `nu` itself. Subsequent processes on that read the output stream may or may not change the tags. For example, `ls` assigns its tags to its column, `pick` does nothing to the tags, `autoview` read the tags.

**Comment by KSXGitHub** [comment]
I want to add: It would be cool to have an [lsd](https://github.com/Peltoche/lsd)-like output when I type `ls` (it only appears like that when `autoview`, it is still a table underneath).
