### ISSUE TITLE
`sys | get host.users` displays the same user account twice while only one exists (macOS)

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1204]
**Describe the bug**
My system has a single user account named `koenraad`

Running `sys | get host.users` I get the following output:
```
━━━┯━━━━━━━━━━
 # │ <value> 
───┼──────────
 0 │ koenraad 
 1 │ koenraad 
━━━┷━━━━━━━━━━
```

**To Reproduce**
See 👆

**Expected behavior**
I expect `sys | get host.users` to return my user account only once.

**Screenshots**
Screenshot of the User preferences menu:
<img width="780" alt="Screenshot 2020-01-12 at 21 18 27" src="https://user-images.githubusercontent.com/7748404/72225047-2077d900-3581-11ea-9f8c-1301d39c0066.png">

**Configuration**
 - macOS Catalina (10.15.2)
 - nu 0.8.0, installed using homebrew

**Comment by svartalf** [comment]
Hey, @koenaad. Since `nu` is utilizing [`heim`](https://crates.io/crates/heim) crate to [fetch](https://github.com/nushell/nushell/blob/c6da56949c3ebe0b572a06157d6dad525aef4365/crates/nu_plugin_sys/src/sys.rs#L116) users information, I had created a corresponding bug: https://github.com/heim-rs/heim/issues/193

**Comment by svartalf** [comment]
Quick follow up: this issue is [not considered](https://github.com/heim-rs/heim/issues/193#issuecomment-586575179) as a bug on the `heim` side, `nushell` can group users by their [usernames](https://docs.rs/heim/0.0.9/heim/host/struct.User.html#method.username) if that's the desired behavior.

**Comment by thegedge** [comment]
I think we have to figure out if we want "users" to also mean "user sessions".

If we do, I would rather just rename it to "sessions" to avoid confusion (@svartalf not sure if you feel similarly about this from the heim side of things).

If we want "users" to mean "user accounts", grouping sessions by username would be incorrect, since not all users will have an active session. We'd have to find another option there (or does heim have some API to return those?).

**Comment by svartalf** [comment]
@thegedge I agree that it is misleading naming both in `heim` and, as a consequence, in `nushell`.
In `heim` it is called "users" only because it was a straightforward rip-off from the Python' [`psutil` library](https://psutil.readthedocs.io/en/latest/?badge=latest#psutil.users), where it is called `users`, with documentation stating that it "returns users currently connected on the system".

Right now `heim` does not provide information on "users" (in context of current discussion), there are only "sessions" available; I tend to create separate "users" and "sessions" API functions, but it should be investigated if it is possible to correctly determine users on all systems supported.

**Comment by thegedge** [comment]
Give all of that, I'm thinking the resolution to this issue is simply to rename `host.users` to `host.sessions` to resolve the confusion. Once we can get user accounts, we can add "users" back.

**Comment by neuronull** [comment]
Hello, I would like to take this if its available. I am teaching myself Rust and looking to get more involved in open source projects at the same time.

**Comment by jonathandturner** [comment]
@neuronull - please do.  feel free to ask questions here or on the discord

**Comment by neuronull** [comment]
Thanks @jonathandturner . Just one question on desired outcome: Is the rename to host.sessions the way to go? I saw in heim-rs/heim#193 , mention of removing duplicate entries in the host.users output as an alternate solution.

**Comment by jonathandturner** [comment]
@neuronull it seems like calling it sessions is maybe best. If people want unique values they can pass it through `| uniq`
