### ISSUE TITLE
Let, mut, const bindings don't parse error when more than one ident is passed in

### ISSUE THREAD

**Issue by RGBCube** [nushell/nushell#12125]
### Describe the bug

And it only binds to the first ident. Quite weird.

### How to reproduce

```nu
~
❯ let foo bar = 123


~
❯ $foo

123

~
❯ $bar

Error: nu::parser::variable_not_found

  × Variable not found.
   ╭─[entry #3:1:1]
 1 │ $bar
   · ──┬─
   ·   ╰── variable not found.
   ╰────
```

```nu

~
❯ const foo bar = 123


~
❯ $bar

Error: nu::parser::variable_not_found

  × Variable not found.
   ╭─[entry #5:1:1]
 1 │ $bar
   · ──┬─
   ·   ╰── variable not found.
   ╰────


~
❯ $foo

123
```

### Expected behavior

Parse error

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.90.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by YizhePKU** [comment]
I can reproduce the issue. Here's my idea of what's happening:

The code that parses a let-expression is kinda hacky. It parses in the following steps:

1. Convert the input into a stream of tokens using a lexer. For example, `let foo bar = 123` is converted into five tokens: `let` `foo` `bar` `=` `123`.
2. Look for an "=" token. Split the token stream into two parts, the "L-value" part and the "R-value" part. In this case, the L-value part would be `foo` `bar`, and the R-value part would be `123`.
3. The L-value part may contain multiple tokens, because nushell allows annotating variables with a type (e.g. `let foo: string = "bar"`). Therefore, we check if the first token in the L-value part ends with a colon `:`. If it does, we strip that colon from the token name, add a variable from the stripped name, and parse the rest of the tokens as type annotations. Otherwise, we simply add a variable from the first token.

Do you see the problem?

When the first L-value token doesn't end with a colon, the remaining tokens are silently ignored. Adding a check should fix the problem.

**Comment by RGBCube** [comment]
> I can reproduce the issue. Here's my idea of what's happening:
> 
> The code that parses a let-expression is kinda hacky. It parses in the following steps:
> 
>     1. Convert the input into a stream of tokens using a lexer. For example, `let foo bar = 123` is converted into five tokens: `let` `foo` `bar` `=` `123`.
> 
>     2. Look for an "=" token. Split the token stream into two parts, the "L-value" part and the "R-value" part. In this case, the L-value part would be `foo` `bar`, and the R-value part would be `123`.
> 
>     3. The L-value part may contain multiple tokens, because nushell allows annotating variables with a type (e.g. `let foo: string = "bar"`). Therefore, we check if the first token in the L-value part ends with a colon `:`. If it does, we strip that colon from the token name, add a variable from the stripped name, and parse the rest of the L-value tokens as type annotations. Otherwise, we simply add a variable from the first L-value token.
> 
> 
> Do you see the problem?
> 
> When the first L-value token doesn't end with a colon, the remaining L-value tokens are silently ignored. Adding a check should fix the problem.

Or the tokenizing step could be fixed, allowing for `let foo : string = "foo"` to work as well. Or won't this work because something like `foo:bar` could be a shell command?

**Comment by YizhePKU** [comment]
> Or the tokenizing step could be fixed, allowing for let foo : string = "foo" to work as well.

I do think `foo : string` should be allowed, but it would be a much bigger change. I haven't figure that out yet.

> Or won't this work because something like foo:bar could be a shell command?

I think Nushell's current lexer splits solely on whitespace. For example, `1+2` would be read as a single identifier, compared to `1 + 2`.
