### ISSUE TITLE
Improve plugin usage documentation for beginners

### ISSUE THREAD

**Issue by jweckman** [nushell/nushell#12146]
I think the current plugin usage documentation is written with nu internals/rust knowledge in mind. Some small changes could drastically improve how easy it is for non-rust people to try out plugins.

Right now there is a separate page for plugins in general and another one for how to build your own and understand it under the hood. This separation is probably a great idea. 

The problems i find are the following:

a)
Searching using "plugin" on the main nushell page first shows the contributor article and then further down the "not so advanced" variant article with the same name "Plugins".

Suggestion: Rename the contributor article to "Creating plugins" and the overview article to "Using plugins". This makes it very clear for newcomers and veterans alike what to expect from each article when searching.

b)
Problem a) is perhaps minor, but the "Adding a plugin" subsection is IMO missing a full example of going from desired plugin to it being installed and available on the users system.  Take an aspiring linux sysadmin user for example who has no development experience and wants to get started with using nushell to query XML using the plugin not included when installed using cargo. How high is the likelihood of such a user to ever get a plugin installed? Pretty low IMO.

I think there should be a copy/paste step-by-step guide on how to use any plugin for people who have no idea about rust or even programming using compiled languages. Most other shells just need a script file or package manager to add plugins. The basic guide does not clearly express any recommended full workflows (git clone? cargo? package manager?) and it can lead to a lot of confusion for people trying out nushell for the first time, leading to them dismissing the whole project even when i think that especially piping is far easier than any of the traditional shells out there.

I'm willing to do some documentation writing if some maintainer can tell me what the recommended ways are to get plugins set up. The way i got things to work after a while of digging was to clone the whole nu repo, compile by hand with all features enabled and use the "tools" to magically make them available. I still don't really know how to get a plugin installed and available and i felt that its a pretty sad state of affairs for something that should take max 10 minutes to figure out.

**Comment by fdncred** [comment]
Right now plugins are in flux as the api keeps changing as we approach a stable api. At some point we'll be stable. Here's the basic steps off the top of my head.

1. Understand the version of nushell you're using `version`
2. Find plugins that support that nushell version either on crates.io, github searching or [awesome-nu](https://github.com/nushell/awesome-nu/blob/main/plugin_details.md). So, you're looking for plugins that use the exact version that nushell uses. The other way to check this is to look at the Cargo.toml file in the plugin's repo and see what version of nushell they depend on. This version needs to be the same as the nushell version.
3. Install the plugins via `cargo install plugin_name` or git cloning a repo and doing `cargo install --path .`
4. Now that the plugins are installed, it's time to register them. https://www.nushell.sh/book/plugins.html#adding-a-plugin This adds all the pertinent data nushell needs to know about a plugin and puts it in `$nu.plugin-path`.
5. Now that plugins are installed and registered, you can use the plugin command. On the latest main branch version of nushell, version 0.91.1, you can do `plugin list` and see all the plugins and the commands they support.

I just rebuilt some plugins yesterday that I use on my mac. Here's what `plugin list` looks like for me right now.
![image](https://github.com/nushell/nushell/assets/343840/bc0c849b-51c8-4c28-b396-da1f5eda9a2e)


Lastly, since the API is currently changing frequently, I find myself updating the code in many plugins to get it to work. This won't be needed eventually but when you change the API, sometimes the plugin code has to change too. So, I had to change code in all the plugins listed above to support 0.91.1.

**Comment by devyn** [comment]
I agree that the book should be more user-focused on plugins and be really light on technical details, linking to the contributor book instead for anyone who wants to create them. For example I think almost everything about what happens when `register` is called is irrelevant - the book should just focus on someone getting a plugin working, and then at the end link to the contributor book for someone who wants to create their own plugins.

I also think it might be good to move it out of the advanced section at some point. It's likely going to be considered a key feature by many users, and not just something that's nice to know about like `explore` or parallelism. I think I understand why it's there at the moment - the whole thing is under active development, we don't really have `nupm` in a state that we can recommend to users, and so it kind of is an advanced topic. But someday it won't be.

**Comment by fdncred** [comment]
We have no issues with people writing up something to make the understanding of plugins better. Our documentation needs to be better in many places, that's for sure.

**Comment by jweckman** [comment]
Added PR with updated docs:
https://github.com/nushell/nushell.github.io/pull/1297

I'm fine with any modifications to it. Tried to write it in the same style as the rest.
