### ISSUE TITLE
Nu “commands” invocation appends a newline

### ISSUE THREAD

**Issue by fnuttens** [nushell/nushell#12154]
### Describe the bug

`nu --commands` appends a newline to the command output, which can be unfortunate, e.g. when using nushell to produce data directly inserted into a modal text editor such as helix.

### How to reproduce

```shell
$ nu -c "echo foo | str trim" | debug -r
String {
    val: "foo\n",
    internal_span: Span {
        start: 301980,
        end: 301982,
    },
}
```

### Expected behavior

I expected nu to send the output of the command as is, without adding an extra newline.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.91.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  | gstat                                                             |

**Comment by devyn** [comment]
I think this is the behavior most people would expect when running with `nu -c`. Most other things do the same thing. If you don't want it, you can pipe to `print -n`

```nushell
> nu -c 'echo foo | print -n' | debug -r
String {
    val: "foo",
    internal_span: Span {
        start: 166782,
        end: 166784,
    },
}
```

**Comment by fnuttens** [comment]
Thanks! Now I’m confused as to why I couldn’t achieve the same result using `str trim` 😅

**Comment by fdncred** [comment]
I think it may be because you're calling `nu` as an external and externals get a trailing newline.

**Comment by fnuttens** [comment]
I see, and `print` is not subject to this trailing newline because it writes to stdout directly. I can now leverage nushell to supercharge my editing experience in Helix, thanks!

**Comment by devyn** [comment]
@fnuttens 

> Thanks! Now I’m confused as to why I couldn’t achieve the same result using `str trim` 😅

It's because when Nu prints values, it prints them with a newline by default. You can see this on the REPL - otherwise there wouldn't be a newline before the next prompt. Similarly, you'd expect just calling `nu -c "2"` to print `"2\n"`

There are some commands that output a string to the user as output, and it's not expected that they need to have a trailing newline - the string is printed bare with a newline.

You didn't need `str trim` there because the newline was being added after. If you use `print -n` manually, nothing is printed by the default printer, and you're explicitly printing without a newline, so it works. It's not an issue of what gets into the pipeline on the other side, it's just what Nu default prints values with.
