### ISSUE TITLE
Making `$env.FILE_PWD` and `$env.CURRENT_FILE` constants, renaming them to be more descriptive, and adding similar constants for any source file

### ISSUE THREAD

**Issue by d4h0** [nushell/nushell#12195]
### Describe the solution you'd like

Hi,

I'd like to propose a few changes to `$env.FILE_PWD` and `$env.CURRENT_FILE`, and the addition of a similar feature to access the path of any source file (not only the path of the main script file or the directory that contains it).

Firstly, I'd like to propose to make variables like `FILE_PWD` and `CURRENT_FILE` constants, so they are usable at parse-time (they don't change during script execution, right? So why not make this information available at parse-time?).

Secondly, I'd like to suggest changing the names to something more descriptive and less confusing.

I don't think, `FILE_PWD` makes sense, to be honest (as mentioned in https://github.com/nushell/nushell/issues/7692, which IMO was closed without a good reason).

'PWD' represents the current working directory on UNIX-like systems (I always thought it stands for "Process Working Directory", but maybe that name was derived from the `pwd` command, which stands for "Print Working Directory").

As far as I can see, `FILE_PWD` contains the path to the directory that contains the main script file – and I can't come up with a reason why such a variable should contain "PWD". The closest I came was "Parent Working Directory" – but I think "working directory" doesn't fit well.

As afar as I know, the directory of a file in often called 'base directory', so `FILE_BASEDIR` seems more appropriate to me.

Even better would be `SCRIPT_BASEDIR` because "FILE" is too unspecific and not descriptive enough ("MAIN_SCRIPT_FILE_BASEDIR" would be ideal, but is probably too long).

Similarly, `CURRENT_FILE` seems too generic/unspecific. Something like `SCRIPT_FILE` (or `MAIN_SCRIPT_FILE`) seems more appropriate to me. 

This also would be less confusing.

When I first saw `CURRENT_FILE`, I thought it points to the path of the (current) source file it is used in (similar to Rust's [file macro](https://doc.rust-lang.org/std/macro.file.html)), however it contains the path to the main script file.

Thirdly, I believe that something like Rust's `file` macro, that points to the path of the source file that it is used in would be useful, as well. Logging, or reading files relative to the current source file, would be two obvious examples.

So it would be great if there were constants like `SRC_FILE` and `SRC_FILE_BASEDIR` (or `CURRENT_SRC_FILE` and `CURRENT_SRC_FILE_BASEDIR`, which is more descriptive, but maybe a bit too long).

Besides the above, `$nu` – which contains already similar data and seems to be already a constant – would be a more appropriate location for such data.

So I'd like to propose to deprecate `$env.FILE_PWD` and `$env.CURRENT_FILE` and to add the following fields to `$nu`:

- script-file (maybe `script-path` would be more consistent, compared to existing fields)
- script-basedir
- src-file
- src-file-basedir

(An issue might be, that `src-file` and `src-file-basedir` would change for every source file, and wouldn't be constant.)

As far as I can see, `$env.FILE_PWD` and `$env.CURRENT_FILE` aren't documented anywhere, so I wouldn't consider the changes I propose a significant breaking change.

From what I remember, the above would fix/solve a couple of open issues.

**Comment by YizhePKU** [comment]
1. I agree `$env.FILE_PWD` and `$env.CURRENT_FILE` are bad names. `$nu.script-path` is much better.
2. I think adding `$nu.script-basedir` is overkill. Users can simply write `$nu.script-path | path basedir`.
3. I think the difference between `$nu.script-path` and `$nu.src-path` is too confusing. I propose we only add `$nu.script-path`, which points to the file being evaluated. This is consistent with Rust's `file!` macro and Python's `__file__` variable. It's unclear whether a variable that points to the "main" file would be useful in Nushell, and `$nu.src-path` is not a descriptive name anyways.

**Comment by d4h0** [comment]
Thank you for your feedback, @YizhePKU!

> I think adding `$nu.script-basedir` is overkill. Users can simply write `$nu.script-path | path basedir`

You are technically right.

I might be wrong, but most of the time the path of the base dir is what is wanted, not the path to the source file of the main script.

(At least I struggle to come up with many use cases where I'd need the script path, instead of the base dir).

So why not offer this quality-of-life improving feature?

> `$nu.src-path` is not a descriptive name anyways.

I believe `$nu.src-file` (what I've proposed) would be descriptive enough, however, IMO `$nu.current-src-file` would be ideal. I don't see any significant value in having a short name for such a variable. Similarly, I'd prefer `$nu.main-script-file`, because that makes it more obvious what data the variable contains. Those longer names would also be less confusing.

> I think the difference between `$nu.script-path` and `$nu.src-path` is too confusing. I propose we only add `$nu.script-path`, which points to the file being evaluated. This is consistent with Rust's `file!` macro and Python's `__file__` variable. It's unclear whether a variable that points to the "main" file would be useful in Nushell

One use case of `$nu.main-script-file`/`$nu.main-script-basedir` would be to indirectly define what the project base directory is.

For example, some library (in a directory in `$env.NU_LIB_DIRS`) could use `$nu.main-script-basedir` to get the path to which it should save data (e.g., `$nu.main-script-basedir | path join "data"`).

**Comment by YizhePKU** [comment]
On second thought, `$nu.script-path` may not be a good name after all. The term "script" has a very specific meaning in Nushell (a file to be evaluated that is NOT a module).

I think I'd prefer `$nu.current-file` instead, in keeping with `$env.CURRENT_FILE`. If we're OK with that, then adding `$nu.current-dir` also seems natural.

**Comment by YizhePKU** [comment]
It turns out this might be hard to implement. Here's the problem:

`$nu` is a variable registered in the `EngineState`. We'd like to use `$nu.current-file` during parsing, which means we need to update the variable within `StateWorkingSet`. However, `StateWorkingSet` cannot just write to the `EngineState` directly (it holds an immutable reference only), and it is also not allowed to shadow variables from the `EngineState`.

@fdncred What's your opinion on this? Is my understanding correct? Is it even a good idea to modify `$nu` during parsing?

**Comment by fdncred** [comment]
There should be 3 terms in consideration.
https://github.com/nushell/nushell/blob/533603b72c128294c19c27324eb74264894cb496/crates/nu-cli/src/eval_file.rs#L94-L106

Here's my position. I've learned that no matter what we name them, people will complain about it. That may sound cynical, but I've learned that people come from a variety of different backgrounds, education, and thought patterns and it's just not possible to have everyone agree with everything because what may seem intuitive to you isn't necessarily intuitive to me. So, what we need to do is name them and tell people this is what they mean and then don't rename them again.

- I'm guessing that they should not be part of $nu.
- I'm fine with making them constants if that's possible.
- I'm fine with a more descriptive name for each of these but I don't want to keep changing them after that.

**Comment by YizhePKU** [comment]
Thanks for the reply. Honestly, at this point I'm also OK with naming them whatever. I'm just wondering how to implement it so that it's constant. If we can't make it part of `$nu`, the only option would be introducing a standalone variable. I'll think about it.

**Comment by kubouch** [comment]
+1 for renaming things and making them constant. Just note that files can be modules as well, not just scripts, and modules are not evaluated, only parsed. So this should be reflected in the naming convention. `script-path` is too restrictive, perhaps using `source` or `src` instead of `script` would fit better, adding `current` for more clarity is OK, too.

Another note: In the parser, relative file imports are relative to the current file. So `use ../foo.nu` already works relative to the current file's base directory. That eliminates some need for FILE_PWD to be constant. But I'd support having it constant, why not.

> I might be wrong, but most of the time the path of the base dir is what is wanted, not the path to the source file of the main script.

I think so, too. Having both the file and the dir just for convenience would be OK.

> One use case of `$nu.main-script-file`/`$nu.main-script-basedir` would be to indirectly define what the project base directory is.

There currently isn't a notion of project base directory in the language. The https://github.com/nushell/nupm defines a package which can be identified via `nupm.nuon`at the root, but that's a 3rd-party construct, not a part of the language. I'd avoid referring to the “main” file or directory for now because we'd have to add it to the language (think Rust's `crate`), which comes with its own set of pitfalls.

> no matter what we name them, people will complain about it

^ This. We can definitely use more descriptive names, but we shouldn't change them after that, unless really necessary.

Finally, I'd also vote for keeping it outside `$nu` because `$nu` contains static data that doesn't change during Nushell's runtime. They could be separate variables, perhaps prefixed with NU_, same as `NU_LIB_DIRS` (yes, it can be both const and env var), for example.

**Comment by WindSoilder** [comment]
I think `path self` can handle it.  So it can be closed.
Feel free to reopen it if `path self` doesn't work for you.
