### ISSUE TITLE
Remove unmaintained `difference` dependency

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#12280]
### Related problem

The `difference` crate in our dependencies [is unmaintained](https://rustsec.org/advisories/RUSTSEC-2020-0095). Since it's used only in a single place [in plugin examples tests](https://github.com/nushell/nushell/blob/87c5f6e45533af47ab0f83ce10ab78812f817c1d/crates/nu-plugin-test-support/src/plugin_test.rs#L216) we should be able to remove it.

### Describe the solution you'd like

Remove the `difference` crate from our dependencies.

### Describe alternatives you've considered

We could replace it with some other crate, but simply comparing the results might be enough? Let's not add dependencies where we don't need them.

### Additional context and details

@devyn It seems like it's been introduced in one of your plugin PRs.

**Comment by devyn** [comment]
Hey @kubouch,

I added this recently for the new plugin test crate. I wanted to be able to demonstrate a nice diff for people who are trying to debug their broken plugin examples. The values can sometimes be rather nested and the differences hard to spot.

If there's another crate that works fine for this purpose, I think that's alright - I just picked one that seemed simple and fit the license requirement.

We have `pretty_assert::assert_eq!` already, but there's no way to use that to generate differences that don't panic. I wanted something like that but so that I could report errors for each example.
