### ISSUE TITLE
No way to emulate coreutils `sort -g` with strings in nu

### ISSUE THREAD

**Issue by Schweber** [nushell/nushell#12396]
### Describe the bug

coreutils `sort -g` will sort numbers like this:
```
+5
+1
-1
-5
```

nushell `sort -n` will sort them like this:
```
+1
+5
-1
-5
```

### How to reproduce

1. `[1 5 (-1) (-5)] | sort -n`

### Expected behavior

I expect nushell `sort -n` to behave the same as coreutils `sort -g`.

### Configuration                                                                                   
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.91.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (built from a source tarball) |
| cargo_version      | cargo 1.76.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by IanManske** [comment]
I think nushell's `sort -n` and coreutils' `sort -g` do different things.

`-g` is a general numeric sort. For the following file:
```
+1
+5
-1
-5
```
`sort -g` gives me
```
-5
-1
+1
+5
```
which is the numbers in ascending order.

The `-n` flag for nushell's builtin sort could use a better description. It looks like it converts each value to a string and then sorts them by alphanumeric order. `sort` without the `-n` flag will match coreutils' `sort -g`.
```nushell
> [1 5 -1 -5] | sort
╭───┬────╮
│ 0 │ -5 │
│ 1 │ -1 │
│ 2 │  1 │
│ 3 │  5 │
╰───┴────╯
```

**Comment by IanManske** [comment]
Filesizes are a built-in data type in nushell, so this works out of the box:
```nushell
[1KiB 5KiB -1KiB -5KiB] | sort 
```
If your original data is in a string format, you can try and use `into filesize` to parse the data:
```
["1 KiB" "5 KiB" "-1 KiB" "-5 KiB"] | into filesize | sort
```
Unfortunately this currently fails because of the negative signs. This could be a good first PR if anyone wants to fix it.

**Comment by singh-priyank** [comment]
Hi, @Schweber @IanManske  I want to pick this up.
I have a few doubts regarding the functionality if the input is inconsistent.

1. Let say the user enters ["1 KiB", "2 KiB", "5"] this as an input 
2. ["1 KiB", "2 Kb"]

**Comment by devyn** [comment]
Hi,

It's very possible to accomplish this using nushell's regex parsing functions:

```nushell
["+5 KiB" "-5 foobar" "+1" "-1 flimflam"] |
  parse -r '(?<full>(?<digits>[+-]?\d+(?:\.\d+)?).*)' |
  into float digits |
  sort-by digits |
  get full
```

(Slightly intimidating regex, but it just captures both the full string and the part with digits, including anything after a decimal point if present)

If you find yourself doing this a lot you can put it in your config or script or library as a custom command.

**Comment by devyn** [comment]
Also, it's probably good to realize that GNU sort has some options that nushell's probably won't ever support. It's necessary when using bash and other POSIX shells to have these kinds of domain specialist programs that really do basically anything you could possibly want to do with one specific type of operation, because of how difficult and slow programming more complex things in those shells are. But we don't have that issue so much in nushell.

Just to give an example, if you pass a really large amount of data to GNU sort, it will automatically do an external merge sort on disk for you. That's something we probably just won't ever add to our `sort`, but if you really want to you can write it in nu or a plugin or (eventually) probably find a library or plugin that does it for you.

Plus, if you're not trying to write something cross-platform, there's always the option of using `^sort`. Part of the advantage of Nushell being a shell is that it's still very low friction to do things like that when you want to. GNU sort is great and has a lot of features and performs well with the right tweaks.

**Comment by singh-priyank** [comment]
I see `into filesize` fails for decimal string values also 
× Can't convert to int.
   ╭─[entry #1:1:2]
 1 │ ["8.3"] | into filesize
   ·  ──┬──
   ·    ╰── can't convert string to int
   
   but works fine with [8.3] | into filesize
   
   I was adding functionality to handle negative file size, should I fix this in the same pr?

**Comment by IanManske** [comment]
Thanks for the PR @singh-priyank, just fixing the negative file size should be fine for now.

**Comment by singh-priyank** [comment]
Fixed the review comments
