### ISSUE TITLE
Canonical way to temporarily elevate access to root, keeping nu and env? (no bash)

### ISSUE THREAD

**Issue by jweckman** [nushell/nushell#12441]
### Question

What is the canonical way to temporarily run a command with elevated access, keeping nu and env intact? (no bash) ?

I basically want to give root privileges to the user, run a command, get back, without ever going through bash.

Standard linux/bash we either use sudo or su as root.

For simple commands, this seems to work ok to run command in nushell with the same env:
sudo -s ls -a

But when i tried this, the dot inside "containerd.io" gets escaped, breaking the program:

```nushell
      let docker = {
            apt: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
            pacman: [docker, docker-compose]
            dnf: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin, docker-compose]
        }
      let packages = $docker.apt
      let package_manager = apt

    match $package_manager {
        apt => (sudo -s apt install -y ...$packages),
        dnf => (sudo -s dnf -y install ...$packages),
        pacman => (sudo -s pacman --noconfirm -S ...$packages),
        aur => (yay --noconfirm -S ...$packages),
        flatpak => (flatpak install -y ...$packages),
        _ => (error make { msg: $"Bad package manager option: ($package_manager)" })
    }
 ```

 ```bash
E: Unable to locate package containerd\.io 
 ```

I'm writing env setup scripts and i really need to run most of the things as the main user and then sometimes pop into root with the same env and nushell not bash. Is there an ergonomic way to do this? Am i completely off using sudo -s ? I would like to avoid setting nushell as login shell for root. Maybe the cleanest way is to create a new user with root access and nu as login shell?

**Comment by devyn** [comment]
I think the problem with `sudo -s` is that it escapes the command arguments using Bourne shell rules, which are not compatible with Nushell. 

This may actually be a very good reason to support something like #12344 so that you can pass args to nushell without having to worry about them being parsed.

You may have better luck using `sudo nu -c "...command..."` though you will absolutely need to escape any string arguments by piping them into `to nuon` at the very least - that's what `sudo -s` is trying to do for other shells but it doesn't know how to do it for nushell, so that's the missing piece there.

That said... You are way better off not using the `-s` argument here, because you don't need it. Sudo does not use bash to run things, it just spawns the command directly. You don't need to start a shell just to run an executable. If you remove `-s` everything will probably work perfectly. Making it launch a shell is an extra step it doesn't need to do.

**Comment by jweckman** [comment]
Ok now i feel really stupid. Sorry for wasting your time. 
Straight up sudo works here at least. 

I think i got confused when i first tried to solve the problem by doing sudo -S (pipe in the password) but then finding i could allow using sudo for my nu program without asking for password and went with that instead (NOPASSWD: /path/to/executable)

I'm making a pull-style ansible clone for all my own environments and with this i think i have all i need. Loving it so far! I might even open source it once 1.0 is out if people want more control over how their personal envs are set up. After just a few days of migrating my old ansible stuff it's just so much more clear and more fun to use.

**Comment by devyn** [comment]
No worries, it's always good to try to think through things like this and get more familiar with `sudo`'s switches. Cheers!
