### ISSUE TITLE
cp can not overwrite a file

### ISSUE THREAD

**Issue by koenaad** [nushell/nushell#1245]
**Describe the bug**
When copying a file to an already existing file, `cp` throws a cryptic error. There is no way to overwrite a file with `cp`.

**To Reproduce**
```
~/Desktop 
❯ touch test.txt

~/Desktop 
❯ cp test.txt copy.txt

~/Desktop 
❯ cp test.txt copy.txt
error: Not a directory (os error 20)
- shell:1:20
1 | cp test.txt copy.txt
  | ^^ Not a directory (os error 20)

```

**Expected behavior**
Either:
- `cp` should warn me, i.e. _"target already exists"_ and offer a flag to overwrite the file anyway (`--force` or `-f`)?
- `cp` should just do it

**Configuration (please complete the following information):**
 - macOS 10.15.2
 - nu 0.8.1 (built from master)

**Comment by notryanb** [comment]
I can confirm this behavior is the same on Windows, albeit the os error is slightly different. `The system cannot find the path specified. (os error 3)`. It looks like the default behavior for a single file is to overwrite on Windows, but prompt on MacOS.

**Comment by twitu** [comment]
I can confirm this behaviour.
* Ubuntu 18.04.03 LTS
* nu 0.9.0 (built from master)

I will try to make this enhancement.

**Comment by thegedge** [comment]
@twitu let me know if you need any help or stop working on this. Thank you! ❤️

**Comment by UltraWelfare** [comment]
I'm using Win10 and indeed the message is correct ('The system cannot find the path specified.')...
I tried `cp test.txt copy.txt` and what I noticed is that in line 268 of filesystem_shell.rs the dst variable is wrong.
src is `"E:\\nushell\\test.txt"` which is correct but dst is `"E:\\nushell\\copy.txt\\test.txt"`...
That's why `std::fs::copy(src,dst)` fails with this message.
std::fs::copy should overwrite by default according to its [documentation](https://doc.rust-lang.org/std/fs/fn.copy.html)
I'll try to find why this is happening and try to fix it.

**Comment by UltraWelfare** [comment]
Update: [This line seems to be the problem](https://github.com/nushell/nushell/blob/7a0bc6bc46d6bc3eb6fb1db90df907d301a51065/src/shell/filesystem_shell.rs#L258)
Removing it completely solves the issue (it correctly overwrites the file) but I'm not completely sure what to do with that if statement... Is there any possibility that `entry.file_name()` wouldn't exist?
I have the quick-fix ready for a Pull Request but I need to search a little bit more about that possibility...

**Comment by twitu** [comment]
I think the check for `destination.exists()` should be changed to `destination.is_dir()`. The flow logic will be,
1. if destination exists and is directory -> new destination is the file name appended to the directory
2. if destination does not exist or it exists and is a file -> try to copy to destination
