### ISSUE TITLE
Are lazy records worth it?

### ISSUE THREAD

**Issue by IanManske** [nushell/nushell#12622]
### Question

It looks like the original use case for lazy records was to speed up accesses to `$nu`, since `$nu` used to contain expensive-to-compute scope data. But `$nu` has since been make constant and is cheap to access. So, the current remaining usages of lazy records are in `sys`, `debug info`, and `lazy make`.

Given the limited use of lazy records, I was wondering if they were worth keeping in the language at all? Namely, supporting lazy records has a few downsides:
- every "record" access may run an arbitrary closure.
  - This is a potential performance footgun, since lazy records are often used to delay expensive computations. A piece of code expecting a regular record may be in for a surprise when provided with a lazy record.
  - The closure can return different results for the same column. This kills "referential transparency", potentially making it harder for users to reason about their code.
  - The closure may have side effects, and so this muddies the semantics around, for example, cell path access.
    ```nushell
    let lazy = lazy make -c ["col"] -g { print "here"; 'test' }
    let table = [{col: 1}, $lazy]
    $table | get col.0
    ```
    Should `$table | get col.0` run the lazy record closure? The current answer is `error`.
- lazy records add yet another case to `Value`, adding to the maintenance burden. That is, we must ensure that lazy records are treated exactly like regular records as to be transparent to the user (note the cell path example above). Currently, I don't think all commands properly support lazy records. 

Instead of returning a lazy record, the `sys` and `debug info` commands could take an optional column or cellpath parameter. Then, `lazy make` would have to be removed, but these would be the only breaking changes necessary to remove lazy records.

**Comment by fdncred** [comment]
I'd vote to remove lazy records because, for me, they're just hard to understand. It may be worth bringing up in designdiscussion and core-team to see what people think. I also wonder if there are `lazy make`s in the wild.

**Comment by devyn** [comment]
Some of the columns of `sys` are currently rather slow to compute. Especially `cpu` always takes some time because it has to measure usage over a period. I think if we get rid of `LazyRecord` it would be nice to have subcommands or switches that don't return the whole thing.

It is possible to have basically the exact same functionality of `LazyRecord` with `CustomValue` if you really want to, and I didn't bother trying to support `LazyRecord` in plugins because it didn't really seem worth it, so I would also vote in favour of removal.

**Comment by rgwood** [comment]
No objections to removal, thanks for bringing this up. I think the idea may be worth revisiting someday but if it’s not worth the complexity right now let’s remove it.

**Comment by rgwood** [comment]
> It is possible to have basically the exact same functionality of `LazyRecord` with `CustomValue` if you really want to

FWIW I kinda think `CustomValue` might need to be extended a bit for this to be true. `CustomValue` doesn't currently have a way to say "these are the columns I have" unless you materialize the whole thing to a regular value with `to_base_value()`.

This is coming up because I'm looking into improving how `explore` interacts with SQLite databases (which are `CustomValue`s). Ideally `explore` would have a way to list the tables in a SQLite database without reading through/converting the entire DB.

(to be clear, I don't think this is a blocker for removing lazy records; it probably makes more sense to extend `CustomValue`)

**Comment by devyn** [comment]
> FWIW I kinda think `CustomValue` might need to be extended a bit for this to be true. `CustomValue` doesn't currently have a way to say "these are the columns I have" unless you materialize the whole thing to a regular value with `to_base_value()`.
>
> (to be clear, I don't think this is a blocker for removing lazy records; it probably makes more sense to extend CustomValue)

Yes, I wonder if maybe we should add `base_value_type(&self) -> Type`, then the `Type` can list the columns if it's a `Record`.

I'm also already planning to add `convert_to(&self, ty: Type)` because it came up a few times that it would be nice to have the conversion commands like `into int` or `into string` be able to convert custom values in a way that makes sense, even if the base value doesn't show as that
