### ISSUE TITLE
'cargo install nushell' can't find nushell in registry 'cargo-io'

### ISSUE THREAD

**Issue by yurivict** [nushell/nushell#12880]
### Describe the bug

n/a

### How to reproduce

cargo install nushell

### Expected behavior

n/a

### Configuration

n/a

### Additional context

n/a

**Comment by fdncred** [comment]
I believe only the crates to build nushell are available on crates.io. You could search crates.io and see what's there. We don't list cargo as a way to install nushell either https://github.com/nushell/nushell?tab=readme-ov-file#installation

**Comment by yurivict** [comment]
```cargo install ...``` is just a very convenient way to install a package.
It requires the least amount of steps out of all other ways to do it on a system that only has Rust installed.

**Comment by fdncred** [comment]
You might try [cargo binstall](https://github.com/cargo-bins/cargo-binstall) to install binaries. I know some people use this. Once it's installed you can do `cargo binstall nu` and it fetches pre-compiled binaries from github.

But `cargo install nushell` will not work, as you've seen. You could try `cargo install nu` if you want to build nushell but `cargo binstall` is faster. Also, you won't get the plugins, they'll have to be installed separately. If you're wanting the fastest way, it's probably just to download the pre-compiled binaries or the nightlies we provide since they do not require compilation.
