### ISSUE TITLE
Kitty shows a desktop notification every time a directory is entered with `shell_integration: { osc9_9: true }`

### ISSUE THREAD

**Issue by Schweber** [nushell/nushell#13092]
### Describe the bug

Version 0.94.0 added the option to set `shell_integration: { osc9_9: true }`. If i do that, kitty shows a desktop notification every time a directory is entered, so on startup of kitty and every time a command completes or the directory is changed. The notification is prefixed by 9; and then prints the path to the directory.

The maintainer of `kitty` [says](https://github.com/kovidgoyal/kitty/issues/7518) that this is due to `nushell` and not due to a problem with `kitty`.

I found no option in `config.nu` that would enable such a behaviour on purpose.

### How to reproduce

1. set `shell_integration: { osc9_9: true }` in `config.nu`.
2. Open nushell in a kitty instance
3. A desktop notification appears immediately and further notifications will appear with every redraw of the prompt or change of directory.

### Expected behavior

No notification.

### Screenshots

![image](https://github.com/nushell/nushell/assets/64630479/3fad237b-d53a-4df6-ab0e-12ba3ea7089f)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.94.1                                                            |
| major              | 0                                                                 |
| minor              | 94                                                                |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09) (built from a source tarball) |
| cargo_version      | cargo 1.77.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash, which                   |
| installed_plugins  |                                                                   |

**Comment by devyn** [comment]
It doesn't look like kitty is actually supporting OSC 9;9, as I can see the `9;` in the desktop notification.

While these 'operating system command' escape sequences are non-standard and kitty is free to implement them however it wants, this is definitely a difference between what nushell expects to happen and what kitty is doing with it.

You can just turn off the osc9_9 shell integration since kitty seems to be incompatible with it.

**Comment by fdncred** [comment]
This is a simple case of different terminals handling escapes differently. This is why we now have the ability to turn individual ones off.

**Comment by devyn** [comment]
Since this is an option that is 

1. Not turned on by default, and
2. Intended to support a specific terminal that implements an escape sequence in a different way (Windows Terminal)

I don't think that this is an issue we need to fix. I could understand if we had an escape sequence enabled by default that isn't widely supported, but it's not. This is just useful for users who want it. But part of the reason we broke up the shell integration features into separate configs is that support between different terminals varies, and it's not always possible to detect.
