### ISSUE TITLE
bash doesn't record commands that start by whitespace

### ISSUE THREAD

**Issue by bingmatv** [nushell/nushell#13134]
### Describe the solution you'd like

Bash doesn't record any commands that start by whitespace, but nushell still records them.

**Comment by ysthakur** [comment]
Hmm, could you post your config and add what you did in the terminal and what you saw? I haven't made any changes related this in my own config and if I start a line with a space, it's not recorded in history. This has been true for several versions now.

**Comment by NotTheDr01ds** [comment]
Yes, this was implemented in #9371 (and the corresponding Reedline https://github.com/nushell/reedline/pull/566) just over a year ago.

However, there might be a slight bug in it depending on how you view things.  The most recent command appears to be cached *in memory* regardless of whether it is preceded by a space or not.  If you hit <kbd>↑</kbd> (Up arrow) immediately after typing a space-suppressed command, that command will appear on the commandline.

However, note that was never written to the history file, and it will disappear from the up-arrow history as soon as the next command is entered.

It's tough to even classify this as a security risk, though, since in that scenario the previous command is going to appear on your screen *anyway*.  Even a <kbd>Ctrl</kbd>+<kbd>L</kbd> to clear the screen is going to leave it in the scrollback for your terminal app.  You'd need to enter a `clear --all` in order to truly remove it, in which case it would *also* no longer be available via up-arrow (since the `clear` command would have overwritten it).

**Comment by sholderbach** [comment]
Closing this, as there doesn't seem to be a regression only the last entry recall which diverges from bash but is I think also done in fish.
