### ISSUE TITLE
Provide $in alias in function body

### ISSUE THREAD

**Issue by rosshadden** [nushell/nushell#13264]
### Related problem

Right now if you want to use the `$in` var later on in a function, you need to alias it like `let input = $in`. This shortcoming makes sense, but I think it can be a lot more ergonomic and consistent with other Nushell features.

### Describe the solution you'd like

I propose function / closure bodies letting you alias `$in` with a scoped variable definition:

```nushell
def foo []: string -> string {|input|
  echo hi
  $input
}
```

This has two enormous advantages over what you have to do as of writing:

1. It's consistent with how closures work with other commands, like `each`, which lets you alias `$in` in the same way `"foo" | each {|input| $input }`.
2. It saves a clunky `let blah = $in` line. I bet we can all agree that would be a big win. Lines are more valuable in a shell language than most other contexts.

It's worth noting that the syntax is already valid. The `{|input|` in my proposal is valid nushell code. It just doesn't do anything at the moment.

**Comment by fdncred** [comment]
It may be worth exploring more as syntax sugar, but I'm not convinced that what we have now is a shortcoming. Perhaps you have a misunderstanding on what `$in` is. Each command that produces a value will create a `$in`, for instance, you can do `echo hi | $in` and it'll print `hi`. So, if you want to maintain a custom command's initial piped in input, you need to capture it because if your next command is `echo hi` you'll overwrite `$in`.

Personally, I think `$in` is a little bit too magical and probably under [documented](https://www.nushell.sh/book/pipelines.html#pipeline-input-and-the-special-in-variable) which makes it difficult to use and understand. 

I've explained it a dozen different ways and each time I explain it, I'm not even sure I'm getting it exactly right. LOL

**Comment by rosshadden** [comment]
I get `$in` about as much as I think I can without intimately knowing the Rust code behind it, and I use it extremely often. I totally understand why you have to alias it or it would be overridden, my example is definitely rather contrived and maybe that hurts my case :sweat_smile:. I just thought it would make a lot of sense if it behaved like the closures you pass to `each`, `insert`, `par-each`, `reduce`, `filter`, `generate`, and probably others.

If function bodies behaved the same way, it wouldn't even change existing behavior, so it would already be opt-in and backwards-compatible.

For example with filter all of the following work:
![image](https://github.com/nushell/nushell/assets/669012/d545c2c8-85f9-407e-abe6-562aff5f03b6)

**Comment by NotTheDr01ds** [comment]
I'm not totally happy when I have to assign `$in` to a variable, but I'm not sure this quite "works" from a parser/syntax perspective.

As I mentioned in #13215, I *think* the current parsing of a `def <block>` that takes a closure with an argument is actually a bug.  I'm still at the surface level of understanding the internals there, but I doubt that it would be easy to change `def` to *really* accept a closure as you propose.  It also would be problematic, as I don't think the user ever really *wants* a `def` to close over the variables in the outer scope.

It *might* be possible to do this with a `def --input=<variable_name>` flag or something like that.

**Comment by NotTheDr01ds** [comment]
I think the initial concern that prompted this request has been addressed in #13357.

Now, `$in` is reusable throughout the closure.

Can this be closed?

**Comment by rosshadden** [comment]
Yep! The new `$in` is beautiful!
