### ISSUE TITLE
'find / | wc -l' - hangs

### ISSUE THREAD

**Issue by ilyash-b** [nushell/nushell#1331]
**Describe the bug**
Running `find / | wc -l` hangs until I hit ^C. Without ` |wc -l` it runs about 3 seconds.

**To Reproduce**

1. `docker run -e RUST_BACKTRACE=full -it quay.io/nushell/nu`
2. `find / | wc -l`

**Expected behavior**
Output - number of files found

**Configuration (please complete the following information):**
 - OS: MacOS
 - Version Catalina 10.15.2

**Info**

When ^C is pressed the result is
```
/> find / | wc -l
^C1896
```

The number doesn't change with the amount of time waited before hitting ^C.

**Comment by jonathandturner** [comment]
This sounds like it could be related to https://github.com/nushell/nushell/issues/1309.

**Comment by ilyash-b** [comment]
Not sure because the following works:
```
/> echo a | wc -l
1
/> ^echo a | wc -l
1
```

**Comment by thegedge** [comment]
Which version of nu? It's perhaps even worse on 0.9.0 because we spawn one process per line (not desirable, we're working on it).

The only way I could see it hanging is if it hits some directory that is taking a long time to `readdir`? 

 > Without `|wc -l it` runs about 3 seconds.

3 seconds sounds fast for `find /`, so I assume it still hangs? If not, sounds like some bug with our async code, since the stream should complete. Or perhaps the `.wait` is blocking and never gets notified of the process ending.

---

I would like people to be able to call things that are familiar, like `wc -l`, and have them work as expected. That being said, to get the most out of nu, it's usually best to start moving towards the builtin commands. In this particular case, does this work for you @ilyash-b :

```
find / | lines | count
```

**Comment by ilyash-b** [comment]
Nope. Apparently docker has older version, which I guess doesn't have `count`.

```
/> find / | count
```

hangs and when I press ^C

```
^Csh: 1: count: not found
```


OK. The `devel` docker does something else. Writes a lot of `1` and I can't stop it with ^C ... but that's another issue.

**Comment by thegedge** [comment]
Thanks for investigating, @ilyash-b 

> Nope. Apparently docker has older version, which I guess doesn't have count.

We'll not worry about that one then, since it's such an older version.

> OK. The `devel` docker does something else. Writes a lot of 1 (with `wc -l`) and I can't stop it with ^C ... but that's another issue.

Yeah, we unfortunately spawn `wc -l` for every line. This is undesirable, but we're working on this. There's still some design issues we need to figure out with regards to internals/externals, but I'm hoping this will eventually work.

I definitely want this to work though, or there be some other way to express it.

> With `count`, the `devel` docker works fine.

🙌 Glad this one worked for you.
