### ISSUE TITLE
Security Issue! Attention Needed!

### ISSUE THREAD

**Issue by psyirius** [nushell/nushell#13480]
I recently came across a security issue while testing for a weird behaviour on another target.

Only found in a specific platform.

I have a speculation about what might be causing this.
I don't want to disclose anything publicly.

I request someone to contact me on a private channel considering the security implications it will cause if publicly disclosed!

**Comment by sholderbach** [comment]
Do you feel comfortable reaching out to the core-team members on our Discord to coordinate the disclosure? Otherwise we will get back to you with an email address for you to send the report to.
We will mark this issue as closed for now, to not attract further outside attention

**Comment by psyirius** [comment]
Sounds Good

**Comment by sholderbach** [comment]
Sorry I am bad at mind reading, please let us know through which channel you want to contact us or if you have reached out and haven't received a response there.

For the [Discord](https://discord.gg/NtAbbGn) either make yourself known in the implementation-chat channel or reach out to us core team members (green role label) so we can arrange a private conversation.
For the project E-mail we are irregularly monitoring `the.nushell[at]gmail.com`
Otherwise we plan on setting up the Github security reporting system to simplify that in the future.

**Comment by psyirius** [comment]
I sent a mail to the above mentioned email address.
