### ISSUE TITLE
Additional `ls --long --realpath` flag to show `realpath` target of a symlink

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13504]
### Related problem

The `target` column of `ls -l` is the direct target of the link, but when it's a link-to-a-link (recursive etc.), there's really no built-in way to get the "final" target (i.e., the "real path").  Implementing this in pure-Nu would involve some significant recursion, I believe.

### Describe the solution you'd like

Either add [`realpath` from `uutils/coreutils`](https://github.com/uutils/coreutils/tree/main/src/uu/realpath) as a Nushell built-in or extend `ls` with a new flag that makes the `target` column be the real path.

### Describe alternatives you've considered

On non-Windows systems `/usr/bin/realpath` can be used.  I'm assuming (but haven't confirmed) that since `coreutils` is cross-platform, that would be a more portable solution.

**Comment by fdncred** [comment]
I'd support adding `realpath` but it needs to be confirmed that 1) it is supported on MacOS/Linux/Windows because not all uutils/coreutils are and 2) that whoever adds this command adds it like the other uutils/coreutils commands were added. This means that changes would have to be made to the uutils/coreutils site to allow parameters to be exposed in such a way that nushell can use them. @dmatos2012 is one of the experts on how to do this. just tagging him in case someone has questions.

**Comment by NotTheDr01ds** [comment]
Closing this since it looks like `path expand` already handles this just fine.
