### ISSUE TITLE
backtick strings in an external command execute subexpressions only after balanced quote mark pair

### ISSUE THREAD

**Issue by Taywee** [nushell/nushell#13578]
### Describe the bug

This one is weird.  A backtick string doesn't normally execute subexpressions, but it does after any balanced pair of quotation marks, and only after the latest of a set of quotes.  This seems related to #13431 to some degree.  Backtick strings seem weird in a lot of ways, especially with them being able to be nested.

### How to reproduce

```nushell
> ^echo `(1 + 1)`
(1 + 1)

> ^echo `""(1 + 1)`
`2`

> ^echo `""(1 + 1) ""(2 + 2) '' (7 + 7) '' (8 + 8)`
`"(1 + 1) "4 ' (7 + 7) ' 16`

> ^echo `(1 + 1)""(2 + 2)""(3 + 3)""(4 + 4)`
`(1 + 1)"(2 + 2)""(3 + 3)"8`
```

### Expected behavior

I expect subexpressions to never run in backtick strings, and I expect quote characters to be treated as quote characters, and not matched or balanced.

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.96.1                                                     |
| major              | 0                                                          |
| minor              | 96                                                         |
| patch              | 1                                                          |
| branch             |                                                            |
| commit_hash        |                                                            |
| build_os           | linux-x86_64                                               |
| build_target       | x86_64-unknown-linux-gnu                                   |
| rust_version       | rustc 1.80.0 (051478957 2024-07-21) (Fedora 1.80.0-1.fc40) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                        |
| build_time         | 2024-08-01 00:00:00 +00:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | default, sqlite, system-clipboard, trash                   |
| installed_plugins  | bexpand 1.3.9, gstat 0.96.0                                |

**Comment by sholderbach** [comment]
To me this seems to be a bug.

The backtick strings behave close to a bare word in our current evaluation logic. (We recently talked about reducing them to be strings that support glob expansions but otherwise be pretty much the same as the single-quoted strings)
We have some additional logic in the generation of arguments passed to the external commands that requires some evaluation (cc @devyn, not sure how much is just #13089 or existed before). This effectively has some string interpolation logic for bare words that we otherwise restrict to the string variants prefixed with dollar (`$''`/`$""`). 

In your example it is first a string but then becomes a string inside bare word string for which that string interpolation kicks in. That extra interpolation has some other bugs. E.g. it interpolates in the position of values for list or record entries even though our general math-like expressions don't do that (https://github.com/nushell/nushell/pull/13413#discussion_r1702324464).
