### ISSUE TITLE
`glob *` on mac and linux is slow in directories that contain many files inside of subdirs

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#13914]
### Describe the bug

On my Mac, `glob ($nu.home-path | path join *) | length` takes a very long time (I can't even wait for it to finish).
Meanwhile, `glob ($nu.home-path | path join *) -d 1 | length` completes quickly. 

I tested it inside a directory that contains subdirectories with many files.
The output of `glob *` is correct. However, it takes much longer when used without the `--depth` flag. Something must be wrong there.

### How to reproduce

```timeit {glob ($nu.home-path | path join *) | length}```

### Expected behavior

I expect nu to list dirs and folders from home directory with no problems. 

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.98.0                              |
| major              | 0                                   |
| minor              | 98                                  |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | macos-aarch64                       |
| build_target       | aarch64-apple-darwin                |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) |
| rust_channel       | stable-aarch64-apple-darwin         |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16) |
| build_time         | 2024-09-18 21:13:07 +00:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  | polars 0.98.0                       |

**Comment by maxim-uvarov** [comment]
I don't know what to do with it, but `rose` wrote this in discord:
```
use wax::Glob;
use std::time::Instant;

let glob = Glob::new("*").unwrap();
let start = Instant::now();
let entries: Vec<_> = glob.walk("/home/rose/").collect();
println!("Done in {:?}", start.elapsed())
```

**Comment by fdncred** [comment]
I ran both on WSL and the first one completed in ~14 seconds and the second one completed in ~3ms. Very weird.

**Comment by fdncred** [comment]
Ah, I'm guessing the problem is this. When no folder_depth is specified, it assumes usize::MAX
https://github.com/nushell/nushell/blob/a940a8aa8095c91d9de969c1dffe02c86e92130c/crates/nu-command/src/filesystem/glob.rs#L172-L176

And it always uses a folder_depth
https://github.com/nushell/nushell/blob/a940a8aa8095c91d9de969c1dffe02c86e92130c/crates/nu-command/src/filesystem/glob.rs#L212-L219

A good experiment would be to change that to `usize::MIN`, which is `0` or maybe `1`.

**Comment by fdncred** [comment]
That seems to fix it (setting the else to 1usize).
![image](https://github.com/user-attachments/assets/43e377c3-3d23-433b-b3ae-7960c84d9abb)
We probably need a new heuristic. Something like "When the glob doesn't contain ** then make the folder_depth 1". Thoughts?

**Comment by 132ikl** [comment]
> I don't know what to do with it, but `rose` wrote this in discord:
> 
> ```
> use wax::Glob;
> use std::time::Instant;
> 
> let glob = Glob::new("*").unwrap();
> let start = Instant::now();
> let entries: Vec<_> = glob.walk("/home/rose/").collect();
> println!("Done in {:?}", start.elapsed())
> ```

Here's my `bench -r 10` results between `glob *` in my homedir and the above program:

test program: `5sec 742ms 598µs 589ns +/- 267ms 483µs 537ns`
`glob`: `5sec 624ms 665µs 509ns +/- 94ms 187µs 840ns`

Which indicates to me that the issue is with Wax's `walk`, not how we use it. Notably, if you don't just `collect` and instead print out each entry, you can see it takes much longer for large directories. I think it's walking the whole file tree no matter what, and only outputting if it matches the glob. 

This is a bit tricky because you can't immediately know whether a file within a subdirectory will be matched by a glob. For example, if you have `*/**.rs`, you can't simply prune a directory named `foobar` since it doesn't have `.rs` in its name. However, obviously something like `*` isn't going to match anything below the current directory. This isn't a "real" fix, but maybe we could default limit the depth to the number of path components? So, unless user-specified. `*` would set depth=1, `*/*` would set depth=2, etc. Anything with `**` can jump straight to `usize::MAX`.

**Comment by 132ikl** [comment]
Also, my results were on Linux, I think we can safely remove "mac" from the issue title

**Comment by fdncred** [comment]
ya, I think it's MacOS or Linux because that glob won't even work on Windows because full paths on Windows don't work for globs like `C:\some\path\to\something`.
