### ISSUE TITLE
Provide `default_config.nu` values by default

### ISSUE THREAD

**Issue by honnip** [nushell/nushell#13924]
### Related problem

Default:
https://github.com/nushell/nushell/blob/71d604067aefa10148ed62063034bde0ba4dfeaf/crates/nu-protocol/src/config/shell_integration.rs#L15-L28
default_config.nu:
https://github.com/nushell/nushell/blob/71d604067aefa10148ed62063034bde0ba4dfeaf/crates/nu-utils/src/sample_config/default_config.nu#L244-L271

(Even what `config nu --default` shows is `default_config.nu`, not the default values)

I was quite confused by the different default values and `default_config.nu`.

### Describe the solution you'd like

Provide `default_config.nu` values as the defaults. 

### Additional context and details

OSC 2 and 7 didn't work and it took me a while to find out why 🤧 (Related: https://github.com/nix-community/home-manager/issues/5527)
I'm curious why default_config.nu (the sane defaults?) is provided separately.

**Comment by NotTheDr01ds** [comment]
There are occasional mismatches between the Rust-backed defaults and the `default_config.nu` defaults.  These are usually bugs, but not always.  In this, case I would *think* the mismatch is a bug, but I haven't looked at when these were implemented or changed to be able to tell for certain.  Sometimes the difference is intentional in order to force a difference between REPL usage vs. script (`nu <script.nu>` or `nu -c`) usage, but that doesn't seem useful in this case.

> I'm curious why default_config.nu (the sane defaults?) is provided separately.

Currently, `default_config.nu` is only used in two situations:

* It is copied to `config.nu` on the filesystem the first time Nushell starts (assuming the user accepts the prompt)
* If the user declines the prompt to create `config.nu`, then and only then is `default_config.nu` evaluated.

I'm working on changing this (#13671) - I'm hoping to start work on that after I finish up #13857 (related) and #13842 (unrelated, but also important).

No guarantees that #13671 will make it in, though.  But I'm hopeful I can demonstrate its benefits.

**Comment by fdncred** [comment]
agreed. bug. i'd accept a PR to fix this.

**Comment by nyabinary** [comment]
Does this resolve #13174 ?
