### ISSUE TITLE
Align list and string slicing with Rust, Python, and other modern languages

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#14097]
### Related problem

A bit of an expansion and rehash on #13077, but today I noticed that the problem extends to *all* indexing, not just negative-indexing.  And apologies that it has taken me so long to write it up - It's a pretty complicated topic, and it's been difficult to find a way to explain it clearly.

I remember @fdncred mention that the Core Team discussed this and decided to follow the way Rust handles it, but unfortunately that still doesn't seem to be the case.  As demonstrated below, the Nushell and Rust slicing syntax diverges in way too many cases.  I'm entering this as a feature request, but if the team thinks it should operate as Rust, then the current behavior (both for positive and negative indices) appears to be a bug here.

* In Nushell, both `range` and `str substring` use closed-interval slicing where the end-index is inclusive.  This is unlike Rust/Python/Java -- The only language I could find that uses this form is F#.
* In other languages like Rust, Python, and Java, slicing indices use an open-interval, where the end-index is exclusive.

```nu
let v = [ "foo", "bar", "baz", "bat", "cat", "spaz"]
let vl = $v | length

$v | range 0..2
# => Returns first three elements in Nushell
# => Returns first two in Rust and others
# => ╭───┬─────╮
# => │ 0 │ foo │
# => │ 1 │ bar │
# => │ 2 │ baz │
# => ╰───┴─────╯

$v | range ..($vl - 1)   # Same as ...
$v | range ..(-1)        # And same as ...
$v | range 0..(-1)

# => Returns all elements in Nushell
# => Returns all but last element in Rust and others
# => ╭───┬──────╮
# => │ 0 │ foo  │
# => │ 1 │ bar  │
# => │ 2 │ baz  │
# => │ 3 │ bat  │
# => │ 4 │ cat  │
# => │ 5 │ spaz │
# => ╰───┴──────╯

$v | range ($vl - 2)..      # Same as ...
$v | range (-2)..
# Works the same as other languages, since closed-interval
# and open-internal operate the same
# => ╭───┬──────╮
# => │ 0 │ cat  │
# => │ 1 │ spaz │
# => ╰───┴──────╯
    
let s = "a good dog"
let sl = $s | str length
$s | str substring 0..2
# Returns first three characters
# In Rust et. al. this would be the
# first two characters
# => a g
    
$s | str substring ..($sl - 3)          # Same as ...
$s | str substring ..(-3)               # Also same as ...
$s | str substring 0..(-3)
# Returns everything but the last two characters
# in Nushell, but returns everything but the last
# three characters in Rust and others
# => a good d

$s | str substring (-3)..        # Same as ...
$s | str substring ($sl - 3)..    
# Works the same as other languages, since closed-interval
# and open-internal operate the same in this case
# Returns last three characters
# => dog
```

### Describe the solution you'd like

Align with Rust and Python "open interval" slicing syntax.

```
                   a          g     o     o     d           d     o     g
               ╰─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────╯
               0     1     2     3     4     5     6     7     9     9    10 (str length)
-(str length) -10    9    -8    -7    -6    -5    -4    -3    -2    -1     0
 
```

The line above shows that, in most other languages, the indices used for slicing refer to the positions **between** the elements, not the elements themselves.  It's similar to the example in the [Python Intro](https://docs.python.org/3/tutorial/introduction.html#strings) on Strings that I learned from quite-a-few-years-ago.

> One way to remember how slices work is to think of the indices as pointing between characters, with the left edge of the first character numbered 0. Then the right edge of the last character of a string of n characters has index n, for example:
> ```
>  +---+---+---+---+---+---+
>  | P | y | t | h | o | n |
>  +---+---+---+---+---+---+
>  0   1   2   3   4   5   6
> -6  -5  -4  -3  -2  -1
> ```
> 
> The first row of numbers gives the position of the indices 0…6 in the string; the second row gives the corresponding negative indices. The slice from i to j consists of all characters between the edges labeled i and j, respectively.
>
> For non-negative indices, the length of a slice is the difference of the indices, if both are within bounds. For example, the length of word[1:3] is 2.
>

This is the same way that Rust works, and the way that I believe Nushell should as well.

Compare Rust to the above Nushell ([Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f9f29396bf1758aed47b63ba00727187)):

```rust
fn main() {
    let v = vec![ "foo", "bar", "baz", "bat", "cat", "spaz"];
    let vl = v.len();
    println!("First two elements: {:?}", &v[0..2]);
    // => ["foo", "bar"]

    println!("Everything but last element: {:?}", &v[0..(vl-1)]);
    // => ["foo", "bar", "baz", "bat", "cat"]
    
    println!("Last two elements: {:?}", &v[(vl-2)..]);
    // => ["cat", "spaz"]
    
    let s = String::from("a good dog");
    let sl = s.len();
    println!("First character: {:?}", &s[0..1]);
    // => "a"
    
    println!("Everything but the last three characters: {:?}", &s[..(sl-3)]);
    // => "a good "
    
    println!("Last three characters: {:?}", &s[(sl-3)..]);
    // => "dog"
}
```

**Comment by 132ikl** [comment]
I would note that the syntax is probably inspired by Haskell, similarly to the step syntax:
```haskell
ghci> [1,2..5]
[1,2,3,4,5]
```

Not saying I think it should stay that way necessarily, but I'm guessing that's the origin.

**Comment by NotTheDr01ds** [comment]
@132ikl Is it?  I don't know Haskell, but both ChatGPT and Claude seem to indicate that it uses `take` and `drop` for rather than any "slicing" syntax.

**Comment by 132ikl** [comment]
I think the key distinction between Nushell and the other languages listed is actually the way ranges work, not anything specific to slicing. Just looking at Nushell and Rust, if you look at slicing through the lens of "return elements which correspond to the indices listed in the range," the actual slicing operation is the same. The difference is the indices listed by the range:

In Rust:

```rust
let vec = vec!["foo", "bar", "baz"];
let range: Vec<_> = (1..2).into_iter().collect();
println!("{:?}", &vec[1..2]);
println!("{:?}", range);
```
Result:
```
["bar"]
[1]
```
In Nushell:
```nushell
> let vec = [foo bar baz]
> let range = 1..2
> $vec | range 1..2
╭───┬─────╮
│ 0 │ bar │
│ 1 │ baz │
╰───┴─────╯
> $range
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
╰───┴───╯
```

In Rust, the range `1..2` only lists `1`, so slicing with it returns only the `1` element. In Nushell, the range `1..2` lists `1` and `2`, so slicing with it returns the `1` and `2` elements.

The other languages don't have range types, but you could interpret Python's `1:2` slicing syntax to be a range equivalent to Rust's `1..2` for example. I think that this would suggest that to align with the behavior of Rust and other languages, range syntax should be changed to be exclusive, rather than changing how `range`/`str substring` work.

**Comment by NotTheDr01ds** [comment]
@132ikl Huh - That's a good point. Thanks!  It me an idea:

```nu
$s | str substring 0..<(-1)
# => a good do

$s | str substring 0..<2
# => "a "
```

That might just answer it.  Closing for now, and I'll reopen in different form if needed.

**Comment by IanManske** [comment]
Yep, as @132ikl has pointed out, this the slicing behavior is primarily determined by the semantics around ranges. We have syntax for both ranges with an inclusive end bound (`..=2`) and ranges with an exclusive end bound (`..<2`). However, `..2` is treated as a range with an inclusive end bound unlike in Rust.

Personally, I would be in favor of making the `..2` syntax exclusive instead of inclusive, as this is what is common in other languages. It also has a few nice benefits, e.g.:
- If I want the next `$n` elements starting from `$i`: `$i..($i + $n)`
- If I want to split a list or string at index `$i`: `..$i` and `$i..`

Wonder what others think about a change like this.

**Comment by NotTheDr01ds** [comment]
@IanManske It's probably an odd dichotomy, but I like the inclusive behavior of ranges in Nushell in *most* use cases.  I think from a user perspective, 1..5 is "mentally" [ 1 2 3 4 5 ], especially in a `for` or `each` context.  Even though this is at odds with other languages :-/.  (Side-note: Definitely an odd-dichotomy on my part. I can't reconcile why I'm okay with this break from other languages when the slicing bugged me initially).

My slicing "confusion" certainly seems to have come because I was looking at the start and end numbers for slicing as a set of indices (as in other languages), rather than a true Nushell `range`.  Now that I've got that mental model in place, I *think* I'm okay with the slicing behavior as well.  I'll just use Nushell's exclusive syntax here in most cases.  So for your examples above:

```nu
let v = [ "foo", "bar", "baz", "bat", "cat", "spaz"]
let i = 3
let n = 2
# If I want the next $n elements starting from $i
let subset = ($v | range $i..<($i + $n))
# If I want to split a list or string at index $i
let first_part = ($v | range ..<$i)
let second_part = ($v | range $i..)
```

We definitely need some `range` and `str substring` examples around that in the help, though - I'll work on adding those.

All that said, I could make the mental shift to it being exclusive, but if so, we should have an inclusive `>` (or something) syntax operator just as we have `<` for inclusive today.  I feel relatively sure that was implied in your proposal above -- It just wasn't explicitly noted.  Perhaps just have both `<` (exclusive) and `>` (inclusive) operators be available regardless of which is the default.

**Comment by IanManske** [comment]
Oh, we do have a more explicit syntax for inclusive ranges. I.e., `..=2` is the same as `..2`.

Otherwise, yeah I have a similar feeling around ranges. The inclusive end isn't that jarring, especially since we have syntax for both inclusive and exclusive ranges. I slightly prefer the `..2` syntax being exclusive, but inclusive is also fine.

**Comment by 132ikl** [comment]
I do think exclusive ranges are useful when working with 0 indexing. With exclusive ranges, something like `for x in ..5` is nice because it's just "iterate 5 times," you don't have to think about off by one. To be honest, I find myself doing `1..<val>` a lot in Nushell where I would do `0..<val>` in other languages, which I'm not sure is a good thing since everything else is 0 indexed of course. I think I also have a slight preference for exclusive ranges because of this.

I do think that if we end up changing ranges to be exclusive we should probably also change the `<start>..<second>..<end>` syntax to be `<start>..<step>..<end>`. Exclusive ranges kind of break of the analogy from `1..2..5` to $1,2,\cdots{},5$, if `1..2..5` actually gives you $1,2,\cdots{},4$.

**Comment by NotTheDr01ds** [comment]
> Exclusive ranges kind of break of the analogy

Perhaps it's just a formatting issue, but I can't quite tell what you are trying to demonstrate there.

From my thinking, there's really not much difference.  In either syntax, there's the opportunity for end-values that aren't in the returned set.

```nu
1..3..6      # Current behavior: <start_value>..<next_value>..<inclusive_end_value>
# => [ 1, 3, 5 ]
1..2..7      # <start_value>..<step>..<exclusive_end>
# => [ 1, 3, 5 ]
```

**Comment by 132ikl** [comment]
Ah, I should have chosen a better example. My concern isn't about end values not being included, but about the concept behind the `<first>..<second>..<last>` syntax. I'm not certain of the history, so maybe this isn't accurate, but I'm guessing the syntax is inspired by the notation frequently used in mathematics where you list the first few elements of a set, elide the ones in the middle, and then list the final element. For example, you might write something like this:

$\\{x_1,x_2,x_3,\cdots{},x_n\\}$

where the middle elements are assumed instead of written out explicitly.

I think of the `<first>..<second>..<last>` syntax as a programming version of this idea. Here's a (better) example using notation, along with the Nushell equivalent:

$\\{2,4,\cdots{},14\\}=\\{2,4,6,8,10,12,14\\}$

In Nushell, this range syntax can be seen as an analogue to the above notation:

```
$ 2..4..14
╭───┬────╮
│ 0 │  2 │
│ 1 │  4 │
│ 2 │  6 │
│ 3 │  8 │
│ 4 │ 10 │
│ 5 │ 12 │
│ 6 │ 14 │
╰───┴────╯
```

But, if ranges are exclusive by default, then the Nushell equivalent would look like this:
```
$ 2..4..14
╭───┬────╮
│ 0 │  2 │
│ 1 │  4 │
│ 2 │  6 │
│ 3 │  8 │
│ 4 │ 10 │
│ 5 │ 12 │
╰───┴────╯
```

Not a big deal, it just makes the choice of `<first>..<second>..<last>` instead of `<start>..<step>..<end>` a bit harder to explain.
