### ISSUE TITLE
Support Bash Completions

### ISSUE THREAD

**Issue by JesterOrNot** [nushell/nushell#1412]
**Is your feature request related to a problem? Please describe.**
As someone coming from Bash I'm used to clicking tab when using `git push -f` to complete origin or something like that but Nu doesn't support them as far as I know
**Describe the solution you'd like**
We need to integrate with them so that it is easier for command line utility developers and people using the shell
**Describe alternatives you've considered**
We could create our own (possibly better) format for Nu completions

**Comment by thegedge** [comment]
I talked to @jonathandturner about having scripts that could export things from existing shells into a nu format. I think this will help a lot with adoption 👍

**Comment by thegedge** [comment]
We're consolidating the completions effort in #290 for now.

**Comment by quarkw** [comment]
Since #290 was closed, I believe this can be reopened?

**Comment by ZerdoX-x** [comment]
@thegedge @amtoine  could you please take a look at this? I think supporting bash completions is still relevant.

Personally it's 1 priority issue for me as I can't really implement completions for every program I am using. It's also very hard to do and documentation is not that wide. For example I still could not find a way to implement a completion for `doas` - sudo like command. I can only see it's hardcoded in sources.

**Comment by amtoine** [comment]
> could you please take a look at this? I think supporting bash completions is still relevant.
> 
> Personally it's 1 priority issue for me as I can't really implement completions for every program I am using. It's also very hard to do and documentation is not that wide. For example I still could not find a way to implement a completion for `doas` - sudo like command. I can only see it's hardcoded in sources.
>
yeah that is sensible goind from a shell that has a lot of completion to another that has close to none built-in :confused: 

we have quite a few options, the pure Nushell one being to use https://github.com/nushell/nu_scripts/tree/main/custom-completions :+1: 
however, be aware that this is a community-driven project and can thus be incomplete / out of date :ok_hand: 

for now, because it is such a big endeavour, i think the safest route is to use an external completion tool, such as `carapace` :relieved: 
personally, i have
- [`completion.nu`](https://github.com/goatfiles/dotfiles/blob/main/.config/nushell/completion.nu) inside my `$nu.default-config-dir`
- i `source` the completion script with [this line](https://github.com/goatfiles/dotfiles/blob/main/.config/nushell/config.nu#L177)

i think leveraging external tools that are dedicated to some precise area of expertise is something that would benefit Nushell a lot :yum: 

let us no if that suits you better for now :innocent:
