### ISSUE TITLE
ls | python3 does not work

### ISSUE THREAD

**Issue by JesterOrNot** [nushell/nushell#1413]
**Describe the bug**
In bash the stdout from `ls` is redirected to python3 when you use a pipe in bash you typically get a syntax error as the variable hasn't been declared
**To Reproduce**
1. open nu
2. run `ls | python3` see that nothing happens
3. open bash
4. run `ls | python3` see that it works

**Expected behavior**
stdout is successfully rerouted
**Screenshots**
![image](https://user-images.githubusercontent.com/50386709/74742108-aa236200-5223-11ea-9d17-a35a59e8934c.png)
![image](https://user-images.githubusercontent.com/50386709/74742155-b9a2ab00-5223-11ea-8b19-9378c4b35447.png)

**Configuration (please complete the following information):**
 - OS: Ubuntu (Gitpod)
 - Version latest
 - Optional features all

**Comment by thegedge** [comment]
I suspect this has to do with trying to stream tables into an external, which should be an error.

**Comment by andrasio** [comment]
Related #1409

**Comment by jonathandturner** [comment]
This seems to work for me in the latest master.  If I do `^ls | python3` which is the equivalent to the example, it gives an error message like you show.  If I do `ls | python3` I get the error about needing to change the structured data into strings, which is currently expected (though we might improve this further in the future)

I'm going to close since `^ls | python3` works and let the internal->external on-going design fix the other part of this issue.
