### ISSUE TITLE
 Nu shell scripting transcoding to rust code

### ISSUE THREAD

**Issue by RokuKent** [nushell/nushell#1425]
**Is your feature request related to a problem? Please describe.**
Most scripting languages do not provide transcoding to native language compilation for speeding up the scripting code performance-wise.

**Describe the solution you'd like**
Nu-shell transcodes to generic rust code which then could be compiled via rust compiler to a binary.

**Describe alternatives you've considered**
Not much out there. This would make nu-shell and its scripting stand out from all the other shell scripting solutions.

**Additional context**
As Nu-shell is in the early days it's doable to structure this from get-go for this purpose rather than retrofit this later. Then basically Nushell's scripting language becomes 'rustscript'.

**Comment by thegedge** [comment]
Love your excitement for nushell scripting, @RokuKent 🙌 

I'm not sure if we'll be investing in this, at least not in the foreseeable future. We believe that nushell scripts will be much more declarative than other shells (in other words, run this pipeline), but the real speed will come from internal/external commands, and plugins.

If some part of a script were actually causing slowness, I'm thinking it would make more sense for that part of the script to become a plugin (which are also pretty easy to write!).

That's what I think for now, at least. Who knows how all of this will evolve. To set the stage, do you happen to have any examples of scripts used in bash/zsh/sh that were slow because the scripting language is slow? It might be nice to explore what that could look like in nushell 🙂

**Comment by RokuKent** [comment]
Most copy scripting functions are slow due to no parallel copying, for example. Having a scripting language for quick Rust prototyping resulting in real Rust apps would speed up the acceptance of the language.
I'm sure someone else will do all this later.
