### ISSUE TITLE
The working directory is the home directory instead of the working directory of the parent process when nushell statrted

### ISSUE THREAD

**Issue by road2coder** [nushell/nushell#14373]
### Question

I've tried the terminals alacritty, wezterm, the systems Windows 11 and WSL, but the problem persists all the time. Is this a bug of nushell or of terminals?

### Additional context and details

I referred to [#5050 ](https://github.com/nushell/nushell/issues/5050) and [#2649](https://github.com/nushell/nushell/issues/2649), but didn't find the answer.
_No response_

**Comment by NotTheDr01ds** [comment]
I'm not able to reproduce, so I want to be sure I understand your scenario.  I'm starting (for this test) from PowerShell for Windows:

```nushell
# In PowerShell
cd c:\
nu
# Now inside Nushell
pwd
# => C:\
```

If that scenario isn't working for you, try starting with `nu -n` instead. Is there any difference?

**Comment by road2coder** [comment]
@NotTheDr01ds `nu -n` works fine. Does it means running nushell without configuration ?  Here is my config:

**Comment by NotTheDr01ds** [comment]
> Does it means running nushell without configuration ? Here is my config:

Yes, the `-n` runs without the config, so we can assume that the problem comes from something there.

The most likely candidate I see is the:

```nushell
load-env (fnm env --json | from json)
```

If the `fnm` command's output includes a `PWD` environment variable, then it's going to change the directory.

If it's not that, then the old-faithful "comment out each section and try again" debug is what I would try next.

**Comment by road2coder** [comment]
@NotTheDr01ds It works fine  with the same config after I updated wezterm to the latest version. I should try this at the begining. Anyway, thanks a lot.
