### ISSUE TITLE
Grepping echo output is oddly complicated

### ISSUE THREAD

**Issue by devurandom** [nushell/nushell#1569]
**Is your feature request related to a problem? Please describe.**

I tried to grep the output of `echo $nu.path`, but found it to be oddly complicated: `echo $nu.path | to-json | jq | rg PATTERN`

The intuitive thing fails with a weird and apparently non-sensical error message (why would I ever want to pipe something through a string instead of a function or a command?):
```
❯ echo $nu.path | rg PATTERN
error: Received unexpected type from pipeline (file path)
- shell:1:35
1 | echo $nu.path | rg PATTERN
  |                 ^^ expected a string
```

**Describe the solution you'd like**

Ideally nushell would detect that the output of a built-in command (`echo`) is being piped into a regular binary (`rg`) and apply some magic: `echo $nu.path | rg PATTERN`

An alternative would be to have a `to-raw` built-in command: `echo $nu.path | to-raw | rg PATTERN`

**Describe alternatives you've considered**

I am using `echo $nu.path | to-json | jq | rg PATTERN` as a workaround, but it is ugly and complex and just barely arrives in the goal with its last breath.

**Comment by jonathandturner** [comment]
Another possible workaround: 

```
> echo $nu.path | to-md | rg sbin
/usr/local/sbin
/usr/sbin
/sbin
```

There's a limitation currently with how our table drawing crate writes directly to the terminal without giving us a string output. This is something I'd like to fix in the future. As you point out, it's a bit annoying to not be able to output from an internal command to an external command and have the external command see the same table you would see.

**Comment by paulkarayan** [comment]
possibly silly question - where are you getting "to-md" and "to-json" from?
I can always alias ```to-json | jq | rg``` but i can't figure out how to get "to-json"

**Comment by jonathandturner** [comment]
@paulkarayan these have been renamed to `to md` and `to json`. The `md` and `json` parts are now subcommands of the `to` command.

**Comment by Marwes-Imperva** [comment]
Still an issue

```
)> ps | rg redis
Unsupported: Row(Dictionary { entries: {"pid": Value { value: Primitive(Int(534342)), tag: Tag { anchor: None, span: Span { start: 20, end: 22 } } }, "name": Value { value: Primitive(String("sh")), tag: Tag { anchor: None, span: Span { start: 20, end: 22 } } }, "status": Value { value: Primitive(String("Sleep")), tag: Tag { anchor: None, span: Span { start: 20, end: 22 } } }, "cpu": Value { value: Primitive(Decimal(BigDecimal("0.000000000000000"))), tag: Tag { anchor: None, span: Span { start: 20, end: 22 } } }, "mem": Value { value: Primitive(Filesize(1484000)), tag: Tag { anchor: None, span: Span { start: 20, end: 22 } } }, "virtual": Value { value: Primitive(Filesize(2441216000)), tag: Tag { anchor: None, span: Span { start: 20, end: 22 } } }} })
error: Received unexpected type from pipeline (row)
  ┌─ shell:2:6
  │
2 │ ps | rg redis
  │      ^^ expected a string, got row as input

```

**Comment by NotTheDr01ds** [comment]
> There's a limitation currently with how our table drawing crate writes directly to the terminal without giving us a string output. This is something I'd like to fix in the future. As you point out, it's a bit annoying to not be able to output from an internal command to an external command and have the external command see the same table you would see.

Since you mention that you'd like to fix it, can we get the Stale tag removed?

Or have you achieved this goal in some other way?

I feel I run into this fairly consistently.  `grep`, `less`/`bat`, and even the Nushell `save` command all seem like places this would be useful.

Notes:

* I know with `grep`, we can use the internal `find` or `match`.
* For pagination, it seems there was an abandoned attempt to provide internal table pagination.  In the meantime, I use `tmux` scrollback buffer, but this isn't nearly as functional as `bat` would be (or even `less`).
* For `save`, I'm not sure what the right incantation should be.  I guess something like [mdless](https://github.com/ttscoff/mdless) can be used, e.g. `help commands | to md | mdless > directory_table.txt`, but that seems pretty clunky.

I keep expecting there to be something like `to text` or `to plaintext`.
