### ISSUE TITLE
Configure aliases dynamically in startup command

### ISSUE THREAD

**Issue by michellocana** [nushell/nushell#1639]
**Problem**
I want to set an "cd" command alias to each subfolder of a folder, i wonder if i could something like this is the startup command: ```ls /path/to/folder | each { alias $it.name [] { cd $it } }```. 
Is there a way i can achieve this?

**Comment by jonathandturner** [comment]
Ahh, this is good catch. Since the first block uses `$it`, the one inside of it can't see the outside one. We need a way of letting them both see the same one.

**Comment by thegedge** [comment]
One challenge to keep in mind:

```
some_pipeline | each { alias $it.name [] { do_a_thing | cmd $it.value } }
```

Is the inner `$it` referencing `$it` from the outer or inner pipeline?

**Comment by quebin31** [comment]
> One challenge to keep in mind:
> 
> ```
> some_pipeline | each { alias $it.name [] { do_a_thing | cmd $it.value } }
> ```
> 
> Is the inner `$it` referencing `$it` from the outer or inner pipeline?

By programming language conventions, the `$it` from inside the block has been redefined, just like Rust lifetimes, when the block dies that `$it'b` dies too

**Comment by Xananax** [comment]
I have the same requirements. For example, there is no agreed upon Godot version manager, and since I use multiple concurrent versions, I do this:
```sh
if [ -d "$HOME/.local/share/hourglass/versions" ]; then
  for d in $HOME/.local/share/hourglass/versions/*; do
    version=$(basename $d)
    alias godot-${version}="$d/godot --editor"
  done 
fi
```
("hourglass" is a project manager that can also download multiple versions of Godot through a UI).
Then I can just run `godot-3.5 .` for example.

Another example, I loop through my Obsidian vaults and have a different alias for each vault.
