### ISSUE TITLE
Achieve better performance for `auto-cd` 

### ISSUE THREAD

**Issue by quebin31** [nushell/nushell#1655]
**Is your feature request related to a problem? Please describe.**
`auto-cd` is cool, but at its current state is kinda slow 

**Describe the solution you'd like**
Better response from `auto-cd` 

**Describe alternatives you've considered**
Do nothing.

**Additional context**
As noted by @avandesa and me, `which` seems to be the culprit of this behavior here: 

https://github.com/nushell/nushell/blob/10768b6ecfa25a1f49a1123d18dce219e892294c/crates/nu-cli/src/cli.rs#L776

**Comment by jonathandturner** [comment]
@quebin31 is it slower than the normal `cd` to the same directory?

**Comment by quebin31** [comment]
Yep, at least for me it's slower that normal `cd`. I have been analyzing the corresponding code and I'm suspecting it's `which` fault (maybe?) 

Also, instead of searching for a matching executable, wouldn't be easy to check if it's a directory?

**Comment by jonathandturner** [comment]
Like check if it's a directory first, and if it's not then check to see if it's a binary?

**Comment by quebin31** [comment]
My mistake, that's what it's currently doing, then it's not `which` fault, but I still can't understand why it's much slower that normal cd.

**Comment by jonathandturner** [comment]
I think it's currently it still checks with `which` just to be sure it's not the name of a program. If it is, you won't be able to run that program unless you use something like `run-external`. I think that's why I did the check that way, so the app would have priority. 

We could still look into ways of making it better though

**Comment by jonathandturner** [comment]
Maybe @avandesa has some ideas?

**Comment by quebin31** [comment]
> I think it's currently it still checks with `which` just to be sure it's not the name of a program. If it is, you won't be able to run that program unless you use something like `run-external`. I think that's why I did the check that way, so the app would have priority. 
> 
> We could still look into ways of making it better though

It doesn't check `which` if it's a directory, but maybe we could remove that call and directly delegate to whatever is in charge of running possible external commands?

**Comment by avandesa** [comment]
I'm fairly certain this is because of the call to `ichwh`. Removing it makes autocd almost instantaneous. `ichwh::which` seems to be slow in the failure case (read: no executable found), and of course we always reach that case when autocd-ing.

Here's the line where it's called: https://github.com/nushell/nushell/blob/10768b6ecfa25a1f49a1123d18dce219e892294c/crates/nu-cli/src/cli.rs#L776

@quebin31 I think you have it backwards - it checks for an executable iff it is a directory. If it's not a directory, then you wouldn't auto-cd anyway.

I'll see what I can do this weekend to improve `ichwh`'s internal logic to speed up the failure case; it really shouldn't bee this slow.

**Comment by quebin31** [comment]
Yeah, again my mistake, so basically that line could be removed since the path is already a directory, and a directory cannot be an executable @avandesa

**Comment by avandesa** [comment]
No, because it covers the case where you have a directory that's the same name as some command or executable. Like, if you had a folder called `ls` - if you run `ls`, you would want to list the contents of you current directory, not cd into it.

**Comment by quebin31** [comment]
@avandesa you're right, I didn't think of that case. @jonathandturner What if the flow control is swapped, I'm thinking on letting flow the pipeline until it's detected as an external command, then we check if it's a valid executable and if it's not we check if it's a directory and finally if both checks fail the whole pipeline will fail.

**Comment by aeosynth** [comment]
fish restricts auto-cd to things that look like paths:

http://fishshell.com/docs/current/cmds/cd.html
> Note that the shell will attempt to change directory without requiring cd if the name of a directory is provided (starting with ., / or ~, or ending with /).

so `ls` would always run the command, and `ls/` would always auto-cd

i don't like nu's current behavior because I *do* want to cd into `foo` and have a `foo` executable, eg:

```
cargo new foo
cargo install --path foo
foo/ #prints "Hello, world!" instead of cd-ing into foo
```

**Comment by jonathandturner** [comment]
@aeosynth - yeah I wonder if we should follow fish more closely here. We can make a few exceptions, like `.`, `..`, `c:` etc, but otherwise if we require the user to type a path separator at the end we can avoid the `ichwh` lookup

**Comment by jonathandturner** [comment]
@aeosynth - can you file an issue for that example you give?

**Comment by quebin31** [comment]
> Note that the shell will attempt to change directory without requiring cd if the name of a directory is provided (starting with ., / or ~, or ending with /).

If the provided starts with `.`, `/`, `~` we still need to check if they may be executables, the good news is that those names have "directory support" (we can check them against a directory, absolute or relative).

**Comment by quebin31** [comment]
@jonathandturner We should consider using [`which` crate](https://docs.rs/which/3/which/), I've been doing some [benches](https://github.com/quebin31/bench-which-ichwh) with `criterion` on both implementations [`which`](https://docs.rs/which/3/which/) and [`ichwh`](https://docs.rs/ichwh/0.3/ichwh/) (with the `futures` executor `block_on`) 

Here I'm including PDFs for both relevant tests (were which is going to fail)

## `which` crate, which is in the order of `us` (mean: 33us)

![pdf_small](https://user-images.githubusercontent.com/3249204/80285706-56823880-86ec-11ea-9103-f351793455a6.png)

## `ichwh` crate, which is the order of `ms` (mean: 300ms)
![pdf_small](https://user-images.githubusercontent.com/3249204/80285735-8af5f480-86ec-11ea-8eab-edcb9b6ddf1b.png)

My guesses are that the extra async runtime needed for `ichwh` is slowing down things.

**Comment by thegedge** [comment]
Love the suggestions. So there are a few ways where we should first do a quick directory check:

1. `./<path>`,
2. `/<path>`,
3. `~/<path>`, and
4. `<path>/` (technically, always a directory).

For Windows, swap out `/` for `\`.

I'm currently taking care of (4) for a separate issue, but it will set us up to easily take care of (1)-(3).

**Comment by avandesa** [comment]
I wrote about the performance issue with `iwhch` and its cause here: https://gitlab.com/avandesa/ichwh-rs/-/issues/4. TLDR, it's not because of the async stuff, but because of how ichwh works internally.

I still have two weeks of school left, so I can't embark on a big refactor right now. However, after that I'll have all the time in the world.

In the meantime, I'll leave it up to the maintainers whether they would like to switch to `which` where `ichwh` is currently used. If I can get the performance back to where it needs to be, we can discuss switching back.

**Comment by thegedge** [comment]
Resolved by https://github.com/nushell/nushell/pull/1672
