### ISSUE TITLE
Add 'explore' functionality

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#171]
We have (or possibly had, past-tense) an `enter` command that allows you to cd/ls your way around the inside of an object. This is pretty cool functionality, but it needs a better home than something that mimics the open command.

It may make sense as a sink:

```
open Cargo.toml | explore
```

Where you are put into an interactive mode (possibly with curses-style abilities as well). Putting this issue here as a reminder to revisit functionality that's interesting but hasn't yet found the right home.

**Comment by Vurich** [comment]
Why not have a `new` command that opens a new shell (instead of `enter`) and have `cd` include all the functionality in one place. Following the principle of least surprise I'd certainly say that it's surprising that nu can "enter" a file by opening it in a new shell but can't `cd` into it within the same shell or open temporary objects. It could take either a path parameter or an object parameter, allowing one to do `sys | cd $it` or `sys | cd` (currently the former fails with `error: Expected string, got Primitive(Nothing)` and the latter just acts as if you'd called `cd` on its own).

**Comment by andrasio** [comment]
#900
