### ISSUE TITLE
`start` doesn't support globs

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1744]
**Describe the bug**
The `start` command supports opening multiple files, but doesn't expand globs.

**To Reproduce**
Steps to reproduce the behaviour:

```
❯ start *.html
error: The file '*.html' does not exist
- shell:1:57
1 | start *.html
  |       ^^^^^^ doesn't exist
```

**Expected behavior**
I would expect the glob to be expanded and start to open all of the files that match the glob.

**Configuration (please complete the following information):**
 - OS: macOS
 - Version 10.15.4

**Comment by arashout** [comment]
So I looked a little bit into this and since I'm new to the project I'm not quite sure what the correct next steps for the implementation should be:
I see the [`parse_filenames` function](https://github.com/nushell/nushell/blob/fbc0dd57e956e03ea2ccb77d88eceb42c11cc3ec/crates/nu_plugin_start/src/start.rs#L45)
And I think if I could somehow expand the globs then just pass the filenames to that function that would be ideal.

However, I'm not sure how to expand the globs. Does nu-shell already use a globbing library?
Or would the implementation involve scanning the required directories recursively to see which files would fit?

@thegedge would you know this? Or should @ someone else?

**Comment by jonathandturner** [comment]
@arashout we use the `glob` crate. If you look for `glob::glob`, you should find some examples.

**Comment by arashout** [comment]
Okay I was looking into another issue, and I see we already use a globbing library

**Comment by arashout** [comment]
I believe this can be resolved after my PR @thegedge , please give it a try when you get a chance

**Comment by thegedge** [comment]
Works for me. Great work, @arashout!
