### ISSUE TITLE
Add Configuration Option to Disable Printing Tables With One Row as a List

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1770]
**Is your feature request related to a problem? Please describe.**
Tables with one row print in a list view (pivoted from the normal table view).  I can understand how this is useful to others, but as someone with dyslexia, keeping things are predictable and static as possible helps out a lot.

**Describe the solution you'd like**
I would like to be able to insert a configuration option to keep Nushell from printing tables with one row as a list.

**Describe alternatives you've considered**
Not sure

**Comment by fdncred** [comment]
I'd augment this to not limit this setting to only tables with 1 row but ti enable or disable the auto-pivot feature alltogether.

**Comment by JosephTLyons** [comment]
I didn’t realize Nu did this automatically in other cases.

**Comment by jonathandturner** [comment]
I think the only auto-pivoting we do is for 1 row tables.

@fdncred - can you think of another situation? There may be another I'm not thinking of.

**Comment by fdncred** [comment]
@jonathandturner I haven't looked at it that close and I am probably mistaken. I know I've run into problems with it in a `x | y | z | a | b` situation when things didn't rotate the way I expected. Personally, in my configuration, I'll probably disable it altogether because I can always just `do whatever command | pivot` and take care of it.

There are places I like the auto pivot, such as `config | get env`, `config --get env`, `echo $nu.env`, and other places I don't like it such as `date`.

What are the rules to auto-pivot? If it's just doing it on 1 line outputs perhaps there should be other rules, such as pivot when the output would be wider than your terminal's width.

**Comment by jonathandturner** [comment]
If someone wants to work on this, https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/commands/autoview.rs#L217-L284 is when the single row gets pivoted.  You'd want to skip this step and go directly to table printing in the case where you don't want to auto-pivot

**Comment by jonathandturner** [comment]
@fdncred currently the only rule is that if it's a single row, it pivots and prints it vertically.

**Comment by fdncred** [comment]
@jonathandturner How do I take this output of a row and format it normally? I was going to prototype a minor change in pseduo code:
```rust
if textwidth + some_padding_factor > termwidth {
    do_the_pivot_thing
} else {
    do_the_normal_thing
}
```
but I'm not sure how to `do_the_normal_thing` here?
