### ISSUE TITLE
Support base16 color schemes

### ISSUE THREAD

**Issue by dysinger** [nushell/nushell#1798]
I, like many, enjoy having a base16 color palette for my i3 desktop, terminal and shells. This makes everything uniform and beautiful. I use base16-gnome-terminal and base16-shell to accomplish this uniform palette. I set everything to base16-phd and it works great. I use those same colors for i3.

I would like the color palette to be configurable via settings. They are currently hard-coded in Rust in nushell.

I am currently loading base16-shell in fish initialization before I start nu manually. It's clunky. I would like to use nu as my login shell. Without base16-shell loaded, my emacs color palette is fugly.

**Comment by jonathandturner** [comment]
For folks interested in working on this, the colors that are used in syntax highlighting are here: https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/shell/helper.rs#L99-L154

For this, we probably want to read in a palette and hand the palette to the painter to use.

The table also uses colors, here: https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/format/table.rs#L329-L333 and a few places lower down.

**Comment by klnusbaum** [comment]
Hey Folks, this looks pretty interesting. Unless anyone objects, I'd like to give it a shot. I've done a little Rust before but will likely need some help.

**Comment by klnusbaum** [comment]
At a high level, the way I see this going is:

1. Abstract out the `Pallet` concept as mentioned by @jonathandturner 
2. Create a base16 file format and generator for NuShell.
3. Create a `Pallet` that can read in the base16 files from step 2.

If I'm off on anything, please feel free to correct me :)

**Comment by klnusbaum** [comment]
Ok, so the next thing we need to do is create a new repository for the nushell base16 template. According to the [base16 guidelines](https://github.com/chriskempson/base16), we should create a repository at github.com/nushell/base16-nushell. In that repository, we can then put our `mustache` template file.

We'll also need to decide on what kind of file format we want to use for our theme files. I'm partial to json since it's so simple, but definitely open to suggestion.

I'm going to ahead and start working on a Palette that loads in a theme from JSON for the time being, but I'll happily change course based on any feedback.

**Comment by jonathandturner** [comment]
I can create the repo. 

For file formats, Nu can read lots of different ones. The config is currently a TOML file, though there's no hard requirement, it's just the current convention.

**Comment by jonathandturner** [comment]
Added: https://github.com/nushell/base16-nushell

**Comment by klnusbaum** [comment]
#1873 for initial them JSON shape support

**Comment by klnusbaum** [comment]
Hey folks, little update on this. I've been distracted with some other stuff as of late, but I'm hoping to resume work on this in the next month or so.
