### ISSUE TITLE
Pipe character is the wrong color (for colorscheme "Solarized light" on Gnome-Terminal)

### ISSUE THREAD

**Issue by baudren** [nushell/nushell#1848]
**Describe the bug**

When using `nu` on my gnome-terminal (installed with `cargo install nu`), setup with solarized light, the pipe character is the same colour as the background

**To Reproduce**
1. Install through cargo
2. Setup a terminal with solarized light colorscheme
3. Write a "|" character: it's invisible

**Expected behavior**
The "|"  should probably be drawn with a darker color :)

**Screenshots**
![image](https://user-images.githubusercontent.com/3526120/82343191-d0a79380-99f2-11ea-9b45-c3af14b244ce.png)

**Configuration (please complete the following information):**
 - OS: Ubuntu 18.04
 - Nu version: 0.14.0

**Comment by lightclient** [comment]
I wonder if this is related to #1839. I realized the issue in #1839 is related to my locale being set to`POSIX`. But I would expect `|` to be available in POSIX-compliant fonts. So maybe there is an issue with the actual character encoding of `|`?

**Comment by tikue** [comment]
I have this problem as well, but I'm not using tmux.

**Comment by fdncred** [comment]
This is a theming issue. This is what I said on Discord. At this time nushell really only looks good in dark terminals. That is because, currently, there is very little control over the theme. I think we limit you to changing the table header colors, textview themes, and `to html` output themes right now. However, we are very interested in themes and would love to have help doing it.

**Comment by Kaiepi** [comment]
I was annoyed by pipes being purple despite using a custom theme. There's a [`shape_pipe`](https://github.com/nushell/nushell/blob/main/crates/nu-color-config/src/shape_color.rs#L37) setting absent from the default `config.nu` that seems to be respected and may be relevant here.
