### ISSUE TITLE
Allow to clear history

### ISSUE THREAD

**Issue by daschl** [nushell/nushell#1936]
I tried to implement `history --clear` which clears out the history file, but it wasn't as easy as I thought. Truncating the file int he history command is not enough, since after some digging I saw that the history is managed in rustyline and it just writes back the history afterwards.

Unfortunately I was not able to get access to rustyline from the history command itself, so I'm creating this ticket - I'd need a bit of advice on whats the best way to funnel the rustyline history API into the history command so we can clear it

**Comment by thegedge** [comment]
> I feel like the best method to bring history information to the history-command is using the `CommandArgs` attributes. Would you guys think that extending `CommandArgs` with a `HistoryManager` is an appropriate solution?

I'm worried that `CommandArgs` has already grown too big, so maybe there's something else we can do.

I haven't thought about this too deeply, but I'm thinking a good direction would be to make `HistoryManager` an attribute of the `History` command struct, which we can then supply here: https://github.com/nushell/nushell/blob/3bb2c9beedc1feff72b08ebb28467957c00c2f70/crates/nu-cli/src/cli.rs#L255-L257

We haven't done this with any other commands yet, besides `RunExternalCommand`, but I feel this is the best approach for things that don't really change throughout the lifetime of `nu`.

**Comment by ErikDeSmedt** [comment]
I see your point in avoiding to extend the `CommandArgs` because it is already quite big. However, I have been struggling a bit to come up with a good solution.

### Naive Approach
The main challenge is that `rustyline::Editor` should be aware of all changes to the history. A naive approach is to create a `HistoryManager` which carries a mutable reference to `rustyline` which is used to send the updates as in the listing below.

```rust
struct HistoryManager {
  rusty : &mut rustyline::Editor
}

impl HistoryManager {
  
  fn clear_history(&mut self) {
    self.rusty.clear_history;
  }
}
```
This code has two issues.

1. Initialization of the `History`-command requires that `rustyline::Editor` has been created first. This is not the case in the current control flow.
2. Both the `HistoryManager` and the `cli`-function require a mutable reference to `rustyline::Editor` at the same time. The borrow-checker will not be happy.

## Alternative Implementation
To avoid storing `rustyline::Editor` as struct-field we could provide it as a parameter. This is the best design I could could come up with.

```rust
struct HistoryManager {
    should_clear_history : bool,
}

impl HistoryManager {

  // This method is used in the History-command
  fn clear_history(&mut self) {
    self.should_clear_history = True;
  }

  // This method is called at the end of each loop in the cli-function
  fn accept_changes(&mut self, rl : &mut rustyline::Editor) {
    if self.should_clear_history {
      rl.clear_history();
      self.should_clear_history = False;
    }
  } 
}
```

Do you think such a design could work?

**Comment by thegedge** [comment]
@ErikDeSmedt "Alternative implementation" looks good to me. You can simplify it further by only using an `Arc<AtomicBool>` (like what we use for `ctrl_c`).

**Comment by ErikDeSmedt** [comment]
I tried walking the path of inserting a history-manager here

https://github.com/nushell/nushell/blob/3bb2c9beedc1feff72b08ebb28467957c00c2f70/crates/nu-cli/src/cli.rs#L255-L257

but got stuck. 

The idea is that we change the `History` command so it hold an `Arc<Bool>`. To edit this atomic bool I need a mutable reference to it. However, the `run`-function has the following signature.

To clear the history I need to have a mutable reference to the `HistoryManager`. However, the run method accepts an immutable reference to `&self` which implements the same

https://github.com/nushell/nushell/blob/3bb2c9beedc1feff72b08ebb28467957c00c2f70/crates/nu-cli/src/commands/history.rs#L25-L29

**Comment by thegedge** [comment]
> To edit this atomic bool I need a mutable reference to it.

Hey, @ErikDeSmedt. You shouldn't need a mutable reference, as the signature of [`store`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicBool.html#method.store) only needs a `&self`. Does that help?

**Comment by chirao237** [comment]
> I forgot to mention that another option is to wrap the rustyline editor in something like Arc<RwLock<rustyline::Editor>> to allow sharing + mutable access.

I think that way is better because the plain `history` command can just iterate over the history directly rather than parsing the history file.

The problem is that `rustyline::Editor` is created after `History`

Would it be okay to create `History` in `cli` instead?

**Comment by ErikDeSmedt** [comment]
I fully agree with @chirao237 that just iterating over the history is a good approach for the plain `history`-command.

I feel uncomfortable with instantiating the `History`-command in the `cli`-function. However, I do believe this is the best approach and I cannot come up with a nice alternative. 

The approach in my [previous comment](https://github.com/nushell/nushell/issues/1936#issuecomment-642858822) tried to solve the same problem by having a `HistoryManager` which has an `accept_changes` method. However, it solves the problem only partially because it is still unclear where that `HistoryManager` should be instantiated.

**Comment by thegedge** [comment]
Although I suggested it, the `Arc<RwLockrustyline::Editor>` unfortunately doesn't make sense when we're not in an interactive mode (e.g., `nu -c '...'`). Given that, I could see some other options being:

1. `AtomicBool`, clear when it's set to true (and reset after).
2. Some kind of enum / trait object (similar to `HistoryManager`). In this solution we'd have one for interactive (clears out rustyline history and the persisted history) and non-interactive (just clears out rustyline history).
3. If `History` actually changes the persisted history file, the interactive loop could check the modified data on every loop.

I'm still leaning towards (1) because it's both simple and ensures `History` stays decoupled from frontend concerns (although a trait is a good decoupling primitive 🙂 )

**Comment by jonathandturner** [comment]
@thegedge - I think your 3rd point helps fix an on-going issue we're seeing, where multiple instances of the shell (like running one inside another) causes issues with the history as it ends up getting overwritten and you lost part of the history. If we reloaded the history before we saved what we had, we might have a chance to work around that issue.

This isn't to say it needs to all be part of one PR, just that as we think about ways to improve history, keeping things in sync would make the experience of using the history a bit nicer and more predictable.

One idea that I might have mentioned on the discord and worth throwing here: we could make a new LineResult.  We have one for Break and CtrlC.  We could add another for HistoryClear.  This would let us send a "message" all the way to the main CLI loop, which has direct access to rustyline.

**Comment by ErikDeSmedt** [comment]
@jonathandturner I really like the idea of creating a new `LineResult`.

I'll try to that implementation and see how that works out

1. It is explicit and easy to implement.
1. It does not leak the `rustyline` to our commands and avoids decoupling.
1. It allows all commands to be instantiated in the same place
1. It does not require to extend `Context` or `CommandArgs`. In the `HistoryManager` and `Arc<AtomicBool>` approach you would probably instantiate them in `create_default_context`, I assume `Context` would be be used to pass this instances to the `cli` method.
