### ISSUE TITLE
Split monorepo structure into multiple repos

### ISSUE THREAD

**Issue by pontaoski** [nushell/nushell#1995]
Currently, nu is a monorepo structure, which poses a problem for packaging. The major ones being:
1) Massive packages generally aren't fun to maintain (an extreme example is LaTeX)
2) Dependency autogeneration for multiple Cargo.tomls in a single repo becomes a hard task when Cargo.tomls interdepend on eachother
3) This can lead to impossible constraints for a package needing to build (e.g. when two binaries in the same repo require mutually exclusive dependencies. These are fine as multiple source packages, but not as a single source package.)

**Comment by jonathandturner** [comment]
@pontaoski - might be good to explore why your 3rd point happens, and how it's related to a monorepo. The case I'm thinking of: let's say we split up the monorepo into multiple repos. We'd keep the files we have now, without changing them, including the Cargo.toml files. Being in multiple repos doesn't change how the project is built, in that each sub-crate still builds itself and its dependencies.

Is the issue coming from the relative links rather than relying on published packages?
