### ISSUE TITLE
Make echo implicit

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2096]
**Is your feature request related to a problem? Please describe.**
While writing aliases I found out it's a pain to have write `echo $var` instead of just `$var` when I need to get the contents of `$var`

**Describe the solution you'd like**
As an example, this alias:
`alias lstrip [ arg ] { echo $arg | str substring '1,' }`
could be:
`alias lstrip [ arg ] { $arg | str substring '1,' }`

**Describe alternatives you've considered**
There are no alternatives right now really.

**Additional context**
It's just a pain. Here's another example. What does `$nu.env` have in it? Right now you have to do `echo $nu.env` instead of just `$nu.env`.

**Comment by thegedge** [comment]
We've definitely chatted about this before, @jonathandturner. I think we were interested in simple values being able to be a pipeline source.

**Comment by jonathandturner** [comment]
Yeah, I think we should definitely consider it.

Something wycats wanted very early on was being able to use `$foo bar` to be able to run a command stored in the `$foo` variable. With @thegedge looking into how to make aliases better, I'm wondering if the alias path is the direction we want to go. Perhaps they could be scoped similarly to what a variable would be, with the end result that we're freed up to do something like what @fdncred is suggesting.

Fwiw, I regularly forget `echo` when I'm trying to get values out of variables, so my fingers at least agree this is the direction we should go 😄

**Comment by thegedge** [comment]
> Something wycats wanted very early on was being able to use `$foo bar` to be able to run a command stored in the $foo variable.

This is actually quite useful in scripting, but I can see it being in conflict with what @fdncred proposed. For example, if `$var` was the string `ps`, do we want to run `ps` or echo the value `"ps"` in `$var | ...`? I think we have to pick one or the other.

**Comment by fdncred** [comment]
How about evaluating `$var` to see if it contains internal commands or other aliases, if it does, execute them. if it doesn't echo it.

**Comment by thegedge** [comment]
That could world, @fdncred, but my vote would be against that. We'd be making an assumption about what the user wants, which would fail the principle of least surprise test (if it's not what they want).

I think the best of both worlds without surprise would be this:

- `$var` always echos
- `$var <args>` always runs a command

But I'm not super into that either. Personally, I'm leaning towards `$var ...` always being a dynamic command execution, so that you could do something like

```
... | $it <args> | ...
```

I'd rather not introduce additional syntax, but we could consider something like this:

```
$var > cmda | cmdb | ...
```

**Comment by fdncred** [comment]
All good information. I wanted to share some reasearch of PowerShell. It may be worth a deeper dive to see how they do this. Not that we have to do it like PowerShell does, but it may be helpful anyway.

1. [CommandType](https://github.com/PowerShell/PowerShell/blob/9212aac0fa020b657454ef4f9ff2fdd6fc6d759c/src/System.Management.Automation/engine/CommandInfo.cs
) Lines 23-86 list the type of commands.
2. [CommandDiscovery](https://github.com/PowerShell/PowerShell/blob/bd90f1921f42059d9b467b501d49576861dfe3e2/src/System.Management.Automation/engine/CommandDiscovery.cs
) Line 572 shows where they match on commandtype
3. [CommandSearcher](https://github.com/PowerShell/PowerShell/blob/f8a588c9551875b129d11edf9d6023bf6c57c432/src/System.Management.Automation/engine/CommandSearcher.cs
) I didn't dig to far into this but it appears to be how it searches the path, etc for the commands.

**Comment by jonathandturner** [comment]
I was just playing around with different cases, and I can't seem to come up with a way to disambiguate.

Say we did:

```
"foo" | echo $it
```

Do we send the string "foo" or run the `foo` command?  We allow you to call commands with quotes (if, say, they have spaces in the path).

I have a hunch for the simple case, we can't go implicit, though it's worth investigating when and how we can expand `$var` for running commands.

@fdncred - not sure if helpful, but there is a shorthand that works similarly:

```
= $arg | str substring '1,'
```

**Comment by fdncred** [comment]
@jonathandturner Please excuse my ignorance of how nushell works under the hood but can you help me understand why it is difficult to disambiguate? Here is what I'm thinking.

Pseudo Code to try and express my thoughts. Why wouldn't this work?
```rust
if which($var) { run $var } else { echo $var} // assuming which checks path and aliases, which it seems to do
```
Alternately, once we have some type of mem store for things perhaps we could do this.
```rust
let internal_cmd = get_datastore($var);
let in_path = which($var);
if internal_cmd | in_path { run $var } else { echo $var }
```

I think the key is understanding what is in the variable (or quotes), which is why I linked the PowerShell items above. They have a Command Discovery process that figures out what is in the $var. Then they categorize it and seem to have `executors` for each type. Again, I'm not suggesting we do what PS does necessarily but it's a good reference. I'd like to understand how bash/fish/zsh solve this problem.

Yes, your example of using `= $arg` is yet another thing I've seen and forgotten about, so it is helpful, if I can remember it. :)

**Comment by thegedge** [comment]
> Why wouldn't this work?

It works, but I would still argue it's confusing. Sometimes it runs a command, sometimes it echos the value. The semantics of when that happens may be pretty clear in the code, but I think as a user this has a high potential for confusion. A rule like "always runs the command" or "always is an implicit echo" is never confusing and has zero potential for error 🙂

Personally, I wouldn't want the behaviour you're proposing, but we could definitely make it configurable. At the very least, we need a way to _force_ one or the other.

Here's two scenarios to consider:

- I provide a script to a user and my script works for some users and not others based on whether or not `$var` is a command on their path. 
- I have a pipeline like `... | $it` to run a series of commands. Now imagine all of those commands just emit a single string, so the end result of that pipeline is a list of strings. Given the "execute if command otherwise echo" behaviour, how can I distinguish an item from a successful command execution versus an implicit echo?

**Comment by fdncred** [comment]
@thegedge I'm happy to respectfully agree to disagree with you and move along. nu is already confusing because it's new and it does things differently. If we want to continue to do things different from every other shell that supports variables and execution of variables, I'm anxious to go along on that ride, but I can't conceive of what that would look like. :)

I do follow your points, as as @jonathandturner demonstrated to me yesterday, "pipes are weird", in that sometimes they don't process from left to right. Sometimes they calculate the whole thing as a unit as in his example `ls | each { echo $it.name } | first 3`.

This isn't really answering the implicit echo thing but I really want to get to these points so I can make a cool prompt. hehe.
1. Write "simplistic" if/then/else multi-line scripts.
2. Store variables so that they can be referenced inside these "simplistic" scripts.

**Comment by thegedge** [comment]
> nu is already confusing because it's new and it does things differently

Just a note: there's a massive difference between "nu does things differently, which is confusing to users migrating to nu" than "nu is internally inconsistent / confusing". The former doesn't bother me, but not the latter 😉 

> If we want to continue to do things different from every other shell that supports variables and execution of variables

What I'm proposing is actually more consistent with other shells, weirdly enough 😄 

To get a variable's value into a pipeline, you `echo` it (e.g., `echo $foo | ...`). To interpret a variable as a command, you just use it directly (e.g., `$cmd | ...`). Personally, I prefer this (in general, I prefer explicitness over implicitness, so I'm biased here).

---

Now, I'm not saying we definitely shouldn't do this, I just want to show the scenarios where the same syntax could evoke two behaviours could cause confusion (again, principle of least surprise is good to keep in mind). If we decide to go ahead with "execute command if var contains command name, otherwise implicit echo", I think I'd be very firm about some requirements:

- One should be able to configure the behaviour of switching between command execution and implicit echo depending whether or not the contents of the variable is a command. This could be a combination of global and/or local configuration (for local config, think `set ...` in a lot of other shells).
- There should always be a way to explicitly choose one behaviour or the other.

With those two in place, I'm a-o-k with going in any direction 🙂
