### ISSUE TITLE
Why I can't pipe any command?

### ISSUE THREAD

**Issue by ProgrammingLife** [nushell/nushell#2099]
For example:
```
> ps | more
error: Received unexpected type from pipeline (row)
```
I want to just send all the output of ```ps``` to next program. Why not?

**Comment by thegedge** [comment]
`ps` is a builtin command, so it emits structured data. We don't have an easy way of automatically selecting what format we should feed into an external program. For example, `more` would probably just want something tabular, like what we display normally, but some other external may want json.

So that's the reasoning why this doesn't work right now. For now, you can manually convert it:

```
ps | to md | more
```

There are two issues to improve this:

1. [Pagination of long tables](https://github.com/nushell/nushell/issues/389), which would mean you'd never have to pipe something into a paging program.
2. [Tagging external programs with marshalling commands](https://github.com/nushell/nushell/issues/451), so that you could configure the behaviour of how the structured data is marshalled before piped into the external.

Do you think those issues would work for you, @ProgrammingLife ?

**Comment by ProgrammingLife** [comment]
@thegedge I think it could solve the problem.

**Comment by thegedge** [comment]
Perfect. If those two will address the issue, then I recommend you subscribe to those issues to see progress. If you still feel like something is missing after they've been closed, please reopen this issue or create a new one 🙂

I'm going to close this one in favour of those two.
