### ISSUE TITLE
Event handlers / hooks

### ISSUE THREAD

**Issue by samhedin** [nushell/nushell#2130]
**Is your feature request related to a problem? Please describe.**
Event handlers are a great way to let users customize the behavior of some software. Fish appears to have a pretty sophisticated system, which can be used as a source of inspiration:
Documentation: https://fishshell.com/docs/current/index.html?highlight=event#event 
Some explanation of how it's used in fish, along with functions: https://zerokspot.com/weblog/2016/01/16/fishy-functions/ 
File manager written with the use of fish's event handlers: https://github.com/cshuaimin/scd 

**Describe the solution you'd like**
I would like to be able to specify scripts and commands to run on certain events. Events could be `on_exit [dir]`, `on_entry [dir]`, `before_command [cmd]`, `after_command [cmd]`, `on_signal [signal]`, `on_nushell_error [optional error]` (if nushell shows an error - do this), `on_startup`, `on_exit`, `on_change_var [var]`

**Example usage**
Run `ls` each time after changing directory: `on_change_var PWD ls`
`on_nushell_error [any] [send angry email to sam]`

**Describe alternatives you've considered**
Alternatives and flexibility could be provided feature-by-feature instead of as a part of a larger event handler framework. 
For example, this issue discusses adding some fields to the config to give the user control over scripts to run on nu startup: https://github.com/nushell/nushell/issues/2117
My initial hunch is that his functionality and more could be provided by a good system for event handling.

**Additional context**
This feature as a whole would probably require a lot of thought and code to implement, but maybe small pieces can be introduced one at a time.

**Comment by stevenbarragan** [comment]
I wanna work on this 🙋

**Comment by jntrnr** [comment]
@stevenbarragan - was just chatting about this issue with the design team. This is a bit of a tricky one that still needs a lot of design up-front to make sure what lands doesn't impact other parts of the engine. If you're up for it, then I think the next step would be to join our [discord](https://discord.gg/NtAbbGn), if you haven't already. It's a great place for doing this kind of deep-dive design work.

Some of the sticky places I can see so far while you're looking into it:
* state mutation in the engine is pretty disciplined, so we will want to make sure that how we probe for these events doesn't break any invariants. If we're flexible in where we can probe, I think this is doable
* we don't want to pay for probes we don't use, so that scripts can run at full speed. this is one that will take a bit of brainstorming, I think
* the probes we do use we'll have to support long-term, so we should think through which ones those will be and what maintenance for them would look like long-term

I think the design challenges should have some good solutions, and if you're up for it, come chat and we can go from there.

**Comment by hustcer** [comment]
+1

**Comment by jntrnr** [comment]
@kubouch - are these finished enough in main to call this one done?

**Comment by kubouch** [comment]
We have the core mechanism there so I'd close it.

If there is a demand for some particular new hook type (`on_exit`, `on_nushell_error`, `before_command`, etc.), let's open a new issue for it separately since they each require different design considerations (e.g., `on_nushell_error` would be best implemented with pattern matching which we don't have yet).
