### ISSUE TITLE
Empty lines when running lines command for parsing git log

### ISSUE THREAD

**Issue by pegak** [nushell/nushell#2228]
**Describe the bug**
I use example from [here](https://www.nushell.sh/cookbook/en/git.html) - Parse formatted commit messages. Output is table, but with wrong data (empty lines).

**To Reproduce**
1. Run `git log --pretty='format:%h<nu>%aN<nu>%s<nu>%aD' | lines | first 10`
2. See bad table with empty lines that shouldn't be there.

**Expected behavior**
Empty lines omitted.

**Screenshots**
![image](https://user-images.githubusercontent.com/12586960/87913326-30600080-ca6f-11ea-80cf-f5a29707c8de.png)

**Configuration (please complete the following information):**
 - OS:   macOS 10.15.6 (19G71a)
 - Nu version (you can use the `version` command to find out): 0.16.0

Add any other context about the problem here:

`git log --pretty='format:%h<nu>%aN<nu>%s<nu>%aD' | lines | where $it != "" | first 10`
and
`git log --pretty='format:%h<nu>%aN<nu>%s<nu>%aD' | first 10`
works. But it is not written in the documentation this way.

Fully working command (with change from issue #2227) is
`git log --pretty='format:%h<nu>%aN<nu>%s<nu>%aD' | lines | where $it != "" | split column "<nu>" sha1 committer desc merged_at | first 10`.

I am using [Redux](https://github.com/reduxjs/redux) for example so we can test it on the same repository.

**Comment by cormacrelf** [comment]
It's worse than empty lines, it is also splitting at apparently random places within lines. Git log's output arrives in chunks, because of various buffering that is occurring in between.

Here is where the error is (noting, mind you, an unnecessary `to_string` clone that should be `.chars().rev().nth(0)`):

https://github.com/nushell/nushell/blob/fe0fc8d5e17231808cd7b718155adca4b8fbaa86/crates/nu-command/src/commands/lines.rs#L36-L44

https://github.com/nushell/nushell/blob/fe0fc8d5e17231808cd7b718155adca4b8fbaa86/crates/nu-command/src/commands/lines.rs#L69-L79

The output of the Lines iterator in std does not include line breaking characters. So this makes no sense. You can't use the Lines iterator to determine if the final piece of the string chunk had a trailing line feed, because Lines strips all line feeds. Quoth the[docs](https://doc.rust-lang.org/std/primitive.str.html#method.lines):

> A string that ends with a final line ending will return the same lines as an otherwise identical string without a final line ending.

The branch above is always taken, because no line ever ends with a line ending. Even if ends_with_line_ending actually did what it says on the tin, there is in fact no mechanism to join an unterminated leftover string to the beginning of the following chunk. So basically the `lines` command needs a complete rewrite. It obviously needs a test that includes multiple string chunks.

**Comment by cormacrelf** [comment]
It's worse than empty lines, it is also splitting at apparently random places within lines, leading to some rows having less than four columns with the wrong data in them.

Git log's output arrives in chunks, because of various waiting and buffering that is occurring in between. Git is waiting for highly sequential file IO chasing SHA pointers, there is some non-line-based buffering in between (delivering "random" chunk endings) and then `MaybeTextCodec` always emits a value, no matter how small a particular read is. So `git log` arrives in chunks. They can be small. I think it may also be possible that MaybeTextCodec emits empty values.

Here is where the error is (noting, mind you, an unnecessary `to_string` clone that should be `.chars().rev().nth(0)`):

https://github.com/nushell/nushell/blob/fe0fc8d5e17231808cd7b718155adca4b8fbaa86/crates/nu-command/src/commands/lines.rs#L36-L44

https://github.com/nushell/nushell/blob/fe0fc8d5e17231808cd7b718155adca4b8fbaa86/crates/nu-command/src/commands/lines.rs#L69-L79

The output of the Lines iterator in std does not include line breaking characters. So this makes no sense. You can't use the Lines iterator to determine if the final piece of the string chunk had a trailing line feed, because Lines strips all line feeds. Quoth the[docs](https://doc.rust-lang.org/std/primitive.str.html#method.lines):

> A string that ends with a final line ending will return the same lines as an otherwise identical string without a final line ending.

The branch above is always taken, because no string tested there ever ends with a line ending. Even if ends_with_line_ending actually did what it says on the tin, there is in fact no longer any mechanism to join an unterminated leftover string to the beginning of the following chunk. This almost certainly broke when https://github.com/nushell/nushell/pull/2655 was merged. That PR reimagined what a string value is here, removing the string concatenation because string values that Nushell already believes to be separate should not be joined together. But there are two kinds of strings at play!

- String *values* like `foo`, `bar\nbaz`, which when lines sees them should produce -> `foo`, `bar`, `baz`
- String *chunks* like `f74bad8e<nu>Author<nu>Date<nu>Description\n9c3de72<nu>Second Aut` and `hor<nu>...` which are actually part of the same conceptual string value, just with a bit of waiting in between.

You can't tell these apart as it stands, and you can't rewrite the lines command correctly until they are distinguishable. The obvious way is to introduce a Chunk(String) (or stringorbinary) variant, and make a little state machine to figure out when they are interspersed with other values that require flushing the leftover buffer.

You could also do something a little more exotic and make nearly-raw file descriptors first class values. Then you can let each parsing mechanism (e.g. a pure NDJSON parser that doesn't suffer the overhead of tagging & boxing all these values) handle a file or an incoming pipe as it wishes. You can send fds between processes too! Anyway. Probably not.

**Comment by jonathandturner** [comment]
this seems to work for me:

```
> git log --pretty='format:%h<nu>%aN<nu>%s<nu>%aD' | lines | first 10
───┬───────────────────────────────────────────────────────────────────────────
 0 │ 1911aad5<nu>Darren Schroeder<nu>add a couple more features                
   │ (#3749)<nu>Wed, 7 Jul 2021 12:03:59 -0500                                 
 1 │ 1943071d<nu>Bruce Mitchener<nu>Simplify `is_executable` in                
   │ `nu-completion`. (#3742)<nu>Wed, 7 Jul 2021 19:53:07 +0700                
 2 │ 08c62457<nu>Darren Schroeder<nu>try to use regular trim commands as much  
   │ as possible (#3743)<nu>Wed, 7 Jul 2021 07:51:52 -0500                     
 3 │ a99a2ce7<nu>Bruce Mitchener<nu>Update wasm sample gitignore for           
   │ node_modules. (#3747)<nu>Wed, 7 Jul 2021 19:48:32 +0700
```

I'm going to close, but if you're still seeing the issue please reopen.
