### ISSUE TITLE
Seeing Windows terminal width off-by-one issues

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#226]
There doesn't seem to be a consistent repro, yet, but I'm seeing some off-by-one issues on Windows where width is being reported to be one larger than it it... but only sometimes.

I've tried alternate crates, but it's tricky to come up with a good solution when getting terminal output correct is a challenge without causing unintended consequences.

This issue should remind us to see if we can come up with a uniform way of detect terminal size (and possibly terminal buffers) in a way that works cross-platform reliably.

**Comment by twe4ked** [comment]
I fixed an [off-by-one issue in `crossterm`](https://github.com/TimonPost/crossterm/pull/170) but there was some confusion around how Windows should be handled. Looks like there's been some more commits since then. Might be a good starting point.

I've got a feeling the new commits might be the issue, they're adding 1 to the width/height.

**Comment by jonathandturner** [comment]
I am! I'll look into this and see if switching to nightly crossterm helps

**Comment by jonathandturner** [comment]
Thanks @twe4ked - I've gone ahead and bumped us to the latest version. I'll keep an eye on it but so far it seems like the issue is gone now
