### ISSUE TITLE
Ignore non-numeric data for `math` operations

### ISSUE THREAD

**Issue by bailey-layzer** [nushell/nushell#2268]
This is an extension/update of #1883.

**Describe the bug**
Currently, the `math` subcommands behave unpredictably with non-numeric input. Using the table:
```
───┬─────
 0 │  30 
 1 │ NaN 
 2 │   3 
 3 │  60 
───┴─────
```
- `... | math sum` gives 63 (looks like it starts over after it encounters a string). Thus, `avg` gives 15.75.
- `median` and `mode` panic
- `min` and `max` raise an Unexpected
- `stddev` and `variance` raise a confusing coercion error:
```
error: Coercion error
  ┌─ shell:1:21
  │
1 │ open nan.json | get total | math stddev
  │                     ^^^^^
  │                     │
  │                     string
  │                     string
```

**To Reproduce**
1. `echo "[{"month":2,"total":30},{"month":3,"total":"NaN"},{"month":4,"total":3},{"month":5,"total":60}]" | from json | get total` gives the example column.
2. `... | math [command]`.

**Expected behavior**
The commands could default to ignoring non-numeric data, keeping data above the bad row (you could have a `--strict` flag to refuse non-numbers). It could also do the opposite and raise an error, but with an optional `--ignore-nonnumeric`. Regardless, the outcome should be consistent across subcommands (and not a panic).

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Manjaro 20.0.3
 - Nu version (you can use the `version` command to find out): 0.17.0
 - Optional features (if any): stable

**Comment by thegedge** [comment]
This has come up before in the context of how we should handle `Nothing` values in a stream. I believe we've come to the conclusion that we should always be strict about this, returning errors instead of coercing/ignoring. I believe @andrasio and @jonathandturner have opinions here also.

That being said, we should make it easy to filter things out with `where`, which I think is more flexible than building filtering functionality into all of the math commands. I'm thinking something like this:

```
open nan.json | get total | where numeric?($it) | math stddev
```

Not sure of the syntax for `numeric?`, and maybe it should be its own command, but I think that captures the essence of the idea 🙂

**Comment by andrasio** [comment]
I believe this is fixed. Please reopen if not.
