### ISSUE TITLE
pipeline does not preserve JSON structure

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#2295]
**Describe the bug**
An array of a single object will be forcefully converted to single object.

**To Reproduce**

```
echo '[{"abc":123}]' | from json | to json
```

**Expected behavior**
Prints original input (`[{"abc":123}]`).

**Actual behavior**
Prints the object inside (`{"abc":123}`).

**Screenshots**

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Linux
 - Nu version (you can use the `version` command to find out): 0.17.0
 - Optional features (if any):

**Comment by thegedge** [comment]
We turn an array of things into a stream. When there's one element in the stream, we assume it's meant to be just the element. If there's more than one element, we assume it's an array.

Unfortunately, I don't think there's an easy way for us to make this work, unless we embedded a table in a list. It would look like this:

```
/Users/gedge/tmp> echo '[1]' | from json
───┬────────────────
 0 │ [table 1 rows]
───┴────────────────
```

which is unfortunately much more difficult to work with.

I can think of two possible solutions:

1. Start tagging the pipeline in a way that we can highlight that the source was originally an array, so if you have only one element in the stream, formatting commands can choose to regard it as an array. We've been discussing "hints" in the pipeline, so it's not unreasonable, but would be good to think about more deeply and RFC.
2. Add a flag so that the user can force it: `to json --array`.

**Comment by KSXGitHub** [comment]
@thegedge I prefer the first solution.

**Comment by andrasio** [comment]
@KSXGitHub As a workaround you can use `--objects` instead.

```
echo '[{"abc":123}]' | from json --objects | to json
[{"abc":123}]
```

**Comment by thegedge** [comment]
Actually, @jonathandturner's [Data Frame RFC](https://github.com/nushell/rfcs/pull/3) should be able to address this, I believe.
