### ISSUE TITLE
Get None when environment variable not exsist

### ISSUE THREAD

**Issue by yanganto** [nushell/nushell#2302]
**Is your feature request related to a problem? Please describe.**
I try to use nu shell as a common shell both for Linux and Window by detecting the environment variable, and I got the shell error with a variable suggestion as following
```
/usr/local/bin> if $nu.env.OS == "Windows_NT" {echo "Windows"} {echo "Not Windows"}
error: Unknown column
  ┌─ shell:1:12
  │
1 │ if $nu.env.OS == "Windows_NT" {echo "Windows"} {echo "Not Windows"}
  │            ^^ did you mean 'ZSH'?

/usr/local/bin> if $nu.env.OS {echo "Windos"} {echo "Not Windows"}
error: Unknown column
  ┌─ shell:1:12
  │
1 │ if $nu.env.OS {echo "Windows"} {echo "Not Windows"}
  │            ^^ did you mean 'ZSH'?
```

**Describe the solution you'd like**
- Add a `None` element in UntaggedValue,
- Add a function `pub fn nun(env: &IndexMap<String, String>, tag: impl Into<Tag>) -> Result<Value, ShellError>`
- Handle `$nun` in `evaluate_reference`
- Implement `fn is_true` of  `UntaggedValue::None`  to return false

If user calls `$nun.env.OS` and the `OS` is not set, it will get a `UntaggedValue::None`.

If this solution is acceptable, I am willing to work on this and make a PR for this issue.

**Comment by fdncred** [comment]
@yanganto Good point. We should have a way to check for the existence of environment variables. We're still thinking about how to best do this.

Related to your specific example, @jonathandturner reminded me that checking for OS is handled by the `sys` command. So, I wrote this alias that might come in handy `alias host_is [host] { sys | if $it.host.name == $host {echo $true} {echo $false}}`. Then you can say, `= $(host_is == "Darwin")` and if you're on a mac it will say `true`.

**Comment by thegedge** [comment]
As for the solution you mentioned, @yanganto, we had some discussion and are hesitant on making variable access evaluate to `Nothing`. Some reasons for that:

- My own experience is that this kind of behaviour often leads to subtle bugs in scripts/systems, because you make a typo, but the thing that consumes the result of your variable access still functions fine.
- If we do this for variables, we would also have to make `get <column name>` work the same, and I'm not sure we want to do that because we would have no way to track errors in a pipeline, making it hard to point users to the source of a problem (although it may be possible to tweak things here to avoid this problem).
- It sets a precedent for all variable access working the same way, and we'd rather not set that precedent right now. In general, we like to defer these kinds of semantics decisions as late as possible, when we have more knowledge, and can hence make better decisions 🙂

So we're thinking we'll do what @fdncred mentioned: expose a way to check if a key exists in a table. That allows one to not get to an error state that isn't possible to get out of. What do you think?

**Comment by yanganto** [comment]
Thanks @fdncred, use following commands solve my problem. 
```
sys | if $it.host.name == "Linux" {echo "Linux"} {}
sys | if $it.host.name == "Darwin" {echo "Mac"} {}
sys | if $it.host.name == "Windows" {echo "Windows"} {}
```

Hi @thegedge 
Thanks for your explanation.

My proposal is to use `$nu` for not allow `Nothing` and to use `$nun` to allow `Nothing`, and it still lacks consideration.

I think this is hard to be chosen because `Nothing` is good in some scenarios but truly leads to subtle bugs is some cases.  

It may be a cool feature to give the power to the user to chose to use `Nothing` to fill or use average value to file,  or values from Multivariate imputation by chained equations (MICE).

Thanks for your work on nu shell.  It is an interesting project. :smile:

**Comment by thegedge** [comment]
Thanks for bringing this up, @yanganto . 

> My proposal is to use $nu for not allow Nothing and to use $nun to allow Nothing, and it still lacks consideration.

We were also thinking along the lines of making this more explicit — `$nun` could easily be a typo too 😱 – so we could create some helper commands to make this work, and when we have time to think about it more deeply, we could consider syntax. A couple of examples:

```
> $nu.?env.?VAR
> $nu.env.VAR?
```

Don't want to rush to either of these, but you've got us looking into and thinking about this 🙂
