### ISSUE TITLE
Chaining commands does not work with internal commands

### ISSUE THREAD

**Issue by bambu** [nushell/nushell#2380]
**Describe the bug**
New to nushell. Looking at the [coming from bash](https://www.nushell.sh/book/en/coming_from_bash.html) page it mentions that: `command1; command2` will "Run a command, and if it's successful run a second". This does not appear to work if the first command is a nushell command. 

**To Reproduce**
```
> echo hello ; echo world
world

> ^echo hello ; echo world
hello
world

> echo hello ; ^echo world
world

> ^echo hello ; ^echo world
hello
world
```

**Expected behavior**
In all of the previous examples, the expected result is:
```
hello
world
```

**Configuration (please complete the following information):**
 - OS: macOS 10.15
 - Nu version: 0.18.1

**Comment by thegedge** [comment]
So, this is expected behaviour. Basically, `pipeline1; pipeline2; ...; pipelineN` will execute pipelines 1 to N-1, but not show their outputs. You'll only see the output from the last pipeline. The internal `echo` command produces structured data into the pipeline, not print it to the screen.

So I see a few options:

1. We keep everything as is, clarify behaviour in the documentation.
1. We show results from all pipelines.
2. We make the internal `echo` actually print to the screen, and have other ways to emit values into the pipeline.

**Comment by thegedge** [comment]
@bambu I'd love to learn more about any confusion you experienced here. Were you expecting "echo" to immediately print to the screen? Or perhaps you understand what `echo` does in the nushell world, but expected both pipelines to show their results? Something else?

**Comment by bambu** [comment]
I was expecting both echo commands to output. When I tested it, I did something like `ps; ls` expecting to see both outputs.

I remember the pipeline chapter only mentioning `|` and not `;`. If this is expected behavior then I would suggest some further documentation explaining what other characters can be used in the pipeline and how.

So just to verify, when `cmd1; cmd2` are both internal it is supposed to only evaluate whether the first cmd has succeeded or not? there is no way to get the output
