### ISSUE TITLE
Configurable behavior on expression (not command) input | Unnamed alias

### ISSUE THREAD

**Issue by LhKipp** [nushell/nushell#2411]
Currently:
```shell
$ /etc
```
Would cd into the directory /etc
I want this behavior configurable. I would rather like the shell to ls /etc here.

As nushell is Syntax aware a mapping from
SyntaxShape1 -> alias 
is possible as soon as aliases have signatures with meaning.

**Describe the solution you'd like**
```shell
alias --unnamed unnamed_ls [path] {ls $path}
```
nushell will now automatically deduct the type of path, check if one such mapping for this syntactical type exists already, and warn me if so. Otherwise typing "/etc" has the same result as "ls /etc" :)

**Comment by thegedge** [comment]
There are two other possibilities:

1. `config set` where we have a config value with a block that runs on this behaviour, or
2. have nushell emit events that people can write scripts to hook into. Some examples of events:
    - before command execute
    - after parse
    - render prompt
    - non-executable path as command
    - exit/enter directory

We've definitely been thinking about hooks (option #2), but haven't designed anything for that yet, since our scripting support isn't top notch. #1 would be a good solution for now, and I would prefer it over a specially named alias / flag on alias because I think it's a bit easier to discover. What do you think?

**Comment by LhKipp** [comment]
I agree. `config set` is the way to go.
I personally think when typing `$ path-to-cd-to` as a command (without name) to execute with `path-to-cd-to` as argument 1. Therefore I don't like alternative 2 that much, as it sounds more complicated.
I would like to reiterate, that I want a configuration option not only for the above mentioned use case, but a general one.
For every SyntaxShape nushell can distinguish, 1 mapping to a command to run when this SyntaxShape gets entered by the user.
`$path --> cd into path´
`$math-expression --> drop me in a python shell and let python evaluate the expression`
`$column-path --> echo the value pointed to by column-path in the last table, which has been printed to the screen`

This proposed idea has the shortcoming of not being able to determine between:
`$ ./file --> execute file`
`$ path --> cd into path`
As file and path are both of SyntaxShape::Path. Therefore a special rule needs to be encoded in nushell for this use case.

**Comment by thegedge** [comment]
Thanks for expanding. That helps clarify your request.

I think that this is a fairly significant feature that would be good to explore in an RFC. I'd love to see us get rid of our hardcoded behaviour for "auto cd when directory" 🙂
