### ISSUE TITLE
cd . changes path

### ISSUE THREAD

**Issue by VincentWo** [nushell/nushell#2432]
**Describe the bug**
With the default prompt the command `cd .` changes the path (appends a '.'), this stacks and doesn't go away when changing paths.
**To Reproduce**
1. Go to random directory
2. Type `cd .` once or more
3.  Observe the prompt changing

**Expected behavior**
The prompt shouldn't change when one does `cd .`

**Configuration (please complete the following information):**
 - OS (e.g. Windows): (Arch)Linux
 - Nu version (you can use the `version` command to find out): 0.17.0
 - Optional features (if any): None

**Comment by VincentWo** [comment]
I would also be open to try to fix this issue myself, if somebody could give me a general direction where the error could have originated (and if you think this is easy enough for a novice rusteacan.

**Comment by dmeijboom** [comment]
@VincentWo I believe you can add this behaviour in `crates/nu-cli/src/shell/help_shell.rs:175` and `crates/nu-cli/src/shell/value_shell.rs:146` because it seems like that's where the actual code for the `cd` builtin is being executed. I'm also quite new to this codebase but it might be an option to move some of the behaviour (how to deal with `.` and `..` for example) outside of those files as it should be the same for other builtins as well.

**Comment by dmeijboom** [comment]
@VincentWo Please let me know if you have sufficient information to go for a PR. If not I can make a PR to fix this.
