### ISSUE TITLE
Add full program invocation to ps ("CommandLine" data on windows)

### ISSUE THREAD

**Issue by AndrewMorsillo** [nushell/nushell#2438]
**Is your feature request related to a problem? Please describe.**
ps doesn't give enough information on Windows to find the processes you want. For example this powershell snippet to kill all gradle processes isn't possible with nushell `ps`

`WMIC PROCESS where "Name like 'java%' AND CommandLine like '%GradleDaemon%'" Call Terminate`

This can't be done with nushell because `ps` doesn't provide the full list of arguments to a command

**Describe the solution you'd like**
Add "CommandLine" or equivalent output of full program invocations to the output of `ps`

**Describe alternatives you've considered**
I don't see any other way around this. The only (bad) alternative with nushell is to kill all java which might not be desirable.

**Additional context**
This affects a very general and I think common case -- find the process id of an invocation of some interpreter like node, java, python, etc. Currently there's no way to differentiate between them on nushell. There could be many unrelated processes with no mechanism to find the specific one you're looking for.

**Comment by jonathandturner** [comment]
For folks who want to help with this one, it looks like this is available via `heim` with this method: https://docs.rs/heim/0.0.10/heim/process/struct.Process.html#method.command

We should probably fold this into `--all`  or via another flag, rather than being in the default `ps` output.

**Comment by dmeijboom** [comment]
@jonathandturner Looks like this is already implemented when using the `--long` flag. Currently it doesn't work on Windows though because of: `#[cfg(not(windows))]`. This was added in march because it crashed on Windows (see: commit 53c8185af386de682eccd9b7729a0b2327ed6421). 

I quickly checked `heim` and it looks like it's still not implemented on Windows :/ (see: https://github.com/heim-rs/heim/blob/master/heim-process/src/sys/windows/process/command.rs#L10). So I don't think someone can actually pick this up.
