### ISSUE TITLE
Crash when creating a numeric range inside another array

### ISSUE THREAD

**Issue by RoastVeg** [nushell/nushell#2442]
**Describe the bug**
I accidentally attempted to use `echo [x..y]` syntax to create a range of numbers, instead of the expected `echo x..y`.

**To Reproduce**
`echo [1..3]`

**Expected behavior**
Returning a single nested table of three rows, as per `[[1 2 3]]` for the example above.

**Configuration (please complete the following information):**
 - OS: Arch Linux
 - Nu version: 0.18.1

**Comment by dmeijboom** [comment]
I quickly looked at the codebase to see what's going on. It seems like this is simply not implemented yet (or so it seems). What I don't get though is why `[1..3]` is evaluated different then `1..3`. Because in the first scenario it panics in `shape.rs` but in the second scenario it simply works. If someone could shed a light on why this isn't recursively evaluated I could go for a PR but for now I don't understand what's exactly going on.

I might create a PR for turning this into a proper error though as it shouldn't panic..

**Comment by jonathandturner** [comment]
@dmeijboom - missed that you were going to fix the crash and ended up putting the fix in https://github.com/nushell/nushell/pull/2455.

There's a question here of what would be expected. Would it make sense that `[1..3]` works the same as `1..3`?

@dmeijboom there are some other outstanding issues with ranges. If you're interested in working on them, I'd be happy to show you

**Comment by dmeijboom** [comment]
> @dmeijboom - missed that you were going to fix the crash and ended up putting the fix in #2455.
> 
> There's a question here of what would be expected. Would it make sense that `[1..3]` works the same as `1..3`?
> 
> @dmeijboom there are some other outstanding issues with ranges. If you're interested in working on them, I'd be happy to show you

> missed that you were going to fix the crash and ended up putting the fix in #2455.
That's okay! Didn't do any work yet :)

>  there are some other outstanding issues with ranges. If you're interested in working on them, I'd be happy to show you
That would be great :+1: I can work on that.

**Comment by jonathandturner** [comment]
@dmeijboom - here's one that came to mind: https://github.com/nushell/nushell/issues/2459

We also don't have a way of range over variables, which would be great.
