### ISSUE TITLE
Consider truncating long decimal numbers

### ISSUE THREAD

**Issue by gillespiecd** [nushell/nushell#2451]
**Is your feature request related to a problem? Please describe.**

This came up in a PR review (https://github.com/nushell/nushell/pull/2447#issuecomment-683346088), I noticed that the `stddev` command can output a very long decimal number.

```
echo [1 4 6 10 50] | math stddev
18.1372544780074142289927665486772038998991290109304180183807006388780888095751453498123844567330072
```

To compare, this is what happens in Python
```
In [3]: statistics.pstdev([1,4,6,10,50])
Out[3]: 18.137254478007414
```

**Describe the solution you'd like**
@thegedge had a good suggestion in the PR comment, there can be two options to consider:

>Truncated: 18.1372544
>Elided: 18.1372544…

**Describe alternatives you've considered**
We could leave as is, but does not seem particularly user friendly to have numbers that take up so much visual real estate. 

Or have a flag to control truncation, leave it up to the user.

**Comment by fdncred** [comment]
What about this? `echo [1 4 6 10 50] | math stddev | str from -d 2`?

**Comment by thegedge** [comment]
@fdncred I think that would work in one-off cases, but wondering if we want the display precision to be configurable, at least in `autoview`? I'm thinking displaying more than half a dozen digits probably isn't valuable.

**Comment by fdncred** [comment]
@thegedge if you're suggesting a config point called precision that works everywhere, I'd support that.

**Comment by thegedge** [comment]
> everywhere

Just to clarify, I was thinking "everywhere" as in everywhere we _display_ a decimal. Everywhere else we should maintain full precision so that results are correct.

But yep, that's what I'm suggesting! 🙂 

My preference would be to show the elided form by default, because it displays nicely and is honest about there being more digits. We could also have a min/max precision for elision, which would give the table display some flexibility in choosing a display precision that makes the end result look really nice.
