### ISSUE TITLE
Hangs when command is followed by a Unix line ending character.

### ISSUE THREAD

**Issue by samuelvanderwaal** [nushell/nushell#2596]
**Describe the bug**
NuShell native and external commands hang when followed by a newline/linefeed character.

**To Reproduce**
1. Open a text editor.
2. Type `ls` followed by the `Enter` key.
3. Copy paste the entire text including the line return to the command line.
4. NuShell will try to execute the command immediately but hang and do nothing.
5. Tested on a variety of commands `ls`, `sys`, `git clone`

**Expected behavior**
NuShell should successfully execute commands that end in a newline character in the same way that other shells like Bash do.

**Screenshots**

![2020-09-23_17-39](https://user-images.githubusercontent.com/1684605/94091059-ba0bb180-fdc3-11ea-95b7-b2f2035021ce.png)

**Configuration (please complete the following information):**
 - OS: Linux -- Manjaro
 - Nu version: v0.20
 - Optional features (if any): default (`cargo install nu`)

**Additional Information**

If this is a good beginner bug I'd be happy to take it if someone can point me to the rough area where I should be looking for the problem code. (`crates/nu-parser/src/lite_parse.rs`?)

**Comment by jonathandturner** [comment]
Doing some experimenting, this looks like an issue in rustyline.. When I do the repro in rustyline's example, I can get the same behavior, which means I have to manually hit enter after the paste to go to the next line.

It may be related to https://github.com/kkawakam/rustyline/issues/202 though might be worth filing a specific issue to see if it's the same.

**Comment by jonathandturner** [comment]
Looks like there's a fix we can take for this, as part of our rustyline setup:

```
editor.bind_sequence(rustyline::KeyPress::BracketedPasteStart
```

Let's see if that helps us work around this issue.

**Comment by jack-greenberg** [comment]
Hi there! If no one else is working on this issue, I'd love to take a look! I am learning Rust currently and this will be my first open source contribution. Do you have any advice on where to get started?

**Comment by ngraham20** [comment]
@jack-greenberg have you started on this or are currently working on it? I'm also interested in this issue if not. If you are, I'll find another issue :)

**Comment by jack-greenberg** [comment]
Hey @ngraham20! I haven't done anything, mostly because I am not sure where to start haha. Feel free to go ahead, and I'll follow along so I can see what you do!

**Comment by wcarss** [comment]
Sorry to scoop the issue @ngraham20, in case you were in the middle of working on it.

I think @jonathandturner's paste above got clipped a little. In the linked thread, @erikgrinaker says to try:
``` rust
editor.bind_sequence(rustyline::KeyPress::BracketedPasteStart, rustyline::Cmd::Noop);
```
and that seems to go roughly here: https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/cli.rs#L672

As a penance for scooping the issue, I wrote up my process of finding and making this fix, for reference for anyone looking at an issue like this and wondering "how do I even get started here?" (e.g. @jack-greenberg or @samuelvanderwaal):

0. I started off thinking: "Okay, someone in-the-know says this is a one line fix, and gave us the line -- I just have to figure out where to put that line, and then test that it's fixed."
1. Without any real clue about where to start looking, I looked for top-level files named `rustyline` or similar. No hits.
2. Since it's an external package, I thought the suggested line might belong in some package configuration, so I looked in `Cargo.toml` at the top level of the nushell project for anything related to `rustyline`. I just did `ctrl+f rusty` in there.
3. No config there that looks like the line I want to add, but there's an indication [here](https://github.com/nushell/nushell/blob/main/Cargo.toml#L68) that rustyline comes from the `nu-cli` section of the code, so I started looking around in `crates/nu-cli`, again at the `Cargo.toml` file.
4. There wasn't anything super informative in the `crates/nu-cli/Cargo.toml` file, so I looked in `crates/nu-cli/src` next, and noticed `cli.rs` -- just on a hunch, I feel like that could be an entry-point part of the `nu-cli` area, so it may have clues about where and how rustyline is initialized, and tell us the next place to look. 
5. After doing `ctrl+f rusty` in that file, there's a ton of hits! What about hits on @jonathandturner's `bind_sequence` call above, to see if we're already doing similar things?
6. `ctrl+f bind_sequence` in there turns up [this](https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/cli.rs#L664), and it's in a function called `default_rustyline_editor_configuration()` -- sounds promising! I'll bet something like this should be set in the default configuration, so this is likely the place to try.
7. But those functions seem like they take _two_ arguments... which doesn't match the code that was suggested.  So I opened back up the original [thread](https://github.com/kkawakam/rustyline/issues/202) and found a slightly different version that does match.
8. Now, I'm going to open a gitpod as is suggested in the [contributing file](https://github.com/nushell/nushell/blob/main/CONTRIBUTING.md) to try it out and run the tests -- I don't want to get bogged down installing/configuring rust this afternoon.
9. I edited the file and modified the line slightly to fit the context:
``` rust
rl.bind_sequence(KeyPress::BracketedPasteStart, rustyline::Cmd::Noop);
```
10. Next, I ran `cargo fmt --all -- --check` as a sanity check. It took a few minutes to run, then it complained about something in some different (albeit nearby) file not being supported yet...  seems like it's not my fault: ignored!
11. Next, I ran `cargo build`. It only took a few minutes. 
12. Then I ran `cargo run`, and tried to repro the case by pasting in:
```
ls
ls

```
... it prints `ls`'s output twice! I also tried with `head -n 1 features.toml`, and `echo "hello"`. `echo` behaves strangely... pasting this:
```
echo "test one"
echo "test two"

```
results in:
```
/workspace/nushell(main)> echo "test one"
/workspace/nushell(main)> echo "test two"
/workspace/nushell(main)> 
```
it seems the output gets  overwritten... but given that `head -n 1` works, as pasting this:
```
head -n 1 features.toml
head -n 1 features.toml

```
results in this:
```
/workspace/nushell(main)> head -n 1 features.toml
[hintsv1]
/workspace/nushell(main)> head -n 1 features.toml
[hintsv1]
/workspace/nushell(main)>
```
I think it may be a separate issue, so we'll move forward with the PR and just note it there.
13. Next, I ran `cargo test --all --features=stable`(again from the [contributing file](https://github.com/nushell/nushell/blob/main/CONTRIBUTING.md)), hoping to heck that there are no test issues, and... nothing popped up broken!
14. Finally, I asked myself: can I add any new tests for this? I don't see anything similar in `crates/nu-cli/tests`, and given it is just a workaround for a library feature... it may not be _worth_ testing. For now, I'll PR the fix on its own, and let the reviewers make suggestions if they feel it's important to add a test.
15. Forked, edited, checked out [a recently merged nushell PR](https://github.com/nushell/nushell/pull/2655) to see what format and info are required / acceptable in a commit message + PR, then committed+opened the PR.

Hopefully following along with my process here has been at least a *tiny* bit illuminating 😄

**Comment by ngraham20** [comment]
All good, I hadn't started yet 👍🏻
