### ISSUE TITLE
scoop install does not include ps and sys built-ins

### ISSUE THREAD

**Issue by s-e** [nushell/nushell#2633]
On Windows 10 (using Windows Terminal), Running `scoop install nu` results in a build (of 0.20.0) that apparently doesn't include `ps` or `sys` built-in commands, which is unfortunate as scoop is listed on the front page of the website as an installation method.

![image](https://user-images.githubusercontent.com/444502/94990263-976f5a80-0572-11eb-919e-99cf1caedc1f.png)

![image](https://user-images.githubusercontent.com/444502/94990274-af46de80-0572-11eb-9760-d5fdb841c489.png)

I asked about this on discord and @andrasio asked me to throw up an issue.

I'll note that installing through `cargo` *without* including the extra features flag works just fine and provides both built-ins.

text output included for searchability:
```
~> scoop install nu
Installing 'nu' (0.20.0) [64bit]
Loading nu_0_20_0_windows.zip from cache
Checking hash of nu_0_20_0_windows.zip ... ok.
Extracting nu_0_20_0_windows.zip ... done.
Running pre-install script...
Linking ~\scoop\apps\nu\current => ~\scoop\apps\nu\0.20.0
Creating shim for 'nu'.
'nu' (0.20.0) was installed successfully!
[11:53:11] PS C:\temp
~> nu
Welcome to Nushell 0.20.0 (type 'help' for more info)
C:\temp> ps
error: Command not found
  ┌─ shell:1:1
  │
1 │ ps
  │ ^^ command not found

C:\temp>
C:\temp> sys
error: Command not found
  ┌─ shell:1:1
  │
1 │ sys
  │ ^^^ command not found

~> scoop --version
Current Scoop version:
6df80c1a (HEAD -> master, origin/master, origin/HEAD) fix(tests): Force pester v4 (#4040)

'extras' bucket:
1b0a843bb (HEAD -> master, origin/master, origin/HEAD) kate: Update to version 20.08.1-1035

'main' bucket:
f1441b6f (HEAD -> master, origin/master, origin/HEAD) nmap: Update to version 7.90

'nerd-fonts' bucket:
6fe7b0c (HEAD -> master, origin/master, origin/HEAD) Merge pull request #89 from vig42/master
```

**Comment by fdncred** [comment]
I think this is because the plugin exe names changed recently to nu_plugin_extra and nu_plugin_core and the wix installer is not including them.

**Comment by houli** [comment]
I'm still able to reproduce this issue with a fresh install of `0.21.0`. I think there was a misunderstanding here regarding wix as installing with scoop does not use the `msi` installer but extracts from the zip file, moves the `nu_plugin_*` files to the `Plugins` directory and puts that directory in your PATH environment variable
https://github.com/ScoopInstaller/Main/blob/master/bucket/nu.json

I can confirm that `C:\Users\<username>\scoop\apps\nu\current\Plugins` is in `$nu.path` and it contains all of the `nu_plugin_*.exe` plugins.

**Comment by fdncred** [comment]
I looked at the zip file and it looks correct. As long as you're running the nu.exe in that directory that has the plugins, then everything should work. 
![image](https://user-images.githubusercontent.com/343840/96032250-06c33500-0e24-11eb-96de-9079d700582d.png)

If the plugins are in a separate directory from nu.exe then you'll have to make a configuration change to the config.toml in order to pick them up. If that's the case you'd have to add/change `plugin_dirs = ["<path to plugins>"]` to the config.toml file.

**Comment by houli** [comment]
![2020-10-14 20_17_14](https://user-images.githubusercontent.com/143868/96035929-a5b75380-0e5b-11eb-8b5b-fbc7558b10fc.png)

It seems to be a problem with how scoop installs nu where it creates a new `Plugins` directory and copies the plugins in there.
Setting the following value for `plugin_dirs` in `config.toml` sure enough did the trick
```toml
plugin_dirs = ["C:\\Users\\<username>\\scoop\\apps\\nu\\0.21.0\\Plugins"]
```

Copying the plugin executables into the folder where `nu.exe` is also worked. So really the issue here is with the scoop manifest file and how scoop is installing `nu`. I suppose this probably warrants fixing given that scoop is listed on the nu website as a supported way to install on Windows.

**Comment by fdncred** [comment]
Thanks for testing. I didn't even know we supported scoop. We may have a contact in the scoop community. I'll ask around.

**Comment by benjivm** [comment]
I installed via scoop (v0.32.0) after reading the [HN post](https://news.ycombinator.com/item?id=27525031) and this is still the current behavior. Placing @houli where is `config.toml` located? I created the file next to `nu.exe` with the correct `plugin_dirs` path specified but still get `sys not found`.

**Comment by fdncred** [comment]
`$nu.config-path` will tell you where `config.toml` is supposed to be.
