### ISSUE TITLE
Table wrap of a utf-8 value gives incorrect width

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2657]
**Describe the bug**
```
> echo [[bar]; [$(char rain)] ]
+---+-------------+
| # |     bar     |
+---+-------------+
| 0 | ☔ |
+---+-------------+
```

**To Reproduce**
1. See above

**Expected behavior**
The above should be able to have the table properly aligned

**Screenshots**

![Screenshot from 2020-10-10 15-51-07](https://user-images.githubusercontent.com/547158/95644087-7679ad00-0b10-11eb-8bd7-85bbc82c4435.png)

**Comment by gillespiecd** [comment]
I took a look and I think the ansi codes in [weather chars](https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/commands/char_.rs#L99-L107) are confusing the `UnicodeWidthStr` heuristics. The simple fix is to move chars to unicode only instead of unicode + ansi. They will then render correctly as a single char, but won't be as dynamic. The better way is to somehow track the width of a "ansi + unicode" string, but that might get complicated (not sure how to do that).  @fdncred What are your thoughts on this?

I have a branch that does the simple fix. Below is the updated view.

![image](https://user-images.githubusercontent.com/6572184/96725176-7aee6300-1365-11eb-888e-fa3ce5855dd4.png)

**Comment by fdncred** [comment]
@gillespiecd Thanks for the research. That's interesting. I wonder if there's a better way. Perhaps replacing these chars with unicode emoji would fix it?

**Comment by fdncred** [comment]
Here's the full weather table.
`echo [ [name, icon]; ['Clear', $(char sun)] ['Clouds', $(char clouds)] ['Rain',$(char rain)] ['Fog', $(char fog)] ['Mist', $(char mist)] ['Haze', $(char haze)] ['Snow', $(char snow)] ['Thunderstorm', $(char thunderstorm)] ]`
┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ # ┃ name         ┃ icon        ┃
┣━━━╋━━━━━━━━━━━━━━╋━━━━━━━━━━━━━┫
┃ 0 ┃ Clear        ┃ ☀  ┃
┃ 1 ┃ Clouds       ┃ ☁  ┃
┃ 2 ┃ Rain         ┃ ☔ ┃
┃ 3 ┃ Fog          ┃ ▒  ┃
┃ 4 ┃ Mist         ┃ ░    ┃
┃ 5 ┃ Haze         ┃ ░    ┃
┃ 6 ┃ Snow         ┃ ❄  ┃
┃ 7 ┃ Thunderstorm ┃ ⚡ ┃
┗━━━┻━━━━━━━━━━━━━━┻━━━━━━━━━━━━━┛
![image](https://user-images.githubusercontent.com/343840/96744280-86a05080-138a-11eb-98e3-45ac9aefa27e.png)

I'd like for the weather symbols to be bigger actually.

**Comment by gillespiecd** [comment]
I believe this is where the width gets calculated for each word: https://github.com/nushell/nushell/blob/adbbcafd30e23847af6ac988385d4f4c74807ea6/crates/nu-table/src/wrap.rs#L60

Sticking to unicode only will keep it consistent, not sure how to render them larger. I agree, making them bigger would like nicer.

**Comment by fdncred** [comment]
If you want to submit a PR with emoji's in place of this mess I did, I'll look at it. It's just about finding the right emojis.
