### ISSUE TITLE
Please confirm the 0.21.0 git tag update was intentional in order to have it picked up by homebrew

### ISSUE THREAD

**Issue by develop7** [nushell/nushell#2680]
So according to https://github.com/nushell/nushell/actions?query=workflow%3A%22Create+Release+Draft%22 the 0.21.0 tag has been actually updated couple of times. That's fine generally, but we at homebrew have picked up an interim version of a tarball and now are unable to build nushell from source (and linuxbrew users are unable to build it at all) due to source hash mismatch. The homebrew policy, however, doesn't allow changing source archive checksum without either version bump or a confirmation the source was changed intentionally. So could you @jonathandturner or someone else drop by at https://github.com/Homebrew/homebrew-core/issues/63093 and do such confirmation, pretty please?

Thank you in advance.

**Comment by jonathandturner** [comment]
@develop7 yes, we had to pull a draft of the release and republish it after a fix was made. Generally we don't want to have to do this, but it sometimes can't be avoided.

Is it possible to trigger the release off the github release rather than the tag?

I'll also swing by homebrew and let them know.

**Comment by develop7** [comment]
@jonathandturner thank you!
