### ISSUE TITLE
Compatibility issues with oh-my-posh

### ISSUE THREAD

**Issue by cdhunt** [nushell/nushell#2703]
**Describe the bug**
I'm trying to use [oh-my-posh](https://ohmyposh.dev/docs/) prompt engine in Nu and running into a few compatibility issues.

1. ~~The main issue is the cursor always shows up on the line after the prompt. I've tried a few variations of calling the exe in the prompt function and I couldn't find a workaround.~~
1. ~~Since Nu calls out to `cmd` to invoke `oh-my-posh.exe` it reports `cmd` as the shell. That's understandable and I don't think it's necessarily something that needs to be fixed by Nu.~~
1. No last exit variable. I can't find any expression that reports the success of the last command. That's a pretty common segment in prompt functions.

EDIT: Issues one and two have been resolved. See comments.

**To Reproduce**
1. Run oh-my-posh 3.23.x as your prompt

**Screenshots**
![image](https://user-images.githubusercontent.com/114173/97177283-7e6e5980-176c-11eb-93f0-2d458cd293c3.png)

**Configuration (please complete the following information):**
 - OS: Windows 10 2004
 - Nu version: 0.21.0

oh-my-posh theme: https://gist.github.com/cdhunt/495992d213745081ee193e1dc3a22965

**Comment by fdncred** [comment]
I ran OMP v3 a few weeks ago and had to turn back to OMP 2 because of bugs. It looks like they've fixed some of them so maybe I should try again. I did notice that nushell was recognized as `cmd` although I'm not sure why. I had a few issues filed about this and integration with nushell in the OMP repo.

Have you looked at the code and do you understand why nushell is being reported as `cmd`?

Related to the cursor position, I noticed that I could redo my config field in a variety of ways and change where the prompt cursor was.

You're right that nushell doesn't report exit codes from any external apps.

**Comment by cdhunt** [comment]
I believe I understand why `cmd` is showing as the shell. I'm pretty sure Nu just invokes `cmd` to run any binary. So, Nu is actually calling the equivalent of  `cmd -c oh-my-posh.exe` so as far as OMP knows, `cmd` is the shell.

I tried some adjustments to my config to eradicate the extra newline, but I'm sharing the config across multiple shells/OSes and all of the others work so I don't want to break them to fix one.

**Comment by fdncred** [comment]
> I believe I understand why `cmd` is showing as the shell. I'm pretty sure Nu just invokes `cmd` to run any binary. So, Nu is actually calling the equivalent of `cmd -c oh-my-posh.exe` so as far as OMP knows, `cmd` is the shell.

I don't believe that is the case. If that were the case, you'd see cmd.exe and under it nushell.exe in Process Explorer when it's showing processes in a tree hierarchy. The only places I see nushell shelling out with `cmd /c` is for calling externals. It could be because `nu.exe` launches `conhost.exe`, which is how windows hosts console applications.

> 
> I tried some adjustments to my config to eradicate the extra newline, but I'm sharing the config across multiple shells/OSes and all of the others work so I don't want to break them to fix one.

Fair enough.

**Comment by JanDeDobbeleer** [comment]
About cursor position, that could be better now as newlines now use `\n` everywhere so there's no need to differentiate between shells on that part. The only thing which could still be an issue is **IF** ANSI escape sequences are still being read as valid characters in the prompt but as far as I've understood, that's not the case.

About the name, it gets the parent process, and according to this it seems to be cmd. I create a small go program which uses the same logic as Oh my Posh to illustrate the issue:

```golang
package main

import (
	"fmt"
	"os"

	"github.com/shirou/gopsutil/process"
)

func main() {
	pid := os.Getppid()
	fmt.Println("PID: ", pid)
	p, _ := process.NewProcess(int32(pid))
	name, err := p.Name()
	if err != nil {
		fmt.Println("NAME: unknown")
		return
	}
	fmt.Println("NAME: ", name)
}
```
<img width="627" alt="afbeelding" src="https://user-images.githubusercontent.com/2492783/97875851-47271c00-1d1b-11eb-8ae7-64dc88d69d90.png">

It's interesting to know that on each invocation of the program, the reported PID is different. So something is calling shell commands inside of `CMD`.

**Comment by cdhunt** [comment]
I tested the logic in OMP.

```go
package main

import (
	"fmt"
	"os"

	ps "github.com/mitchellh/go-ps"
)

func main() {
	pid := os.Getppid()
	p, _ := ps.FindProcess(pid)

	fmt.Println(pid)
	fmt.Println(p.Executable())
}
```

![image](https://user-images.githubusercontent.com/114173/97875880-057d7d80-1ce9-11eb-89e1-3e25cae85f8a.png)

This is from the [standard OS library](https://golang.org/pkg/os/#Getpid).

`func Getpid() int`
> Getpid returns the process id of the caller.

**Comment by fdncred** [comment]
@JanDeDobbeleer Thanks for pointing this out. I had just tracked down this piece of code in OMP3. :) I was originally thinking it was getting the shell name from an environment variable but it appears to get the name from `Process Name`, as you suggest.

As far as a different PID on each invocation, that is expected on Windows due to the amount of crap the Windows is always running. PIDs do, in fact, get reused and are reusable as soon as the process exits.

> Getpid returns the process id of the caller
Are you saying `cmd.exe` is calling your `test.exe`?

**Comment by JanDeDobbeleer** [comment]
In regards to the last statement, yes, it appears so. Every statement in nushell on Windows seems to be called via CMD (tried to find out how but no success). About the PID reuse, it's not doing that for Powershell (or not as frequent that I could see), whereas for nushell it does seem every command gets a new invocation of CMD running the command. But I lack info/insights in seeing where nushell contains this logic.

**Comment by cdhunt** [comment]
Found the code. Any external command is invoked via `cmd /c` on Windows.

https://github.com/nushell/nushell/blob/c6fe58467be8960e6c951b7ff3e8bf81d9134a27/crates/nu-cli/src/commands/classified/external.rs#L149-L161

**Comment by fdncred** [comment]
@cdhunt You'll notice that the code you referenced is in `external.rs` which is for running command external to nushell. nu.exe is not an external command.

@JanDeDobbeleer I don't see how it's possible for `cmd.exe` to be calling `nu.exe` before it's even launched. However, in your examples, you appear to be in `nushell` and since your compiled exes are not internal commands they are being run as external commands which is using the code @cdhunt just mentioned. 

Are we all talking about the same thing? I'm talking about why `nu.exe` is being recognized by go as `cmd.exe` not how external commands are being recognized.  Either way, I appreciate the conjecture. I definitely want to solve this problem.

**Comment by JanDeDobbeleer** [comment]
We're saying the same thing 😁. Basically we have no way to identify the shell's name like we do for other shells due to this. Semantically, the reported parent is correct, but ideally its name is nu rather than CMD. However, I have no idea how to achieve that, changing a process name isn't supported out of the box looking at `std::process::Command` so I might have to figure out a fix in Oh my Posh.

**Comment by fdncred** [comment]
I'm trying to look into the go code too. What i've seen so far is that it's just calling normal Windows API things.  I wonder if the problem is that nu.exe has no "normal" windows properties. i.e. If I figure out how to add a `Product Name` I wonder if it would be recognized.
![image](https://user-images.githubusercontent.com/343840/97882270-0dd5b880-1ce9-11eb-8307-d2e845b60cbe.png)

**Comment by JanDeDobbeleer** [comment]
I don't think we can fix this without changing how nushell executes commands on Windows.

**Comment by fdncred** [comment]
oh, i think i finally see what y'all are saying. OMP3 is an exe, which is being called from withing nushell and happens to be external. So, of course, nushell is shelling out with cmd /c to run OMP3 and therefore OMP3 see's the parent process as cmd.exe.  Makes perfect sense now. Duh, sorry for being so obtuse.

I'm not sure how to change how nushell executes commands on windows. I'll have to research it a bit. Maybe there's some parameters with startprocess or something.

**Comment by cdhunt** [comment]
This is a design decision mentioned in the [README](https://github.com/nushell/nushell#status).
> If a command is unknown, the command will shell-out and execute it (using cmd on Windows or bash on Linux and macOS),

**Comment by cdhunt** [comment]
It would likely be possible to add some logic that would let OMP run as a nushell plugin therefore making it an internal command.

https://vsoch.github.io/2019/nushell-plugin-golang/

That's beyond the time commitment I'm willing to make at the moment.

**Comment by fdncred** [comment]
@JanDeDobbeleer How about this suggestion? I thought I remembered reading somewhere that OMP3 wasn't going to work with cmd.exe. If that's the case, couldn't you get the process name and if it's cmd get that processes name? i.e. get the grandparent name instead of the parent name?

**Comment by JanDeDobbeleer** [comment]
That could work. I already have the grandparent code 😅

**Comment by JanDeDobbeleer** [comment]
Validated and merged. Also @cdhunt it seems I now no longer have the issue with the newline in nu shell. Might be interesting to check on your end as well.

**Comment by fdncred** [comment]
Thanks @JanDeDobbeleer !!! I'm going to try it out sometime today. Need to find some time. I love what you've done with OMP!

**Comment by cdhunt** [comment]
@JanDeDobbeleer 👍 for the quick fix for Nu. It doesn't appear to have fixed the new line issue for me. I'll mess around with the config some and see if I can find an offending segment.

**Comment by JanDeDobbeleer** [comment]
In theory a segment can't introduce a newline (unless it prints \n). Keep me posted, I tested this on Windows and MacOS with the paradox theme.

**Comment by cdhunt** [comment]
Fixed my prompt syntax from `oh-my-posh -config ...` to `echo $(oh-my-posh -config ...` and that removed the extra newline.

The only remaining issue is no way to get last command success.

**Comment by fdncred** [comment]
OMP3 is working much better now for me too with the recent changes!

> The only remaining issue is no way to get last command success.

@cdhunt Last command success/exit codes are not supported in nushell at this time. I'd like to see them added at some point.

**Comment by fdncred** [comment]
@JanDeDobbeleer btw - I'm having some pretty serious issues with wrapping on OMP3. I think i'm going to have to revert. I just added https://github.com/JanDeDobbeleer/oh-my-posh3/issues/128
