### ISSUE TITLE
Pipe from string list to rm

### ISSUE THREAD

**Issue by acanalis** [nushell/nushell#2824]
##  Current 

The currently (Nushell 0.24.1) `rm` accepts blob patters, and arbitrary number of arguments (where at least one of them should be a valid path to remove). 

For advanced uses where the blob patterns aren't enough, some filtering is needed. For example, to delete the first 5 files in the current directory in alphabetical order, this is acceptable:

```nu
ls | get name | sort-by | first 5 | each {rm $it}
```

However, this requires the user to be familiar with how `each` works. 

## Proposed

Knowledge of `each` wouldn't be necessary if piping a list of strings to `rm` were possible: 

```nu 
ls | get name | sort-by | first 5 | rm
```
note: This syntax currently fails with "error: rm requires target paths"

The resulting syntax is simpler, easy to understand conceptually, and works well with other tools like `str`. 

## Alternatives
`rm`  could accept rows from ls directly (notice that the `get name` filter is missing) :
```nu 
ls | sort-by name | first 5 | rm
```
However, this could limit the usefulness of rm. For example, if someone has a list of files to delete,  the following wouldn't be possible: 

```nu
open deletethese.txt | lines | rm
``` 
This is a contrived example, but there might be other missed opportunities with string manipulation and data contained in other forms. 

## Additional context
This was discussed in [Discord](https://discord.com/channels/601130461678272522/601130461678272524/791536860211183616)

## Generation of full example 
```nu
mkdir example | seq 100 | each {touch $(random chars)} 
ls | get name | sort-by | first 20 | each {rm $it}
```

**Comment by acanalis** [comment]
Worth mentioning here: 

Arguably, all the functions that take multiple arguments should be list-pipeable. Most of them already are, but it would be a great simplification of the model if all of them did. 

Right now, the list of all commands that have "...args" in the help description are: 

build-string, compact, echo, empty?, exec, flatten, get, hash, help, histogram, inc, into-int, kill, mkdir, move, nth, pivot, reject, rename, rm, select, seq, sleep, sort-by, str, touch. 

(Proudfully queried using `help commands | where $(help $it.name | str contains "...args") | get name | str collect ", "`)

**Comment by myrrlyn** [comment]
An `xargs`-alike that translates from a stream to an argument splat would be a great stopgap.

```sh
seq 2 5 | each { echo `{{$it}}.txt` } | str collect ' ' | ^xargs touch
seq 2 5 | each { echo `{{$it}}.txt` } | str collect ' ' | ^xargs rm
```

correctly creates and destroys `2.txt` through `5.txt`, but because `xargs` is an external command and receives bare text, it must be prefixed with a `str collect ' '` in order to parse the stream as text rather than an iterable.

Ideally I too would prefer that commands which expect 1+ argument would, when presented with 0 arguments, switch to pulling from the pipeline instead; however, this can easily be done with one adapter command before the rest of the command set gets this behavior.

**Comment by deeuu** [comment]
Hey all,
As a new user, I too was disappointed to find that `| rm` did not work as expected. This feels more natural than wrapping with `each`, though admittedly I wasn't aware of the `each` command.

Thanks for the great shell!

**Comment by Cody-Duncan** [comment]
Example in the latest version of nushell

1. Create 100 files:
`seq 100 | each {touch (random chars)} ` 
(no output)

2. Delete the first 20 files sorted by name
`ls | get name | sort-by | first 20 | each { |it| rm --verbose $it } `
```
╭────┬───────────────╮
│  0 │ [list 1 item] │
│  1 │ [list 1 item] │
│  2 │ [list 1 item] │
│  3 │ [list 1 item] │
│  4 │ [list 1 item] │
│  5 │ [list 1 item] │
│  6 │ [list 1 item] │
│  7 │ [list 1 item] │
│  8 │ [list 1 item] │
│  9 │ [list 1 item] │
│ 10 │ [list 1 item] │
│ 11 │ [list 1 item] │
│ 12 │ [list 1 item] │
│ 13 │ [list 1 item] │
│ 14 │ [list 1 item] │
│ 15 │ [list 1 item] │
│ 16 │ [list 1 item] │
│ 17 │ [list 1 item] │
│ 18 │ [list 1 item] │
│ 19 │ [list 1 item] │
╰────┴───────────────╯
```

Note that even though the `rm` command was given the `--verbose` flag, the output did not print the list of deleted files. It only reported the number of deleted elements.


Piping directly to rm does not work
```
Error:
  × rm requires target paths
   ╭─[entry #93:1:1]
 1 │ ls | get name | sort-by | first 20 | rm
   ·                                      ─┬
   ·                                       ╰── needs parameter
   ╰────
```

Deleting with multiple file parameters and the `verbose` flag does report the deleted files (expected behavior)
```
rm zS5J04CbTDoSVpBhItwbf8x2B zHtZrS7DURxytDeScKEF2YpxT --verbose                                                                                                                                             08/20/2022 12:25:44 AM╭───┬─────────────────────────────────────────────────────────────────────────────────╮
│ 0 │ deleted G:\bungie\v700_worlds\tiger\temp\reports\junk\zHtZrS7DURxytDeScKEF2YpxT │
│ 1 │ deleted G:\bungie\v700_worlds\tiger\temp\reports\junk\zS5J04CbTDoSVpBhItwbf8x2B │
╰───┴─────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by hustcer** [comment]
The output is a list of list, You need to flatten it like this: `ls | get name | sort-by | first 5 | each {|it| rm -v $it } | flatten`
