### ISSUE TITLE
Add icon in the project and release folder

### ISSUE THREAD

**Issue by kameko** [nushell/nushell#2872]
Not a duplicate of https://github.com/nushell/nushell/issues/528, I recommend adding an icon in the folder of the executable itself. When I added Nu to my Windows Terminal, it didn't have an icon, so I had to make one myself. It would also be good for non-Windows platforms to have access to the icon for their own system GUIs.

**Comment by fdncred** [comment]
Here's a few we've tried out. Which is your fave?

1. ![nushell-original](https://user-images.githubusercontent.com/343840/103777144-0fc43c80-4ff6-11eb-9b6c-eee486bc382b.png)
2. ![nushell-round-black2](https://user-images.githubusercontent.com/343840/103776930-c8d64700-4ff5-11eb-9adb-a32667a3db9d.png)
3. ![nushell-round-black4](https://user-images.githubusercontent.com/343840/103776932-c96edd80-4ff5-11eb-9633-af10c803641b.png)
4. ![black-white](https://user-images.githubusercontent.com/343840/103776933-ca077400-4ff5-11eb-8316-35d5eafe6006.png)
5. ![green-black](https://user-images.githubusercontent.com/343840/103776935-caa00a80-4ff5-11eb-8fe8-034299c90859.png)
6. ![green-white2](https://user-images.githubusercontent.com/343840/103776937-cb38a100-4ff5-11eb-8db3-f25a4180f42c.png)
7. ![green-white6](https://user-images.githubusercontent.com/343840/103776941-cbd13780-4ff5-11eb-9b6a-9f5d95496ed3.png)
8. ![green-white7](https://user-images.githubusercontent.com/343840/103776943-cc69ce00-4ff5-11eb-9192-f48357e1c6d0.png)
9. ![green-white-black-circle](https://user-images.githubusercontent.com/343840/103776944-cd026480-4ff5-11eb-9b76-79c28d3cd0c7.png)
10. ![nushell-round-black](https://user-images.githubusercontent.com/343840/103776946-cd026480-4ff5-11eb-8aa9-0726e1f33ba4.png)

**Comment by kameko** [comment]
5 is probably both the most unique and best for very small icons. 1, 2, 3 and 10 probably wouldn't scale too well if they got too small, 7 and 8 are far too generic and could get confused with icons such as the default GNOME icons for the terminal, 9 looks too much like a face, and I don't feel like the white greater-than in 4 and 6 fit Nu since it's favicon on the website is a green greater-than. But that's just my opinion.

**Comment by jmoore34** [comment]
Seconded on 5 looking the most unique

**Comment by ehawman-rosenberg** [comment]
If you would allow me to necro this topic, I whipped up a preview board with variously resized icons.
![nu_preview](https://user-images.githubusercontent.com/81652082/169419921-fac64159-ca52-444c-b4b1-5aa80ffbdf50.png)
Now, the resizing was done via https://hotpot.ai/icon-resizer and as such you will likely have better luck if this is manually done, but it gives a decent impression of which icons are going to survive the favicon transformation and which wont.

IMHO, 10 is the clear winner, being unique enough to stand on its own right while also conveying that uniqueness at small sizes. 

9, 8/7 (I prefer 8 of the two), and 1 are runners up. 

I don't hate 6 or 5 but they seem a bit too generic even with the unique color (7 and 8 have a unique resolution to fall back on).

I love what 2 and 3 are going for (they're very similar to my favorite, after all), but I think the shell just dissolves into nothingness far too early.

4 is... a generic terminal-emulator logo.

**Comment by fdncred** [comment]
ya, 10 is cool!

**Comment by NotTheDr01ds** [comment]
An attempt to recreate (with some vibe-coding from Gemini) the Nushell Discord logo as a scalable SVG:

<img src="https://github.com/user-attachments/assets/1db1ad10-c48b-43ac-acbe-14d9720c3977" width="32" /> <img src="https://github.com/user-attachments/assets/1db1ad10-c48b-43ac-acbe-14d9720c3977" width="64" /> <img src="https://github.com/user-attachments/assets/1db1ad10-c48b-43ac-acbe-14d9720c3977" width="128" /> <img src="https://github.com/user-attachments/assets/1db1ad10-c48b-43ac-acbe-14d9720c3977" width="256" />

**Comment by fdncred** [comment]
very cool! nice work!

**Comment by ehawman-rosenberg** [comment]
![Image](https://github.com/user-attachments/assets/ee131459-e009-4bf3-8100-386f2c194802) ![Image](https://github.com/user-attachments/assets/7fcfef86-31ac-4fde-a0bd-f661d9344ae5) ![Image](https://github.com/user-attachments/assets/ceebec7f-6ca0-4f8f-b4f9-42538e2441d6) ![Image](https://github.com/user-attachments/assets/3f28a574-14ff-4ba9-963c-3be208a0a118) ![Image](https://github.com/user-attachments/assets/ab01106a-d43e-4d07-bf81-ca28a4c10ebb) ![Image](https://github.com/user-attachments/assets/38b4b329-1dba-4e83-beab-63b36166a7f9)

First of all, kudos to the designer because that looks incredible. And kudos to you for making it a svg.

I am seeing a weird line artifact. The `n` object/group isn't being properly masked. The mask ends at the bottom of `n`, so you get a single line there.

<img width="1496" height="687" alt="Image" src="https://github.com/user-attachments/assets/386045e4-907d-4626-bf50-9c1fa69bc0d0" />

Also, the image can vary wildly based on which application/platform is doing the rendering. That's because the letters are text, not paths.

This version:
1. Extends the mask an extra unit down
2. Converts text to paths
3. Assigns descriptive labels to most things
4. Adds some other elements for accessibility, including `<title>` and `aria-label` for screen readers
5. Strips out unnecessary elements and includes a minimized version (thanks to [SVGOMG](https://svgomg.net/))!

## Full w/ comments:
![Image](https://github.com/user-attachments/assets/ee131459-e009-4bf3-8100-386f2c194802) ![Image](https://github.com/user-attachments/assets/7fcfef86-31ac-4fde-a0bd-f661d9344ae5) ![Image](https://github.com/user-attachments/assets/ceebec7f-6ca0-4f8f-b4f9-42538e2441d6) ![Image](https://github.com/user-attachments/assets/3f28a574-14ff-4ba9-963c-3be208a0a118) ![Image](https://github.com/user-attachments/assets/ab01106a-d43e-4d07-bf81-ca28a4c10ebb) ![Image](https://github.com/user-attachments/assets/38b4b329-1dba-4e83-beab-63b36166a7f9)

## Minimized:
![Image](https://github.com/user-attachments/assets/31cc4f27-a7c6-463d-8959-7e3192a0bb1e) ![Image](https://github.com/user-attachments/assets/4f72df41-5a69-47c9-9782-9671b5015702) ![Image](https://github.com/user-attachments/assets/26f55a1b-1f64-40c5-8477-c13e7dbac7f7) ![Image](https://github.com/user-attachments/assets/94ee2fa8-acc8-4e29-a791-fc87cf2eab3a) ![Image](https://github.com/user-attachments/assets/f7d9b259-60e3-4021-b0e7-9697e5e8aec8) ![Image](https://github.com/user-attachments/assets/68073516-0185-4976-8d04-dd110db5bdfb)

I learned a lot editing this and had a great time!

If there are still issues I missed please let me know.

**Comment by fdncred** [comment]
I'm getting some jaggies when zoomed in Affinity. Not sure why.

<img width="2298" height="1323" alt="Image" src="https://github.com/user-attachments/assets/b32430ac-9400-4e82-8efa-361e2bb781a0" />

**Comment by ehawman-rosenberg** [comment]
@fdncred I believe that's because mask uses rasterization, and the settings here might not be perfect for it. Tell me how this one looks to you. It uses clipPath instead of mask. I did mess with the viewBox and stuff so it might get wonky.

![Image](https://github.com/user-attachments/assets/0720098b-8abb-4b43-b091-606c7ab45a1c)

**Comment by fdncred** [comment]
ya, that's much better. thanks! now i can just change the background to black like it should be and we're all set.

<img width="3328" height="2038" alt="Image" src="https://github.com/user-attachments/assets/2dbc33e7-6bb9-457c-bf7b-814885225ece" />

**Comment by fdncred** [comment]
I'm not sure how macos decides to render desktop icons but through the iterations of this svg, i've seen many different ones and this one is different again, LOL.

<img width="489" height="292" alt="Image" src="https://github.com/user-attachments/assets/07353f60-be0d-4ddb-81ac-7e03d8f6aa0a" />

**Comment by ehawman-rosenberg** [comment]
Oh that's just great. I found out that Qt6 doesn't implement clipPath either, so KDE users get this nonsense:

<img width="351" height="327" alt="Image" src="https://github.com/user-attachments/assets/6273d44b-57b3-4ec6-960d-96c129b9bc49" />

Is there a better way to implement masks that we're missing? Is there a way we can just manually edit the paths to achieve the same result? What did people do before these "advanced" tools?

Art people help us out!

**Comment by ehawman-rosenberg** [comment]
Aha! I figured it out. Rather than using fancy path tools and multiple objects, I just turned on snapping, moved two nodes to the intersection between my object and its clip, deleted the excess nodes, then straightened the path between them. I'm almost positive that's the "correct" way.

Arrow-upper during editing in Inkscape: clip gone, nodes snapped, extra points deleted:
<img width="968" height="724" alt="Arrow-upper during editing in Inkscape: clip gone, nodes snapped, extra points deleted." src="https://github.com/user-attachments/assets/d85891a4-9348-4260-8db5-96c8a887d5dd" />  

No transforms. No clips. No masks. The lightest of footprints.

``` svg
<svg xmlns="http://www.w3.org/2000/svg" id="nushell-logo" aria-label="new shell logo" viewBox="0 0 100 100">
  <title>Nushell Logo</title>
  <rect id="background-rect" width="100%" height="100%" fill="#000" stroke-width=".5" rx="20"/>
  <path id="arrow-lower" fill="#ccc" stroke-linecap="round" stroke-linejoin="round" d="M82.265 47.436l-19.388 10.48v6.17L84.846 52.21a2.714 2.714 0 1 0-2.58-4.775z" overflow="visible"/>
  <path id="arrow-upper" fill="#fff" stroke-linecap="round" stroke-linejoin="round" d="M62.877 41.732l19.388 10.48a2.714 2.714 0 1 0 2.58-4.776L62.878 35.56z" overflow="visible"/>
  <path id="n-path" fill="#00dc82" stroke-width=".5" d="M13.73 62.62V31.347h4.77v4.447c2.297-3.436 5.614-5.153 9.953-5.153 1.884 0 3.611.343 5.182 1.03 1.59.668 2.778 1.551 3.563 2.65.785 1.1 1.335 2.405 1.649 3.916.196.982.266 3.975.27 6.428l-5.301 5.301c-.004-2.159-.181-10.138-.593-11.199-.412-1.08-1.149-1.933-2.209-2.561-1.04-.648-2.267-.971-3.68-.971-2.258 0-4.211.716-5.86 2.148-1.63 1.434-2.444 4.153-2.444 8.157v17.078z"/>
  <path id="u-path" fill="#00684a" stroke-width=".5" d="M54.427 68.65v-4.592c-2.435 3.533-5.742 5.3-9.924 5.3-1.845 0-3.572-.353-5.182-1.06-1.59-.707-2.777-1.59-3.562-2.65-.766-1.08-1.305-2.395-1.62-3.946-.215-1.04-.323-4.761-.323-7.019l5.3-5.3c0 2.767.108 9.973.324 10.935.334 1.394 1.04 2.493 2.12 3.298 1.08.785 2.415 1.178 4.004 1.178 1.59 0 3.083-.403 4.477-1.207 1.393-.825 2.375-1.934 2.944-3.328.589-1.414.883-3.455.883-6.124V37.38h5.3v31.27z"/>
</svg>
```
![Image](https://github.com/user-attachments/assets/8bb6077b-564f-47bd-827a-2428bcf55c40)

And here's one with just the nu, which I love the symmetry of.
![Image](https://github.com/user-attachments/assets/23ef985e-1ad5-4df5-b655-d5f1b818a9ed)

**Comment by fdncred** [comment]
Yup, looks better now! Thanks!
