### ISSUE TITLE
Allow clearing definitions in a current scope

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#2876]
**Is your feature request related to a problem? Please describe.**
Model scenario: I want to create a shorthand to a command with `alias foo = ...` but realize i need `def foo [] { ... }` to do the job. Since alias takes precedence (see #2875) and I already have `foo` defined as alias from previous experiments, I need to exit and run nu again to clear the namespace.

Ideally, there would be a way to detach a name from its definitions in the current scope.

**Describe the solution you'd like**
* `forget` command that would detach any definitions connected to names passed as arguments (e.g. `forget ll` would forget the existing `alias ll = ls -l` in the current scope).
* `forget --all` would restore the current scope to the default state. This is different from closing and opening nu because you can use it inside scripts and inside blocks in those scripts without touching outer scopes.

**Additional context**
Related to #2875.

**Comment by fdncred** [comment]
Here's a bit of repro research:

by playing around the other day i figured out that you can do something like this:

`alias foo = ls`

then you can execute `foo` and it does the `ls` as expected
if you want to remove that alias from the current scope you can do

`alias foo = ''`

then if you do `foo` you'll get `command not found`

then if you do `def foo [] { ls }` you can define `foo` as a `custom command` but there seems to be a bug because if you try to execute this new `custom command` `foo` it returns `command not found`.

if you exit out of `nushell` and restart it you can then do `def foo [] { ls }` and then execute `foo` just fine.

then you can do `def foo [] {}` and it doesn't really re-define it but it doesn't do anything. at that point you can do `alias foo = ls` and then execute `foo` and as expected it will return the directory listing.

however, if you do a `which foo` it reports `foo` as a `nushell custom command`

**Comment by kubouch** [comment]
There is `unlet-env` now. Do we want to have this for variables / defs / aliases?

**Comment by adsick** [comment]
@kubouch is making sense.

**Comment by kubouch** [comment]
Solved with `hide`
