### ISSUE TITLE
Possible Malware

### ISSUE THREAD

**Issue by gfleetwood** [nushell/nushell#2980]
Hi. I'm a rust novice who checked your project a while back to see what it was all about. Recently my computer (Ubuntu 20.04) has been running slowly and freezing so I decided to do a virus scan with ClamAV. The results turned out these suspicious files:

```
/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/**nu-0.15.0**/tests/fixtures/formats/sample.eml: Html.Phishing.Auction-308 FOUND
/home/user/.cargo/registry/cache/github.com-1ecc6299db9ec823/**nu-0.15.0.crate**: Html.Phishing.Auction-308 FOUND
```

I ended up deleting the entire .cargo directory since I don't actually use Rust - just installed a few rust based programs. Just wanted to raise this and see if anyone knew what it was about.

**Comment by andrasio** [comment]
@gfleetwood Hey! Thanks for the heads up. This was a sample file used as fixture in the unit tests of the project. Precisely because virus scanners flags it as suspicious it was removed since, [here is the change](https://github.com/nushell/nushell/pull/2445).

Please update to Nu latest version (yours is quite old! `0.15`, today we are at `0.26`)

Thank you.

**Comment by gfleetwood** [comment]
@andrasio Good to know. Thanks!
