### ISSUE TITLE
Should `in` and `not-in` work on strings

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#3087]
Right now we have `=~` and `!~` to check for substring matches. Honestly, though, it always takes me a few seconds to remember them and what order things go in.

Can we just use `in` and `not-in` and if both sides are strings do the substring check?

**Comment by fdncred** [comment]
I always start with `contains` (dotnet syntax) then wish for `like` (sql syntax) then try to remember `=~`. `in` and `not-in` are not even on my radar. lol. but it does seem intuitive that `in/not-in` should 'just work'.

**Comment by andrasio** [comment]
mmm... I have more mental stops with whether it is `=~` or `~=` but knowing that `!` always means `not` in normal equal sign then I remember `~` goes like `=~` or `!~`

This is weird because when I suggested that operator, it was meant to take patterns and regex it against the string (not check for substring matches).

**Comment by andrasio** [comment]
What about leaving `!~` and `=~` to take patterns and pattern match it against the left hand side of the operator and also let the behavior for substring checks in the `in` and `not-in` operator?

**Comment by kubouch** [comment]
Even though I like the operators, I would vote for removing `=~` and `!=`, replacing them with `in` and `not-in`, and have them just checking substrings. That would make it very similar to well-known Python for example.

There is the `match` command that handles regex and can take additional flags while the operators can't. I would avoid feature duplication in this case.

**Comment by andrasio** [comment]
@kubouch it's not relevant whether something is duplicated elsewhere, (like first and keep commands for example)

It's more about the syntax. See =~ usage for comparing against a regex literal (pattern type in Nu's case) in Ruby.

**Comment by andrasio** [comment]
@kubouch [here in use](https://docs.ruby-lang.org/en/2.0.0/Regexp.html)

**Comment by kubouch** [comment]
I see, thanks for the link @andrasio. Didn't know it's actually used somewhere else as well.

My line of thinking is that `=~` and `match` require different syntax. If you happen to use `=~` and realize you need some extra flags from `match`, you'd need to redo the pipeline. But now thinking about it, `match` right now requires a column, so having a quick way to compare against a literal (e.g., `=~` operator) would be nice. Otherwise, you'd have to `echo | wrap` every time you want to use regex. So yeah, having a command that operates on structured data and an operator that operates on literals sounds good. Then, `in` and `not-in` for substrings.

**Comment by andrasio** [comment]
@kubouch Yes, sir. Mostly used in comparisons like `ls | where name ~= my_pattern` is what I meant. It's practical.

**Comment by kubouch** [comment]
@andrasio Your particular example is a good use case for `match`: `ls | match name my_pattern`. I see the main use case of regex operators with plain values. Even with modified `match` that doesn't require the column arg, the operator would still be easier e.g. in this case: `if $some-var =~ pattern {} {}` vs. `if $(echo $some-var | match pattern) {} {}`
