### ISSUE TITLE
Clearing the screen in vi mode with CTRL-L

### ISSUE THREAD

**Issue by lokegustafsson** [nushell/nushell#3158]
This might be a bug or the intended behavior. Either way, it surprised me. I run nu version `0.27.1` with `edit_mode = "vi"` and I want to clear the screen. In fish this would just be `CTRL-L`, which works in both insert and normal mode. In nu I must enter normal mode, then do `CTRL-L`. This usually works the first time but sometimes I need to press the combination twice. I find this very unintuitive. Bug or intended behavior? Am I doing something wrong?

**Comment by fdncred** [comment]
This could have something to do with `nushell` using an older version of `rustyline`, the line editor that controls such things as you describe, but I'm not positive. I'd like to get us current with `rustyline`. I'm not really sure what the blockers are to it right now.

**Comment by jonathandturner** [comment]
@fdncred last time we tried to update rustyline, we were losing output that should be printing to the screen (like `echo 1`)

They may have fixed it since then

**Comment by fdncred** [comment]
@jonathandturner agreed. #2776 was the PR. I wonder if we can just pull that code back out, update the dependency and run with it. or better yet, get the original author @gillespiecd to chime in on what he thinks.

**Comment by gillespiecd** [comment]
> I wonder if we can just pull that code back out, update the dependency and run with it

That would be my suggestion.

There were quite a lot of tricky, breaking changes to the Rustyline API when I tried to update, so it might help to use my old PR as a template and go from there rather than starting from scratch and re-implementing. There may also be Rustyline improvements since then, perhaps fixing the bug, since it was a while ago.

Unfortunately I don't have much free time these days, otherwise I would give it another go.

**Comment by fdncred** [comment]
version 8.0 of rustyline has the same issue :(

**Comment by ahkrr** [comment]
I have also encountered this behaviour. 
For me the this occurs if I press only `ESC` and directly afterwards `CTRL-L`. 
It seems there is a slight delay until the exit from insert mode occurs. 
If I press `CTRL-L` in that time frame, it doesn't register.
To reproduce this behaviour, type some characters into the line ( to more easily see the transition from insert to normal mode ) 
then press `ESC` and look for the cursor to shift one to the left. This is the time delay where `CTRL-L` doesn't register.
I am currently testing `rustyline 8` and it seems to still be the case. 
If I am not doing something wrong, it might be even more annoying, because it seems that when I press `ESC` and then `CTRL-L` in that time frame without any other key in between, it seems to cancel the switch to normal mode, needing me to press ESC once again and then wait a moment, to be sure that the problem doesn't happen once again.
