### ISSUE TITLE
Column width incorrectly computed

### ISSUE THREAD

**Issue by jakobnissen** [nushell/nushell#3229]
**Describe the bug**
Some strings of text cause the coulmn width to be incorrectly computed, if it contains the string "VOF NGS rådata og behandling.docx"

**To Reproduce**
1. Create a table with one column called `VOF NGS rådata og behandling.docx`, e.g. by creating a file with that name and running `ls`
2. Run it through `autoview`

**Expected behavior**
Should be obvious

**Screenshots**
```
/Users/jakobnissen/Downloads/test/test> cat test.txt
VOF NGS rådata og behandling.docx|a
/Users/jakobnissen/Downloads/test/test> open test.txt | split column '|'
───┬────────────────────────────────────┬─────────
 # │              Column1               │ Column2
───┼────────────────────────────────────┼─────────
 0 │ VOF NGS rådata og behandling.docx │ a
───┴────────────────────────────────────┴─────────
```

**Configuration (please complete the following information):**
```
/Users/jakobnissen/Downloads/test/test> version | pivot
───┬────────────────────┬───────────────────────────────────────────────────────────────────
 # │      Column0       │                              Column1
───┼────────────────────┼───────────────────────────────────────────────────────────────────
 0 │ version            │ 0.28.0
 1 │ build_os           │ macos-x86_64
 2 │ rust_version       │ rustc 1.50.0
 3 │ cargo_version      │ cargo 1.50.0
 4 │ pkg_version        │ 0.28.0
 5 │ build_time         │ 2021-03-09 22:34:29
 6 │ build_rust_channel │ release
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term,
   │                    │ uuid, which, zip
───┴────────────────────┴───────────────────────────────────────────────────────────────────
```

**Comment by jakobnissen** [comment]
This is still relevant.

**Comment by fdncred** [comment]
Dealing with column widths an unicode characters is still an issue. I'm not sure what the solution may be. We're always open to suggestions.

**Comment by fdncred** [comment]
Multibyte characters are still a problem in 0.59.1
"VOF NGS ra\u{30a}data og behandling.docx"

**Comment by fdncred** [comment]
Yes, it's impossible to be perfect with this. We've used and are using most of these things, not the julia function ofc, and what we've found is that it's beyond measuring. Measuring the width of a word/character/symbol is part of it but the other part deals with how terminal render these code points as well. And the last thing that comes into play is streaming data. In nushell, we don't always collect data before outputting it to the screen. It can be streamed bit-by-bit, which means, there's no way to measure all the column widths because we haven't seen all the data. Of course, we could cache 1000 rows and establish widths that way, and I'd like someone to do that, but that technique isn't implemented yet.

You can see some of the things I've personally tried here https://github.com/nushell/nushell/blob/10d805c1fae2d4f71e6c039c2318ab0a0c1c9427/crates/nu-table/src/wrap.rs#L93-L122 I've left it with what I thought was the best at the time. We're definitely open to improving this in any way we can.

**Comment by jakobnissen** [comment]
The problem I reported in OP pertains to `å`, which is a single non-ligature char. So it looks to me like the function you just provided should correctly handle `å`. Perhaps that means the original issue is elsewhere in the code?

**Comment by jakobnissen** [comment]
The following program - a simplified version of your code:
```
use unicode_width::UnicodeWidthStr;

fn main() {
    let s = &std::env::args().collect::<Vec<_>>()[1];
    let c = s.chars().count(); 
    let u = s.width();
    println!("\"{}\" {}", s, std::cmp::max(c, u));
}
```
Run with `cargo run rådata`, produces
```
"rådata" 6
```
Which is correct.

**Comment by fdncred** [comment]
feel free to tweak on the codebase to see if you can get it to work on a table.

**Comment by dandavison** [comment]
I believe that this can be closed now. @jakobnissen's example is working correctly now (MacOS Alacritty and Terminal.app):

```
〉ls `VOF NGS rådata og behandling.docx`
╭───────────────────────────────────┬──────┬──────┬────────────────╮
│               name                │ type │ size │    modified    │
├───────────────────────────────────┼──────┼──────┼────────────────┤
│ VOF NGS rådata og behandling.docx │ file │  0 B │ 13 minutes ago │
╰───────────────────────────────────┴──────┴──────┴────────────────╯
```

I think it was fixed by @zhiburt's work switching to the tabled library in d1687df0678ec55241031860e6f7132dec3f2503.

**Comment by fdncred** [comment]
thanks for finding this one too @dandavison
