### ISSUE TITLE
open command on file in git repo with changes doesn't show them

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#3254]
**Describe the bug**
The `open` command uses the `bat` crate to nicely render text files.
The docs here: https://www.nushell.sh/book/configuration.html#nushell-configuration-with-config-toml
say that setting the `[textview]` `vcs_modification_markers` option to `true` causes it to show modification markers, but it doesn't currently work. However, running `bat` on the same file does show modification markers.

**To Reproduce**
1. Modify the Nushell config file to have a `[textview]` section with the following line:

```bash
vcs_modification_markers = true
```

2. cd to a directory of a git repository that contains modified files.
2.  Enter `open some-file-path`
3. Note that no lines contain indicators to show that there were added, deleted, or modified.
4. Enter `cargo install bat` (requires that Rust is installed)
5. Enter `bat some-file-path`
6. Note that added, deleted, and modified lines to have indicators.

**Expected behavior**
The `open` and `bat` commands should produce the same output.

**Configuration (please complete the following information):**

│ 0 │ version            │ 0.29.0                                                                             │
│ 1 │ build_os           │ macos-x86_64                                                                       │
│ 2 │ rust_version       │ rustc 1.50.0 (cb75ad5db 2021-02-10)                                                │
│ 3 │ rust_channel       │ stable-x86_64-apple-darwin (default)                                               │
│ 4 │ cargo_version      │ cargo 1.50.0 (f04e7fab7 2021-02-04)                                                │
│ 5 │ pkg_version        │ 0.29.0                                                                             │
│ 6 │ build_time         │ 2021-03-30 20:30:47                                                                │
│ 7 │ build_rust_channel │ release                                                                            │
│ 8 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip │

**Comment by mvolkmann** [comment]
I did install the plugin by entering `cargo install nu_plugin_textview`.

**Comment by fdncred** [comment]
I'm guessing because the `bat` [documentation says](https://github.com/sharkdp/bat/blob/d89fa3ebc2639375b0184437607003a639d8ecef/CHANGELOG.md) `vcs_modification_markers` is removed if not built with `git` feature. Maybe we're not building that way.

**Comment by mvolkmann** [comment]
I'll take a shot at making this simple change and testing it.

**Comment by mvolkmann** [comment]
Adding "get" to the list of features for `bat` in the line suggested above did not fix the problem for me. I forked the nushell repo, cd'ed to it, ran `cargo build`, ran `cargo run`, and ran the `open` command on a file that I know is in a git repo and has local modifications. No modification markers were rendered.

**Comment by fdncred** [comment]
That's odd. The [source code is pretty clear](https://github.com/sharkdp/bat/blob/2e7f2b6c0709d758e4e92e5b9cab134d8d04b931/src/pretty_printer.rs#L158-L164) that it's behind the git feature.

**Comment by stepnivlk** [comment]
I did a bit of debugging and found the issue:
textview uses `bat::Input::from_bytes` (https://github.com/nushell/nushell/blob/main/crates/nu_plugin_textview/src/textview.rs#L123) since the content of file is already present on the value.
In such case bat configures its `Input` as `CustomReader` (https://github.com/sharkdp/bat/blob/master/src/input.rs#L135)
But it applies git diff only on the `OrdinaryFile` input (https://github.com/sharkdp/bat/blob/master/src/controller.rs#L101), it's actually calling git2 with file path in the background.

When I change the input to `bat::Input::from_file(file_path)` in the textview the markers show up at the expense of opening the file multiple times.

**Comment by stepnivlk** [comment]
By looking into the code further, I think nu should not open the file when this condition https://github.com/nushell/nushell/blob/main/crates/nu-command/src/commands/open.rs#L156 hits and rely on the open in bat itself that's more effective as it uses buf reader. WWYD?

I also noticed that when shell manager is used to open a file (https://github.com/nushell/nushell/blob/main/crates/nu-command/src/commands/open.rs#L174) there's buf reader used for large file (https://github.com/nushell/nushell/blob/main/crates/nu-engine/src/filesystem/filesystem_shell.rs#L814) but such an optimization is missing in `open/fetch`.

Since this is quite old issue I'm going to tag you @fdncred directly, hope that's fine.

**Comment by fdncred** [comment]
hmmm, interesting. I think the way it's working now is that `bat` doesn't open any files. This open eventually [calls into textview](https://github.com/nushell/nushell/blob/5fcc7f23285b1abe6eb9b3a4985b9c76b0b9be80/crates/nu_plugin_textview/src/textview.rs#L15) which calls `bat::PrettyPrinter::new().input(bat::Input::from_bytes()` with all the configuration parameters.

Maybe on the `match file_path` we let `bat` open the file path?

**Comment by fdncred** [comment]
A quick experiment shows that it's putting git markers (i think)
![image](https://user-images.githubusercontent.com/343840/119353734-e1739080-bc68-11eb-9f30-16b5ab170b40.png)
I'm just not sure what that means for the other `AnchorLocation`s that are in the match arms to create the `file_path` variable. If you'd like to play around and experiment to figure it out, we'd accept a PR.

BTW - there's no issue tagging me.

**Comment by stepnivlk** [comment]
Yes, I conducted same experiment :). I'm definitely not sure what are the implications of file_path variable as I'm new here but happy to explore it.

**Comment by fdncred** [comment]
Have at it. Most of all, have fun. :)

**Comment by fdncred** [comment]
I guess this is broke again because I don't see the vcs markers in a modified file under git control. Not sure what changed?

**Comment by rbpatt2019** [comment]
Can confirm that issue exists in the most recent version! 

```shell
version            │ 0.42.0
 build_os           │ macos-x86_64
 rust_version       │ rustc 1.57.0 (f1edd0429 2021-11-29)
 rust_channel       │ stable-x86_64-apple-darwin
 cargo_version      │ cargo 1.57.0 (b2e52d7ca 2021-10-21)
 pkg_version        │ 0.42.0
 build_time         │ 2022-01-11 16:32:02 +00:00
 build_rust_channel │ release
 features           │ ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
 installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query
                    │ json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath
```

**Comment by fdncred** [comment]
i'm thinking that this won't be fixed since our new engine, engine-q, doesn't support `bat` built in. if you want to use the features of `bat` like seeing git repo changes and syntax highlighting, you'll probably have to download `bat` itself.

**Comment by rbpatt2019** [comment]
Fair enough! Personally not too bothered (I already use `bat` as my daily driver instead of `cat` anyways!), but now I'm curious - how will nutshell/engine-q handle `open` calls on non-tabular data in the future then?

**Comment by fdncred** [comment]
It works pretty similar to nushell. All the nushell commands aren't ported to engine-q yet but you're welcome to try it out. https://github.com/nushell/engine-q. The `open` command is ported.

**Comment by jntrnr** [comment]
We're now on the new engine. There are some differences with the new engine - one is that we now recommend calling out to `bat` directly and using that to view files instead of using the nushell pipeline system. You'll get better performance and better results generally.

We also handle things like tables differently. Whereas before they tried to handle all the interaction, they now output strings, which makes it easier to call other external commands (even external pagers). You can do things like `ls | less` now and page through the rendered tables.

With these things in mind, I'm going to close this. As we've gone away from the `textview` functionality to something more general I think that's as close as we'll get.
