### ISSUE TITLE
index_color should change the color of the # in the top left of the ls table

### ISSUE THREAD

**Issue by cjwyett** [nushell/nushell#3371]
**Is your feature request related to a problem? Please describe.**
`index_color` doesn't change the color of the # in the `ls` output. In fact I haven't found how to change the color of the # at all

**Describe the solution you'd like**
`index_color` to change the color of the hash.

**Describe alternatives you've considered**
Being able to delete the hash. or the `with_love` `table_mode` replacing the # with a ❤

**Comment by fdncred** [comment]
good point. the `#` itself isn't changeable. i never noticed that. `index_color` was meant to change the index of each line, which it does. `header_color` is meant to change the color of the header row in `ls`. Neither, as you point out, change the color of the hash itself. LOL.

also, LOL because no one has ever mentioned the `with_love` theme. hehe.
