### ISSUE TITLE
Execute Binary in String

### ISSUE THREAD

**Issue by oberien** [nushell/nushell#3433]
I have a folder stored in a variable. I'd like to concatenate a binary in that folder to the string and run that binary.

Just concatenating it as string prints the concatenated string:
```
> let folder = /bin
> $"{$folder}/ps"
/bin/ps
```
Running `exec` replaces nushell, which isn't what I want here:
```
> let folder = /bin
> exec $"{$folder}/ps"
    PID TTY          TIME CMD
  52364 pts/1    00:00:00 nu
  52514 pts/1    00:00:00 ps
<ps exits and the terminal closes>
```
Using the circumflex escape hatch also doesn't work.
```
> let folder = /bin
> ^$"{$folder}/ps"
error: Expected string for command name
  ┌─ shell:3:1
  │
3 │ ^$"{$folder}/ps"
  │ ^^^^^^^^^^^^^^^^ expected string
```

A new command like `run <command-strng>` could be added, or as @jonathandturner suggested on discord, the circumflex behaviour could be modified to work.

**Comment by jonathandturner** [comment]
I think there are two parts to this:

* updating the parser to support this form
* updating the external command runner so that it will process the string interpolation before it tries to run the external command

I believe both should be pretty isolated parts of the code, so I'll mark this as a good first issue for beginners. If someone wants to try this and gets stuck, reply here or join the discord and we'll help get you unstuck.
