### ISSUE TITLE
Source-ing a file containing an external command requires you to hit Enter

### ISSUE THREAD

**Issue by lily-mara** [nushell/nushell#3480]
**Describe the bug**
When a `nu` file contains an external command, `source`-ing it causes the nushell process to hang until you hit Enter. If you're not expecting it (as I was not) then you may think that the terminal process is hung.

**To Reproduce**
1. `echo '/bin/ls' | save bar.nu`
2. `source bar.nu`
3. Your nushell process should print the output from `ls` then wait for you to hit Enter before showing the prompt again

**Expected behavior**
Sourcing script containing external commands should exit normally without any required user input.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
───┬────────────────────┬────────────────────────────────────────────────────────────────
 # │      Column0       │                            Column1
───┼────────────────────┼────────────────────────────────────────────────────────────────
 0 │ version            │ 0.31.0
 1 │ build_os           │ macos-aarch64
 2 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)
 3 │ rust_channel       │ stable-aarch64-apple-darwin (default)
 4 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)
 5 │ pkg_version        │ 0.31.0
 6 │ build_time         │ 2021-05-12 23:15:02
 7 │ build_rust_channel │ release
 8 │ features           │ ctrlc, default, directories, dirs, rustyline, term, which, zip
───┴────────────────────┴────────────────────────────────────────────────────────────────
```

**Comment by jonathandturner** [comment]
I'd still like to investigate this.

**Comment by jokeyrhyme** [comment]
I think I just encountered this today

I've been working on a .nu script to add to my config.startup and it has to run with `source` because I want to manipulate the current scope (not a new sub-scope)

I read through https://www.nushell.sh/book/pipeline.html#working-with-external-commands and just happened to try a hack that seems to workaround this problem: start your pipeline with `echo '' | `

e.g. `echo '' | echo '/bin/ls' | save bar.nu`

With the particular external command I need to run for my own use case (`systemctl`) this happens to work perfectly for me

**Comment by rgwood** [comment]
I believe this has been fixed since the initial bug report. I'm not able to reproduce this on v0.72, `source bar.nu` now runs `ls` without waiting. Happy to reopen if I've missed something.

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.0                                   |
| branch             | main                                     |
| commit_hash        | fa97e819ebfa6c568101da4cefec1505964b48b7 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.0                                   |
| build_time         | 2022-11-29 22:27:52 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |
