### ISSUE TITLE
ls command formatting as table but exa does not

### ISSUE THREAD

**Issue by nickwmo** [nushell/nushell#3543]
Formatting files and directories listing as a table is a really neat feature of nushell. When I run `ls` I get a nicely formatted table but when I run `exa` which is an `ls` replacement written in rust, I don't get the nicely formatted table. I would love to see the same table format apply to `exa` if possible. 

![screenshot-of-exa-not-formatting-as-table](https://user-images.githubusercontent.com/21003994/120529711-c280a700-c3aa-11eb-978f-454f14e93430.jpg)

**Comment by jonathandturner** [comment]
@nickwmo - The `exa` command is one that was created outside of Nushell, so when Nushell runs it, you'll get the output that `exa` creates.

One of the things that lets nushell create tables for commands like `ls` is that the commands are built into Nushell and use Nushell's structured data. When you run `ls` what `ls` gives back is that structured data, which gets displayed as a table.

You can think of `exa` as an "external" command, or a command that lives outside of nushell, and `ls` as a "internal" command or a command that lives inside of nushell.

In the future, we'd like to make it possible to create signatures for external commands so that we can do additional steps like parsing and displaying their output as structured data, but for now external and internal commands will work differently.

**Comment by nickwmo** [comment]
Thanks for the detailed reply JT. Keep up the great work!
