### ISSUE TITLE
Terminal multiplexing with shells

### ISSUE THREAD

**Issue by tylerlaberge** [nushell/nushell#359]
The current "enter" command creates shells that you can navigate between with "p" and "n", which is nice, but it would be even better if there was a built-in way you could split your shells into multiple windows, think tmux/terminator.

**Comment by androbtech** [comment]
Something like #245 ?

**Comment by jonathandturner** [comment]
I think @tylerlaberge might mean split-screen, where half the screen is one shell and the other half is the other?

Would be curious to hear more.

**Comment by tylerlaberge** [comment]
@jonathandturner is right, basically each shell would split the screen

![image](https://user-images.githubusercontent.com/16872788/63654835-a2d83b80-c74d-11e9-9ff9-01600905cd43.png)

The "p" and "n" commands could jump between the windows, the "exit" command would close the current window, and the "enter" command would split your current window in two.

This may be a large effort and may be less of a priority than other issues right now, but if nushell had shell multiplexing built-in instead of having to use terminator/tmux alongside nushell then that would be a killer feature imo

**Comment by Akito13** [comment]
>if nushell had shell multiplexing built-in instead of having to use terminator/tmux alongside nushell then that would be a killer feature imo

Fully agree. I was already in good mood to see the easy access to different shells, but some basic multiplexing would be indeed awesome.

**Comment by OliverWich** [comment]
Is there any way / plans to get this issue back on track?

This would be such an awesome feature, as nushell is crossplatform and some platform (looking at you windows) does not have any good terminal multiplexers, having at least some basic support for this native to nushell feels like a big advantage for nu in by book.

Especially for windows, where tmux is not supported, a good terminal multiplexer is desperately neededn. WindowsTerminal is actually very good at this, but splitting the terminal can not be controlled programmatically for an existing wt session. You need to launch a new wt session with flags if you are building a complex script.

On my day to day, I currently use a powershell script that starts up such a wt session with multiple panes (looks similar to the screenshot of @tylerlaberge). Some run server processes and one is just an interactive shell in my current project directory.
I would like to move to nu and make this script more cross platform (and less reliant on pwsh and wt), but since I need to keep supporting windows, and there is no other terminal multiplexer, I can't.

I would really appreciate it if nu would support terminal multiplexing. It does not have to be fancy, just some command that splits the current "pane", maybe even with a specific ratio of how much space the new pane should take up in the old one.

If there is anything I (as a mainly web focused dev with only some very sparse rust experience) can to do help get this feature rolling, please let me know!

**Comment by weirdan** [comment]
> just some command that splits the current "pane", maybe even with a specific ratio of how much space the new pane should take up in the old one.

Doesn't wezterm have this? 

https://wezterm.org/cli/cli/split-pane.html

**Comment by OliverWich** [comment]
Yes, exactly like this!

That behaviour is pretty much what I am imagining for nushell to support natively.
