### ISSUE TITLE
History limited to command written

### ISSUE THREAD

**Issue by 00sapo** [nushell/nushell#3614]
In Fish, Xonsh, and many other shells, when pressing arrows up/down for navigating through history, the user only sees commands that share the part of the command already written.

E.g.

```shell
$ ffmpeg -i file.ext -o file.out -a -long -list -of -options
[...]
$ ls ~/Develop/
[...]
$ many
[...]
$ other
[...]
$ commands
[...]
$ ffmpeg <arrow-up>
```

when pressing <arrow-up>, the user should see `ffmpeg` command and the intermediate commands (`ls` etc.)

**Comment by fdncred** [comment]
We've been trying to get rustyline to support such a thing as is documented in the PR that @oberien pushed over a year ago. https://github.com/kkawakam/rustyline/pull/424

**Comment by oberien** [comment]
This issue is probably a duplicate of #465, the original issue I wrote the PR to rustyline for. If you want this feature, you could use [my fork](https://github.com/oberien/nushell) of nushell from [this PR](https://github.com/nushell/nushell/pull/2296) which includes the rustyline version with that PR. I only update the fork once in a blue moon though currently.

**Comment by oberien** [comment]
Not stale.

**Comment by fdncred** [comment]
agreed. what's the latest on this @oberien ?

**Comment by sigmaSd** [comment]
I think now nushell uses reedline, is that feature available there ? personaly I can't replace fish because of these kind of details

**Comment by sigmaSd** [comment]
Actually it seems to be implemented now, but it works only if the commands share the starting part, fish doesn't have this limitation

**Comment by fdncred** [comment]
@sigmaSd how should it work? I don't know what you mean where you say, "but it works only if the commands share the starting point". can you give examples of what this means please?

**Comment by sigmaSd** [comment]
if you have `cd hello` on your history, now you type hello and then up, fish will give you that entry while nu won't

This is the same case btw in tab completion, if you have a directory called `ab` in fish you can press b then tab to get that directory, in nu you have to give the same start so only a works

**Comment by sigmaSd** [comment]
In that case I guess this issue can be closed

**Comment by sholderbach** [comment]
Happy to take (reedline) PRs that give our history traversal and completions options to be closer to fish's magic.
We currently have the base logic via common prefix search but are certainly open to make more users happy :)

In my mind the core of this issue is implemented and thus would agree to close.
