### ISSUE TITLE
File manipulation commands fail if file contains square brackers

### ISSUE THREAD

**Issue by stomar117** [nushell/nushell#4041]
### Describe the bug

Using file manipulation commands like `cp`, `rm`, and `mv`, the commands fail if the file name contains square brackets(`[]`).

### How to reproduce

1. Have a file containing square brackets, Eg: `somefile [test].txt`,
2. Try removing the file using `rm`: `rm "./somefile [test].txt"`(errors out),
3. Try using escape sequence: `rm "./somefile \[test\].txt"`(errors out),
4. Try using some more escape sequences: `rm somefile\ \[test\].txt`(errors out).

### Expected behavior

I expected the removal of the file to be working at least in the third try, because if I were to replace the square brackets with the regular brackets(parenthesis) the `3rd` and the `4th` method mentioned above worked just fine.

### Screenshots

Using `rm`:

![image](https://user-images.githubusercontent.com/57960301/134766604-aedd168d-d1b4-4a84-a721-9237535dae77.png)

Using `mv`:

![image](https://user-images.githubusercontent.com/57960301/134766616-91ceb8bb-62f1-40c1-95d6-fcacdb4a823d.png)

Using `cp`:

![image](https://user-images.githubusercontent.com/57960301/134766625-90e0eb8d-256b-4f52-9f18-7ac87e150b70.png)

### Configuration

|key|value|
|-|-|
|version|0.37.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.55.0|
|cargo_version|cargo 1.55.0|
|pkg_version|0.37.0|
|build_time|2021-09-15 00:41:44 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by arthur-targaryen** [comment]
This is because globbing is always applied to the first argument.
For example with `mv`, the source is always expanded. Thus, when you have `mv ./READ[ME].md ./README.md` it will try to move either *READM.md* or *READE.md* if it can find them but not *./READ[ME].md*.

In the code, if no file is matching the glob pattern, it **does not** try to `mv` (or `cp` or `rm`) the first argument without applying globbing (which seems pretty fair). I don't know if there's a way to disable globbing; if not, there should probably be.

**Comment by theEndurance-del** [comment]
Maybe, we could pass `[` as a character by using `\[` to prevent globbing.

**Comment by fdncred** [comment]
nushell doesn't support the `\` character for escaping. however, it does support `char lbracket` or `char left_bracket`.
example:
```
> $"(char lbracket)test(char rbracket).txt"
[test].txt
```

**Comment by theEndurance-del** [comment]
> nushell doesn't support the `\` character for escaping. however, it does support `char lbracket` or `char left_bracket`.
> example:
> ```
> > $"(char lbracket)test(char rbracket).txt"
> [test].txt
> ```

> I tried the second method just now but even that doesn't seem to work!

[Screenshot_20211002-004317_Termux.jpg](https://user-images.githubusercontent.com/57960301/135674541-02cc4ebb-aba0-4dc1-98c3-a4da44302771.jpg)

**Comment by fdncred** [comment]
ya, the escapes work as expected, the `rm` not so much. i had to do `rm SOMEFI~1.TXT` on windows to get rid of the file i made.

**Comment by theEndurance-del** [comment]
> i had to do `rm SOMEFI~1.TXT` on windows to get rid of the file i made.

As for me I had to use globbing to remove the file like so `rm ./somefile*`, not the most efficient method, but works.
Still I think it would be better if escape characters like `\` should exist in `nu` because none of our "workarounds" are as efficient as escape characters.

**Comment by jansol** [comment]
The autocomplete should do this escaping so autocompleted paths work out of the box even if you add a wildcard at the end. For example I recently had a case like this:

```
f[oo]bar/
    01-aaaa.flac
    02-bbbb.flac
    f[oo]bar.log
    f[oo]bar.m3u
    f[oo]bar.toc
    f[oo]bar.cue
```

Now I manage my music collection with `beet` which does not handle auxiliary files particularly well, so I have to copy the log, cue, m3u and toc files to the library directory manually. I'd expect to be able to do

```
$ cp f<tab>/f<tab>.*
```

And get a working source path with a wildcard for the file extension. With nushell I instead get a double quoted path which does not work at all because the double quotes added by the autocompletion cause the square brackets to still get interpreted as special characters. Changing them to single quotes "works" but then I can't use wildcards, and it is something I have to fix manually before I can use the autocompleted paths which kind of defeats the point of using autocomplete.

**Comment by fdncred** [comment]
ya, agreed. it would be cool if that stuff just worked.

**Comment by hustcer** [comment]
`rm some<tab>` will be expanded to <code>rm \`somefile [test].txt\`</code>, and the operation will success now, please try it on the latest nu version
