### ISSUE TITLE
Pasting multi-line command (with backslash) doesn't work

### ISSUE THREAD

**Issue by torarvid** [nushell/nushell#4044]
### Related problem

When finding command line examples online, I find that it's fairly common to split these up into multiple lines for readability. Usually, a backslash character is used to do this split, like:

```bash
curl -o out.json \
  -H 'Authorization: Bearer some-token' \
  http://www.example.com/some-path
```

I can't get this to work when trying nushell on my mac.

### Describe the solution you'd like

These examples using backslash as line separator are so common that nushell should support it.

### Describe alternatives you've considered

I just tried googling "nushell multiline command" and the like to see whether there was some config or whatever that I should have set to get it to work. Didn't find anything 🤷🏻

**Comment by fdncred** [comment]
The backslash character `\` is not a line continuation character in nushell. At the moment the only line continuation characters that are supported are `[`, `(`, and `{` while they're being used in nushell syntax.

**Comment by jntrnr** [comment]
There's some more info in the release notes blog post: https://www.nushell.sh/blog/2021-07-13-nushell_0_34.html#improved-multiline-support-jt

**Comment by torarvid** [comment]
I see. It looks like I might have failed to convey the underlying intention with this issue... I'm happy to hear that there **is** a way to construct a multiline command in nushell (which I hadn't realized) 👍🏻

But my issue is that copying and pasting "commands using backslash as a multiline separator" from the plethora of articles and websites already present on the internet does not work in nushell, while it **does** work in bash, zsh and fish.

I'm new to nushell, and I really like some parts of it, but I'm trying to make you aware of "reasons to stay with zsh", which I've been using for the past couple of years, and things like this are among them.

I'd be curious to know whether there's a technical or philosophical reason why nushell can't support pasting the curl command snippet from my description at the top? Or is it just something that "hasn't been implemented yet"? If the latter is the case, it could possibly be an interesting thing for a Rust-novice like me to try and implement?

**Comment by jntrnr** [comment]
@torarvid - one issue with the traditional line continuation character (`\`) is that this is a valid path name in Windows. Nushell, whenever possible, tries to always be compatible across platforms, including Windows. If we supported the `\` as a continuation character, we'd need to do it in a way that this also works with Windows paths.

**Comment by torarvid** [comment]
@jntrnr That's a fair point 👍🏼 Would you be open to some sort of opt-in feature where, say, linux/mac users could either set an env flag or config option to enable backslash for line continuation? (I think it would be sad if users on any given platform have to "suffer" a less-than-awesome experience in the name of platform independence 😉)

**Comment by jntrnr** [comment]
yeah, that sounds good. Maybe the opt-in feature converts what you paste to being the Nushell style multiline sub-expression, so it's more portable?

**Comment by fdncred** [comment]
I'd rather not have a fundamental shell functionality, like line continuation, only work on *nix platforms. I'd prefer to do something that works on all platforms the same way such as using an alternate line continuation character like backtick as pwsh does.

**Comment by torarvid** [comment]
Not sure I understand what you're saying, @fdncred. The existing command examples that I'm talking about on the web, already have backslashes in them. My desire for this issue is to discuss whether we can make something to make such an example command paste-able in nushell.

But I think my last proposal can be made more generic. Say that, on the web there are:

1. Some set of command examples where `\` is used for line continuation
2. Some set of command examples where `` ` `` is used for line continuation
3. Some set of command examples where `foobar` is used for line continuation

I'm picturing a config option where the user can opt-in to say that "Whenever somebody pastes something containing the magic string `my-line-continuation-delimiter` followed by a newline, modify the contents of the paste so that it instead matches the nushell `(multiline cmd)` format.

**Comment by fdncred** [comment]
I didn't get that at all from this thread. lol. it sounded to me like you and jt wanted to implement a `\` line continuation character as opt-in in *nix only. that's what I was objecting to. If you're talking only about pasting and reformatting into the proper nushell line continuation format, then i'd support it, given what you've described just now in your 'more generic' proposal. i think having a config point is also good.

**Comment by LevitatingBusinessMan** [comment]
Can this issue be opened in https://github.com/nushell/reedline/ instead? I use reedline for use other than a shell, and it's only downfall has been the inability to paste multiline text into it.

**Comment by fdncred** [comment]
We've had some success on non-windows systems pasting multiline text if bracketed paste is enabled. @LevitatingBusinessMan have you tried that approach?

**Comment by LevitatingBusinessMan** [comment]
> We've had some success on non-windows systems pasting multiline text if bracketed paste is enabled. 

My goodness it works... That option wasn't present in the older version of reedline I had been using.

**Comment by fdncred** [comment]
> That only works for lines that are suffixed with a paren or a comma.

This is not my experience. @amtoine showed me the other day and I did it. He had something like 
```
ls
| sort-by name
| get name
| get 0
```
That command traditionally wouldn't be able to copy-n-paste, but with bracketed paste enabled on *nix system, it seems to be working.

**Comment by amtoine** [comment]
> ```nushell
> ls
> | sort-by name
> | get name
> | get 0
> ```
>
if we forget about https://github.com/nushell/nushell/issues/9944, yes it does work :yum:

**Comment by LevitatingBusinessMan** [comment]
My bad, bracketed paste does (disregardig #9944). I now use it in my project.

**Comment by leetemil** [comment]
I think this is still a valid issue. There are so many examples on the internet using `\` for multi-line shell commands. Every time I need such an example from stack overflow etc., I have to (1) open a bash/zsh shell, (2) execute that command and then (3) exit back to nushell. This is something I regularly do. I know that nushell is not bash/zsh, but being incompatible with multi-line commands from these shells do cause some friction when using nushell as a daily driver.

**Comment by theAkito** [comment]
> I think this is still a valid issue. There are so many examples on the internet using `\` for multi-line shell commands. Every time I need such an example from stack overflow etc., I have to (1) open a bash/zsh shell, (2) execute that command and then (3) exit back to nushell. This is something I regularly do. I know that nushell is not bash/zsh, but being incompatible with multi-line commands from these shells do cause some friction when using nushell as a daily driver.

If I understood the issue correctly, then all people who complain about this & propose Nushell compatibility for something from the 80's, drew the wrong conclusions from the problem.

If the entire world of shells would write hex code for newlines, would you seriously suggest this crappy behaviour to be supported in Nushell? I doubt that. I hope, nobody would seriously propose to make Nushell worse, although I have already seen some crazy compatibility issues, which basically worsen Nushell by making it more like inferior shells, but that's another story...

So, I think, it's just natural & smart, that Nushell **does not** support crappy behaviour like that, else we could just drop this project altogether, if it supports all that crappy stuff from other inferior shells.
The whole point of Nushell is, that it does everything better & does **not** support crappy obsolete shell stuff, which should've been deprecated three decades ago.

Now what solution would actually *make sense*?

Simple. Add an extension function, i.e. addon/plugin, which takes a string like that as an argument & converts it into Nu, which basically just means, that backslashes, which are not inside string arguments, should be removed. All `&&` should be also replaced with `;`. Done.

Guys, do you *really* want Nushell to support all the crap from inferior shells, we were running away from in the first place? At least, I don't. I wouldn't see a purpose in using Nushell, if it supports all the POSIX bullshit, we had to use for so many years, just because "they've always done it like this".

Those shells, or at least many of their inherited anti-features, should be deprecated & people should upgrade their scripts, rather than saying "but muh script from 1981 stops working, if you deprecate this useless anti-feature"....

____

Two last examples to make my point absolutely clear.

1. Already mentioned `&&`.
    When you see code examples with backslashes, they also usually use `&&`. So, making Nushell compatible with backslashes like that just works around part of the problem.

2. On "the internet" there are lots of people stuck in the 80's who _still to this day_ use \` for command substitution.

    Example:
    
    ```
    echo `ls`
    ```
    
    Now, in Nushell, we use this for literal strings.

Do you guys want this deprecated stuff to be supported in Nushell, too? It's even already deprecated in inferior shells!

**Comment by leetemil** [comment]
I don't think there's a compromise here - you can have the leisure of being compatible with the idiosyncrasies of bash/zsh, without losing the more modern features of nushell. But you're right that if I can augment nushell with this behavior through extensions, then there's probably no need for built-in support. That could solve this day-to-day problem that I have with nushell as my daily driver.

**Comment by theAkito** [comment]
> I don't think there's a compromise here - you can have the leisure of being compatible with the idiosyncrasies of bash/zsh, without losing the more modern features of nushell.

I think, the principle behind this statement is too simplistic.

When any software developers adds something, it always needs to answer the "Why?" question properly.
In this case, I do not see that question answered properly, because "well, it needs to work with crap other products have done wrong or in a bad way" is not a proper answer to the "Why?" question.

Additionally, with every feature, addition, patch & essential *change* to any software's core, you add another bit of attack surface for bugs, exploits & loss of security.
For example, the most secure pieces of software in the entire world are extremely minimalistic & do only **one** thing & they do it well. Their maintainers are extremely particular about what to add & what to keep outside.

Nushell isn't a hyper security product, yes, but we still need to ask ourselves what actually makes sense for the product.

I think, we already have way too much compatibility with old stuff, because people constantly open issues like "I have done X in Bash, now I want X in Nushell, too" (even though X is very bad & the only reason you opened this issue, is because you got used to X & you have always used it like this).

Things like this always remind me of this very important piece of art.

https://imgs.xkcd.com/comics/workflow.png

Like, do we really want such features, just because people are used to them?

I think, it should be absolutely normalised, that people just get used to getting used to new stuff quickly, rather than complaining, that some 80's feature is **finally** deprecated & does not work anymore.

To be clear, I'm talking about the _general perception_ I have of such situations across software projects. I'm not saying, that people talking about such stuff in this issue or in general in the Nu project are this annoying about it.

All I wish is basically people to ask themselves "what would Nu do, when I need this to work?" rather than "I can do X in Bash, now I must be able to do X **precisely** the same way in Nushell, because I am incapable of adjusting to anything created past the 90's.".

____



> if I can augment nushell with this behavior through extensions, then there's probably no need for built-in support.

Exactly. This is how Nu would do it. The core needs to satisfy all your Nu, Nushell, Nu Shell needs. All the needs, that are a 100% compatible with Nu's philosophy & ways to work.
Nobody is stopping anyone from creating an extra plugin, which does some specific stuff for a specific use case. In fact, that's how I understand plugins. Everything specific & too weird or rarely needed, does not belong into the core but into a plugin.

With this way, everyone would be happy. All core Nu loyalists would be happy with the actual 100% Nu philosophy based core of the product, while all others needing/wanting workarounds for other shells' mistakes can just install plugins, without any issues. Everyone is happy then. Just don't bloat the core with mistakes from other projects. 🙂

**Comment by Banyc** [comment]
If one command is wrapped in `(...)`, it no longer produces a stream. Therefore, this example will fail:

```py
def test_exit_code [] {
    let res = do {
        (nu -c "exit 2")
    } | complete
    print $res
}
```

...with the complain `complete only works on external streams`

**Comment by jonahbron** [comment]
+1 on the parentheses wrapping, the output gets buffered until the expression completes, which is different behavior from running it un-wrapped.

**Comment by Sammmmm** [comment]
Semi-related -- Is there a way to change it on windows so pasting in multiple lines that are lf and not crlf still respects the newlines?.  I can't paste in multiple distinct commands for this reason from my preferred text editors.

**Comment by fdncred** [comment]
I paste multi lines into windows terminal but they have to be setup right (lines ending with pipe, for instance) since Windows Terminal does not support bracketed paste.

**Comment by phreed** [comment]
I know 'nu' is not a posix shell, has there been any thought given to construct a posix-shell to nushell translator?

There are several rust libraries which might be useful:
* [yash-syntax](https://lib.rs/crates/yash-syntax):
    This library, part of the yash project, focuses specifically on parsing POSIX shell scripts. It's designed to be used independently for parsing shell code. https://magicant.github.io/yash-rs/  and https://github.com/magicant/yash-rs. 

* [brush-parser](https://crates.io/crates/brush-parser):
While not solely a parser, the brush project is a POSIX/Bash compatible shell implemented in Rust. The brush-parser crate within it provides parsing capabilities. The brush-parser uses libraries from nushell.

* [shellish_parse](https://github.com/SolraBizna/shellish_parse):
This library offers a parser for "shellish" command line syntax, inspired by the Bourne shell. You can find it on [Docs.rs](https://docs.rs/shellish_parse) and [GitHub](). 

* [conch-parser](https://github.com/ipetkov/conch-parser):
This library is designed for parsing Unix shell commands and is known for being correct, efficient, and agnostic to the final AST representation. It supports various shell features like conditional lists, pipelines, and redirections. It's available on [GitHub](https://github.com/ipetkov/conch-parser) and [Docs.rs](https://docs.rs/conch-parser).

**Comment by fdncred** [comment]
not that i know of. sounds like something difficult to write.

**Comment by phreed** [comment]
Claude Sonnet 4 and I built a nushell plugin which uses the yash-syntax parser to give nu some rudimentary posix capability. 
https://github.com/phreed/nushell-posix
I will be using it for my own purposes.
I presume it has many bugs.
Because it is using yash-syntax I think it needs to be GPLv3.

**Comment by fdncred** [comment]
Sounds like a cool exercise. We wouldn't allow any GPL licensed crates in nushell though.

**Comment by phreed** [comment]
> Sounds like a cool exercise. We wouldn't allow any GPL licensed crates in nushell though.

https://github.com/phreed/nushell-posix/issues/1
My understanding is that the nushell plugins are separate executables, hence there should be no license issue with making this plugin GPLv3.
Are you saying it could never be welcomed into the family?
https://github.com/nushell

**Comment by fdncred** [comment]
The GPL license is incompatible with the MIT license. People can create GPL plugins, and they work just fine with nushell. I have one in fact. However, I don't believe we will be hosting GPL plugins in any of our nushell repos. Also, no one on our team is a copyright attorney so we'll err on the side safety and MIT.

**Comment by SetsuikiHyoryu** [comment]
I came to this issue because I didn’t know how to insert a line break in Nushell.
This issue appeared near the top of the first page of Google search results when I searched with the keyword `Nushell wrap line`.

> There's some more info in the release notes blog post: https://www.nushell.sh/blog/2021-07-13-nushell_0_34.html#improved-multiline-support-jt

I’m glad to learn about the official explanation regarding line breaks from the above.
Although it’s just a blog post rather than formal documentation.

Of course, I also tried to find related descriptions in the official documentation:
[https://www.nushell.sh/book/style\_guide.html#multi-line-format](https://www.nushell.sh/book/style_guide.html#multi-line-format)

However, I think neither clearly explains the workflow for line breaks,
after all, writing in a file is different from pressing Enter in a command line which immediately executes the command.

From my practical attempts,
if you write a `(` or `[` first and then press Enter, Nushell will create a new line instead of executing,
if you don’t write brackets, then you can only use Shift + Enter to break the line,
but in this case, the second line is not recognized as a continuation of the first line.

I don’t really care whether there is a symbol indicating a line break or not, but I believe the documentation should consider the usability within the command line.

**Comment by SetsuikiHyoryu** [comment]
Ok, I found that this page <https://www.nushell.sh/book/line_editor.html#multi-line-editing> describes how to control line wrapping in the command line.

**Comment by rondymesquita** [comment]
I wrote this keybinding, that replaces enter:
```
$env.config.keybindings = [{
  name: "replace_slash_line_break_and_run"
	modifier: "none"
	keycode: "enter"
	mode: "emacs"
  event: [
		{
			send: executehostcommand,
			cmd: '
				mut cmd = (commandline)
				let $line_break_regex = '\\\n'
				$cmd = $cmd | str replace --all --regex $line_break_regex ''
				commandline edit $"($cmd)" --accept
			'
		},
	]
}]
```
It is not perfect, because the terminal blinks and duplicates the prompt. It would be good to have a hook, that we could process the cmd before submitting to nushell. I tried using the `pre_execution` hook, but without success.
