### ISSUE TITLE
Problem entering spaced containing directories 

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#4053]
### Describe the bug

Unable to enter directories whose name has spaces for example `./Solana Tutorials/` which results in error 
```sh
error: Command not found
   ┌─ shell:12:1
   │
12 │ ./Solana Tutorials/
   │ ^^^^^^^^ command ./Solana not found
```

Even using `cd ./Solana Tutorials/` results in the error message 
```sh
error: cd unexpected Tutorials/
   ┌─ shell:11:13
   │
11 │ cd ./Solana Tutorials/
   │             ^^^^^^^^^^ unexpected argument (try cd -h)
```

### How to reproduce

1. Ensure you have a directory with spaces in it's name like `Foo Bar`
2. Try switching to that directory

### Expected behavior

The shell won't switch to that directory and it will throw an error

**Comment by kubouch** [comment]
You need to wrap it in quotes: `cd "Solana Tutorials"`. If you try `cd Sol<Tab>`, it should autocomplete to `cd "./Solana Tutorials/"`.

The issue here is with with autocd. Typing `Sol<Tab>` autocompletes to `./Solana Tutorial` but Nushell interprets it as a command and its argument (there is no way it should know this is actually a directory with a space). Wrapping it in quotes `"./Solana Tutorial"`doesn't work either since that would just output a string. So I think we need to tweak autocomplete to be more autocd--aware and not offer broken suggestions.

**Comment by herlon214** [comment]
Is this still an issue? I tried to reproduce locally here by creating a folder `Test Folder` and doing `cd <tab>` it completed the `Test Folder` and quoted when I selected.

**Comment by charleschege** [comment]
Latest nushell fixed this
