### ISSUE TITLE
Unable to split columns filtered by match

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#4071]
### Describe the bug

After filtering rows with match split column complains that it requires string input

### How to reproduce

cargo install --list|lines|wrap|match Column ":"|split column " "

### Expected behavior

I expected nu to split the lines using provided delimiter (space)

### Screenshots

![image](https://user-images.githubusercontent.com/26117918/136599505-9539b70d-2185-45e1-beb5-2a2b12e0190d.png)

### Additional context

can be worked around by piping into each and then splitting each line separately but that's much longer

**Comment by fdncred** [comment]
how about this? `cargo install --list | lines | wrap | match Column ":" | get Column | split column ' ' name version`

**Comment by Yethal** [comment]
@fdncred Your version does work as expected but why do I need to get the Column if it's the only column available?

**Comment by fdncred** [comment]
Here's a version that works in nushell v0.59.1 `cargo install --list | lines | wrap installed | find ":" | get installed | split column ' ' name version | update version {|v| $v.version | str find-replace -a '^v|:$' ''}`.

You have to get the "column", which in this version is "installed" because that changes it from a list of records to a list of strings. I'm sure there are other ways to do this too.
