### ISSUE TITLE
`git log` complains about "command failed" on normal exit

### ISSUE THREAD

**Issue by TENX-S** [nushell/nushell#4082]
### Describe the bug

![image](https://user-images.githubusercontent.com/40336192/137570373-a7395a6d-99fe-411e-8959-934bd41f7b37.png)

Pressing `q` will cause this error when the `git log` cannot be displayed all at once.

### How to reproduce

1. Run `git log` in the nushell directory
2. Press `q`

### Expected behavior

Should not report an error in most cases

### Screenshots

![bug](https://user-images.githubusercontent.com/40336192/137570700-5858feb0-e081-4fa7-aff2-1b13a73aa2b0.gif)

### Configuration

|key|value|
|-|-|
|version|0.38.0|
|branch|main|
|short_commit|a986de8a|
|commit_hash|a986de8ad03b163837138436ad63b2f2733f8959|
|commit_date|2021-10-09 19:50:27 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.57.0-nightly (e1e9319d9 2021-10-14)|
|rust_channel|nightly-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.57.0-nightly (c7957a74b 2021-10-11)|
|pkg_version|0.38.0|
|build_time|2021-10-15 23:14:46 +08:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

### Additional context
`bat (config path)`:
![image](https://user-images.githubusercontent.com/40336192/137570563-06522cc8-1cf0-41bf-9c66-c6d999987c39.png)

**Comment by jntrnr** [comment]
@TENX-S - this is one of those areas of how commandline apps works that feels very fuzzy :-/

Apps can return non-zero exit codes for things that aren't actually errors. If you try your example in bash, you get this:

```
$ echo $?
141
```

Why did `git log` return 141?  I googled a bit because I was baffled. Seems to be related to: https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q

So when you're quitting the log, you might be getting a sigpipe as it finishes, and that's getting translated to an exit code of 141.

**Comment by TENX-S** [comment]
Cool, thanks for the explanation. I'll use the previous workaround.

**Comment by jntrnr** [comment]
@TENX-S - it looks like the error is actually coming from `less` and not `git log`. Someone dug into this a few years back: https://www.ingeniousmalarkey.com/2016/07/git-log-exit-code-141.html
