### ISSUE TITLE
[Feature] Parse "#!/bin/bash" or "#!/bin/sh"/etc

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4167]
When parsing these lines, switch to the referred shell. After done, keep parsing and do the same if another is found.

Reason:

Enable nu scripts to come in `.sh` files, and run compatibility messages/commands on other shells.

**Comment by kubouch** [comment]
This is a bit similar to the `&&` issue. We do not plan to support bash etc. parsing.

You can still run regular shell scripts from Nushell. They will work. However, they will run under their respective shell interpreter as a separate process, not as a part of Nushell.

Again, closing this since we don't plan to support this.

**Comment by danimesq** [comment]
> This is a bit similar to the && issue.

It isn't, because:

> We do not plan to support bash etc. parsing.

That's not what I was suggesting.
As nu supports redirecting bash scripts to bash/sh/etc, it could do it from inside .nu scripts.

> You can still run regular shell scripts from Nushell. They will work.

Yes.

> However, they will run under their respective shell interpreter as a separate process, not as a part of Nushell.

Yes, already noticed it. But this isn't what I was suggesting.
