### ISSUE TITLE
Drop with iter range `| drop nth 15..29`

### ISSUE THREAD

**Issue by cnrmck** [nushell/nushell#4210]
### Related problem

I'd like to be able to drop multiple rows by using an iterator.

E.g. 
```
echo 15..30 | drop nth 15..29
```
should return only row 30

### Describe the solution you'd like

drop accepts range iterators

### Describe alternatives you've considered

alternatively, the syntax could be drop nth 15 - 29, but that doesn't seem as consistent

### Additional context and details

This would save me from having to enumerate all of the rows I want to drop manually.

**Comment by onsah** [comment]
I am planning to work on this, but shouldn't the command be
```
echo 15..30 | drop nth 1..14
```
to return only row 30? Since the prior range has 15 elements and we want to drop first 14 of them.

**Comment by jntrnr** [comment]
@onsah - I think `drop nth 1..14` might leave you two elements: `[15, 30]`, since the normal `nth` works on row numbers.

**Comment by jntrnr** [comment]
(while I'm thinking of it, it'd be cool if ranges with a stride also worked, so something like:

```
> echo 15..30 | drop nth 1..3..15
```
would skip all the odd-numbered rows.

**Comment by onsah** [comment]
@jntrnr Yes, I think it makes sense. I will first make it work for simple ranges and continue from there. 

But I have a question. If we allow `drop nth` to accept both int list and range, what should be the error like if the type is neither of them (We can't say expected int, since we don't specifically expect an int)? Are there similar commands that accept different types and have proper error message?

**Comment by jntrnr** [comment]
@onsah I think we could make a new error for it, something like "expected int or range" or something like that?

**Comment by onsah** [comment]
@jntrnr @cnrmck  Can you the revıew the PR? I also have some questions in there.

**Comment by jntrnr** [comment]
This is now in main
