### ISSUE TITLE
Quote parsing in 0.42 breaks passing arguments in quotes

### ISSUE THREAD

**Issue by jansol** [nushell/nushell#4248]
### Describe the bug

Assume a command that takes say, a directory and filename template as arguments for ripping tracks from a CD:
```
whipper cd -d /dev/sr0 rip --disc-template="%A - %d - %y/%A - %d" --track-template="%A - %d - %y/%t - %a - %n"
```

When running in nu 0.42, this command will create an output directory named `"Artist - Album - year` which can't be easily interacted with due to the leading quote. The files inside that directory will be named `tracknum - Artist - Title".flac`, which is slightly less catastrophic but still leads to amusing interactions.

### How to reproduce

`echo aaa="foo/bar"`

Nu:
```
❯ echo aaa="foo/bar"
aaa="foo/bar"
```

### Expected behavior

Bash:
```console
$ echo aaa="foo/bar"
aaa=foo/bar
```

**Comment by kubouch** [comment]
I think this is correct:
```
❯ echo aaa="foo/bar"
aaa="foo/bar"
```
`aaa="foo/bar"` is parsed as a string and the double quotes are a part of the string. What you could try is something like this:
```
> let fmt1 = "%A - %d - %y/%A - %d"

> let fmt2 = "%A - %d - %y/%t - %a - %n"

> whipper cd -d /dev/sr0 rip $"--disc-template=($fmt1)" $"--track-template=($fmt2)"
```
which will pass the formatting string as one string, but without the double quotes.

**Comment by jansol** [comment]
If this is intended, the correct syntax for strings with special characters should be used all over the docs.

**Comment by kubouch** [comment]
The docs explain the [string interpolation](https://www.nushell.sh/book/types_of_data.html#strings) but maybe it should include more examples of working with external arguments and special characters.

In Nushell, strings are always "literal", they don't interpolate, escape or drop anything (similar to `''` in bash). If you need that, you need to use the "string interpolation". So maybe `$""` can be thought as an equivalent of `""` in bash.

I think the confusing thing here is that `aaa="foo/bar"` is understood as a "bare string" instead of `--arg=value` combo. Essentially, it's similar to writing `'aaa="foo/bar"'`.

Did you manage to get it working btw?

**Comment by jansol** [comment]
I just used bash

**Comment by fdncred** [comment]
from what i read here, it seems like nushell is working as designed as with kubouch's fmt1 and fmt2 example above. please reopen if you disagree.
