### ISSUE TITLE
Numbers and arguments don show up on black terminal background

### ISSUE THREAD

**Issue by JackFly26** [nushell/nushell#426]
When I use Nu in my kitty terminal, the numbers in a table are the exact same shade as the background, and so are the arguments to any commands.

**Comment by wycats** [comment]
Do we need theme support?

**Comment by JackFly26** [comment]
Probably. I definitely wouldn't mind it.

**Comment by coolshaurya** [comment]
I have the same  problem on kitty too. fish and bash work fine.

some photos - 
![image](https://user-images.githubusercontent.com/32027323/69965896-3f735c00-153b-11ea-8408-f92038715ab2.png)

when cursor is on flag -
![image](https://user-images.githubusercontent.com/32027323/69966006-819c9d80-153b-11ea-9b8d-0c7b9472b254.png)

**Comment by coolshaurya** [comment]
i messed around with other themes for kitty and it seems to work (taken from https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/kitty)

github theme -
![image](https://user-images.githubusercontent.com/32027323/69966567-ae04e980-153c-11ea-9b9f-30fa06f11c42.png)
![image](https://user-images.githubusercontent.com/32027323/69966590-ba894200-153c-11ea-9893-5226f9858cf3.png)


cobalt2 theme :
![image](https://user-images.githubusercontent.com/32027323/69966632-d55bb680-153c-11ea-9606-00a630fe777c.png)
![image](https://user-images.githubusercontent.com/32027323/69966654-df7db500-153c-11ea-8c28-8bb392abcc6a.png)

**Comment by coolshaurya** [comment]
Digging a bit further into the issue, the problem seems to be the `color0` variable in the kitty conf file
matches with the `background` variable. Since `color0` is used as the color for that text and it's same as the background, this gives black text on a black background. 

Possible fixes -

* switch to a different theme
* change the `color1` in your theme_name.conf
* make nu use something other than `color1` for table indices and command flags (not very practical in the short term)

I have chosen to go with the first option personally.

**Comment by coolshaurya** [comment]
This is related to #747

**Comment by coolshaurya** [comment]
I believe this issue was fixed by #1194

**Comment by jonathandturner** [comment]
Closing but please reopen if the issue still occurs with the latest master
