### ISSUE TITLE
No pushd?

### ISSUE THREAD

**Issue by cdecompilador** [nushell/nushell#4269]
### Related problem

I need `pushd`, I mean is avaible in all platforms, is weird that nushell doesn't have it

### Describe the solution you'd like

Implement it as a core command (not a plugin)

### Describe alternatives you've considered

None

### Additional context and details

None

**Comment by jntrnr** [comment]
In Nu, we've got a few other similar features that we use. You should check out the `shells` (which works with `enter` on a directory) command along with `n`, `p`, and `g` commands.

**Comment by cdecompilador** [comment]
ty

**Comment by unrelentingtech** [comment]
It is possible to use the "shells" feature in a similar way, with `enter` being a push and `exit` being a pop, but:

- you lose the ability to use "shells" for different purposes, like a more bookmark-esque usage;
- you don't get the equivalent of zsh's `auto_pushd`, which works great with `auto_cd` (my habit is to just run bare paths like `/tmp` `/usr/src` etc. to push and `p` (`popd` alias) to pop);
- `exit` docs say: "If this is the last open shell, Nu will quit" — this is soooo not acceptable for a `popd` replacement!

I just managed to recreate something similar to `auto_pushd` with scripting:

```nu
let-env PWD_STACK = []
let-env PWD_POPPING = false

let-env config = {
  # …
  hooks: {
    env_change: {
      PWD: {|before, after|
        let-env PWD_STACK = if $before != $nothing && $env.PWD_POPPING == false { ($env.PWD_STACK | append $before) } else { $env.PWD_STACK }
        let-env PWD_POPPING = false # must be here because of when the hook actually runs
      }
    }
  }
}

alias p = (
  let-env PWD_POPPING = true;
  cd ($env.PWD_STACK | last);
  let-env PWD_STACK = ($env.PWD_STACK | drop);
)
```

however:

- because the environment is not local to "shells", this does not work with them well either;
- the error when popping from an empty stack is not nice, I can't wrap this in an `if` because that's a scope and we'd be affecting the *scoped* env variables.

So the ideal solution would be a native directory history stack that would be *local* to each "shell".

**Comment by BatmanAoD** [comment]
I also think that a directory-stack _per shell_ would be useful, but I'm not currently using `shells` for anything else so I'll try using `enter` as a `cd` replacement for now.
