### ISSUE TITLE
Help needed to automatically deploy to winget

### ISSUE THREAD

**Issue by Macleykun** [nushell/nushell#4275]
I saw this article: https://www.techwatching.dev/posts/wingetcreate
And tried making this work for this project: https://github.com/Macleykun/MSEdgeRedirect/tree/main/.github/workflows
however, i'm not able to trigger the workflow to make the manifest.
And i'm not able to parse the version and url for the manifest from github release page.

What am i'm doing wrong? Should i use a different action to upload to releases?
I really think the article is well written, but i think i'm doing something wrong with either pushing to github and/or the initial workflow to make releases.

**Comment by fdncred** [comment]
@TechWatching did all the hard work. maybe they can give you some tips. since this isn't related to nushell, I think we should close this.

**Comment by TechWatching** [comment]
@Macleykun  I can have a look at your pipeline and releases if you want. But this nushell repo is not the place to discuss what is going wrong. Maybe you could ping me in an issue or discussion of your repository and give me details on what is going wrong and what did you do exactly.

**Comment by TechWatching** [comment]
While waiting for you to ping me in another issue: your workflow is not triggering because it uses GITHUB_TOKEN secret to publish the release. You can read more on that [here](https://www.techwatching.dev/posts/github-actions-var-and-context#tip-n2-do-not-use-your-repository-github_token-in-tasks-that-need-to-trigger-another-workflow).
