### ISSUE TITLE
 dbus-send: Data item ">/dev/null" is badly formed 

### ISSUE THREAD

**Issue by jithinX01** [nushell/nushell#4383]
### Describe the bug

`dbus-send: Data item ">/dev/null" is badly formed`      message is coming whenever enter key pressed. This was not coming in previous version. I upgraded from previous version to 0.44. I dont remember previous version. I use elementory os based on ubuntu 20.04. Also **folder location~** not visible.

### How to reproduce

No idea. It came after latest upgrade to 0.44

### Expected behavior

dbus-send: Data item ">/dev/null" is badly formed , should not come.

### Screenshots

![Screenshot from 2022-02-09 13-22-00](https://user-images.githubusercontent.com/2071424/153145771-cb816d2e-f080-4f77-aade-5b9b1e1de507.png)

**Comment by fdncred** [comment]
That's odd. I wonder how it worked on previous versions since nushell has never allowed redirection like `>/dev/null`. I doubt we fix this since we're all working on the latest version of nushell (0.59). You can try it and see if the latest version in nushell/main still has this problem. or if you don't want to compile nushell you can try and roll back to version 0.43 found in our release.

**Comment by hustcer** [comment]
@jithinX01 Can you try it again on the latest main or nu v0.62? Does this issue still exists?

**Comment by rgwood** [comment]
We haven't seen this recently. Suspect it's fixed, but @jithinX01 let us know if you're still experiencing it.
