### ISSUE TITLE
Add number of threads to `par-each`

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4407]
### Related problem

It would be useful to have the option to limit the number of threads used by `par-each` to avoid clogging resources on shared servers.

### Describe the solution you'd like

E.g., `par-each -j 8` would spawn only 8 threads.

**Comment by fdncred** [comment]
I think more testing of #4424 is needed to determine if it solves this problem or not. In theory, it should limit the thread count to the number specified. However, it was reported that it does not, which I don't fully understand since I believe it's using rayon's api appropriately. 

One point of speculation on my part is that it's similar to C#'s MaxDegreeOfParallelism setting which definitely limits threads but it doesn't exactly limit threads to the amount you specify because there are threads needed to manage the threads. But this is just a guess on my part. 

One way to tell is to pass the thread option and then query how many threads are created in the rayon thread pool. It could be that [RAYON_NUM_THREADS](https://github.com/rayon-rs/rayon/blob/master/FAQ.md#how-many-threads-will-rayon-spawn) is working as well, assuming my assumption above is correct.

**Comment by Benjamin-L** [comment]
#4424 doesn't solve the full problem here, even if it does correctly set the number of threads used, because that option is global for the entire `nu` process. It's often useful to have more granular control over the number of threads used in a single command or single scope.

For example, I often use `par-each` to dispatch high-latency network requests in parallel. In this case, you can use a very high number of threads and still see throughput improvements. On the other hand, when using parallelism for tasks that are CPU or IO-intensive, it often makes sense to limit the number of threads to something lower. In order to combine both types of tasks in a single script, you need the ability to control the number of threads in a finer grained way.

**Comment by fdncred** [comment]
ya, it looks to me like we need to use a `rayon::ThreadPool`. Something along these lines https://users.rust-lang.org/t/how-to-dispatch-work-to-rayon-threadpool/40918 maybe?

**Comment by fdncred** [comment]
I'd do the simplest thing to get implemented to let people try it out. Coming from Windows, you can supply MaxDegreeOfParallelism to C# programs but it doesn't work the way most people think it does. So, I'd implement something and see if it's a good fit and works as anticipated first. We can always make things fancy and feature-rich later.
