### ISSUE TITLE
Should we keep the `reverse` command as well as `--reverse` flags on some commands

### ISSUE THREAD

**Issue by twe4ked** [nushell/nushell#452]
Should we keep `sort-by foo --reverse` when we also have `sort-by foo | reverse`.

I don't have a strong opinion on this but it might flow on to other similar things where we could either add a flag to multiple commands or rely on more composable commands.

**Comment by Akito13** [comment]
Looking at the principle and goals of the project, I assume it might make sense to use the piped solution. On the one hand it seems more conforming, on the other it seems more modular, as you could obviously rearrange the reverse in another flow whereas an option is bound to a specific command. 
There is also the option to make both available, but I don't think this would be useful. It is helpful to make certain things strict, especially looking from a mechanical point of view, to partially enforce good practice and following a pattern that has as few exceptions to the rule as possible, so that understanding the concept is easy and its usage becomes intuitive over time, as you understand the prime design model behind this project.

**Comment by jedahan** [comment]
Less flags more pipes seems to be a space this project is well-equipped to explore.

**Comment by twe4ked** [comment]
Will do!
