### ISSUE TITLE
Move env_conversions from config to environment variables

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4545]
### Related problem

Config shouldn't change how the code is executed. Env conversions can have subtle effects on how external commands behave and missing / different config can thus change the behavior. This was the cause of #4463.

### Describe the solution you'd like

Change existing `env_conversion` config entry to be `ENV_CONVERSIONS` environment variable.

**Comment by lukexor** [comment]
This bit me today when upgrading since PATHs stopped working and normal externals like `ifconfig` couldn't be found. Could you update #4300 and remove the invalid conversion configuration. I suspect not having this "out of the box" is going to bite a lot of users who try to define their PATH in their config with a list.

**Comment by kubouch** [comment]
@lukexor Yeah, sorry, I forgot to remove it from the config. It's fixed now. It is also a part of the default config now: https://github.com/nushell/nushell/blob/main/src/default_config.nu#L31
