### ISSUE TITLE
Surprising (buggy?) ctrl-c behavior

### ISSUE THREAD

**Issue by llimllib** [nushell/nushell#457]
This sequence of events is surprising (and, I think, buggy) to me:

1. type `ls /tmp/xzy^c`
2. the command exits and I'm brought to a new line, which I expect. I frequently ctrl-c in bash to mean "abandon this command and return me to a blank prompt"
3. type `ls /tmp/xzy^c`
4. `nu` exits

```console
$ nu
/Users/llimllib> ls /tmp/xzy
CTRL-C pressed (again to quit)
/Users/llimllib> ls /tmp/xzy
<I get returned to my bash prompt>
```

In this case, I expect to just have told nu twice to abandon the command I was entering, but instead I get dumped from the shell.

Is this expected behavior? `^c^c` in bash doesn't exit the shell, and I'm going to have to retrain my hands if I want to use nu without that.

**Comment by marekdedic** [comment]
Thumbs up for this - I also use Ctrl-c in this situation.
IMHO closing the shell on double Ctrl-c is weird - that's what Ctrl-d is for...

**Comment by Akito13** [comment]
I share this view. Additionally, I think there should be no warning at all, for the "click do le CTRL+C to exit shell", because this is utterly redundant. Especially since you are supposed to use a shell basically your whole session and not only for a couple minutes (like e. g. a SQL CLI ). 
Im not against removing the double CTRL+C exiting way, but the mentioned bug in this issue should be gone, as well as the warning message, in my opinion.

**Comment by SafariMonkey** [comment]
FWIW, I very frequently press CTRL-C many times in a row, the same way as I press CTRL-S repeatedly in editors or ESC multiple times in Vim. Quitting the shell every time that happens would be annoying, PDB (python debugger) already does quit on CTRL-C and it annoys me every time. I feel like this should be at least allowed to be disabled in favour of the usual CTRL-D on an empty line quitting.

**Comment by jonathandturner** [comment]
Yes, we can definitely make it configurable how ctrl-c works.
