### ISSUE TITLE
Wrong short flag parsing of `nu` binary

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4602]
### Describe the bug

Passing `-t` flag to Nushell does not work.

### How to reproduce

1. `nu -t 10`
```
Error: nu::parser::missing_flag_param (https://docs.rs/nu-parser/0.59.0/nu-parser/enum.ParseError.html#variant.MissingFlagParam)

  × Missing flag argument.
   ╭─[source:1:1]
 1 │ nu -t
   ·    ─┬
   ·     ╰── flag missing int argument
   ╰────
```

### Expected behavior

Should work. `nu --threads 10` works fine.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | 41fa1ab6                                 |
| commit_hash        | 41fa1ab6561e7bd048f3705628546e18a5a026b1 |
| commit_date        | 2022-02-21 15:46:19 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-21 17:46:48 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

**Comment by jntrnr** [comment]
I think this is coming from the hack I used to separate the flags given to `nu` vs the flags and params given to the script. We should probably improve the logic there a bit.

I'm also wondering if there's a way to make signature and the parser a bit smarter so that you can describe the idea of things after a certain point in the args as being not yours to parse. Between this and https://github.com/nushell/nushell/issues/4618 there seems to be some need for fancier signatures and signature parsing.

**Comment by jntrnr** [comment]
@kubouch this requires putting the flag into two places: the signature and a little workaround parser that gathers up the arguments for nu itself and the arguments for the script.

I'm putting together a PR to fix it up now, just something to watch for in the future as we add new flags.
