### ISSUE TITLE
Improve command not found error message with search terms

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4996]
### Describe the solution you'd like

JT's idea:
> What if when we can't find a command at all, if we should search the keywords and give an error like "The command fold isn't supported but the reduce command may support this functionality"

**Comment by rgwood** [comment]
This would be great!

Implementation might require a little bit of thought. As I understand it, resolving a command can happen in multiple stages:

1. Look for an internal command with the right name
2. If that failed, look for an external command with the right name
3. (Windows only) If that failed, [tell cmd.exe to run the command and hope for the best](https://github.com/nushell/nushell/issues/4932#issuecomment-1078628243)

I think Nu will still need to do all of that, and then display the new message _only if the external command was not found_. On Windows, we might need to parse cmd.exe's output to detect whether it was able to find the command.

### Current Error Message

For context, here's what currently happens if you try to run a non-existent `foo` command  in Nu on Linux:

```
〉foo
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #2:1:1]
 1 │ foo
   · ─┬─
   ·  ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

And here's Windows:

```
> foo
'foo' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by kubouch** [comment]
Yes, good points. It might be a bit tricky to figure out when external command has failed on Windows. Checking for a string "not recognized" or similar won't work because of different localizations.

**Comment by kubouch** [comment]
Yes, good points. It might be a bit tricky to figure out when external command has failed on Windows. Checking for a string "not recognized" or similar won't work because of different localizations.

**Comment by rgwood** [comment]
I think this should be easier to implement now that this change for Windows has landed: https://github.com/nushell/nushell/pull/6253
