### ISSUE TITLE
Design better raw string syntax

### ISSUE THREAD

**Issue by sophiajt** [nushell/nushell#5091]
### Related problem

As of https://github.com/nushell/nushell/pull/5090 we're using backticks for raw strings.

These are fine, but have some issues:

- they're a bashism, but don't work like the bash version
- they're difficult to type on some keyboards

### Describe the solution you'd like

Something a bit more Rust-like maybe? Something that isn't a bashism and is clearly a special kind of string.

### Describe alternatives you've considered

We can keep backtick and just take the disadvantages.

**Comment by webbedspace** [comment]
Backtick strings aren't necessarily a "Bashism" - they've been added to Javascript in 2016 (but serve as multi-line + interpolation strings rather than raw strings).

**Comment by e-codes-stuff** [comment]
Any updates on this? I feel that backtick strings are a bit confusing right now specifically because of how they are interpreted as a command to execute in the context of things like `let` bindings. I would prefer these cases being separate, and having some explicit "raw string" concept like Rusts `r"<string contents>"` syntax which always produces a string value.
