### ISSUE TITLE
Rich text input features

### ISSUE THREAD

**Issue by brandonros** [nushell/nushell#510]
One of my biggest complaints about working with the command line all day is that it doesn't support the same flexibility of a "rich text" input. Some examples include:

* Ctrl + Z / Ctrl + Shift + Z for undo / redo
* mousedown + drag to select

Is this possible at the shell level? I could be mistaken.

**Comment by Geemili** [comment]
> * Ctrl + Z / Ctrl + Shift + Z for undo / redo

This is already supported at the text level using `rustyline`. List of actions `rustyline` supports: https://github.com/kkawakam/rustyline#actions

`bash`, `fish`, `zsh`, etc. all have some support for these kinds of commands too, btw.

A higher-level undo/redo, like undoing `rm foo.txt`, may be possible at the shell level, but I think it would be better at the application level.

> * mousedown + drag to select

Some terminal emulators handle this already. For example the [termite](https://github.com/thestinger/termite) terminal emulator, supports selecting text with the mouse and copying/pasting it.

However, it is also possible to [recieve mouse events](http://www.tldp.org/HOWTO/NCURSES-Programming-HOWTO/mouse.html) from terminal applications. The shell could integrate text selection to provide a better experience. However, I can't think of any benefits of doing this off the top of my head.

**Comment by Aloso** [comment]
One very important action that's missing is <kbd>Ctrl + ArrowLeft</kbd>/<kbd>Ctrl + ArrowRight</kbd> to move the cursor by a whole word. I use it in bash all the time.

**Comment by brandonros** [comment]
> However, it is also possible to recieve mouse events from terminal applications. The shell could integrate text selection to provide a better experience. However, I can't think of any benefits of doing this off the top of my head.

beginning middle end

![image](https://user-images.githubusercontent.com/8949910/64135005-33e48d80-cdb2-11e9-837a-4fce1592b71d.png)

double click to select word

![image](https://user-images.githubusercontent.com/8949910/64135016-3ba43200-cdb2-11e9-9411-2d22a5a7d624.png)

use mouse cursor to select entire line, or parts of line quickly

**Comment by Geemili** [comment]
> One very important action that's missing is Ctrl + ArrowLeft/Ctrl + ArrowRight to move the cursor by a whole word. I use it in bash all the time.

I agree, and it looks like it's somewhat straightforward to implement this: https://github.com/kkawakam/rustyline/issues/146


> double click to select word
>
> use mouse cursor to select entire line, or parts of line quickly

This is built into termite as well.

**Comment by Aloso** [comment]
I really dislike the approach to close issues after 30 days of inactivity. Just because there are no new comments does NOT mean that the issue is solved -- I would even say the opposite is true.

**Comment by jonathandturner** [comment]
@Aloso - we may need to update how often it checks, to get the right balance, but it's important that there are people who report an issue and are actively around to help with it also. Many issues tend to be someone who had an idea, and that idea may have already been fixed or the design may need to be updated to match with recent changes. Keeping the issues fresh is important.

It's a bit of a balancing act. To stop the automatic closure, you can reply to an issue and just let the bot know it's still active, and it won't close the issue.

**Comment by waldyrious** [comment]
> To stop the automatic closure, you can reply to an issue and just let the bot know it's still active, and it won't close the issue.

IMHO that's not a good way to ensure issues keep fresh. It just adds noise to the discussion: a comment by the bot, a reply to the bot which may not add anything new to the discussion (e.g. it may be waiting on a decision by the core team, or for another feature to land, or for someone who's temporarily unavailable, etc.) plus the labeling/unlabeling action logs. All this just adds more clutter to the thread and makes it harder to process afterwards — unless someone comes and manually hides those comments (which also requires more work from maintainers).

I'm all for having the bot help surfacing issues that may have inadvertently slipped out of people's attention, but otherwise I don't see much benefit in automatically closing issues. I mean, it's not like a repo needs to get to inbox zero — it's hopeless to try that, since the maintainers can't control the input anyway. Older issues naturally drift to the tail end of the issue list, so they won't really be taking up real estate in the issue list or anything. My suggestion would be to simply disable the automatic closing of issues, but if you want to keep that feature, then I'd suggest at least making it a relatively long period after the stale warning.

(Sorry for the rant btw! 😅 As you can imagine, this is a subject that bothers me a bit.)

**Comment by wischi-chr** [comment]
I tried nu a few versions ago and it was really nice. I just gave it a go again and I must say it improved a lot, but this issue is IMHO still the biggest blocker to switch from other shells.
 
The cmd `Ctrl + Z` to undo works fine. I like that it undoes an entire word and not just a single letter like powershell.

I use the following combinations a lot and they are (unless it can be configured/enabled and I missed that) currently missing:

| Combination                                                                                  | Explanation                                                                                                                                                                                          |
| -------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `Ctrl + LeftArrow` <br/> `Ctrl + RightArrow`                                                 | Works partially, IMHO some special characters like punctuation should also work as stop points (try in powershell with "some.very.long.string.with.dots"). Maybe make those characters configurable? |
| `Ctrl + Z` <br/> `Ctrl + Y`                                                                  | Works partially, Undo with `Ctrl + Z` works but there is no redo                                                                                                                                     |
| `Shift` <br/> + all `Ctrl` movements from above (including `Shift + Home` and `Shift + End`) | Select text                                                                                                                                                                                          |
