### ISSUE TITLE
Tech Debt: Compile times

### ISSUE THREAD

**Issue by xmclark** [nushell/nushell#517]
Installing with the bells-and-whistles features leads to an end-to-end install time of nearly 10 minutes. 

For `nu 0.2.0`, running `measure-command -Expression { cargo +nightly install nu --features rawkey,clipboard }` on Windows 10, Intel i7-8850H 2.60 GHz, 32 GB of RAM:

```
Days                  : 0
Hours                 : 0
Minutes              : 9
Seconds              : 42
Milliseconds        : 730
Ticks                   : 5827303547
TotalDays            : 0.00674456429050926
TotalHours          : 0.161869542972222
TotalMinutes       : 9.71217257833333
TotalSeconds       : 582.7303547
TotalMilliseconds : 582730.3547
```

It is typical of Rust to have long compile times, so this is par for the course. There is opportunity for improvement here. 

Some ideas:
- As of `0.2.0`, this project has 64 dependencies. Through refactoring, dependencies could be tuned or removed.
- ??? 🙃 

---

Edit, just saw https://github.com/nushell/nushell/issues/518

This test was made for the version that says 0.2.0 but actually installs 0.1.3 :)

**Comment by wycats** [comment]
Thanks for taking the time to gather this information!

We're definitely open to efforts to improve cold compile times, and I wouldn't say no to PRs that made compile times faster without making nushell harder to maintain.

[PDI!][pdi] (Please Do Investigate)

[pdi]: https://github.com/basecamp/handbook/blob/master/vocabulary.md#pdi

I'm going to close this issue because it doesn't represent an area of active work, but we are very interested in improvements here, and would gladly accept concrete pull requests to improve it.
