### ISSUE TITLE
path relative-to example is broken

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#5202]
### Describe the bug

```
>  ls ~ | path relative-to ~ -c [ name ]
╭────┬──────────────────────────────────────────────────────────────────────────────┬──────┬───────┬──────────────╮
│ #  │                                     name                                     │ type │ size  │   modified   │
├────┼──────────────────────────────────────────────────────────────────────────────┼──────┼───────┼──────────────┤
│  0 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │    96 │ 4 months ago │
│  1 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │   224 │ 2 days ago   │
│  2 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │   160 │ 4 months ago │
│  3 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │   384 │ 3 days ago   │
│  4 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │ 2,784 │ 3 months ago │
│  5 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │   160 │ 4 months ago │
│  6 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │   160 │ 3 months ago │
│  7 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │   192 │ 4 months ago │
│  8 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │   160 │ 4 months ago │
│  9 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │   832 │ 4 months ago │
│ 10 │ CantConvert("prefix not found", "string", Span { start: 77494, end: 77496 }) │ dir  │   128 │ 4 months ago 
```

### How to reproduce

run the command above

### Expected behavior

works

### Configuration

|key|value|
|-|-|
|version|0.61.0|
|branch|update_cargo_lock|
|tag||
|short_commit|56af7e8d|
|commit_hash|56af7e8d5f3db8c9838aea92ca1c8541dccec36b|
|commit_date|2022-04-14 11:48:17 +00:00|
|build_os|macos-aarch64|
|rust_version|rustc 1.60.0 (7737e0b5c 2022-04-04)|
|rust_channel|stable-aarch64-apple-darwin|
|cargo_version|cargo 1.60.0 (d1fd9fe2c 2022-03-01)|
|pkg_version|0.61.0|
|build_time|2022-04-14 06:58:07 -05:00|
|build_rust_channel|debug|
|features|dataframe, default, trash, which, zip|
|installed_plugins|gstat|

**Comment by strega-nil** [comment]
It looks like there are two issues here:

* `ls` does a `relative-to ('.' | path expand)`
* `relative-to` does not support going up in directory structures
* `relative-to` does not support relative paths at all

I think there are a few things that'd be good to change:

1. don't do `relative-to` in `ls`
2. allow `relative-to` to go up in directories
3. allow `relative-to` to use expanded and relative paths (allow starting with ~, allow cwd-relative paths)
4. don't error in `relative-to` if the paths are non-related
   - this is the least important one to me, since with 2., the only unrelated paths are those in different drives on Windows
   - We could also consider doing this instead of 2., but I think `'/a/b' | relative-to /a/b/c` should return `..`

Just the first will solve the _specific_ example, tho it still makes `relative-to` not as useful as it could be.

**Comment by fdncred** [comment]
It actually used to work in older versions of nushell. I'd like it to work like it did previously in version 0.44.0.
```
> ls ~ | path relative-to ~ -c [ name ]
╭────┬──────────────┬──────┬───────┬──────────────╮
│ #  │ name         │ type │ size  │ modified     │
├────┼──────────────┼──────┼───────┼──────────────┤
│  0 │ Applications │ Dir  │    96 │ 4 months ago │
│  1 │ Desktop      │ Dir  │   288 │ 2 hours ago  │
│  2 │ Documents    │ Dir  │   160 │ 4 months ago │
│  3 │ Downloads    │ Dir  │   384 │ 4 days ago   │
│  4 │ Library      │ Dir  │ 2,784 │ 3 months ago │
│  5 │ Movies       │ Dir  │   160 │ 4 months ago │
│  6 │ Music        │ Dir  │   160 │ 3 months ago │
│  7 │ Pictures     │ Dir  │   192 │ 4 months ago │
│  8 │ Public       │ Dir  │   160 │ 4 months ago │
│  9 │ from_old_mac │ Dir  │   832 │ 4 months ago │
│ 10 │ src          │ Dir  │   128 │ 4 months ago │
╰────┴──────────────┴──────┴───────┴──────────────╯
```

**Comment by strega-nil** [comment]
Investigation report for 0.44.0:

### 1.`ls ~`, `ls relative-path`

`ls ~` _does not_ return paths relative to the current directory.

```
/Users/nimazzuc/projects/nushell(HEAD)> ls ~ | to md
```
|name|type|size|modified|
|-|-|-|-|
|/Users/nimazzuc/Applications|Dir|128 B|2 months ago|
|/Users/nimazzuc/Desktop|Dir|448 B|2 days ago|
|/Users/nimazzuc/Documents|Dir|768 B|2 months ago|
|/Users/nimazzuc/Downloads|Dir|2.3 KB|an hour ago|
|/Users/nimazzuc/Library|Dir|2.9 KB|3 months ago|
|/Users/nimazzuc/Movies|Dir|224 B|2 months ago|
|/Users/nimazzuc/Music|Dir|192 B|2 months ago|
|/Users/nimazzuc/Parallels|Dir|192 B|2 days ago|
|/Users/nimazzuc/Pictures|Dir|288 B|2 months ago|
|/Users/nimazzuc/Public|Dir|128 B|a year ago|
|/Users/nimazzuc/projects|Dir|608 B|2 days ago|

However, `ls ..` _does_ return relative directories, so they are not absoluted.

```
/Users/nimazzuc/projects/nushell(HEAD)> ls .. | to md
```
|name|type|size|modified|
|-|-|-|-|
|../ApprovalTests.cpp.CMakeSamples|Dir|736 B|6 months ago|
|../cmake|Dir|1.2 KB|a week ago|
|../dotfiles|Dir|160 B|9 months ago|
|../homebrew|Dir|992 B|2 weeks ago|
|../misc-fun|Dir|320 B|2 months ago|
|../misc-work|Dir|864 B|2 months ago|
|../msvc|Dir|672 B|a week ago|
|../ninja|Dir|640 B|a week ago|
|../nushell|Dir|864 B|16 minutes ago|
|../rust|Dir|640 B|a week ago|
|../testproj|Dir|256 B|2 hours ago|
|../vcpkg|Dir|992 B|2 days ago|
|../vcpkg-ce|Dir|800 B|3 weeks ago|
|../vcpkg-tool|Dir|928 B|4 days ago|
|../vcpkg.github.io|Dir|704 B|4 months ago|
|../x264|Dir|896 B|2 days ago|

resolution: implement 1b.

### 2. `a/b relative-to a`

This doesn't work; however, the error message is a _lot_ nicer

```
/Users/nimazzuc/projects/nushell(HEAD)> '/a' | path relative-to '/a/b'
error: '/a' is not a subpath of '/a/b'
   ┌─ shell:25:25
   │
25 │ '/a' | path relative-to '/a/b'
   │ ----                    ^^^^^^ should be a parent of the input path
   │ │                        
   │ originates from here
```

resolution: implement 2a. (no change)

### `path relative-to` - expanded and relative paths

`path relative-to` _does_ expand the rhs, and does _not_ expand the lhs.

```
/Users/nimazzuc/projects/nushell(HEAD)> '~' | path relative-to '~'
error: '~' is not a subpath of '/Users/nimazzuc/'
   ┌─ shell:30:24
   │
30 │ '~' | path relative-to '~'
   │ ---                    ^^^ should be a parent of the input path
   │ │                       
   │ originates from here
```

`path relative-to` _does not_ prepend the CWD.

```
/Users/nimazzuc/projects/nushell(HEAD)> '..' | path relative-to '/Users/nimazzuc'
error: '..' is not a subpath of '/Users/nimazzuc'
   ┌─ shell:36:25
   │
36 │ '..' | path relative-to '/Users/nimazzuc'
   │ ----                    ^^^^^^^^^^^^^^^^^ should be a parent of the input path
   │ │                        
   │ originates from here
```

resolution: implement 3b. (this is a slight change in behavior since it also expands the lhs)
