### ISSUE TITLE
Cannot build Docker image

### ISSUE THREAD

**Issue by dedifferentiator** [nushell/nushell#525]
Trying to build an image with [Dockerfile](Dockerfile), but it always crashes on:

```
   ...

    Compiling futures-async-stream v0.1.0-alpha.4
error[E0554]: #![feature] may not be used on the stable release channel
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.1.0-alpha.4/src/lib.rs:194:1
    |
194 | #![feature(gen_future, generator_trait)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `futures-async-stream`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installoCE6K1`

Caused by:
  build failed
The command '/bin/sh -c cargo install nu' returned a non-zero code: 101

```
Have no idea what to do with this.

**Comment by androbtech** [comment]
@vsoch

**Comment by vsoch** [comment]
That’s strange I didn’t hit that error -  can you try the recipes here that build from source? https://github.com/nushell/nushell/pull/500

**Comment by vsoch** [comment]
It's disconcerting that there could be differences in building using Docker - @dedifferentiator did you see a message about using a nightly build (I did) which would contradict the message about using a stable release channel?

@androbtech can we turn on CircleCI asap for #500 so we can test, and get the Dockerfile fixed in master fixed asap?

**Comment by vsoch** [comment]
I think this error comes down to inconsistency between when the install decides to use the stable vs. nightly channels (when I built, if you look at the PR [I noted](https://github.com/nushell/nushell/pull/429#issuecomment-524675238) that nightly was used for the build, and mine worked). As a workaround (and we will need to test the updated files too) you can try this fix - specifying nightly specifically!

https://stackoverflow.com/a/53137160/3212944

Terribly sorry about the issue - this almost never happens with containers. I'm trying to rebuild again without cache to see if it triggers for me, and I'm hoping we can turn on CircleCI for the PR I linked so that the container build can be properly tested.

**Comment by dedifferentiator** [comment]
@vsoch nevermind, I've found the reason, it's on my side :)

Thanks for paying attention and sorry for interrupting

**Comment by vsoch** [comment]
Definitely never apologize for posting issues! We're here to help :) What was the issue?

**Comment by dedifferentiator** [comment]
Looks like I didn't have the part of source code from repo, I thought the problem in Dockerfile or the image. Should've checked it before opening an issue :c

**Comment by vsoch** [comment]
@dedifferentiator since your build is resolved, do you want to close the issue?

**Comment by wycats** [comment]
Closing as fixed on master 👍
