### ISSUE TITLE
Confusing `merge` behaviour involving duplicate fields

### ISSUE THREAD

**Issue by panicbit** [nushell/nushell#5282]
### Describe the bug

According to the help of `merge`, the table given as parameter is supposed to get merged into the input table:

> Parameters:
>   block: the block to run and merge into the table

However, the effect appears to be exactly the opposite (observable via overlapping column names).

#### Example 1: Tables
```
❯ [{foo: 42}] | merge { [{foo: 777}] }
╭───┬─────╮
│ # │ foo │
├───┼─────┤
│ 0 │  42 │
╰───┴─────╯
```

#### Example 2: Records
```
❯ let res = ({foo: 42} | merge { {foo: 777} })
❯ $res
╭─────┬─────╮
│ foo │ 42  │
│ foo │ 777 │
╰─────┴─────╯
❯ $res.foo
42
```

#### Example 1: Tables
```
❯ [{foo: 42}] | merge { [{foo: 777}] }
╭───┬─────╮
│ # │ foo │
├───┼─────┤
│ 0 │ 777 │
╰───┴─────╯
```

#### Example 2: Records
```
❯ let res = ({foo: 42} | merge { {foo: 777} })
❯ $res
╭─────┬─────╮
│ foo │ 777 │
╰─────┴─────╯
❯ $res.foo
777
```

The record key appearing twice is surprising, but probably acceptable and even useful, *however*, I think it might be a good idea to have a flag for toggling that behaviour.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | 7e730e28                                 |
| commit_hash        | 7e730e28bbe5c76147bd4fe88ad043662f9155ba |
| commit_date        | 2022-04-21 05:56:56 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-21 10:59:42 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
this may be a clue to what's going on.
```
> let f = ([{foo: 42}] | merge { [{foo: 777}] })
$f
╭─────╮
│ foo │
├─────┤
│  42 │
├─────┤
│ foo │
╰─────╯
```
```
$f | debug -r 
╭────────────────────────────────╮
│ Record {                       │
│     cols: [                    │
│         "foo",                 │
│         "foo",                 │
│     ],                         │
│     vals: [                    │
│         Int {                  │
│             val: 42,           │
│             span: Span {       │
│                 start: 122253, │
│                 end: 122255,   │
│             },                 │
│         },                     │
│         Int {                  │
│             val: 777,          │
│             span: Span {       │
│                 start: 122275, │
│                 end: 122278,   │
│             },                 │
│         },                     │
│     ],                         │
│     span: Span {               │
│         start: 122260,         │
│         end: 122265,           │
│     },                         │
│ }                              │
╰────────────────────────────────╯
```
so,i wonder if the table drawing just has a bug, but those 2 "foo" columns look suspiciously wrong too... maybe?

**Comment by WindSoilder** [comment]
Occasionally, I've investigated the command, and it's relative to duplicate column :)  I'd like to share what I find, please correct me if I'm wrong:

------

The issue comes from cols and vals all represent as `Vec`, when `Value::Record` is created, it doesn't filter duplicated column.  So duplicate column and relative different value can exist inside `nu`.  

It's [get_columns](https://github.com/nushell/nushell/blob/main/crates/nu-engine/src/column.rs#L4) function to make sure that table column unique, but just at `view` level.  So in internal, duplicate columns can go everywhere.

-------------

> so,i wonder if the table drawing just has a bug, but those 2 "foo" columns look suspiciously wrong too... maybe?

@fdncred It maybe wrong, but I think we have no choice to make the duplicate columns(and relative values) lays inside `nu`.
In ideal, we can restrict `cols` to be unique while creating table or record.
But we may introduce too high performance overhead during creating Record(we create it every where, and duplicate column in a table shoudn't happen too much?), from what I learned, that's just why columns and vals are represent as `Vec`.

**Comment by fdncred** [comment]
@WindSoilder after talking about this a bit this was one recommendation, we should probably merge columns of the same name together, and maybe error if the values don't line up.
