### ISSUE TITLE
Configurable default viewers

### ISSUE THREAD

**Issue by ZetaNumbers** [nushell/nushell#5368]
### Related problem

Someone would like to have `ls` print like it's `ls | grid -s " "`. 

### Describe the solution you'd like

Make default viewer configurable, as a block with input arguments: last command as a list of strings, input value.

### Describe alternatives you've considered

`def l [path : path = .] { ls $path | grid -s " "}`

**Comment by PerBothner** [comment]
Alternatively, one could specify a "viewer pipeline" as a string.  For example:

     let-env REPL_VIEWER = 'grid -s " "'

But I suspect a command would be cleaner:

    def repl_viewer [] { grid -s " " }

This solves the issue of #1570 - for example:

    def repl_viewer [] { to html --partial | domterm hcat }

Most sophisticated output printing could use a plugin.

This [comment](https://github.com/nushell/nushell/issues/1570#issuecomment-612347661) mentions an `autoview` command and `autoview.rs` - neither of which exist in the current code.  I suspect this would be a bit more complicated with the current codebase, though I believe the "hook" should go somewhere in the `print` function in `pipeline_data.rs`.

**Comment by PerBothner** [comment]
Here is a simple/experimental proof-of-concept:

[printer-patch.txt](https://github.com/nushell/nushell/files/9845186/printer-patch.txt)

It "works" for DomTerm by putting the following in env.nu: 

    def repl_print [] {
        to html --partial | domterm hcat
    }

First problem - I don't know how to conditionalize this. For example, the following doesn't work:

    if "DOMTERM" in (env).name {
    def repl_print [] {
        to html --partial | domterm hcat
    }
    } else {
    }

Other problems/issues that I can think of:

* Perhaps this would be a "hook" rather than a function?
* What is a good name - whether as a hook or function?
* We probably want to do the initial part of `pipeline_data::print` (the code that handles `PipelineData::ExternalStream`) before we check for `repl_print`.  Seems easy to fix by putting the former logic into a separate function.
* The logic is not robust - the result of the nested `eval_block` is ignored.

I'll bring these issues up on Discourse.

**Comment by PerBothner** [comment]
An alternative patch, using a `print_value` hook:

[print-hook-patch.txt](https://github.com/nushell/nushell/files/9845829/print-hook-patch.txt)

The logic in the `eval_source` function looks a little half-assed.

**Comment by sholderbach** [comment]
Considered solved with the `display_output` hook (#6915)
