### ISSUE TITLE
error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by tim77** [nushell/nushell#540]
Trying to build this on Fedora 30 but got this error when compile `nu v0.2.0`:

```
error: linking with `cc` failed: exit code: 1
```

Rust-nightly from rustup.

[full build.log](https://github.com/nushell/nushell/files/3560805/full.build.log)

**Comment by jonathandturner** [comment]
@tim77 - Building with Rust requires a C compiler toolchain (mostly for linking, I think). Do you happened to have clang or gcc installed?

**Comment by tim77** [comment]
Installed:
```
gcc
gcc-c++
gmp-devel
```
No luck unfortunately.

**Comment by jonathandturner** [comment]
@tim77 - can you share the whole error that you're seeing?

**Comment by tim77** [comment]
😕
[build.log](https://github.com/nushell/nushell/files/3562181/build.log)

**Comment by jonathandturner** [comment]
@tim77 - one thing I see in the log that doesn't seem quite right is this bit:

```
warning: the feature `async_await` has been stable since 1.39.0 and no longer requires an attribute to enable
 --> src/lib.rs:3:12
  |
3 | #![feature(async_await)]
  |            ^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

error: linking with `cc` failed: exit code: 1
```

It looks like your version of rustc may not be from the latest nightly. Are you building `nu` with the latest nightly of `rustc` and `cargo`?  You may also want to try to build `nu` directly from github rather than trying to build the 0.2.0 release, as there have been many bugfixes this past week.

**Comment by tim77** [comment]
Jesus Christ, @jonathandturner i apologize, this because i shared not enough RAM in VM and that's it. Terribly sorry for this noise.
