### ISSUE TITLE
Tilde expansion and external apps (Windows)

### ISSUE THREAD

**Issue by gitblit** [nushell/nushell#5456]
### Describe the bug

Internally, tilde expansion seems to be work correctly. The hand-off from `nu` to external apps does not work so seamlessly. To be fair, I tested this same ability in PowerShell and it suffers from the exact same problem. Perhaps it's my expectations that are wrong.

### How to reproduce

1. `ls ~/some/file/you/know` (works nicely)
2. `code ~/some/file/you/know` (opens editor for new file relative to your current directory)

### Expected behavior

I expected nu to pass along a fully-resolved path to the external tool.

### Screenshots

![image](https://user-images.githubusercontent.com/868217/167128493-803dde90-d11a-4612-8f87-d9dc381ef0d5.png)

**Comment by fdncred** [comment]
it would be nice to expand this before handing it off, not sure how easy/hard that is though.

**Comment by kubouch** [comment]
We've been recently toning down the auto-expansion on paths (in general, not just tilde) with externals because sometimes, a program wants to handle it in its own specific way. We cannot really know that `code` is a code editor that accepts a path. We can certainly discuss the tradeoffs but we've got a couple of complaints where Nushell's path autoexpansion messed up some external tools.

There are a couple of options now:
* You can use `code (~/some/file/you/know | path expand)`
* Create an `extern` wrapper around `code` which accepts a path type which then should auto-expand
* Make a PR to VSCode to expand tilde correctly

We could allow auto-expansion on external arguments, but then, we need to be sure to have a way to turn it off if necessary.

**Comment by gitblit** [comment]
Thinking out loud...

PowerShell has a behavior which will resolve `~` paths to the full path on interactive tab completion. Would that be an approach that could work for nu?

**Comment by fdncred** [comment]
so you do `ls ~/<tab>` and it expands to `ls /home/username` on mac/lin and `$env.HOMEDRIIVE$env.HOMEPATH` on windows? seems a reasonable approach to me.

**Comment by gitblit** [comment]
I am not sure how it behaves on mac/lin. That's a good guess. On Windows it behaves exactly as you describe.

**Comment by Halkcyon** [comment]
@kubouch if that's the case, why have it at all?  `| path expand` also requires you to quote the path which breaks the autocompletion.  It'd be a nice option to have it expand the tilde if you tab-complete the path.

**Comment by hustcer** [comment]
I think it works now on the latest main, if not please reopen

**Comment by pewill** [comment]
This works now. If there is a file `foo.txt` in the downloads folder you can open it in vscode with `code ~\Downloads\foo.txt` or notepad `notepad ~\Downloads\foo.txt`
