### ISSUE TITLE
nushell crashes when pressing CTRL + \ in `top`

### ISSUE THREAD

**Issue by joepie91** [nushell/nushell#5615]
### Describe the bug

When pressing `CTRL + \` ( ie. `^\`) while running `top`, nushell coredumps without any sort of error message.

### How to reproduce

1. Start a new nushell
2. Run `top`
3. Press `CTRL + \`

### Expected behavior

nushell should either pass on the input or do nothing with it.

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             |                                       |
| tag                |                                       |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.60.0                          |
| cargo_version      | cargo 1.60.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 1980-01-01 00:00:00 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

Tested in both Yakuake and Konsole, on NixOS 21.11. Issue also appeared in at least one other case, when running my development tooling in watch mode, but that'd be a lot harder to reproduce than just running `top`.

**Comment by bugabinga** [comment]
I can reproduce this in release `0.63.1` but also on `main` branch (888758b8132149e85b65492eb2e57ff97c5ef4b4).

Additional observations:
- some input scenarios are affected, some are not
  - affected
    - top
    - sudo password prompt
    - nushell `input` command
    - ssh-keygen
  - not affected
    - nushell readline
    - nano editor
    - helix editor
    - skim fuzzy finder   
- i am using a german keyboard. to input `\` i need to press `AltGr+ß`. `ß` is a key next to `0`. so in order to provoke the bug i press `Ctrl+AltGr+ß`.

|column0|column1|
|-|-|
|version|0.63.1|
|branch||
|commit_hash|6c07bc10e2cf3445e098089d184b86463c0a330a|
|build_os|linux-x86_64|
|build_target|x86_64-unknown-linux-gnu|
|rust_version|rustc 1.61.0 (Arch Linux rust 1:1.61.0-1)|
|cargo_version|cargo 1.61.0|
|pkg_version|0.63.1|
|build_time|2022-05-29 02:16:59 +00:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins||
