### ISSUE TITLE
Configurable shell fallback

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#5662]
### Related problem

When we use Invoke-WebRequest on windows in nushell like 

```pwsh
Invoke-WebRequest -Uri 'https://github.com/jftuga/less-Windows/releases/download/less-v562.0/less.exe' -OutFile $'($dist)\less.exe'
```
It fails with "'Invoke-WebRequest' is not recognized as an internal or external command, operable program or batch file.", guess `nu` will fallback to `cmd.exe` on Windows, can we fallback to `pwsh.exe` in someway? 

### Describe the solution you'd like

Add a config option like `fallback_shell` in the config file to make it possible to fallback to `pwsh.exe`

**Comment by hustcer** [comment]
Related issue: https://github.com/nushell/nushell/issues/4932

**Comment by fdncred** [comment]
We all know powershell/pwsh can be super slow to startup so I'm documenting this here in case this goes forward. 

We would need to call powershell something like this to minimize slowdowns as much as possible `pwsh_or_powershell -NoLogo -NonInteractive -NoProfile -ExecutionPolicy ByPass -Command "cmds"`

**Comment by CAD97** [comment]
Having pwsh as a fallback shell leads to an interesting case, where running scripts in the current directory is going to become quite difficult. If you run e.g. `x.py -h`<sub>pwsh</sub> in pwsh, you get

> Suggestion [3,General]: The command `x.py` was not found, but does exist in the current location. PowerShell does not load commands from the current location by default. If you trust this command, instead type: `.\x.py`. See `get-help about_Command_Precedence` for more details.

If `^x.py`<sub>nu</sub> sees the script file and "runs" it directly (this works because I have `py` as the launcher for `*.py` files, and this is the default for Python on Windows), then everything will work. But if this is going through the fallback shell, this won't work.

The reason this is interesting is that doing as pwsh asks and running `^"./x.py"`<sub>nu</sub> currently results in

```nu
❯ ^"./x.py" -h
'.' is not recognized as an internal or external command,
operable program or batch file.
```

coming from cmd:

```cmd
D:\git\rust-lang\rust>cmd /c ./x.py -h
'.' is not recognized as an internal or external command,
operable program or batch file.

D:\git\rust-lang\rust>cmd /c .\x.py -h
info: Downloading and building bootstrap before processing --help
      command. See src/bootstrap/README.md for help with common
      commands.
Updating only changed submodules
  Submodules updated in 0.03 seconds
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.48s
Usage: x.py <subcommand> [options] [<paths>...]

Subcommands:
    build, b    Compile either the compiler or libraries
    check, c    Compile either the compiler or libraries, using cargo check
    clippy      Run clippy (uses rustup/cargo-installed clippy binary)
    fix         Run cargo fix
    fmt         Run rustfmt
    test, t     Build and run some test suites
    bench       Build and run some benchmarks
    doc, d      Build documentation
    clean       Clean out build directories
    dist        Build distribution artifacts
    install     Install distribution artifacts
    run, r      Run tools contained in this repository
    setup       Create a config.toml (making it easier to use `x.py` itself)

To learn more about a subcommand, run `./x.py <subcommand> -h`
```

... so following this investigation, I guess `^"./x.py"`<sub>nu</sub> would work with a pwsh fallback shell, and it not working is a quirk of cmd.exe not accepting forward-slash paths.

However, the `pwsh` command @fdncred provides opens a new terminal window rather than running with the current stdin/out/err. This makes it not really appropriate for use as a fallback shell...

**Comment by fdncred** [comment]
yuck, we don't want to open another window.

**Comment by hustcer** [comment]
I think we can close this issue after https://github.com/nushell/nushell/pull/6253
