### ISSUE TITLE
Split open and fetch

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#568]
Currently open takes either a URL or a filepath. This is fun for demos, but it can get potentially confusing. Also, if people don't want to type out the whole url, we might mistake sites like "yahoo.com" as a filename rather than a website.

Seems good reason to split off the URL opening functionality into its own command. `fetch` could be a good first name

**Comment by AndresMPR** [comment]
I support this idea 💡 fetch for URL (maybe with options for GET and POST for interaction with web services, etc.) E.G. send email when certain ERRORS occur in a file system or on other ‘oops’ detection.

Open for files only, lots of ways to get mixed up otherwise!

This makes sense to me, at first blush anyway.
