### ISSUE TITLE
Visual length of Bengali text is incorrectly determined

### ISSUE THREAD

**Issue by schuelermine** [nushell/nushell#5735]
### Describe the bug

Nushell inserts too little padding after Bengali text

### How to reproduce

1. Write `echo ["জী._ডি._ব্লক_সল্টলেক_দূর্গা_পুজো_২০১৮.jpg", "Hello"]`

### Expected behavior

Expected output:

```
╭───┬───────────────────────────────────────────╮
│ 0 │ জী._ডি._ব্লক_সল্টলেক_দূর্গা_পুজো_২০১৮.jpg      │
│ 1 │ Hello                                     │
╰───┴───────────────────────────────────────────╯
```

Actual output:

```
╭───┬───────────────────────────────────────────╮
│ 0 │ জী._ডি._ব্লক_সল্টলেক_দূর্গা_পুজো_২০১৮.jpg │
│ 1 │ Hello                                     │
╰───┴───────────────────────────────────────────╯
```

### Screenshots

![Screenshot from 2022-06-08 01-48-11](https://user-images.githubusercontent.com/48802534/172501953-50d54626-d5fa-4765-9b28-40e02b8a3fdd.png)
![Screenshot from 2022-06-08 01-47-54](https://user-images.githubusercontent.com/48802534/172501962-92d190d1-5127-4602-bd37-4cf65c8d2997.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0                                    |
| cargo_version      | cargo 1.61.0                                    |
| pkg_version        | 0.63.0                                          |
| build_time         | 1980-01-01 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

I have tested this with Terminals `kitty` and `kgx` aka `gnome-terminal` and `konsole`. This includes the “correct” output.

**Comment by sholderbach** [comment]
That's a hard problem to solve:

For length determination we use the [unicode_width](https://unicode-rs.github.io/unicode-width/unicode_width/index.html) crate, that tries to follow a Unicode annex specifiying expected lengths. But that seems to be more of a suggestion than something that fixed with fonts and terminals seem to follow consistently. @fdncred and I ran several tests in that regard. I once slapped together a little testing binary to check if emojis are rendered with their defined with and it is super inconsistent where they differ from the specified with. 

https://github.com/sholderbach/unicode_measurements

Maybe we can try to adapt that to record data for that for differrent terminal emulators to have something to correct for. But as codepoints may be joined for a grapheme that could be a hard undertaking. (Also `reedline` currently always assumes that text flows from left to right. So RTL scripts like Hebrew or Arabic will cause mayhem. Unsure about the textflow for traditional Chinese)

**Comment by schuelermine** [comment]
Yeah, after further checking, my “correct” versions seem to not actually work all of the time.

**Comment by fdncred** [comment]
This is Windows Terminal with `FiraCode NF` font

![image](https://user-images.githubusercontent.com/343840/172689151-39e10627-db58-42de-9a03-cdb17f234bfe.png)
