### ISSUE TITLE
Add `nu check` command

### ISSUE THREAD

**Issue by rycee** [nushell/nushell#5825]
As discussed in https://github.com/nushell/nushell/discussions/5702 it would be useful to have a `nu check` command. When this command is applied to a file then the file is parsed but not run. If any errors are discovered during parsing then they are printed (either stdout or stderr are fine by me) and the command exits with an error status. A file without any errors discovered during parsing will result in `nu check` returning with a successful error status and no output printed.

**Comment by kubouch** [comment]
Cool, I've been thinking about the same thing some time ago. A couple of thoughts:

* I think it could be implemented such that inside the command, we create a working set, then parse the source but never merge the delta back to the engine state (it's not even possible since the engine state is immutable).

* The command should have two modes: one for modules, the other for scripts -- they are parsed a bit differently. Could be a flag, for example, `nu-check --as-module`.

* Instead of a file argument, the command could operate on a string or a raw output: `open foo.nu | nu-check`. This way we could use it to check any string, for example, the output from `view-source` (something like `view-source $env.PROMPT_COMMAND | nu-check` might be useful).

**Comment by hustcer** [comment]
`nu-check` is supported, thanks @Kangaxx-0
