### ISSUE TITLE
PosOverflow when parsing JSON containing very large number

### ISSUE THREAD

**Issue by chvck** [nushell/nushell#5907]
### Describe the bug

When parsing a JSON file where an object contains a very large number I see `thread 'main' panicked at 'Internal error: json parsing: ParseIntError { kind: PosOverflow }', crates/nu-json/src/util.rs:220:52` as it's attempting to parse the number as a u64, and hitting the `expect`

### How to reproduce

Try to parse 
```﻿
﻿          {
            "cmd_get": 1.998001998001998,
            "couch_docs_actual_disk_size": 29044032244,
            "couch_docs_data_size": 20956132290,
            "couch_spatial_data_size": 0,
            "couch_spatial_disk_size": 0,
            "couch_views_actual_disk_size": 18785057365,
            "couch_views_data_size": 5323749123,
            "curr_items": 18446744073715094000,
            "curr_items_tot": 16626891,
            "ep_bg_fetched": 0,
            "get_hits": 0.999000999000999,
            "mem_used": 14482854736,
            "ops": 1.998001998001998,
            "vb_active_num_non_resident": 2640298,
            "vb_replica_curr_items": 11086582
          }
```
The `curr_items` field causes a panic. I did this by creating a json file and just using `open`.

### Expected behavior

It should parse the number correctly.

### Additional context

I'm happy to undertake the work required here but needs discussion around how to handle this. Something with https://crates.io/crates/num maybe?

**Comment by WindSoilder** [comment]
I think the fix involved in supporting something like u128 or i128 value, which is builtin in rust.

But I wonder if we need to support such large number?

**Comment by chvck** [comment]
Ahh I wasn't aware of u128/i128. I think that some sort of support is needed (also open to other approaches though), this is a real world example and panicking is not ideal :)

**Comment by jntrnr** [comment]
I dug around a bit in the JSON spec:

https://www.rfc-editor.org/rfc/rfc7159#section-6

"This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [[IEEE754](https://www.rfc-editor.org/rfc/rfc7159#ref-IEEE754)] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.  A JSON
   number such as 1E400 or 3.141592653589793238462643383279 may indicate
   potential interoperability problems, since it suggests that the
   software that created it expects receiving software to have greater
   capabilities for numeric magnitude and precision than is widely
   available.

Note that when such software is used, numbers that are integers and
   are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.
"

My read of this is that we should be reading in numbers first as f64 and then, if they're an int and can fit in the int range, we can convert them to ints.

**Comment by chvck** [comment]
Do we definitely only want to conform to JSON spec and not go beyond with number support? Just thinking that this JSON file was actually written with Nushell (using `save`) so either both sides should support the larger number or neither side? Being able to write a file but then be unable to read it back is a bit of a weird user experience.

As an aside the Golang JSON library can certainly read this JSON object so I wonder if we should just try to parse to i/u128 looking at the length of the value or if i/u64 parsing fails?

I have looked at parsing as a float and then trying to coerce as an int as the JSON spec dictates but there aren't really constructs in Rust to do that (from what I can see) and the parsing logic that already exists seems like a good approximation - it does try to parse as a float first based on the characters within the value.
