### ISSUE TITLE
Environment variables set from config not available in standalone scripts

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#5934]
### Describe the bug

Environment variables set by config.nu and env.nu are not in scope when running a standalone script.

### How to reproduce

1. Run `$env`
2. Notice all nushell variables (such as NU_LIB_DIRS etc) available
3. Create following script and chmod it (if on Unix):
 ```
#!/usr/bin/env nu
$env
```
4. Run the script via `./script.nu`
5. Notice none of nushell's variables are available
6. Run the script via `nu script.nu`
7. Notice none of nushell's variables are available
8. Run the script via `nu --env-config $nu.env-path --config $nu.config-path script.nu`
9. Notice all variables are available as expected

### Expected behavior

I expected nu to source the config files automatically when running a standalone script

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.64.0                                              |
| branch             |                                                     |
| commit_hash        |                                                     |
| build_os           | linux-x86_64                                        |
| build_target       | x86_64-unknown-linux-gnu                            |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)                 |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)                   |
| pkg_version        | 0.64.0                                              |
| build_time         | 2022-06-15 09:04:16 +02:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
I believe this is because the config files aren't being loaded when running nushell this way. We've had several discussions about whether or not to loading config files like this. I can't remember the reasons why we do or don't. It would be good to discuss this in discord. There have also been a few changes to this in the last month or so.

**Comment by WindSoilder** [comment]
> I can't remember the reasons why we do or don't.

It's mentioned here: https://github.com/nushell/nushell/issues/5544#issuecomment-1133582699

> One argument against loading config by default when running scripts is portability. If you rely on implicit loading of your local config and send the script to your friend's machine, the friend won't be able to run it.
We already have --config and --env-config flags to nu so maybe we could change it that when you specify them, it would load the config but otherwise not?

And currently in the latest main, standalone will auto load config which is set from `env.nu`, but `config.nu` is not auto loaded.

**Comment by Yethal** [comment]
@WindSoilder in that case I think this can be closed down.
