### ISSUE TITLE
Support flag completion with only one `-`

### ISSUE THREAD

**Issue by merelymyself** [nushell/nushell#5949]
### Related problem

Currently, when you want to autocomplete flags, you have to type in `--` before `<tab>` suggests completions.

### Describe the solution you'd like

Allow for flag completions when one `-` is placed.

**Comment by merelymyself** [comment]
This is weirder than I thought at first. Completing `ls -` works perfectly, but completing another command (e.g. `do -`) does not.

**Comment by jackos** [comment]
I'm having a go at fixing this, can see my progress here:

https://github.com/nushell/nushell/compare/main...jackos:nushell:completions-fix

**Comment by jackos** [comment]
@merelymyself I found the problem here, for completions before running through the parser, it will push a `b'a'` onto the end of the command to signify where the user's cursor is. The short flags will only push into the vec if they match the definition, this is why `ls` works, because it has a `-a` short argument. https://github.com/nushell/nushell/pull/6067 fixes this by pushing a '-a' into that vec when the parser has found that short flags do exist, but it hasn't matched anything.
