### ISSUE TITLE
Error message has incorrectly proportioned labels on ─

### ISSUE THREAD

**Issue by schuelermine** [nushell/nushell#6165]
### Describe the bug

When typing `"─" - 2`, the resulting error message has a too large tooltip for `"─"`.

### How to reproduce

1. Type `"─" - 2`

### Expected behavior

Correctly proportion the string tooltip

### Screenshots

```
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
   ╭─[entry #15:1:1]
 1 │ "─" - 2
   · ──┬── ┬ ┬
   ·   │   │ ╰── int
   ·   │   ╰── doesn't support these values.
   ·   ╰── string
   ╰────
  help: Change string or int to be the right types and try again.
```

**Comment by fdncred** [comment]
oh, I see what you're saying. the underscore is too long for the one that points to "string". I think this is due to a span being off a little in the code.

**Comment by fancyplants** [comment]
I wanted to swipe this issue to fix since it would be my first contribution, but after some investigation it looks like this is actually an issue in the underlying error diagnostic crate: https://github.com/zkat/miette/issues/97

Would the goal be to wait (or attempt to fix in `miette` directly) for a fix from the underlying crate, or some workaround in the Nu code?

**Comment by fdncred** [comment]
If it's truly a miette issue you might submit a pr to kat's repo.

**Comment by sholderbach** [comment]
Should be resolved thanks to an upstream fix to miette
