### ISSUE TITLE
Regression in setting vi mode

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#627]
I think this used to work `config --set [edit_mode vi]` as per the PR that landed to add it, but if I try this now I get this error:

```
> config --set [edit_mode vi]
error: Error("unknown variant `vi`, expected one of `Primitive`, `Row`, `Binary`, `Table`, `Block`", line: 1, column: 63)
```

**Comment by androbtech** [comment]
Confirmed. It works on `0.2.0`

**Comment by est31** [comment]
This was a regression caused by #579 (verified through testing it before & after that PR). Most likely caused by cc8872b4eec3f39896ccb11d9c25a30a79c04dd7. In #569 I still verified that `config --set` still works but I didn't test it for #579 any more. Sorry for the inconvenience. Will try to find a fix by tommorow!

**Comment by androbtech** [comment]
@est31 No problem! Thank you!!
