### ISSUE TITLE
`open`/`save` URL and remove `fetch`

### ISSUE THREAD

**Issue by olanod** [nushell/nushell#6297]
### Describe the solution you'd like

Following the spirit of "everything is a URL" of Redox, it would be interesting if `open` could be a more generic concept and do more than just files. If we allow opening URLs `open` would also become pretty much the same as `fetch` so we wouldn't need that, to fetch a URL we just `open https://some.example/url`, the http(s) protocol handler does the necessary HTTP GET, similarly if we `{ some: data } | (write?)save https://some.example/url` the handler does a POST by default trying to infer the content-type. 

To avoid breaking everything the default protocol should be `file://` and any absolute or relative path gets expanded to `file://<the path>`. Other protocols can be added over time. e.g. `open postgresql://foo/db` should work the same as opening a sqlite file.

Having the possibility to extend this mechanism with custom protocol handlers can also be a powerful feature, it can be static code bundled with the shell or more interesting if it's some kind of plugin system that does work in external processes or using something like WASM.

**Comment by fdncred** [comment]
your proposal sounds interesting but i'm going to need a minute to get used to the thought of removing fetch.

**Comment by ksandvik** [comment]
We alredy have problems with 'open' in MacOSX as default way to open files, urls, so please do not extend it even further with moving fetch to open.

**Comment by hyiltiz** [comment]
It is probably better to keep network IO separate from local operations, esp. for a common shell command. Maybe an explicit subcommand `open url https://debian.org` can be used for discoverability (via tab completion)? But there are probably as many users who'd think of `fetch`ing a URL rather than opening one, so which one is more discoverable is debatable, and there is almost no point in creating two interfaces; users can easily create their own aliases if needed.

**Comment by adamijak** [comment]
I think we could support basic open/get and save/post methods. For anything more complicated we could use `fetch`.
