### ISSUE TITLE
Add support for the EDN data format

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [nushell/nushell#6415]
### Related problem

Nushell doesn't support working with data in the EDN format yet.

### Describe the solution you'd like

Adding support for parsing, working with, and exporting data in the EDN format.

### Additional context and details

I use EDN (Extensible Data Notation) as my primary structured serialisation format, not just in Clojure projects (EDN itself is an official subset of the Clojure language - the data literal part), but also for most of my scripting and general day-to-day system and workflow. Having 1st-class support for it in my Nushell would be amazingly powerful, allowing me to extend Nushell with my Clojure scripts and vice versa.

It's expressive, more readable than JSON or CSV, extensible for custom data (although the data fields can still be parsed if the receiver isn't aware of your custom data types, so best of both worlds!), and already has parsers in most popular languages (including a couple for Rust).

As an added bonus of supporting it, Nushell would also automatically gain the ability to parse Clojure programs into structured data and analyze/manipulate them!

**Comment by WindSoilder** [comment]
Hi, it's implemented in a plugin called [nu_plugin_formats](https://github.com/WindSoilder/nu_plugin_formats)

The plugin provides a command `from edn`, which converts from edn format string to nushell table. 

But I think it's impossible to convert from nushell table to edn file back, because edn contains more type infomration then nushell table(like edn have set structure, or something called symbol), when constructing table, original edn will lose these information.

And I'll close the issue for now, because it's not going to the nushell core command, feel free to play with that plugin and give your feed back :)

**Comment by NonlinearFruit** [comment]
WindSoilder's plugin is archived now and it recommends [nushell/nushell/tree/main/crates/nu_plugin_formats](https://github.com/nushell/nushell/tree/main/crates/nu_plugin_formats)

**Comment by FOSSforlife** [comment]
> WindSoilder's plugin is archived now and it recommends [nushell/nushell/tree/main/crates/nu_plugin_formats](https://github.com/nushell/nushell/tree/main/crates/nu_plugin_formats)

Hi, was EDN removed? I don't see it in the link you shared.

**Comment by NonlinearFruit** [comment]
I believe this story is to add EDN support to the official plugin format, but was closed because it was implemented in WindSoilder's plugin. But WindSoilder's plugin is now archived.
