### ISSUE TITLE
broken docker image nushell/nu:devel

### ISSUE THREAD

**Issue by jeka** [nushell/nushell#646]
In the last few days the docker image nushell/nu:devel is broken.
```
$podman  run -it --rm nushell/nu:devel 
nu: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by jonathandturner** [comment]
Thanks for letting us know, we'll investigate.

**Comment by vsoch** [comment]
hey @jeka see https://github.com/nushell/nushell/pull/650 - I missed those dependencies in the README, sorry about that!

Also really cool you are using podman! :)

**Comment by jeka** [comment]
I am sorry but I am confused. What is the connection between Image pool in Azure Pipelines and base image for generated Docker images?

**Comment by jankoprowski** [comment]
As far as I see you do not define Dockerfiles for Azure, just configure image you want to use in https://github.com/nushell/nushell/blob/master/.azure/azure-pipelines.yml

**Comment by jeka** [comment]
@jankoprowski, I am still confused. This issue is not about Azure DevOps services. It's about the base image for generated Docker images.

**Comment by vsoch** [comment]
@jeka there is no connection - I had tried to use the same base (16.04) but judging on the link shared (thank you @jankoprowski !) the choice simply seems to be because the better alterntive (18.04) isn't available. It's weird that the azure team maintains some set of special (modified) based images, but that's neither here nor there! I'm not completely happy with having nu-base and nu with two different bases, so I'm going to put in a PR to update both to 18.04, especially since reading the above.

**Comment by vsoch** [comment]
This issue is also fixed, there is no more libssl error. Thanks for reporting it @jeka and starting up conversation to make both bases better! Closing issue, PR coming in soon for the above.
