### ISSUE TITLE
Why are we deprecating `source`?

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#6571]
### Question

From what I understood, `source-env` was created to be usable with dynamic paths, in contrast to `use` which requires static paths. I understand that these have their own use cases, but my question is - why deprecate `source`?

Once `source` is deprecated, the [zoxide](https://github.com/ajeetdsouza/zoxide) plugin would now require running the same file twice:

```shell
use ~/.zoxide.nu * # this pulls in functions
source-env ~/.zoxide.nu # this pulls in the configuration
```

IMO, this is quite unfortunate and there should be a simpler way of doing this.

**Comment by fdncred** [comment]
we're still trying to figure out what to do exactly. `source-env` no longer is able to take dynamic paths due to a bug we found with it. I _think_ we plan on making `use` allow env vars and custom commands, but I could be mistaken. @kubouch do you remember what our plans are?

**Comment by kubouch** [comment]
Yeah, fdncred is right, currently, we're planning to actually remove `source-env` altogether because dynamic paths were proven unfeasible. Instead, we plan to make `use` automatically run the `export-env` block when called. You won't need to run the two commands anymore:
```
use ~/.zoxide.nu *  # this pulls in functions AND the configuration
```

The reason for removing `source` is that it doesn't really work like other shells' source. It is more equivalent to C's `#include` and it causes a constant confusion for users trying to source dynamic paths (it is one of the main issues we keep getting). Also it doesn't scale very well with larger applications so we're kind of trying to push more towards using the modules.

However, I think we should still keep the `source` in at least for the next release so that everybody has the chance to accommodate to the new changes.

**Comment by ajeetdsouza** [comment]
> Instead, we plan to make use automatically run the export-env block when called.

That's a reasonable solution, I think. Thanks!
