### ISSUE TITLE
Incorrect documentation for some string operations

### ISSUE THREAD

**Issue by MichelMunoz** [nushell/nushell#6582]
### Describe the bug

In nushell there seem to be two types of regular expressions, the globs for files ops, and "regular expression" for string operations ; the later are not (to my knowledge) documented, which can lead to surprising results

### How to reproduce

```
> '/home/joe/test.txt' | str ends-with '.txt'
true
> '/home/joe/test.txt' | str ends-with '.txt|.sh'
false
```
The second should be `true` _if the regular expression are the usual type of syntax used in editors / languages_.
The other possibility is that nushell as its own definition, which is not documented. 

### Expected behavior

_if its not a bug_, then somewhere in the book, have event a short chapter describing the expected syntax for regular expressions in string ops, otherwise have the second test return true.

### Configuration

0.68.1
linux

**Comment by dandavison** [comment]
I don't think there's a bug here, but maybe the docs could be improved. String commands such as `starts-with`, `ends-with`, and `index-of` are not searching for a regular expression match or a glob match: they are simply searching for exact substring matches. That's true of the implementation, e.g. see https://github.com/nushell/nushell/blob/main/crates/nu-command/src/strings/str_/index_of.rs#L181 and https://github.com/nushell/nushell/blob/d704b05b7a2b6c2923e68eaf8fecd6a454af1950/crates/nu-command/src/strings/str_/ends_with.rs#L104 which are using Rust standard library utilities such as https://doc.rust-lang.org/std/primitive.str.html#method.ends_with.

Of course the question is what the intention is. But I believe nushell's intention matches the implementation: that these are extract substring matching commands. In that case, the question is: are the nushell docs confusing?

```
 〉str index-of -h
Returns start index of first occurrence of pattern in string, or -1 if no match
```

I personally agree with you that the word "pattern" there sounds like it might be talking about a glob or regexp. The same word is used in the Rust docs, and I don't find it very helpful there either. So, perhaps we should change the nushell `--help` text for the `str` subcommands to use a word like "substring" rather than pattern, e.g.

```
Returns start index of first occurrence of substring in input, or -1 if no match

Usage:
  > str index-of {flags} <substring> ...(rest)

Flags:
  -h, --help - Display this help message
  -r, --range <Any> - optional start and/or end index
  -e, --end - search from the end of the string

Parameters:
  substring <String>: the substring to find index of
  ...rest <CellPath>: optionally returns index of substring in input strings at column paths

Examples:
  Returns index of substring in input string
  >  'my_library.rb' | str index-of '.rb'

  Returns index of substring in input string with start index
  >  '.rb.rb' | str index-of '.rb' -r '1,'

  Returns index of substring in input string with end index
  >  '123456' | str index-of '6' -r ',4'

  Returns index of substring in input string with start and end index
  >  '123456' | str index-of '3' -r '1,4'

  Alternatively you can use this form
  >  '123456' | str index-of '3' -r [1 4]

  Returns index of substring in input string
  >  '/this/is/some/path/file.txt' | str index-of '/' -e
```

However, we should probably get core team input before actually taking the time to prepare that change. (The word "substring" might be thought to be too technical?)

**Comment by MichelMunoz** [comment]
Ok, I see ; in that case "pattern" is not to be used, for sure. As for terminology, it varies. For inspiration...
Here's the java docs, it varies :
```
endsWith(String suffix)
Tests if this string ends with the specified suffix.
```
and C# docs
```
EndsWith(String)
Determines whether the end of this string instance matches the specified string.
```
and Javascript
```
The endsWith() method determines whether a string ends with the characters of a specified string, returning true or false as appropriate.
```

**Comment by MichelMunoz** [comment]
Updated titlte to better reflect the issue.

**Comment by sholderbach** [comment]
Some commands in the `str` family support regular expression patterns (with a switch) so we could expand that to further commands within reason.

**Comment by dandavison** [comment]
@sholderbach it sounds like you approve of @MichelMunoz's suggestion to replace the word "pattern" with a word that more obviously indicates that these are O(N) exact substring comparison operations. Can you confirm that? (And @MichelMunoz are you interested in making the change if @sholderbach confirms?)

**Comment by sholderbach** [comment]
I am open to both clarifying that a bit better and adding regex support that can be switched on/off. (Pattern itself would be vague for me even which regex flavor it is following. The term pattern would be a superset of e.g. `suffix`  and `PCRE2 compatible regex`)

**Comment by MichelMunoz** [comment]
I'm not sure adding pattern support is necessary here (none of the languages I cited does) ; just correcting the doc should do.

The non necessity is further suggested when taking into account the api/feel of the language (the commands), something along the lines of what I have done for my use would fit the existing api better, ex.
```
export def "str ends-with any" [suffixes : list] {
	let text = $in
	($suffixes | any ($text | str ends-with $it))
}

export def "str ends-with none" [suffixes : list] {
	let text = $in
	not ($text | str ends-with any $suffixes)
}
```
that produces
```
> "toto.a" | str ends-with none [.a .b .c]
false
> "toto.f" | str ends-with none [.a .b .c]
true
> "toto.a" | str ends-with any [.a .b .c]
true
> "toto.f" | str ends-with any [.a .b .c]
false
```
feels more nushell-y :)

**Comment by dandavison** [comment]
@MichelMunoz would you like to make the doc fix PR?

**Comment by MichelMunoz** [comment]
Sure, I can try this week end (time permitting). What terminology "suffix" , "suffix string", ... ?
