### ISSUE TITLE
(Seemingly) unable to bind the space key in keybindings?

### ISSUE THREAD

**Issue by fishsayhelo** [nushell/nushell#6586]
## Question

Hi, i am trying to set a bind to quick exit vi_normal mode that uses the space key as the `keycode:` option, but it never seems to work.

```
modifier: control
keycode: char_<CHAR: U+0020> 
mode: vi_normal
event: {
    # not actually the event i want to send, i was just using it to test things
    send: ClearScreen 
}
```

## Things that did not cause an error but didnt work anyway:

`keycode: char_<CHAR: U+0020>`
`keycode: CHAR: U+0020`

I'm just quite confused on how to set space as a keycode binding, especially because of the attemps that did not cause an error, but did not function

**Comment by fdncred** [comment]
I don't believe `space` is a valid keycode in crossterm 0.24. Also `char_` currently only works with a-z and not characters specified like U+0020, although, theoretically, someone may be able to add that since `KeyCode::Char` takes a rust `char`.

Crossterm 0.25 adds quite a bit to keycodes so maybe if we can land the reedline PR bumping it we can do more things, but I'm not positive at this point.

**Comment by sholderbach** [comment]
The limitation was just on our parser to translate to the proper keys. Added a `"space"`.
