### ISSUE TITLE
Inconsistent `first` vs `last` behavior 

### ISSUE THREAD

**Issue by extemporalgenome** [nushell/nushell#6611]
### Describe the bug

`first` and `last` have different behavior when given a positional argument of `1`. `first 1` behaves analogously to `first` (yields an element), whereas `last 1` always maintains a table/list. The behavior of `last 1` seems more useful (as `first` changes type/behavior based on the value of the param given).

### How to reproduce

```
/tmp〉echo [a, b] | first
a
/tmp〉echo [a, b] | last
b
/tmp〉echo [a, b] | first 1
a
/tmp〉echo [a, b] | last 1
╭───┬───╮
│ 0 │ b │
╰───┴───╯
/tmp〉echo [a, b] | first 2
╭───┬───╮
│ 0 │ a │
│ 1 │ b │
╰───┴───╯
/tmp〉echo [a, b] | last 2
╭───┬───╮
│ 0 │ a │
│ 1 │ b │
╰───┴───╯
```

### Expected behavior

All behavior is as expected except for `first 1`, for which I expect the output to be:

```
/tmp〉echo [a, b] | first 1
╭───┬───╮
│ 0 │ a │
╰───┴───╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.1                                          |
| branch             |                                                 |
| commit_hash        | e76b3d61deef832adce76b0f73f19131de8cbc9e        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)       |
| cargo_version      | cargo 1.63.0                                    |
| pkg_version        | 0.68.1                                          |
| build_time         | 2022-09-10 09:52:14 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
agreed. would like to see a PR to fix this.

**Comment by dandavison** [comment]
@extemporalgenome @merelymyself have you thought about what (if any) role `take` should play, and whether changes should be made to its behavior? It looks like its suffering from some of the same issues:

```
〉[a, b] | take # <== I don't think this should be allowed; doesn't make much 'semantic' sense
                #     certainly not as much 'semantic' sense as "first"
a
〉[a, b] | take 1
a # <== same bug as first had before #6616
〉[a, b] | take 2
╭───┬───╮
│ 0 │ a │  # <== OK
│ 1 │ b │
╰───┴───╯
〉[a, b] | take 0
〉[a, b] | take 0 | to json
[]  # <== OK
〉[a, b] | take -1
╭───┬───╮
│ 0 │ a │  # <== should be an error I guess
│ 1 │ b │
╰───┴───╯
```

Really, I think the language is going to need to decide whether it is going to have `first` or `take`. Having both doesn't seem to be an option since they seem to be basically the same modulo bugs.

**Comment by dandavison** [comment]
Here are a couple of possible resolutions:

1. Get rid of `take`: we have everything we need in `first`, `first n`, `last`, and `last n`.
2. Get rid of `first n` and `last n` and use `take n` for `first n`.

(2) is potentially attractive in that each command would then return one type only (even though the comment here is totally valid about the two calling styles being individually consistent: https://github.com/nushell/nushell/pull/6616#issuecomment-1259145238)

(2) is similar to what [Scala](https://www.scala-lang.org/api/2.13.4/scala/collection/Seq.html), Python [more-itertools](https://pypi.org/project/more-itertools/), JS [lodash](https://lodash.com/docs/#head), and [Rust](https://doc.rust-lang.org/std/iter/trait.Iterator.html#) do (although Rust refuses to offer `first`, only offering `nth 0`. So that's probably a fairly strong argument for (2). There's a question about what name to use for `last n`.

**Comment by fdncred** [comment]
Personally, I want to keep `take` because I use `skip` `take` often. If we maybe make `take` work like `last` by using negative numbers, then maybe we could get rid of `last`. `first` seems to be kind of duplicated with `take`. However, I really don't have a problem with duplicate commands that much. I think of it like Windows having 20 ways to start Windows Explorer.

**Comment by dandavison** [comment]
I think aliases are OK (e.g. lodash has `head` aliased to `first` I believe). But there should not be duplicate commands with duplicate implementations.

> Personally, I want to keep take because I use skip take often. 

Yes, we definitely want to keep the functionality: the question is just what the user-facing API is (name and flags) to access that functionality.
