### ISSUE TITLE
Output stdout and stderr to a file together

### ISSUE THREAD

**Issue by SUPERCILEX** [nushell/nushell#6658]
### Question

I know you can use `do -i {} | complete`, but that completely separates the streams. I'd like them interleaved as if they were one like in bash.

**Comment by fdncred** [comment]
This isn't supported in nushell at this time.

**Comment by WindSoilder** [comment]
In detail: 
I think it's hard to implement for now, because our external result sender always send out stderr, then stdout.  

Whatever our program generate stderr message or stdout meesage first.

One way to implement this is using two different threads, one sends out stderr, one sends out stdout, but it seems resource wasting..
