### ISSUE TITLE
`to lua` format

### ISSUE THREAD

**Issue by irishgreencitrus** [nushell/nushell#6698]
### Related problem

I want a way to convert nushell tables directly into a Lua table.

### Describe the solution you'd like

A pipe command `to lua` which outputs a Lua table.

### Additional context and details

I am willing to implement this feature if I'm given a pointer on where to implement it

**Comment by fdncred** [comment]
one way to go about this is to do `your | pipeline | to json` and then take the json output and convert it to a lua table, whatever that looks like.

**Comment by dandavison** [comment]
@irishgreencitrus Are you suggesting this should be a nushell builtin rather than a nushell utility implemented in nushell? (I don't think I see an argument for that -- there are lots of possible output formats and nushell shouldn't take on responsibility for doing any arbitrary format interconversion)

**Comment by rgwood** [comment]
@irishgreencitrus We're unlikely to build this feature into Nu itself, but I think this would make a great plugin or maybe even a custom command: https://www.nushell.sh/book/plugins.html

If you need any help building a plugin for this just let us know.
