### ISSUE TITLE
Test failures when packaging 0.72.0 for Nix

### ISSUE THREAD

**Issue by raboof** [nushell/nushell#6708]
### Describe the bug

When updating the Nix package from 0.68.1 to 0.69.1, I'm encountering a number of test failures:

```
       > failures:
       >     overlays::remove_overlay_discard_env
       >     overlays::remove_overlay_dont_keep_env
       >     overlays::remove_overlay_dont_keep_env_in_latest_overlay
```

Of course it is very possible that this is some nix-specific problem, but I'd appreciate any pointers if you have an idea in what area I should be looking ;)

### How to reproduce

1. check out https://github.com/raboof/nixpkgs/pull/new/nushell-0.68.1-to-0.69.1
2. in the `nixpkgs` directory, run `nix-build . -A nushell`

### Expected behavior

complete successfully

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.1                                          |
| branch             | nushell-0.68.1-to-0.69.1                        |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0                                    |
| cargo_version      | cargo 1.63.0                                    |
| pkg_version        | 0.68.1                                          |
| build_time         | 1980-01-01 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Logs: 
[nushell-build.log](https://github.com/nushell/nushell/files/9763851/nushell-build.log)

**Comment by rgwood** [comment]
Thanks for the report. Is this still happening?

**Comment by raboof** [comment]
Yes, I still see it with 0.72.0:

[logs.txt](https://github.com/nushell/nushell/files/10139997/logs.txt)

**Comment by rgwood** [comment]
Thanks. Looks like a Nix-specific issue (don't think we've seen this elsewhere), but I'm paging @kubouch (the resident overlay expert) just in case he has any ideas.

**Comment by kubouch** [comment]
OK, so what's happening is that the error message is different than expected on NixOS. We're checking for "cannot find column" but on NixOS, the error message says "did you mean ...?". What might be happening is that a few versions ago I remember Dan added smarter "Did you mean" errors that if no existing environment variable has a Levenshtein distance within some threshold, it won't suggest the "Did you mean" message. So, on NixOS, there apparently is an "AR" environment variable which triggers the "Did you mean" message but we can't reproduce it locally or in Nushell CI because no environment variable is close enough to the tested "BAGR".

This looks like a stupid error, we just need to make the test to look for something more robust.

**Comment by rgwood** [comment]
Good sleuthing!
