### ISSUE TITLE
String interpolation doesn't seem to work with escaped \ characters immediately before it

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6737]
### Describe the bug

When a \ appears directly before the string interpolation parentheses in a $ string, the parentheses stop working altogether, EVEN if the \ is escaped with another \\.

### How to reproduce

Get a load of this:
```
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe ($in)"
fee fie foe foo
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \($in)"
fee fie foe ($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\($in)"
fee fie foe \($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\\($in)"
fee fie foe \($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\\\($in)"
fee fie foe \\($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\\\\($in)"
fee fie foe \\($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\\\\\($in)"
fee fie foe \\\($in)
```
As you can see, there is *NO* amount of \\'s you can use to make the parentheses work again.

### Expected behavior

It should be possible in these examples to make one that outputs "fee fie foe \foo", but it currently isn't possible without writing something demented like `print $"fee fie foe("\\")($in)"`.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Maybe read this, which I just wrote yesterday https://hackmd.io/yBEUx4czTMuHcTICt-xZAA?view, to understand how it's supposed to work.

> When a \ appears directly before the string interpolation ...

It's not really a matter of string interpolation but instead I believe it's because of the double quotes which recognize and interpret `\` as escapes. Having said that, it's possible there are bugs.

**Comment by gavinfoley** [comment]
I believe the issue is here: https://github.com/nushell/nushell/blob/0.70.0/crates/nu-parser/src/parser.rs#L1611

The parser checks whether the open parenthesis `(` which could begin an expression is preceded by an escaping backslash `\`, but doesn't consider that that backslash might itself be escaped.

For example, given `\\("some expression")`, the parentheses _do_ denote an interpolated expression despite an immediately preceding backslash, because that backslash was escaped by the backslash before it (`\\`).

**Comment by fdncred** [comment]
> I believe the issue is here: ...

good insight. you might be right. now if we just had someone to submit a PR. :)
