### ISSUE TITLE
`table` has `--list`, but no way to select a mode/theme

### ISSUE THREAD

**Issue by extemporalgenome** [nushell/nushell#6820]
### Related problem

The `table` command has a `--list` option, permitting themes to be enumerated, but it does not appear to have an option to permit customization of the runtime render, such as from a non-interactive script.

### Describe the solution you'd like

A `--theme (-t)` or `--mode (-m)` option for the `table` command.

I would be happy to work on contributing code if sufficient consensus/agreement is reached on a particular flag spelling. Between the two above, I believe `--theme` has clearer intent.

### Describe alternatives you've considered

Alternatively, we could remove `--list` as a flag from the table command (since at present I can't see a way to make meaningful use of it), and instead migrate that functionality under the `config` command, if this is meant to be used primarily for interactive use.

**Comment by extemporalgenome** [comment]
@fdncred to clarify, do you mean `table --table-mode` (that might be a bit redundant)? How would you envision `table mode light` working? Would that be equivalent to your `let-env` snippet?

**Comment by fdncred** [comment]
```
let-env config = ($env.config | upsert table_mode light)
```
is the same as
```
table mode light
```
is the same as
```
table --mode light
```

**Comment by extemporalgenome** [comment]
Would you think it would also render input to that same table command using that mode, or would that be mutually exclusive with input?

Would the following (or some variation of the following) be allowed?

```
# Render just this input using mode light
ls | table --mode light

# Normally configured render
ls

# All future renders in this scope will use compact by default
table --mode compact
ls
```

**Comment by fdncred** [comment]
@extemporalgenome the one with "all future renders" would really be "all renders in this session" unless you're planning on overwriting the config.nu file.

**Comment by extemporalgenome** [comment]
Indeed, yes, that's what I meant.

I'm starting to work on this now. I tentatively like the idea of a sub-command for setting the default mode for the rest of the session. It seems a bit overly magical to have `table --mode compact` set the session default if the command has no input.

**Comment by stellarpower** [comment]
I think since most of the business logic is already in there, it'd be really useful to be able to give it a particular theme as an argument on a one-off basis.

E.g. being able to call as part of a custom hook for rendering as discussed in #10669. I could select a different table border depending on the real type of the data.

**Comment by fdncred** [comment]
I wrote [a script](https://github.com/nushell/nu_scripts/blob/main/themes/themes/preview-generate-script.nu) that automatically tries out every theme in nu_scripts/themes and takes a screenshot. So, such a thing should already be possible via writing a custom command.

**Comment by stellarpower** [comment]
Thanks, that is useful. Although I feel that setting and then clearing config variables isn't the best way to do this in general.

**Comment by fdncred** [comment]
I'm not sure it's worth another table parameter myself when you could potentially write a custom command and use it like `ls | mode rounded | table`. If something like that doesn't work, we should address it.

**Comment by fdncred** [comment]
I threw this together real quick as an example with filename mode.nu.
```nushell
# Pass in a table mode to change the table style for a single table
export def-env main [mode: string] {
  let input = $in
  let original_mode = $env.config.table.mode

  match $mode {
    "basic" => { $env.config.table.mode = "basic" }
    "compact" => { $env.config.table.mode = "compact" }
    "compact_double" => { $env.config.table.mode = "compact_double" }
    "default" => { $env.config.table.mode = "default" }
    "heavy" => { $env.config.table.mode = "heavy" }
    "light" => { $env.config.table.mode = "light" }
    "none" => { $env.config.table.mode = "none" }
    "reinforced" => { $env.config.table.mode = "reinforced" }
    "rounded" => { $env.config.table.mode = "rounded" }
    "thin" => { $env.config.table.mode = "thin" }
    "with_love" => { $env.config.table.mode = "with_love" }
    "psql" => { $env.config.table.mode = "psql" }
    "markdown" => { $env.config.table.mode = "markdown" }
    "dots" => { $env.config.table.mode = "dots" }
    "restructured" => { $env.config.table.mode = "restructured" }
    "ascii_rounded" => { $env.config.table.mode = "ascii_rounded" }
    "basic_compact" => { $env.config.table.mode = "basic_compact" }
   }

  echo ($input | first 3 | table) # remove the | first 3 to use for real
  $env.config.table.mode = $original_mode
 }
```
![image](https://github.com/nushell/nushell/assets/343840/f871fc0d-3f9f-408f-ae30-a06600ece802)

**Comment by stellarpower** [comment]
So, I can produce a visual example later - but where I'm going with this is 

1. printing different types of data (record vs table vs list vs dataframe) using different colour schemes/table styles (doable with the above, although using environment variables whilst commonplace in other languages, still feels a bit of a hacky solution to me), and then
2. printing subelements of a table/etc. using different colour schemes. I.e. a record is styled differently to a list, so a record containing a list `{someIntegers: [1 2 3]}` would be using two styles.

Having support for this in the table command (or some other mechanism) would not be sufficient for 2 above, but it starts the ball rolling.

I reckon it could be advantageous to have an API for changing various config items in general, rather than setting the config and dropping it after (the values in the config would then become like the defaults if no explicit arguments were specified, kinda like how I would have default values for an overload in a different language), but IDK enough about the design of nu to know if that leaves us in a worse situation than before. Being able to specify overrides for defaults directly feels neater to me, but, I also understand this can then balloon and have unexpected implications in unexpected other parts of the codebase if adopted across the board.

I guess to me, it feels the config should apply by default to my interactive shell session, but that's a different scenario to explicitly saying "go and render this data in this format please". Kinda like how there's a config item for having `rm` "trash" a file, but I can override this as a one-off when I want to; same for `save`. I'm assuming here that, apart from where it is called by something else, if an end-user uses `table`, it's because they explicitly want to render data and do something with it - the main usecase for this command would be showing data as the result of a pipeline, which is happening behind the scenes within the REPL and not normally requested specifically by the user or their script, right?

**Comment by stellarpower** [comment]
Also, slight tangent - is there a programmatic way to get the valid values for a config key? To avoid the repetition in the match statement above. Kinda like what `table --list` is doing, but I guess this is on the rust side.

**Comment by fdncred** [comment]
This will report a valid value, but not all the possible values.
```nushell
$env.config.table.mode
```

**Comment by stellarpower** [comment]
Yeah, I'm thinking something like this
```nushell
~> envValidValues config.completions.algorithm
[prefix, fuzzy]
```

**Comment by fdncred** [comment]
There are no completions for editing the config file...yet.

**Comment by stellarpower** [comment]
Want me to open as a separate FR?

**Comment by IanManske** [comment]
`table --theme` was added in #11058 and should be present in version 0.88 and later.
