### ISSUE TITLE
Support switching drive on Windows with `d:`, `e:`, etc.

### ISSUE THREAD

**Issue by larsch** [nushell/nushell#687]
This is a feature request to support the classic cmd.exe way of switching drives:

```
C:\> D: {ENTER}

D:\> _
```

I think Windows user will be expecting this to work. Currently it does nothing (Probably because it runs the command in a cmd.exe, which just changes drive in the subprocess).

**Comment by ubsan** [comment]
This doesn't seem like that important of a feature, and would require a lot of Windows-specific code and contexts (for remembering what directory the drive's CWD is). I feel like it would be better to use multiple shells instead which you could switch to with `n` and `p`, although I also never use this feature, since almost all of my work stuff is on the `C:` drive.

**Comment by jonathandturner** [comment]
@ubsan - this goes along with the muscle memory of a Windows user. There are techniques in Windows to be able to map drives to remove locations, working directories, etc, and being able to plug into some of those workflows could help Windows users transition to use Nu.

**Comment by ubsan** [comment]
@jonathandturner I'd rather make it a common feature across operating systems, and (perhaps) have it under a config option -- one could, for example, give different shells names, and then switch between them with `<name>:`.

```
> enter D:\ # implicitly names the shell D
> C: # go to the C drive shell
> D: # go to the D drive shell
```

**Comment by wycats** [comment]
I wouldn't mind supporting this feature if we could rationalize it as a language feature somehow. Nu has a fairly flexible syntax (initially in order to support the difference between internal and external commands, and shorthand blocks) so it seems possible that we could rationalize this feature. I would want to do that before adding support.

**Comment by wycats** [comment]
Some notes:

- In nu, `C:` is a bare word (bare words support most idiomatic paths across our supported operating systems)
- Today, when the head of a command is a bare word, and that bare word is not a registered command, we try to execute it by interpreting it as a path pointing at an external command
- But if we fail to find an executable on the path with that name, we error
- `C:` points logically at a directory, not an executable
- We could have a feature that when a command is a directory, we interpret it as `cd that-directory`, and I think this makes sense in *Nix as well

**Comment by andrasio** [comment]
#900

**Comment by jonathandturner** [comment]
This works in recent versions of Nu (0.12.0 and later)
