### ISSUE TITLE
Don't save history for commands starting with a space

### ISSUE THREAD

**Issue by Kixunil** [nushell/nushell#6886]
### Related problem

Some commands may be dangerous if accidentally repeated - typically `rm`, `mv` or even `cp` if the intention is to modified the copied file. To avoid accidental repeating I put a space before a command when using bash and it won't add the command into the history (this is configurable, on by default on distros I use). Nu doesn't seem to support it.

### Describe the solution you'd like

When a space is put in front of a command it's not saved in history. This may be configurable. I'd prefer it to be on by default but I'd rather have it off by default than not at all.

### Describe alternatives you've considered

* Just manually edit-out the history after writing the command - annoying
* Some other marker to exclude from history - space is better because it's already known by people and there doesn't seem to be any downside
* A command to remove last entry from history - e.g. `history rm-last`, this may be OK but the command itself is dangerous (risks accidental removal of interesting history line) so it'd have to somehow remove itself too but then the correct naming would be `history rm-self-and-last` which is not appealing.

**Comment by theAkito** [comment]
> Some commands may be dangerous if accidentally repeated - typically `rm`, `mv` or even `cp` if the intention is to modified the copied file. To avoid accidental repeating I put a space before a command when using bash and it won't add the command into the history (this is configurable, on by default on distros I use).

Thanks for solving the mistery of why some commands were missing in my Bash history over the years.
That was really annoying.

When you copy commands from somewhere (sometimes even right from the terminal) and paste them into the terminal, it's not unusual, that there is leading & trailing whitespace involved.



> I'd prefer it to be on by default but I'd rather have it off by default than not at all.

I'm here to give a vote for the opposite. Please, do not make this default, if the feature is based around leading whitespace. This is utteraly confusing.



> * A command to remove last entry from history - e.g. `history rm-last`, this may be OK but the command itself is dangerous (risks accidental removal of interesting history line) so it'd have to somehow remove itself too but then the correct naming would be `history rm-self-and-last` which is not appealing.

I think, it would fit the Nu style, if we had something like this.

```nu
history-ignore {
  git push -f
}
```

Since we already have `do`, `benchmark`, `collect` and other commands which naturally take a block.

**Comment by Kixunil** [comment]
> Please, do not make this default, if the feature is based around leading whitespace. This is utteraly confusing.

How about printing a warning the first time this is used? It's really useful feature once you get into the habit. Accidentally copying things doesn't happen to me.

```
history-ignore {
  git push -f
}
```

That'd be super-annoying, I use the feature very often. :( Maybe something short like `nh {}` would be acceptable though.

**Comment by theAkito** [comment]
> That'd be super-annoying, I use the feature very often. :( Maybe something short like `nh {}` would be acceptable though.

The standard one has to be a clearly understandable word combination, because it fits Nu's philosophy and I certainly don't want this Shell to go down the Bourne shell path, where everything is cryptic and nothing makes sense.



> How about printing a warning the first time this is used? It's really useful feature once you get into the habit. 

It's still a highly implicit invisible something. I think, one major reason for switching from the Bourne catastrophies is, because one is tired of all this implicit stuff, you just "have to know", because you cannot intuitively get it.
At least, that's how I completely feel about the situation. All this cryptic, symbolic & extremely implicit stuff, plus "any character might be an input stream to your CLI app" is making Bourne-like shells so atrocious.
My view is, that this space thing is just another tool in that devious toolbox of implicit tools, which are essentially useless, because you have to study those shells with their unreadable manuals and even then, there's no point, because it's hard to remember all those cryptic symbols & implications.
I'm not even talking about `eval`, people still using backticks rather than command expansion or how people expect Bash scripts to be POSIX compliant or whatever nightmare one may imagine.
It already starts with stuff like formatting via Bash's built-in `printf` command.
Have used that so many years now and I literally cannot remember the symbols off the top of my head, because it's an utterly cryptic mess.

So, the point of my explanation is to give context to why I oppose this leading whitespace feature to be enabled by default.

I'm all open to options, though. Options are most of the time nice. Make things options. People are different and have different preferences. But it's important to have sane defaults.
And I think, the defaults should be pretty intuitive & self-explaining **without** having to look up some manual.
Exhibit A: Bash usually had the leading whitespace feature enabled and I didn't even know what was going on, because I did not notice, that it was related to the leading whitespace, anyway. This is just objectively bad design, to have this enabled and expect people to just magically "know" this from thin air.

So, regarding whether it should be the default or not, I am a 100% convinced, that `history-ignore` is worth the effort, considering how intuitive it is and how it instantly should make sense most of the time.
If we start doing shit like `nh {}` we are in Bourne land again and basically can trash the entire project, if we allow for disgusting, unreadable symbols like that, which don't make any sense, from the perspective of a human being.

That said, if you want to have it `nh`, you can still do that with a custom `def` in your `config.nu` or somewhere.

```nu
def "nh" [input: block] {
  history-ignore {
    $input
  }
}
```

Or something like that. Did not test this code, but something resembling this should be certainly possible, right now.

> Accidentally copying things doesn't happen to me.

I meant, I intentionally copy code from the terminal, paste it & suddenly it's gone from the history, because the copy had a leading space in front of it.
When you do an operation like this, then the leading whitespace being the cause for the missing history entry is the opposite of obvious. It's an utterly obfuscated feature you just have to "know".

P.S.:

If you wouldn't have used other shells in your life, I bet you wouldn't even miss that feature. It's just that you got used to it, so you think you need it now.
However, I am quoting you:
> It's really useful feature once you get into the habit.

If you get into the habit of not being used to the implicit hell holes traditional shells offer, you will stop missing the leading whitespace feature at some point anyway, in case this wouldn't be implemented or something.

**Comment by Kixunil** [comment]
> because one is tired of all this implicit stuff, you just "have to know", because you cannot intuitively get it.
At least, that's how I completely feel about the situation

Interesting, for me I don't have much problem with "have to know" stuff, it's more about having less footguns. But I do see how a single space could be considered footgun and I do understand some people might find it annoying to learn.

That being said I really like Rust philosophy where commonly used things are abbreviated (`fn`, `Vec`...) I use space pretty much daily.

>  I didn't even know what was going on

I'm curious if it ever occurred to you to type "bash some commands missing from history" into Google. Fourth answer in the first SO post mentions this.

>  you can still do that with a custom `def` 

I don't think it'd work here. `history-ignore` would have to be a magic built-in command of nushell and it probably wouldn't see through def. And inspecting the inside of `def` to recognize this would be probably quite complicated.

Also I just realized the command already breaks consistency because history is per-line. Whatever `history-ignore { foo }; bar` would do would be weird in all cases. I think some per-line marker is needed. Maybe make it `- ` - won't get copied accidentally and minus sign is kinda natural. It's also easy to google "what does minus sign in front of nushell command do".

>  I bet you wouldn't even miss that feature.

Hard to say. I'd be definitely frustrated if I accidentally re-ran a data-destroying command. I'm not sure if a "this should have some way of not adding the command into history" though would've occurred to me.

> implicit hell holes traditional shells offer

You're mistaking verbosity and implicitness here. Leading whitespace is explicit, just not verbose and has bad readability. I'm OK with using some other *terse* marker. Remember that this is a safety features and safety features must not cost much energy to use otherwise people's mind will naturally not want to use them, leading to bad outcomes. This is Atomic Habits 101.

**Comment by theAkito** [comment]
> That being said I really like Rust philosophy where commonly used things are abbreviated (`fn`, `Vec`...) I use space pretty much daily.

I get that point, too, though (now I'm just purely subjectively guessing) it seems to me, like you are using this feature a lot, though I am not sure if so many users use it on average. It would be interesting to know, how popular it is.

If it is not so popular, which I would subjectively guess right now, then it probably would be best to have an option, which you can enable in your installations. I mean, you would need to modify `config.nu` or any equivalent once & that'd be it.



> I'm curious if it ever occurred to you to type "bash some commands missing from history" into Google. Fourth answer in the first SO post mentions this.

No, didn't occur to me, because it was pretty rare in relation to how much time I would use the terminal and if you can fix something rather quickly, you won't look it up & forget about it 5 minutes later, anyway; especially if you are in the middle of something. There are tons of issues nobody has ever reported, because they get fixed too quickly.
Same for my experience with the history. I'm usually in the middle of something and only look something up, when I am stuck or do not understand. Which happens with all those unintuitive design blunders that are spread all over the Bourne family.



> I don't think it'd work here. `history-ignore` would have to be a magic built-in command of nushell and it probably wouldn't see through def. And inspecting the inside of `def` to recognize this would be probably quite complicated.

That makes sense. Haven't thought about it.



> Also I just realized the command already breaks consistency because history is per-line. Whatever `history-ignore { foo }; bar` would do would be weird in all cases. I think some per-line marker is needed. Maybe make it `- ` - won't get copied accidentally and minus sign is kinda natural. It's also easy to google "what does minus sign in front of nushell command do".

Good point, too, haven't thought about it. I was focusing so much on the definition of the procedure that I forgot, we are talking about one-liners on the CLI.

A perhaps(?) cumbersome (you tell me, if it feels cumbersome) alternative would be to enable some kind of stealth mode.

```nu
stealth enable
echo "my-password"
echo "you can all log in as root now"
stealth disable
```

This would be pretty useful for extended usage of omitting history. Ideally, the colours of the prompt would change to indicate the enabled stealth mode, as well.
The obvious downside would be, that it takes lot of typing if you just want to issue a single & possibly terse command line.



> Hard to say. I'd be definitely frustrated if I accidentally re-ran a data-destroying command. I'm not sure if a "this should have some way of not adding the command into history" though would've occurred to me.

Since I didn't know about that whitespace feature, I usually just typed a benign command afterward, to avoid accidental re-running the last destructive one.
Though, I have though about finding a solution regarding the avoidance of repeating the last destructive commands.
In my mind, I was thinking of a command specific confirmation prompt, though this wouldn't be generic, at all.

Since you were mentioning the `magic built-in command`, that would be needed to be implemented, perhaps this syntax should be worth thinking about.

```nu
echo "my-password" | history-ignore
```

If it's a magic built-in anyway, it might as well work like this, I suppose.



> You're mistaking verbosity and implicitness here. Leading whitespace is explicit, just not verbose and has bad readability. I'm OK with using some other _terse_ marker.

I think, it's not "verbose", if something is clear & intuitive. For example, when I started using Nu, of course I had to get the point of it somehow by looking at the "book" (documentation).
But, once I got the point, I could make out like at least 80% of commands, just by guessing their names. This is, in my view, **HUGE** for user experience. This is how it always should be.
Now try that in some Bourne shell. You will be lucky to even unmount a volume because apparently writing `unmount` is too much work, but `umount` is perfectly fine. 💩

The less one has to look up the manual, the better the program.

Now with shells, obviously there is a point to using frequent commands & their name length. I wouldn't change `cd`, because it is used millions of times in a short time span, so that wouldn't be an issue. However, when something is used less frequently than `cd`, then it already does not belong to the category of "I'm using it so often, there is no way I would forget that command's name". In my setup for example, I would use that command maybe once a week, I guess. Although, I am using the CLI every single day for a relatively long period of time.
That said, `alias` definitions are usually used to shorten something you do often, but most don't. Like e.g. I have an `h` alias for `cd /home/$USER` and `s` for `cd /home/$USER/src`, which would be pointless for other users, perhaps.
If we had something like `history-ignore` which accepts an input stream & would be able to alias it, that would maybe be the solution to this issue.

> Remember that this is a safety features and safety features must not cost much energy to use otherwise people's mind will naturally not want to use them, leading to bad outcomes. This is Atomic Habits 101.

I expected that you use the space out of your own volition and not because someone is forcing you to. If you want to do it, because you actually want to, you would even use some complicated `history-ignore {} $in` structure, or whatever.
If people do not understand and/or are not willing to follow the security principles for whatever reason, then yes, your example applies.

That said, realistically and pragmatically speaking, it is safer to not hide some command from the history.
On average, the chance of some intruder looking up your shell history and exploiting a command from there is far less probable than you entering some complicated command without saving it first and then it's not in the history anymore, which forces you to research it again. Especially annoying, when you try to make a complicated command work on the fly, without wasting time & effort of making a proper script or something.

Actually, funny story, just yesterday I updated my Nu configuration on a machine and lost my history there. I literally had to restore the previous `sqlite3` database, to get the command back I hacked together on the fly, on the Nu CLI. I really would've been annoyed to research that one-liner, an additional time.

As another example, look at cryptocurrency wallets. People cannot stress enough, that it must have a secure password, this & that.
The truth is, for the average normal user, it is most important, that you can still access the wallet anytime you need to, rather than making it "too secure" and losing it altogether.
The chance of someone breaking into your home and stealing your wallet or something is _extremely_ low compared to how too damn easy it is to forget/lose/mistype the password.

Therefore, I think it is actually a safety feature to put everything into the database and make it not too easy to bypass it.
Once it's in the database (or plaintext file) you can still delete it after the fact. Which you can do for example, with tons of workarounds, right at this moment.
But, if the history file/database has been omitted in the first place, there is no way to rewind time and save the previous command from dropping into the abyss...

**Comment by theAkito** [comment]
Thinking about this issue again, taking all things said into account, I think it makes sense to have a marker, which forces a database bypass on the CLI.

However, in my opinion, it should not be a leading space. It should be something clear & intuitive.

P.S.:

I have _never_ in my life used `.`. I always used the word `source`, because it is absolutely atrocious how Bournies think, that a command like that should be reduced to a single dot.
There is a reason, why there are beginners spread all over the internet, being stuck at sourcing a script, because this dot is too easy to miss and unintuitive.

**Comment by Kixunil** [comment]
Hmm, your response made me realize that maybe we should have two features: one hides the command from history and the other stores deactivated version of it. First is for avoiding storing secrets, the second is just to not accidentally re-run the command.

However putting secrets on command line is already bad - other programs can read them, so I'm not sure if a feature to not store them is that useful. But I wouldn't mind having it.

The dangerous command case is pretty common, so I'd definitely want it as short as possible. I agree that not typing it by accident is useful. I'd suggest `!` but it already does something (non-intuitive, BTW :)). `!!` also does something (also non-intuitive). Maybe `!:` would work.

So if you type `!: command` the command would be stored  as `# command`. If you really want to run it again you have to remove the leading `#` (or replace it with `!:`). For hiding things `history off` and `history on` would be fine. Or `no-history: ` prefix.

> you tell me, if it feels cumbersome

Definitely yes. I use potentially-destructive commands quite often. I did use the equivalent of "stealth" a few times - setting `HISTFILE=/dev/null` so it'd still be useful (but `history off` sounds more intuitive to me)

> If you want to do it, because you actually want to, you would even use some complicated `history-ignore {} $in` structure

Unfortunately, that's [not how human brain works](https://www.youtube.com/watch?v=vGQficynmIY). This is a well-researched topic and something safety-focused systems deal with all the time. "Right things should be easy to do, bad things should be hard to do."

> But, once I got the point, I could make out like at least 80% of commands, just by guessing their names. This is, in my view, **HUGE** for user experience. This is how it always should be.
> Now try that in some Bourne shell. You will be lucky to even unmount a volume because apparently writing unmount is too much work, but umount is perfectly fine.

100% this! I want most commands to be obvious and easy to guess. I just believe that anything safety or security related should not require too much energy to use. There won't be many such things anyway so a single page in the doc should be able to cover them.

> The truth is, for the average normal user, it is most important, that you can still access the wallet anytime you need to, rather than making it "too secure" and losing it altogether.

I'm in Bitcoin security space for quite a few years and I know this very well. :) That's why good wallets make correct things easy and incorrect things hard. Actually, moving coins from an exchange is considered annoying for many users so they don't do it and lose the money in MtGox/FTX/whatever events.

**Comment by theAkito** [comment]
> Hmm, your response made me realize that maybe we should have two features: one hides the command from history and the other stores deactivated version of it. First is for avoiding storing secrets, the second is just to not accidentally re-run the command.

Sounds not too bad in theory, but it's important to not forget practicability. No idea, how a practical solution might look like. It's probably a subjective thing, again. Two commands are sometimes nothing, other times it's already 1.5 too much... Not sure about that.



> However putting secrets on command line is already bad - other programs can read them, so I'm not sure if a feature to not store them is that useful. But I wouldn't mind having it.

Actually, I went on with that, because I got carried away with what I remembered people complain about on the internet. I have seen tons of people talk about credentials on the CLI, which is why I had that in mind. Therefore, it does not seem an uncommon to me. Otherwise, it's not recommended in general & perhaps people should start doing this correctly, however it's hard not do it, when it's so convenient. Especially, when the credentials are not too important.



> The dangerous command case is pretty common, so I'd definitely want it as short as possible. I agree that not typing it by accident is useful. I'd suggest `!` but it already does something (non-intuitive, BTW :)). `!!` also does something (also non-intuitive). Maybe `!:` would work.

`!:` sounds a bit lik `!:1`, which would be something, that is considered to be implemented, as far as I have read. (I cannot seem to find an issue anymore, but there was one about implementing some old school styled functionalities like `!:1`.)



> So if you type `!: command` the command would be stored as `# command`. If you really want to run it again you have to remove the leading `#` (or replace it with `!:`). For hiding things `history off` and `history on` would be fine. Or `no-history: ` prefix.

I like the idea of auto-defusing the bomb. Though, I'm torn apart between having something readable & intuitive, as opposed to have something short, that can be used frequently.

I think, an important point is also that many shortcuts & certain commands are very `en_US` centric. Anyone who made up using `^`, `/` (Windows) & and `-` (Linux luckily is more acceptable than Windows in this regard) for the most common operations, like giving options to a CLI command, forgets that different popular keyboard layouts around the world are really hiding that stuff.

To me, typing `!:` is already a bit of work on the US layout, because it involves holding the SHIFT key the entire time. Not sure about these two symbols on other layouts, but I imagine they would be just as tough or even more difficult to press. Not sure.
So, I am in the following way wondering, whether the time we make up by using two symbols only gets partially eaten up by the complexity of the symbols. To be honest, I think it's usually quicker to type `cat` or `cate` on a keyboard, rather than that combination.

Though, again, this is half subjective.

Maybe `nohist` would be in-between? Pretty terse, but it resembles its purpose a bit. `nohist` is still a hundred times more intuitive than an exclamation mark followed by a colon. 😄



> Unfortunately, that's [not how human brain works](https://www.youtube.com/watch?v=vGQficynmIY). This is a well-researched topic and something safety-focused systems deal with all the time. "Right things should be easy to do, bad things should be hard to do."

I knew all that & am very well aware of that, however, when someone truly *wants* to keep something safe & *truly understands* the point, then this urge will be louder, than the other one.
The reason people don't do it for passwords & PINs & whatever is because this is extremely abstract.
If you tell a human some number, it is utterly meaningless. A number by itself has literally no meaning, at all. Nothing. It might be a weird artpiece like *Monochrome Bleu*, which is essentially just a canvas, painted blue.

Opposed to that, when you tell someone "if you won't do this, we are going to burn down your home & erase your entire family" then I bet you a million bucks, this person would rather rip his own eyes out than being too lazy to do it.

The reason for that is, that everything is relative.

If people are "lazy" or do not do something, it's not because they don't want to. That's incorrect.
It's because, they want to do something else. When several desires fight in the brain, the most desired ones win.

So, if someone uses a password on a CLI, it's not a big deal, the brain thinks, because first of all, it's abstract, second of all it thinks, that an abused password is not something, that can happen.
When people always ask "why me" when they get hit with reality, they are asking the wrong question.
The correct question would be asked by the ones, whose situations went fine: "Why did it not happen to me?"

To sum it up, if people would *truly* understand & *truly* want to prevent ordering a painful mistake, they would be able to always follow the rules, because the desire to not be in that misery is higher than the desire to skip a second of doing the right thing.

From my personal experience, exactly that is the case, as well.
I'm pretty lazy with passwords and I honestly don't care whether they are in my history, because of other permanent security measures (and I very rarely do that stuff, anyway), however whenever I do that `git push -f` my senses are basically heightened and I really look out for that one, because my desire to not break my Git setup is way higher than my desire to skip doing the right thing.



> 100% this! I want most commands to be obvious and easy to guess. I just believe that anything safety or security related should not require too much energy to use. There won't be many such things anyway so a single page in the doc should be able to cover them.

In general, I agree. It should not require too much energy, especially when protecting something abstract.
Though, as already mentioned, it's always a fight between security & usability.
If you start using symbols as commands, you are basically automatically making the system less secure for every clean casual, who uses the CLI maybe once a week. Or, maybe someone wants to get into Nu and it simply does not work out, because it's too damn easy to forget weird symbols, that don't make out words.

Think this example through.
A clean casual is using Nu once a week. He wants to protect his stuff with the history ignore like command.
Since, security measures shouldn't take up too much energy, then `history ignore` or whatever would be much less energy, than looking up the Nushell manual every single week, because the command is forgotten or having it to write down once & not lose the piece of paper the advice was written on.
This would immediately kick the symbols out of being the lowest energy alternative for certain types of users.



> I'm in Bitcoin security space for quite a few years and I know this very well. :) That's why good wallets make correct things easy and incorrect things hard. Actually, moving coins from an exchange is considered annoying for many users so they don't do it and lose the money in MtGox/FTX/whatever events.

I fully concur.

**Comment by Kixunil** [comment]
Good point about shift. I think the layout problem can't be avoided if we want a unique character. Semicolon would be at least usable without shift on all layouts I use (`en_US`, `sk_SK`) and feels reasonable but maybe there's a bunch of bad layouts for it.

> Maybe `nohist` would be in-between? 

I tried to type `nohist` twice to get a sense of it and I made a typo both times. :) But your point about casual users is also interesting. Maybe it should be `defuse` with some well-documented abbreviation for frequent users. Could be configurable too but there are weird edge cases that cause problems - e.g. helping someone else on his differently-configured computer and type a wrong command out of habit.

> "if you won't do this, we are going to burn down your home & erase your entire family" then I bet you a million bucks, this person would rather rip his own eyes out than being too lazy to do it.

I wouldn't be so sure. An infamous story of a rich guy storing seed in Evernote (IIUC, it was some kind of cloud) losing all his coins to some attacker comes to mind. I also have a quite strong mind when it comes to this but can be in a bad state sometimes.

**Comment by theAkito** [comment]
> Good point about shift. I think the layout problem can't be avoided if we want a unique character. Semicolon would be at least usable without shift on all layouts I use (`en_US`, `sk_SK`) and feels reasonable but maybe there's a bunch of bad layouts for it.

Simple semi-colon in front of the command. Feels like an old school scripting comment, but maybe that's one option. It would counter the intuitiveness argument, because you would just need to remember "it was a single symbol on the keyboard, that you can type just like that, without using a key combination", which would make accidentally finding it fairly easy.



> I tried to type `nohist` twice to get a sense of it and I made a typo both times. :) But your point about casual users is also interesting. Maybe it should be `defuse` with some well-documented abbreviation for frequent users. Could be configurable too but there are weird edge cases that cause problems - e.g. helping someone else on his differently-configured computer and type a wrong command out of habit.

If you type in `nohup` & TAB, then `nohup` immediately comes up. However, even with such hack, it would be only a matter of time, until another command makes the TAB less quick by presenting different options.

Well, not sure. I guess it's all about taste. I could certainly live with `history-ignore` or something. No problem for me. I do not use dangerous commands all the time & when I do use one, I run it in a safe environment or try to make it safer some other way, if possible.

I think, we could have a quick workaround for an issue, before implementing a good fix.

There are some commands, which are clearly always destructive and these are common among CLI users. For example, `git push -f` is, as far as I know, pretty common & could just be hard-coded for now.
Same for other similar commands.

When we develop a real solution by trying out custom defs or whatever, then we can get rid of or complement the hard-coded workaround by a better fix.



> I wouldn't be so sure. An infamous story of a rich guy storing seed in Evernote (IIUC, it was some kind of cloud) losing all his coins to some attacker comes to mind. I also have a quite strong mind when it comes to this but can be in a bad state sometimes.

While typing that example, extreme examples came to my mind. People going on top of towers, without having any ropes attached & other mad people.
Although, these people seem like an absolute exception to me.
I am convinced, that the big majority of people would behave in the way I described.
There are always exceptions to the rule.

Especially, if you apply the extremes to your "less energy" goal.

Do you think, the Evernote guy would've used `!:` or whatever, if he could've (if the story would be applicable to our CLI scenario, that is....)?
I think, even if you offered this guy to save it properly for free, all the time 24/7, he still probably wouldn't have agreed, because he extremely did not care about it or maybe he was too damn stupid, I don't know.

Either way, I think you cannot catch those extreme hardcore people with making it take up less energy. These people simply don't want to do it. They simply don't care, at all.

**Comment by Kixunil** [comment]
> `git push -f` is, as far as I know, pretty common & could just be hard-coded for now.

I happen to keep that one in history because I always work with branches for non-trivial things. :laughing: 
I also keep `rm -rf some/specific/path` because that path is trivially restorable and some software refuses to update the directory in-place (for a good reason I think).

However, ironically `cp` is often destructive for me because it's often `cp something_similar_to_what_i_need something_i_will_edit`.

So I really don't want hard-coded things like that. If it was a configuration option with regex support it could be interesting though.

> maybe he was too damn stupid

TBH there's a good chance the guy didn't understand why there's a separate device for holding private keys. So yeah, the example may be invalid.

But yes, I do think there's a limit to how many people can we save.

**Comment by theAkito** [comment]
> I happen to keep that one in history because I always work with branches for non-trivial things. 😆

Even more reason to not accidentally overwrite your correct changes. 😄



> I also keep `rm -rf some/specific/path` because that path is trivially restorable and some software refuses to update the directory in-place (for a good reason I think).

Just recently I had read about someone executing `rm -rf / some/specific/path`, rather than `rm -rf /some/specific/path` on a production system... Didn't go well.



> But yes, I do think there's a limit to how many people can we save.

Yes, I think it's important to stay pragmatic with such things. We don't want to C++ our way into having a million methods for doing one thing.

**Comment by rgwood** [comment]
I have not read the full conversation but this has been asked for a few times.

I started implementing this in reedline last week but got bogged down in some design+implementation problems: https://github.com/nushell/reedline/issues/516

If someone wants to take over the PR feel free, otherwise I will come back to it next time I have the energy to work on it.

**Comment by samlich** [comment]
https://github.com/nushell/reedline/pull/566

>When you copy commands from somewhere (sometimes even right from the terminal) and paste them into the terminal, it's not unusual, that there is leading & trailing whitespace involved.

Fish solves this by trimming pasted commands. This requires bracketed paste support; depends on https://github.com/nushell/reedline/pull/560 or https://github.com/nushell/reedline/pull/464 being merged.

See also https://github.com/nushell/reedline/pull/567 for deleting existing items.
