### ISSUE TITLE
Consider deprecating `update <name> { block }` and `upsert <name> { block }`

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6936]
### Describe the solution you'd like

Break-off from https://github.com/nushell/nushell/issues/6926#issuecomment-1294983349. 

The `update <name> { block }` form is kind of confusing: it only properly iterates with tables (because it requires a column name) and moreover doesn't seem to have much advantage over `each` combined with the single-value form of `update` (which can also iterate over tables):

```
〉ls *.md | update name { $in.name + '!!' }
╭───┬──────────────────────┬──────┬─────────┬────────────╮
│ # │         name         │ type │  size   │  modified  │
├───┼──────────────────────┼──────┼─────────┼────────────┤
│ 0 │ CODE_OF_CONDUCT.md!! │ file │  3.4 KB │ a week ago │
│ 1 │ CONTRIBUTING.md!!    │ file │  1.8 KB │ a week ago │
│ 2 │ README.md!!          │ file │ 13.1 KB │ a week ago │
╰───┴──────────────────────┴──────┴─────────┴────────────╯
〉ls *.md | each { update name ( $in.name + '!!' ) }
╭───┬──────────────────────┬──────┬─────────┬────────────╮
│ # │         name         │ type │  size   │  modified  │
├───┼──────────────────────┼──────┼─────────┼────────────┤
│ 0 │ CODE_OF_CONDUCT.md!! │ file │  3.4 KB │ a week ago │
│ 1 │ CONTRIBUTING.md!!    │ file │  1.8 KB │ a week ago │
│ 2 │ README.md!!          │ file │ 13.1 KB │ a week ago │
╰───┴──────────────────────┴──────┴─────────┴────────────╯
```
I greatly prefer the `each` form, above due to making it very explicit how the iteration happens (what $in's value is during each iteration).

For plain records, `update { block }` does no iteration, instead passing the entire record into the block - and thus the block can seemingly be replaced with `( $in | expression )` (or, if you have a block stored in a variable, `($in | each $block)`.)

In closing, I think `update { block }` is syntactically unnecessary (compared to the `each { update name }` form), makes iteration unhelpfully implicit (which the `each` form makes implicit) and complicates the signature of this command. I think the only things that really need, and should explicitly take, blocks as arguments are commands that explicitly iterate (and `do`, of course).

### Additional context and details

Deprecation simply means marking this form as deprecated in documentation and help, for now.

**Comment by fdncred** [comment]
I found this again after looking at #7266 and I'm still not a fan. 

As a user, I don't want to have to type 50% more characters (or more) just to update/upsert something.  In @WindSoilder's PR we change `upsert c {|it| $it.a + 4}` to `each {|it| $it | upsert c ($it.a + 4)}`, 25 chars to 38 chars.

It also reminds me of @rgwood's change to `seq` where we take this command `seq -s ' | ' -w 1 2 10` and make it `seq 1 10 | into string | str lpad -c 0 -l 2 | str join ' | '`, 22 chars to 62 chars.

Maybe I'm just missing it. Why is double or triple the amount of characters better and why can't we just have some sugar on some commands to make thing easier? Don't get me wrong, I'm not up for posix's 100 parameters on every command but I'm not sure all these changes are changes for the better. I'm sincerely interested in your input, not wanting just to go on a rant.

**Comment by rgwood** [comment]
@fdncred I agree that the change to `seq` made the ergonomics of that specific use case ("I want a sequence of numbers in a string, all padded to the exact same length, separated by pipes") worse.

But that feels like a fairly uncommon use case, and removing it from `seq` meant we could make `seq` consistently return a `list<number>`. I think we should generally avoid changing return types based on command flags without a very good reason.

I haven't given enough thought to the `update` and `upsert` issue, and don't have an opinion on it right now.

**Comment by WindSoilder** [comment]
I just think that's because the closure input powerful, but hard to understand at first, so maybe less command accept closure input is better, and it inspires user use more powerful `each` command

**Comment by WindSoilder** [comment]
I just think that's because the closure input powerful, but hard to understand at first, so maybe less command accept closure input is better, and it inspires user use more powerful `each` command

**Comment by webbedspace** [comment]
>`upsert c {|it| $it.a + 4}` to `each {|it| $it | upsert c ($it.a + 4)}`

OK, all I have to say is, why aren't you using `$in` if character count is such an issue? Both of these turn into these:
`upsert c {$it.a + 4}`
`each {upsert c ($in.a + 4)}`

**Comment by kubouch** [comment]
I think the main point here is to standardize in all our commands when we do auto-iterate and when we don't. IMO, we should support auto-iteration because it saves a lot of boilerplate but there should be some logic behind which command do that and which don't.

**Comment by WindSoilder** [comment]
>  why aren't you using $in if character count is such an issue? Both of these turn into these:
upsert c {$in.a + 4}
each {upsert c {$in.a + 4}}

Oh sorry, it's my fault that I'm failed to get the value of `$in`, for the following example:
```
[{'a': 1, 'b': 2}, {'a': 3, 'b': 4}] | each {upsert c {$in.a + 4}}
```

I thought `$in` is the whole input table rather than a single record...

**Comment by sholderbach** [comment]
As @kubouch says we should make sure our broadcasting behavior over tables/lists is documented well and behaves consistent. 
But I agree that the auto iteration is one of the core powerful features of nushell.

Also the closure/block/row-condition rules should be consistent and thus feel intuitive after a bit of exposure (I remember struggling with the update command when first using nushelll due to that). 

I don't think this change fits with the move towards more explicit and consistent type information as part of the `0.80` push. 
As `table | upsert => table`, `record | upsert => record` remains unchanged.

Apart from extra characters needed to type I see that making this change would harm readability, composability, and performance.

### Readability

**Disclaimer:** My preferred language background is dominated by scientific python, tidyverse-style R, and Rust with a heavy leaning in the iterator/functional direction.

Apart from the amount of typing, I think the readability suffers from changing from `upsert a {do-stuff}` to `each {|i| upsert a ($i | do-stuff)}`. Not only do you have to mentally ignore a bunch of extra symbols. That operations have to deal with multiple entries is basically implied at every step anyways in the pipeline style. 

Furthermore when you want to debug a pipeline I would follow from the back and read each pipeline step from left to right to see if it affects what I care about. Making `upsert`/`update`/`insert` the first command followed by the name of the affected column makes that more obvious to me.

### Composability

One benefit of the current construction is that it *doesn't* matter if you are handed a table or a record.
`each` on the other hand is well defined for lists or tables but it is not obvious how a record should be treated.

With `upsert name {...}` you can easily write a readable custom command that is generic over records, tables or other objects that would support cell path indexing.

### Performance

Apart from obviously requiring the execution of two instead of one rust-implemented core commands, this change require double the evaluation contexts `each {|i| $i | update a ($i | do stuff)}` for the subexpression.

Furthermore on a more theoretical note: 
Optimizing a pure function closure for `update`/`upsert`/`insert` is much more straighforward than doing the transformation based on a loop body in an explicit nushell iteration.
You could trivially prove that a closure only reads the outside environment or the fields of the passed in object. For the each expression proving that the inner update is only modifying the input.
With the information that there is a pure function you can either parallelize the operation on the nushell level or make use of vectorized operations like the dataframe engine could.

## Personal conclusion

Overall I think this change would not be helpful for idiomatic nushell.
Nothing is stopping users from preferring a more procedural style in their code but it makes it harder for other styles of code.

**Comment by webbedspace** [comment]
Hmm… I'll accept those considerations, in particular about performance.

**Comment by fdncred** [comment]
Thanks for your insight and feedback.
