### ISSUE TITLE
Git-tag publish didn't work

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#701]
Judging from https://github.com/nushell/nushell/commit/3f8448da0daeea30452e63080812caa2ce4a0e27/checks it looks like git-tag publishing isn't quite working yet.

cc @DrSensor

**Comment by DrSensor** [comment]
- I think the `DOCKER_REGISTRY` token is not set :thinking:

> **For example** :point_down: 
![Screenshot_20190925_165422](https://user-images.githubusercontent.com/4953069/65590428-fdff8700-dfb4-11e9-95e2-dcf54a430855.png)

---
- the `secrets.DOCKER_REGISTRY` should be set in order to publish it to github package registry.
> ref: https://github.com/nushell/nushell/pull/625#issuecomment-532629823
![comment](https://user-images.githubusercontent.com/4953069/65590931-cf35e080-dfb5-11e9-9de3-88df1b58f780.png)

---
- guide to generate token for publishing into github package registry :point_down: 
<blockquote>

ref: [Authenticating to GitHub Package Registry](https://help.github.com/en/articles/configuring-docker-for-use-with-github-package-registry#authenticating-to-github-package-registry)
1. visit <https://github.com/settings/tokens/new>
2. check **write:packages**
![demo](https://user-images.githubusercontent.com/4953069/65592154-3eaccf80-dfb8-11e9-9b07-13009436a122.gif)
3. click
![Generate token button](https://user-images.githubusercontent.com/4953069/65592444-c1358f00-dfb8-11e9-9735-fd0762d604d1.png)
</blockquote>

**Comment by jonathandturner** [comment]
@DrSensor with those steps it got closer. I'm not sure if you can see the results

**Comment by jonathandturner** [comment]
![Screenshot from 2019-09-27 01-25-17](https://user-images.githubusercontent.com/547158/65691882-bcaacc80-e0c5-11e9-8a16-9db511c311aa.png)

Seems like something isn't finishing. I tried to cancel it, but I got this error:

![Screenshot from 2019-09-27 01-26-24](https://user-images.githubusercontent.com/547158/65691954-de0bb880-e0c5-11e9-8530-c501f55cb599.png)

**Comment by DrSensor** [comment]
Seems github action for organization has more bugs :thinking: 
Try to force push the tag or create a new dummy tag. For example:
```
git tag -a 0.0.7-jamesbond && git push --tags
```
> Although I don't have permission, I can click the cancel run. Luckily it's 404 :joy: 
![Peek 2019-09-27 01-04](https://user-images.githubusercontent.com/4953069/65713344-31c8d280-e0c3-11e9-8898-2d5234632354.gif)

**Comment by andrasio** [comment]
How are we doing on this end? @DrSensor @jonathandturner

**Comment by DrSensor** [comment]
Waiting for the next releases to see if the latest merged PR works 😊

**Comment by jonathandturner** [comment]
I think I still need to figure out how to get access to the quay.io account. Should we just create a new one?

**Comment by DrSensor** [comment]
What about using hub.docker.com?
(seems the username already [reserved](https://hub.docker.com/u/nushell) 😣)
