### ISSUE TITLE
Support ignoring program errors when working with `;`

### ISSUE THREAD

**Issue by SUPERCILEX** [nushell/nushell#7076]
### Describe the solution you'd like

Bash has:
- `&&` which means "continue only if everything before me succeeded"
- `||` which means "run the stuff to the right only if stuff to the left failed"
- `;` which means "run the stuff to the right no matter what"

Nu has:
- `;` which means "continue only if everything before me succeeded"
- `do -i { ... };` which means "run the stuff to the right only if no **shell** errors occurred"

Proposal: add `do -p { ... };` which means "run the stuff to the right only if no **program** errors occurred". Combined with `-i`, you get "run the stuff to the right no matter what."

**Comment by WindSoilder** [comment]
I think it's a regression, and `do -i` should works as expected on 0.69.

https://discord.com/channels/601130461678272522/614593951969574961/1040168737816453120

**Comment by fdncred** [comment]
I'm still not a fan of other `-i` type parameters. I'd vote for landing https://github.com/nushell/nushell/pull/7084 until we can get the normal bashisms the OP talks about in place. They are planned but I'm not sure how long until we get to them.

**Comment by WindSoilder** [comment]
Sorry I don't really get the idea.  Refer to your comment: https://github.com/nushell/nushell/pull/6958#issuecomment-1303840054

> That's exactly what this PR is addressing. && is already handled by ; and || would now be handled by ignoring program errors.

But I don't think `||` is same as `ignoring programming errors`, you mentioned that in bash, `||` is "run the stuff to the right only if stuff to the left failed".  I've played a bit about your pr
```
❯ do -p {echo i}; echo post
i
post
```
If `-p` is doing something like `||`, I don't think `post` should be echoed, because the previous `do` is executed successfully.

**Comment by SUPERCILEX** [comment]
@WindSoilder yeah, I think my comment is just straight up wrong. The behavior my PR was trying to emulate is bash's `;`, but since Nu now has `;` that means something completely different I guess I got confused. Anyway, my PR did the same thing as https://github.com/nushell/nushell/pull/7084 but with a sperate flag.

@fdncred I do think a separate flag is an improvement over bash. If there's a shell error like the program not existing, I want to know. With bash you can't do that. With a separate flag, you have to pick the errors you want to ignore which will eliminate bugs when something totally unexpected happens.

**Comment by WindSoilder** [comment]
> I do think a separate flag is an improvement over bash. If there's a shell error like the program not existing, I want to know.

I'm still not convinced that separate these with different flag is helpful(in addition, it's more confused to me why we have thses separate flag, why separate shellerror and program error matters in `do -i`?).  
Do you have a usage scenario for this?  How will you use it in nushell ?

**Comment by SUPERCILEX** [comment]
Let's say I want to write `ls -a`, but I made a typo and wrote `ls-a`. With a single flag, I would not be able to tell the difference between `ls -a` returning a non-zero exit code and `ls-a` never executing at all. So then you have to waste time trying to figure out why stuff isn't working. With two flags, you can say "continue to tell me about shell errors" so now when you make the `ls-a` typo it fail and you can immediately fix it.

For the other direction (you want shell errors and not program errors), maybe you actually want to optionally run a binary (so it's fine if it doesn't exist), but if the binary does run then you want to know whether or not it failed.

These are separate errors—they should not be conflated.

**Comment by dandavison** [comment]
Hi @SUPERCILEX @WindSoilder  I'm also someone contributing to nushell. I'm happy to see several of us are working on improvements.

I haven't followed all the discussion so sorry for drive-by commenting but I think my personal opinion is that something like handling errors arising when evaluating a block is very fundamental and should be done by "dedicated language features" rather than flags on commands (e.g. `||` and `&&`, or `try...catch`, or something like Rust's `?` operator, etc)

So obviously if these PRs are doing implementation work can later be exposed by nice language features then that's great. But my instinct is that neither `do -i` nor `do -c` are interfaces that should survive in the final version of nushell (and so I think any addition of `-p` would similarly only be temporary).

I just wanted to say that but my comment doesn't really clarify anything: as I said it could be the right thing to do to expose useful functionality via flags first pending new language features.

**Comment by dandavison** [comment]
OK so what's the situation with the current `do -i`. (@SUPERCILEX could you update the intro to this Issue if it's no longer accurate?) It seems like it

- Respects the exit code of an executable (e.g. compare `do -i { ^false }; echo hello` does not print)

- Ignores `nu::shell::external_command executable was not found` errors (`do -i { doesnotexist }; echo hello` prints)

- Is powerless in the face of certain parser errors. E.g. `do -i {into doesnotexist}` 

- But swallows some `nu::parser::not_found` errors E.g. `do -i {g doesnotexist}; echo hello` prints, despite `g doesnotexist` throwing `nu::parser::not_found`

This is just a thought and might be wrong, but the nature of Nushell is that certain parser errors will always throw inside a `do` block, because the whole thing is parsed before doing anything `do`-specific, right? Given that fact, is it actually helpful to have something that "ignores shell errors"? Since a fraction of "shell errors" will never be ignored. Maybe we should just focus on providing ergonomic ways of handling external executable errors?

Finally, I guess we should try to open design discussions before opening PRs in many cases. But, I know that I personally like writing code as well as design docs, and I think that's true of others. So maybe what we should do in these areas is open a design discussion in an issue, and then open a PR where the PR basically says "Ignore this for now and let's resolve the design discussion in #XXXX. This is just some prototyping I did that may or may not turn out to be mergeable."

**Comment by WindSoilder** [comment]
> but I think my personal opinion is that something like handling errors arising when evaluating a block is very fundamental and should be done by "dedicated language features" rather than flags on commands (e.g. || and &&, or try...catch, or something like Rust's ? operator, etc

Yeah, I think that should be in nushell 0.80 according to the doc. 

The current situation is simple, `do -i` is only ignore shell error, but if the program itself exit's with `non-zero` exit code, it will respect it.  You can try `do -c { ^false }; echo hello`, nushell will propogate error says that external command runs to failed.

I don't think the current behavior of `do -i` is expected, it's a regression introduced by https://github.com/nushell/nushell/pull/6643, previously(version 0.69), when we run do -i, nushell will ignore all errors.   And @SUPERCILEX thinks the current behavior of `do -i` is fine.

**Comment by fdncred** [comment]
> I don't think the current behavior of do -i is expected,

I agree, which is why I approved @WindSoilder's PR, to get us back to our old behavior. I'm still fine with landing it and continue to work on the proper fix.

**Comment by SUPERCILEX** [comment]
If we only want to have one flag, then can we make `-i` only ignore program errors? While I came up with a potential use case for ignoring not-found errors, it's pretty weak and I don't personally care about it. I only see value in ignoring program errors, but was trying to keep existing behavior.

**Comment by WindSoilder** [comment]
Not sure if it's ok for script usage, sometimes I just want to `fire and forget` something, if `-i` only ignore program errors, we would make restrict requirement for that binary.

But I think we can have a try and see hows going on.  Would you mind me to continue work on #7084?

**Comment by SUPERCILEX** [comment]
> if -i only ignore program errors, we would make restrict requirement for that binary.

Hence having two flags.

> continue to work on the proper fix

My beef is that if by proper you mean bashisms, then it won't be possible to ignore just program errors since the interface will be kept as simple as possible. Hence `do` should be seen a primitive from which the bashisms could be built, i.e. by having the bashism take in a lambda run within `do` with the two flags enabled. Of course that's not how it'll be implemented, but it's a good sign when things are easily composable.

Would someone mind concretely explaining why the idea of having two flags is so hideous? I don't get it.

> Would you mind me to continue work on https://github.com/nushell/nushell/pull/7084?

I can't stop you, but I'm planning on reopening my PR once we reach consensus so that'd be a little rude.

**Comment by fdncred** [comment]
I hoping we have "normal" `||` and `&&` soon. I think if we have those bashisms, we'll be ok. Do you agree @SUPERCILEX, or do you think a solution like yours will still be needed.

**Comment by SUPERCILEX** [comment]
> we'll be ok

No. As I mentioned above, those will be as simple as possible which means they will ignore all errors. So it will be impossible to just ignore program errors.

**Comment by WindSoilder** [comment]
> but I'm planning on reopening my PR once we reach consensus so that'd be a little rude

That's ok, I just open the previous PR because I'm the one to make that regression, and I'll leave it to you :-)
As a result, I'd still like to make `-i` to do what it was like(ignore all errors), for programming error, we can have something like `-r` mode(indicates restrict mode), which will raise `ShellError` but ignore `Programming Error`.

I strongly feel that `do -i` should behave the same as before.

**Comment by dandavison** [comment]
@SUPERCILEX how about adding your low-level control as two new flags (names up to you), so we would have

- `-i` meaning "ignore all"
- (x TBD)  meaning "ignore errors in external processes"
- (y TBD) meaning "ignore nushell errors"

and the implementation of `-i` would be activating both your flags?

Maybe this isn't too unpalatable because, after all, "ignore" didn't specify what it was ignoring whereas your additions will be explicit about this.

I suspect the actual user interface here will evolve -- as you've touched upon on the discussion -- so I think it's OK to have these low-level flags even if the original `-i` now becomes unnecessary in the presence of the two new flags.

**Comment by SUPERCILEX** [comment]
@dandavison hey, I like that! @WindSoilder you get the old behavior and people like me can still activate only the error catching we need. Everybody on board?

**Comment by rgwood** [comment]
I also like @dandavison's proposal; seems like a pragmatic way to move this forward.
