### ISSUE TITLE
`let-env` should not be able to set `PWD`

### ISSUE THREAD

**Issue by Decodetalkers** [nushell/nushell#7097]
### Describe the bug

the path of directory should be changed by `cd`, and should not be set by let-env, cd already can handle the `let-env PWD` , and can report error , use let-env to set it is useless

### How to reproduce

I don't think PWD should be set by let-env

### Expected behavior

PWD should also not be set manully

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             | makepkg                                         |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (Arch Linux rust 1:1.65.0-1)       |
| cargo_version      | cargo 1.65.0                                    |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-09 06:34:03 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Hi,

In the future, please include examples of the commands you are running - that will help us understand your issue more quickly.

If I understand correctly, you're saying that `let-env PWD = "/foo"` should not change the current directory to `/foo` because `cd /foo` can do the same thing. I think the flip side of that is that `PWD` _is_ an environment variable, and it would be unusual if `let-env` had special behaviour for `PWD`.

It doesn't seem like the current behaviour will cause any significant problems for users, and so I don't think we'll be changing this. But if I've missed something, just let me know.

**Comment by Decodetalkers** [comment]
> 
try
```
let-env PWD = "/root"
```

**Comment by rgwood** [comment]
Thanks, that example helps me understand the problem better. I can see how permission checks are important here, and probably better done in `cd` than in `let-env`.
