### ISSUE TITLE
Light gray and dark gray display as black and white

### ISSUE THREAD

**Issue by robenkleene** [nushell/nushell#7138]
### Question

As illustrated by running the `ansi -l` command, dark gray and light gray are displayed as black and white respectively. Is there any way I can fix this?

![image](https://user-images.githubusercontent.com/1058778/201895408-fb5b6096-8b09-40cd-ae00-5a1671880d46.png)

![image](https://user-images.githubusercontent.com/1058778/201896095-791c96c5-a58a-4a37-84d0-499667ff6dd1.png)

**Comment by fdncred** [comment]
It's not commonly known but these colors are palette colors and those come from your terminal theme.

dark gray is `[90m` and light gray is `[97m`. `90` and `97` aren't real colors, they're just looking up whatever color your terminal has those set to. If you want "real" colors, you can specify them with hex colors like `#aabbcc` or specify foreground and background with `{fg: '#aabbcc' bg: '#ddeeff' attr: b}`

**Comment by fdncred** [comment]
> Just to be crystal clear when you say "terminal" you mean from the terminal emulator that I'm running? (E.g., iTerm2, etc...)

Yes, You can typically choose color themes in your terminal emulator. For instance, this is Windows Terminal, which calls theme color schemes. You'll notice that for the "Campbell" scheme, you can choose what each color is. Theoretically, i could pick red and make it green actually.
![image](https://user-images.githubusercontent.com/343840/201945226-d2ac1891-4a26-4822-808e-6c13ea759969.png)

I'm using "Tango Dark"
![image](https://user-images.githubusercontent.com/343840/201945438-6608564e-a358-4db0-8903-14f243b4277e.png)
This is dark gray
![image](https://user-images.githubusercontent.com/343840/201945542-f8ad8359-1d35-4fb8-991e-a9a3cd49f7d0.png)
This is light gray
![image](https://user-images.githubusercontent.com/343840/201945620-51b95ab4-7d0f-48cc-85f2-c047daac0cb2.png)

but notice that you can't see black. that's because my terminal background color is black, so black on black is essentially invisible.

> Just to be clear here, you mean when I'm configuring a theme, I can set hex colors? 

Yes, when you're configuring a nushell theme you can use hex colors. You can see that in the default config files in the repo.

**Comment by fdncred** [comment]
8 colors are standard in most terminals. Some call the additional 8 colors as bright or bold. There are gray colors in the configuration. Maybe this would help explain https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by robenkleene** [comment]
Thanks for the reply!

When you say "There are gray colors in the configuration." What does that mean exactly? That sounds like the answer to my question!

**Comment by robenkleene** [comment]
Ha yeah, light gray is just what's normally (at least in my experience) called bright white, and dark gray is bright black. So simple! Thanks so much for your help!
