### ISSUE TITLE
Ctrl-d treated the same as Ctrl-c

### ISSUE THREAD

**Issue by SafariMonkey** [nushell/nushell#714]
I noticed in previous versions of nushell that Ctrl-d acted exactly like Ctrl-c (even printing "CTRL-C pressed"). This seems odd to me. And now, as of #706, Ctrl-d is now not able to be used to exit the shell.

Is this conflation of two historically very different hotkeys (two of my most used in Bash) deliberate? Or is there just some behaviour that you want both to share?

Oh, and [this](https://github.com/landaire/nushell/blob/master/src/cli.rs#L364-L365) is the line that I believe causes it.

**Comment by jonathandturner** [comment]
I believe this was a recent change that we may want to rethink. I agree that it's be good to keep them separate.

**Comment by zbeekman** [comment]
@jonathandturner is CTRL-D supposed to work to exit the shell? I think it was for me in 0.2.0, but now in 0.4.0 it does not. I'm on macOS (and I have modifier keys re-mapped and a custom layout).

**Comment by andrasio** [comment]
#900

**Comment by samford** [comment]
In the process of updating the Nushell formula in Homebrew from v0.2.0 to v0.5.0 (Homebrew/homebrew-core#46505), I also encountered this issue when the test wouldn't execute to completion and would simply hang until it timed out.

Basically, [the test](https://github.com/Homebrew/homebrew-core/blob/47437a918aec92a08d5cfaa8ea0428b8c91b6ed2/Formula/nushell.rb#L35) calls a function that opens `nu` and runs a command, after which it seems to use Ctrl+D to exit the process.  The test was originally designed for v0.2.0 and works properly on that version but with versions 0.3.0 to 0.5.0, it hangs due to Ctrl+D not working as expected.

At least from the perspective of the Homebrew formula, it would be helpful if Ctrl+D's behavior was in line with Bash, Zsh, etc. (i.e., EOF -> exit).

**Comment by Compro-Prasad** [comment]
Why is this the default behaviour? Can someone explain to me?

**Comment by jonathandturner** [comment]
We want it to be in-line with Bash's behavior, as having them work the same is confusing. I believe it was changed as part of an unrelated fix, but it still needs to be reset back to working differently than Ctrl-C

**Comment by jonathandturner** [comment]
I went ahead and reverted the changes that led to ctrl-d and ctrl-c being treated the same. We should be back to where ctrl-d works as expected.
