### ISSUE TITLE
OpenSSL error with precompiled binary on Arch Linux

### ISSUE THREAD

**Issue by jonmast** [nushell/nushell#715]
I get the following error when running the latest 0.3 release:
`./nu: relocation error: ./nu: symbol SSLv3_client_method version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference`

From a quick web search it appears this is because the openssl package on Arch is compiled without SSL3 support. The 0.2 release of nu does work fine though, so I'm guessing something changed in the build setup.

Compiling it myself with cargo does work fine so this isn't a major issue, but it would be nice to be able to use the pre-built binary.

**Comment by jonathandturner** [comment]
Thanks for letting us know. We may use a different configuration in the future, so the ssl lib isn't required.

**Comment by devurandom** [comment]
It appears nushell links against `libssl.so.1.0.0` (i.e. locking to a very specific version in addition to the ABI) instead of `libssl.so.1` (i.e. ABI version 1):
```
$ scanelf --needed bin/nu                                                           
 TYPE   NEEDED FILE                                                                        
ET_DYN libssl.so.1.0.0,libcrypto.so.1.0.0,libz.so.1,libxcb.so.1,libxcb-render.so.0,libxcb-shape.so.0,libxcb-xfixes.so.0,libdl.so.2,librt.so.1,libpthread.so.0,libgcc_s.so.1,libc.so.6,ld-linux-x86-64.so.2,libm.so.6 bin/nu
```

From a distro maintainer's perspective this seems wrong. Software should link against a specific ABI version (e.g. `libssl.so.1`, but not be more specific than that (e.g. `libssl.so.1.0` or `libssl.so.1.0.0`).

Any idea why this is done / happens? I cannot see an immediate reason in the build scripts of nushell, (rust-)curl or (rust-)openssl-sys.

Since nushell's dependencies `surf` and `async-stream` use unstable language features (async), I cannot build nushell myself, to try to reproduce this behaviour.

**Comment by jonathandturner** [comment]
This may be part of how the crate that uses ssl links to the library, though to be honest I'm not familiar with how dynamic libraries link to Rust binaries.

I think we should move off of using the ssl features for the binary build so that it's maximally portable.

If you're trying to build nushell, the latest version in the repo has moved from nightly to beta.

**Comment by devurandom** [comment]
To be maximally portable, one could link statically against libssl -- `openssl-sys` supports that. But I would recommend against it, since you would not get any security updates from the system library / distro, which I would consider more important.

Linking against `libssl.so.1` (library name with ABI version, the `SONAME`) is generally very portable: Every distro release of the past years ships that library. `libssl.so.0` is AFAIK considered outdated and insecure, since upstream does no longer support it (and OpenSSL 1.0 will also reach EOL by the end of the year).

I would assume that linking against `libssl.so.1` should not be too hard, because it should actually be the default. Passing `-lssl` to the linker should make it find `libssl.so` somewhere in the library path, look into it's `DT_SONAME`, which should be `libssl.so.1`, and then record that in `DT_NEEDED` of the resulting binary (same for shared objects / libraries). No idea why that is currently not happening for the nushell release builds... Lacking a beta build of Rust, I cannot investigate myself at the moment.

**Comment by andrasio** [comment]
#900

**Comment by jonathandturner** [comment]
@jonmast - we switched how we were doing the builds. Is this still an issue with more recent releases?

I saw that Arch has AUR for nushell, too, which is another possibility.

**Comment by jonmast** [comment]
@jonathandturner  This hasn't been an issue for quite some time, recent releases work fine on Arch even without using the bundled SSL lib.

 I'm the maintainer of nushell-bin on the AUR, it relies on these binaries for a speedier install than the build from source variant.

Thanks for all your hard work on this, I'll close this out now.

**Comment by jonathandturner** [comment]
Great to hear. And thanks for working on the AUR :)
