### ISSUE TITLE
Possible to create `def`s that start with `^` (thus preventing external command access)

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7273]
### Describe the bug

See title.

### How to reproduce

```
〉def ^cat [] { 'Bah!' }
〉^cat
Bah!
```

### Expected behavior

I expect the ^ to be a protected syntactic element that can't be overridden by someone making a nefarious `def`.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 18:03:36 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by theAkito** [comment]
At first, I thought, this is about enabling this behaviour, because that sounds really cool & useful. Perhaps it would be best to make it configurable via `config.nu`?

This feature sounds amazing!

**Comment by webbedspace** [comment]
Pardon me, but… how… is it useful?

**Comment by theAkito** [comment]
Let me start off with the argument for disabling that functionality.

> I expect the ^ to be a protected syntactic element that can't be overridden by someone making a nefarious `def`.

Is there ever any chance, that a third party can modify your personal configuration in a way, so that you eventually by accident type in an external command explicitly?

There are so many assumptions in that statement, that it's practically almost impossible. It will pragmatically never ever happen, ever. Especially, since there are other locations much more harmful to edit, when someone is logged in as you, i.e. has write access to your `~/.config` folder, etc.

Now, I think, having an additional option, which is not harmful, as I outlined above, is usually good, if it doesn't go out of scope or out of philosophy. Clearly, having such a possibility is neither, since it's pretty much a natural result from what was already there. It's basically an implicit part of the feature set.

Following that, it can be useful to override any possibility of issuing an external command, if you have two defs overriding one, of which one has the additional symbol prefixed.
Which is why, when I initially read your issue, surprised that you "accidentally" chose the bug template, because I thought, that you proposed a great feature. The feature to completely override an external command in this way.

Therefore, whether you find it useful in your scenario or not is not that decisive, because there are enough reasons for this feature to be kept, as it isn't harmful and it might have a use in specific cases.

Not everyone uses every feature of something, yet there is always a set of features, which tries to account for as many demands as possible from the target audience.

Finally, I think it's great, that natural features like this arise from the fundamental feature set. Which leads to my question: why do you _expect_ it "to be a protected syntactic element"?
Why restrict something, which is great?

Again, I am convinced, that it's not possible to exploit this specific feature in some way, except for fun with you knowing & expecting it. No third party would make such a joke def to exploit something. It does not make sense. They could just hijack your `ls` and whenever you `ls` something you deploy a hack or something. No need for prepending `^` to anything.

My largest point about this is basically, that your argument of exploitation does not make any pragmatic, realistic sense in this context. There is no risk of exploitation whatsoever, beyond what we already have available. If someone can just randomly access your `config.nu`, they are just going to hijack your `ls` & `cd`, etc.

```nu
def ls [] { echo exploited }
```
Took me like a second to exploit myself, by redefining `ls`.

**Comment by webbedspace** [comment]
>Now, I think, having an additional option, which is not harmful, as I outlined above, is usually good, if it doesn't go out of scope or out of philosophy.

Look, the whole point of the ^ symbol in the first place is that it's supposed to be understood as something "separate" from barewords themselves. "You attach ^ to a bareword and it prevents a Nushell internal from being activated" is how the new users need to understand how ^ works. This very brazenly complicates the behaviour by creating a situation where ^ does not function like that at all.

>Why restrict something, which is great?

You've given no examples or reasons why this is "great". Show me any new functionality that this provides that makes Nushell easier to use.

**Comment by theAkito** [comment]
> Look, the whole point of the ^ symbol in the first place is that it's supposed to be understood as something "separate" from barewords themselves. "You attach ^ to a bareword and it prevents a Nushell internal from being activated" is how the new users need to understand how ^ works. This very brazenly complicates the behaviour by creating a situation where ^ does not function like that at all.

Does not matter at all, because one would need to consciously create a `def` starting with that symbol. So, yes, for a new user as you described, they wouldn't even know about this and would never have trouble, because they wouldn't have such a `def`, in the first place.

So, again, that point is absolutely moot. Your examples do not apply to reality, at all. You assume like a thousand weird things. Then, yes, it could be harmful. However, that's not reality.
It's simply senseless to assume, someone creates a ` def "^ls"` and then wonders about how this command is different from the traditional `^ls`. It does not make sense.



> You've given no examples or reasons why this is "great". Show me any new functionality that this provides that makes Nushell easier to use.

I have explained, in my perception, very thoroughly how the largest point I was making was referring to how your arguments against it are neither applicable to reality nor have any significance in the context of this issue.

Following that, I wondered, and still do wonder, why you want to restrict something, that is neither harmful, nor did you experience anything bad with it.
It just feels like you saw this work & then decided, that it doesn't feel right to you, hence this issue.

My point is, your arguments against it are absolutely moot and my argument is, that if there is no argument against something, then one should leave it.

Therefore, I don't need to provide great examples. You need to provide realistic examples of why it is bad, since you created this issue. So, the burden of arguments is on you.

I said it's "great", because there is literally no argument against it. You have provided no argument of significance against it.
Which is "great", because if something isn't bad, it's good enough to stay.

If you can provide me with actual arguments for why this is harmful, then I will definitely re-evaluate my position.
Though, as of right now, there is no argument against it, whatsoever.
Except some weird alien scenario, that will never happen, in anybody's lifetime, ever.
