### ISSUE TITLE
Custom command should also be executed when only the flag parameters

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#7485]
### Describe the solution you'd like

def test [
  --name (-n): string
] {
  echo $name
}

test --name foo
should be able to be executed

**Comment by sholderbach** [comment]
![grafik](https://user-images.githubusercontent.com/15833959/207945574-167d578c-7567-4321-9a6c-c20a2ce60aef.png)

This runs without a problem on the current major version (and should have been possible for many versions). Unclear to me what your problem is.

Please be more descriptive in your bug reports/issues by including the things you have tried either as code snippets (`\`\`` markdown quotes make them more readable) or screenshots.
