### ISSUE TITLE
pick doens't produce error messages when given an invalid column name

### ISSUE THREAD

**Issue by boxed** [nushell/nushell#750]
```
> mkdir pick-test
> cd pick-test/
> touch foo.txt

> ls | pick invalid1 invalid2
━━━━━━━━━━┯━━━━━━━━━━
 invalid1 │ invalid2 
──────────┼──────────
          │  
━━━━━━━━━━┷━━━━━━━━━━
```

This seems wrong. An error message seems much more reasonable.

**Comment by andrasio** [comment]
@boxed Thanks for reporting it!

**Comment by andrasio** [comment]
#900

**Comment by drmason13** [comment]
I'd like to take a crack at this, if I may? Fair warning though, I'm new to this code base :)

At the moment pick sees "Nothing" as a completely valid response every time it runs `select_fields`, which is why the table with empty rows gets printed.

I'm struggling to see where to add the error checking code.
As far as I can see `pick` calls `select_fields()` which returns an `InputStream`.
My difficulty is that `select_fields` doesn't return a `Result`, and an `InputStream` is, on the surface, difficult to inspect.

Inside `select_fields()` when matching `None`, a `Primitive::Nothing` is used by way of `Value::nothing()`. This might be the place to try and return errors? `Err("Nothing selected")` or thereabouts :)

There may be a reason a `Primitive::Nothing` is returned by `select_fields()`, but if everything that should allow a `Primitive::Nothing` from `select_fields` is able to match the Err and opt to return `Primitive::Nothing` themselves then we'd be good, if that's not too burdensome!

**Comment by boxed** [comment]
Was this fixed?

**Comment by andrasio** [comment]
@boxed Not yet. We are tracking it from #900 now to avoid having so many open issues.

**Comment by boxed** [comment]
Now you're just making me confused! :)

**Comment by andrasio** [comment]
@boxed Heh, we decided to reopen them and track them in the meta-issue.

**Comment by boxed** [comment]
🎉
