### ISSUE TITLE
Do any know of a tab-completion document for `gcloud` CLI in `nu`?

### ISSUE THREAD

**Issue by iiian** [nushell/nushell#7578]
### Question

Do any know of tab-completion for `gcloud` in `nushell`?

I'm trying to get `gcloud` tab-completion support set up for nushell. Right now, tab-completion support is provided for bash/zsh/fish using https://github.com/twistedpair/google-cloud-sdk, AFAIK. I am aware of this issue https://github.com/nushell/nushell/issues/290 regarding tab-completions, but I'm not sure if its implications (ie ticket scope, being closed) apply here.

**Comment by theAkito** [comment]
What is the actual problem?

https://xyproblem.info/

**Comment by iiian** [comment]
Sorry, maybe I didn't make it clear enough with context, friend. 😄  I'd like to use `gcloud` tab-completion with `nu` shell, but of course it doesn't work OOTB, and Google search doesn't produce any results for a `nu` shell script that enables tab-completion, so I'm hosed, unless someone knows of a tab completion document for `gcloud`.

**Comment by theAkito** [comment]
> I'd like to use `gcloud` tab-completion with `nu` shell, but of course it doesn't work OOTB, and Google search doesn't produce any results for a `nu` shell script that enables tab-completion, so I'm hosed, unless someone knows of a tab completion document for `gcloud`.

If I understand correctly, nobody has yet created an `extern` for this external command.

https://www.nushell.sh/book/externs.html#externs

This document explains, how you can create an `extern`.

You need the manual for the `gcloud` command & then you have to port every option of it into Nu.

As you can see in the `git push` example of  the manual, you can even attach custom hooks/commands to an option. So, for example, if your `gcloud` implementation is supposed to search for a `cluster` when pressing TAB, you can make it work.

Once you are done with everything, you might consider making it available for everyone.

https://github.com/nushell/nu_scripts

**Comment by iiian** [comment]
Thanks @theAkito for sharing your insight, it is very much appreciated.

> You need the manual for the gcloud command & then you have to port every option of it into Nu.

Man, that does not sound like fun. In the `google-cloud-sdk` library I linked in the first message, a python library[1] manages tab-completion work (numbering in the dozens or hundreds of different command modes) and then (2) provides glue scripts per shell to invoke the python lib on-tab. Given that it's using `complete` command which seems to be common across shells and clis (for instance, I know that aws uses it as well[3]), is there not a way we can do the same with `nu`? Just a "glue-script" in `nu` syntax that plugs us into that python lib?

[1] https://github.com/twistedpair/google-cloud-sdk/blob/master/google-cloud-sdk/lib/googlecloudsdk/
[2] https://github.com/twistedpair/google-cloud-sdk/blob/master/google-cloud-sdk/completion.zsh.inc.
[3] https://github.com/aws/aws-cli/blob/develop/bin/aws_zsh_completer.sh

**Comment by theAkito** [comment]
> provides glue scripts per shell to invoke the python lib on-tab.
> is there not a way we can do the same with nu? Just a \"glue-script\" in nu syntax that plugs us into that python lib?

Yes, you can create a Nu plugin in Python.

https://www.nushell.sh/contributor-book/plugins.html#creating-a-plugin-in-python



The general problem of the matter is, that this is a bit like apples to oranges. Yes, it may seem like it's more work, but you have it all with the performance and full Nu support, without ugly Python + even uglier glue code.

So, you can make it ugly in Nu, as well, but then you perhaps won't have all the Nu benefits coming with it.

From what you have said so far, I assume you prefer the glue code thing for the sake of the associated time & effort savings, which is reasonable.

Although, then you probably still need some Nu interface in-between, a mix from what I have offered before.

There is I guess one last resort for the ugliest & worst possible solution, but it may be the quickest in your situation.
You perhaps may invoke one of the already supported shells within Nu & then leverage those already implemented abilities.
Thinking about this again, I'm not sure if it'd be that easy, since we are talking about tabulator related commands/completions. Not sure.

You could also look into how the Python and glue code are managing this stuff & translate the logic.
Though, once you start looking into Python to begin with, you might as well write a plugin, as suggested, previously.

Conclusion:
No matter how you'd like to do it, there will always be some effort & time investment involved, in varying degrees depending on the chosen method.
There's no one-second Fix solution to your request.

Anyway, I suggest you read into the Nushell manual, so you can have an idea about my suggestions and how solving this would be possible.

**Comment by iiian** [comment]
> > provides glue scripts per shell to invoke the python lib on-tab.
> > is there not a way we can do the same with nu? Just a \"glue-script\" in nu syntax that plugs us into that python lib?
> 
> Yes, you can create a Nu plugin in Python.
> 
> https://www.nushell.sh/contributor-book/plugins.html#creating-a-plugin-in-python
> 
> 
> 
> The general problem of the matter is, that this is a bit like apples to oranges. Yes, it may seem like it's more work, but you have it all with the performance and full Nu support, without ugly Python + even uglier glue code.
> 
> So, you can make it ugly in Nu, as well, but then you perhaps won't have all the Nu benefits coming with it.
> 
> From what you have said so far, I assume you prefer the glue code thing for the sake of the associated time & effort savings, which is reasonable.
> 
> Although, then you probably still need some Nu interface in-between, a mix from what I have offered before.
> 
> There is I guess one last resort for the ugliest & worst possible solution, but it may be the quickest in your situation.
> You perhaps may invoke one of the already supported shells within Nu & then leverage those already implemented abilities.
> Thinking about this again, I'm not sure if it'd be that easy, since we are talking about tabulator related commands/completions. Not sure.
> 
> You could also look into how the Python and glue code are managing this stuff & translate the logic.
> Though, once you start looking into Python to begin with, you might as well write a plugin, as suggested, previously.
> 
> Conclusion:
> No matter how you'd like to do it, there will always be some effort & time investment involved, in varying degrees depending on the chosen method.
> There's no one-second Fix solution to your request.
> 
> Anyway, I suggest you read into the Nushell manual, so you can have an idea about my suggestions and how solving this would be possible. 

Appreciate your time and thoughts @theAkito. I don't think I'm the right person to move all of gcloud into nu, but you've inspired me to pick up the Nu book, so thanks for that!
