### ISSUE TITLE
Consider a different name for environment variable `FILE_PWD`

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#7692]
https://github.com/nushell/nushell/pull/7424 by @kubouch introduced the environment variable `FILE_PWD` which is set to the directory where the script is.
This feature is much appreciated.

However, I would suggest giving this variable a different name.
`pwd` is a known Unix command, but it stands for "print working directory".
The "print" doesn't make a lot of sense here.
Also, the name `pwd` is not very descriptive.

I would instead suggest using `FILE_WORKDIR` or (if brevity is the priority) `FILE_WD`.

**Comment by kubouch** [comment]
That's a fair comment. I didn't know that it stands for "print working directory". We could change it to `$env.FILE_CWD` (as for "current working directory") and probably also change `$env.PWD` to `$env.CWD`. One problem with this is that it is a significant breaking change so we'd probably want to do it in two stages: 1. Introduce the CWD-based env vars but keep the PWD ones working, 2. Deprecate the PWD-based env vars.

**Comment by Hofer-Julian** [comment]
> We could change it to `$env.FILE_CWD`

My gut feeling is that the word `current` should be reserved to, well, the current working directory :)
But maybe other languages do that too, I haven't put too much research into that.
In Python, you can use `__file__` put that means the file path, not the parent directory.

> One problem with this is that it is a significant breaking change

Ah, too bad :)
I was hoping that this variable wasn't released yet.

**Comment by Hofer-Julian** [comment]
> $env.CURRENT_DIR - prints the current directory (probably using the nu-engine::env::current_dir(), instead of std::env)
$env.CURRENT_EXE - prints the full filesystem path of the current running script

@fdncred Any reason why you would go for "EXE" instead of "FILE" here?

**Comment by fdncred** [comment]
> @fdncred Any reason why you would go for "EXE" instead of "FILE" here?

because that's what rust does. that's what i meant by the comment above those lines.

**Comment by Hofer-Julian** [comment]
> because that's what rust does. that's what i meant by the comment above those lines.
but i don't have objections to $env.CURRENT_FILE either.

I see :)
I could indeed imagine that `$env.CURRENT_FILE` would feel a bit more natural for an interpreted language such as nushell.

**Comment by kubouch** [comment]
Yeah, `$env.CURRENT_FILE` seems good to me as well. Even `$env.FILE`. The `__` names in Python always seemed quite mysterious to me. The problem with `$env.CURRENT_DIR`, however, is that it is not clear that it's the file-relative directory, not the current working directory. That's why I (incorrectly) named it `FILE_PWD` to denote it's relative to the file. Maybe it should be `FILE_CWD` then?

**Comment by Hofer-Julian** [comment]
Maybe the directory is not necessary if dirname exists: https://www.nushell.sh/book/commands/path_dirname.html

**Comment by kubouch** [comment]
That's true, it's not necessary for the user, but the reason why it was added is that it's used by Nushell internals. But yeah, we could have just the file path and change the internals to derive the directory from the file path, that should work as well.

**Comment by kubouch** [comment]
Actually, it seems like `PWD` is a standard POSIX environment variable: https://en.wikipedia.org/wiki/Pwd#Working_directory_shell_variables

While Nushell does not aim to be POSIX-compliant, in this case I'd say there is no reason to deviate. Changing FILE_PWD is not a big deal but switching from PWD to CWD would be a hassle because we'd need to keep both running at the same time, etc. So, now that I learned PWD comes from the POSIX standard, I'd vote for keeping things as they are.

**Comment by Hofer-Julian** [comment]
I had no idea, nice find!
I agree that this issue can be closed.
