### ISSUE TITLE
http get see response headers

### ISSUE THREAD

**Issue by PumpedSardines** [nushell/nushell#7986]
### Related problem

I'm trying to see if my server sets the correct response headers for a specific request, however I can't seem to see what http headers are being set. It would be nice to be able to see response headers

### Describe the solution you'd like

For example using a flag like upper case h (`http get -H http://mydomain.com`) to get the response headers as an array

**Comment by fdncred** [comment]
Thanks for the suggestion. If we want to display response headers, we'd have to use a different parameter since -H is already taken, as you can see in the help.
```
help http get                                                                                                             37  06:53:17 AM
Fetch the contents from a URL.

Performs HTTP GET operation.

Search terms: network, fetch, pull, request, download, curl, wget

Usage:
  > http get {flags} <URL>

Flags:
  -h, --help - Display the help message for this command
  -u, --user <Any> - the username when authenticating
  -p, --password <Any> - the password when authenticating
  -t, --timeout <Int> - timeout period in seconds
  -H, --headers <Any> - custom headers you want to add
  -r, --raw - fetch contents as text rather than a table

Signatures:
  <nothing> | http get <string> -> <any>

Parameters:
  URL <string>: the URL to fetch the contents from

Examples:
  http get content from example.com
  > http get https://www.example.com

  http get content from example.com, with username and password
  > http get -u myuser -p mypass https://www.example.com

  http get content from example.com, with custom header
  > http get -H [my-header-key my-header-value] https://www.example.com
```

**Comment by fdncred** [comment]
We don't like to clutter up commands with too many parameters. So, a different thought is that we try to be composable so that we can chain together commands via a pipe. I wonder if it would make sense to have a `http response` command that could be used is this family of `http` commands. For this instance, something like `http get https://www.example.com | http response` and it prints what you were talking about and perhaps more?

Have at it if you feel like you want to try and add this.

**Comment by PumpedSardines** [comment]
Yes that looks way cleaner

**Comment by PumpedSardines** [comment]
@fdncred When I looked at the code, it seems like `http get` returns a RawStream, and I can't seem to get the raw response struct from that stream. I'm relatively new to rust and this project so I don't know how to approach this. It seems like I need to add more fields to the ExternalStream struct, but I'm afraid I'll clutter the core. Am I missing something?

**Comment by fdncred** [comment]
Hmmm, I'm not sure either without digging into it and even then, I probably wouldn't know. 🤣 Free free to drop by our discord and ask questions in #implementation-chat or #design-discussion. There are probably people lurking there that could help.

**Comment by dmatos2012** [comment]
@PumpedSardines  I was also sort of starting to work on this as well, but in order to collect the `raw response` you can do something like:
```
let config = engine_state.get_config():
`let stream = input.collect_string_strict("", config)?` -> contains what you want,
```
However, that does not include as you can see the response headers, you need to somehow include it in the response. I thought by adding it to the `metadata` field on `RawStream`, but not sure if thats what its for. I was gonna ask the devs on discord. but didnt get around it.

It helps me a TON to look at the existing code since someone has already done what you are trying to do but just with different command, so do some sort of grep around the code and find related words, at least that helps me a lot!

Since you are working on this, I will stop working on it myself, but if you feel you want to find a different issue, let me know here so I can resume it!

Good luck!

Disclaimer: I am also kinda new with rust and project in general :)

**Comment by WindSoilder** [comment]
Is it covered by `http head` command?

**Comment by fdncred** [comment]
I think so. Closing for now.
```
http head https://example.org
╭──────────────────┬───────────────────────────────╮
│ content-encoding │ gzip                          │
│ accept-ranges    │ bytes                         │
│ age              │ 50256                         │
│ cache-control    │ max-age=604800                │
│ content-type     │ text/html; charset=UTF-8      │
│ date             │ Fri, 24 Feb 2023 15:47:58 GMT │
│ etag             │ "3147526947"                  │
│ expires          │ Fri, 03 Mar 2023 15:47:58 GMT │
│ last-modified    │ Thu, 17 Oct 2019 07:18:26 GMT │
│ server           │ ECS (chb/0286)                │
│ x-cache          │ HIT                           │
│ content-length   │ 648                           │
╰──────────────────┴───────────────────────────────╯
```
