### ISSUE TITLE
completion_menu crashes if `only_buffer_difference` is `true`

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#8091]
### Describe the bug

If I do `cd <tab>` it returns nothing, and then if I hit `c` it panics like this:
``` 
cd thread 'main' panicked at 'insertion index (is 3) should be <= len (is 1)', library/alloc/src/vec/mod.rs:1445:13 FOUND
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrack
```

I narrowed this down to this completion_menu in my config. Note it's matches the default_config.nu except the colors are different and `only_buffer_difference` is `true` here and `false` in the default_config.nu.
```
  {
    name: completion_menu
    only_buffer_difference: true
    marker: $"(char -u 1f4ce) "
    type: {
      layout: columnar
      columns: 4
      col_width: 20   # Optional value. If missing all the screen width is used to calculate column width
      col_padding: 2
    }
    style: {
      text: { fg: "#33ff00" }
      selected_text: { fg: "#0c0c0c" bg: "#33ff00" attr: b}
      description_text: yellow
    }
  }
```

if `only_buffer_difference: true` it crashes. If it's `false` it does not crash.

This is fernando's documentation for that menu option.
```
only_buffer_difference: true # Search is done on the text written after activating the menu
```

### How to reproduce

See above

### Expected behavior

Even if `only_buffer_difference` is supposed to be `false` and I have it set to `true` it shouldn't panic. I've had this value set to `true` for (probably) years. So, I'm guessing that this is a recent regression.

### Configuration

|key|value|
|-|-|
|version|0.75.1|
|branch|main|
|commit_hash|ade7bde813218ed599552731266eea844766b9cc|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.66.1 (90743e729 2023-01-10)|
|rust_channel|1.66.1-aarch64-apple-darwin|
|cargo_version|cargo 1.66.1 (ad779e08b 2023-01-10)|
|pkg_version|0.75.1|
|build_time|2023-02-16 05:37:23 -06:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, hist, inc, nu-example-1, nu-example-2, nu-example-3, periodic-table, plot, pnet, query, query json, query web, query xml, regex, xyplot|

**Comment by sholderbach** [comment]
Thanks for the investigation into that!

**Comment by sholderbach** [comment]
## Repro copied over from #9006 by @epbuennig

I had the following completion menu from some default config back when I first installed `nu`, after fixing because of some breaking updates I tried out this completion menu. I encountered a panic when completing and using a navigation key.

```nu
let config = {
  # ...
  menus: [
    {
      name: commands_with_description
      only_buffer_difference: true
      marker: "# "
      type: {
        layout: description
        columns: 4
        col_width: 20
        col_padding: 2
        selection_rows: 4
        description_rows: 10
      }
      style: {
        text: green
        selected_text: green_reverse
        description_text: yellow
      }
      source: { |buffer, position|
        $nu.scope.commands
        | where name =~ $buffer
        | each { |it| { value: $it.name description: $it.usage } }
      }
    }
  ]
  # ...
}
```

### How to reproduce

1. type at least one character into the line buffer
2. run the completion menu given above
3. complete some command, accepting the completion to drop out of the menu
4. press `arrow-up` (or I assume `k` in vi mode)

### Expected behavior

It rejects the current line and moves up the command history as if the line was empty and `arrow-up` (`k`) was pressed.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.78.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1) |
| cargo_version      | cargo 1.68.2                                                     |
| build_time         | 2023-04-05 02:09:35 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

### Additional context

I, unfortunately, am too lazy to build with debug symbols to get a better stack trace, but it contains the line number and is reproducible.
```
~
❯ taliasthread 'main' panicked at 'byte index 7 is out of bounds of `talias`', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.18.0/src/core_editor/line_buffer.rs:647:10
stack backtrace:
   0:     0x562dd845f29e - <unknown>
...
  27:                0x0 - <unknown>
```

I am using [starship](https://github.com/starship/starship) for my prompt, not sure if this meddles with the line buffer position because of the different prompt.

**Comment by ysthakur** [comment]
It looks like the problem was that when you pass a `line` and `pos` to the completer, it assumes that `line` is the entire line, not just a portion of it, and `pos` is the end of the portion of the line to complete (either the end of the buffer difference or your cursor's position, depending on `only_buffer_difference`). This doesn't true when `only_buffer_difference` is true since only a part of the line is passed (also, the start of the buffer difference was being passed instead of the end).

I made a Reedline PR (https://github.com/nushell/reedline/pull/695) that makes `only_buffer_difference: true` work with the columnar and list menus built into Reedline when used with the `DefaultCompleter`. After that, https://github.com/nushell/nushell/pull/11488/ should finish the job by making it work with Nushell's `NuCompleter`.

**Comment by kubouch** [comment]
Can this be closed now since https://github.com/nushell/nushell/pull/11488 was merged?

**Comment by fdncred** [comment]
yup, i just tested and it doesn't crash. another issue though is `cd <tab>` should bring up folders and not everything plus it doesn't `# Search is done on the text written after activating the menu`, but this issue is about crashing so i'll close it.
