### ISSUE TITLE
Internal -> External should not drain

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#816]
Currently, based on our previous model, we're draining the input into an external:

https://github.com/nushell/nushell/blob/master/src/commands/classified.rs#L227

We should instead take in the lines one at a time instead of draining all at once.  We can use the async generators approach we use for Internal's run (which is above it in the same file)

**Comment by thegedge** [comment]
Hey, @jonathandturner. I'll try to tackle this one this weekend.

**Comment by jonathandturner** [comment]
@thegedge sounds good - feel free to ping here or on the discord if you want to brainstorm at any point.

**Comment by thegedge** [comment]
When digging around, I found an issue and first decided to fix it first (see https://github.com/nushell/nushell/pull/829).

So my understanding is that we want to avoid the `into_vec()`, and rather stream out the items in `input.objects` one by one, correct? If so, this seems like a fairly straightforward task of iterating over the stream instead of collecting it into a vec, unless I'm missing something 😅

**Comment by jonathandturner** [comment]
@thegedge - that's right. You might have seen us using `async_stream! { ... }`  Using this should let you iterate through each element rather than using `into_vec()` and send to the stdin of the external one line at a time rather than building something and then sending it all at once.

That's the theory at least :)

**Comment by thegedge** [comment]
Given we have to construct a command string (e.g., `cmd <it1> && cmd <it2> && ...`) to pass to a shell, we're going to have to drain no matter what we do, right? Would the benefit here be that we could potentially do this without an intermediate `Vec`, or perhaps I'm missing something 😅

The only other option I can see is that instead of constructing an `&&` command string to pass to a shell, we handle the executing of each of those individual commands in nushell, in which case I can definitely see how we can stream the result. Is that what you were thinking with this issue?

**Comment by jonathandturner** [comment]
Oh that's a good point. It makes me wonder if we should move away from using && as well, and just evaluate the commands one after another instead.

I haven't thought through the impact of that, but I suspect we should investigate it.

**Comment by thegedge** [comment]
> I haven't thought through the impact of that, but I suspect we should investigate it.

One positive I can see is the ability to run a command against all inputs, regardless of whether or not one of the inputs results in the command failing (could be opt-in behaviour). Imagine something like this:

```
echo google.com asdjhasd.com web.com  | split-row " "
```

Where we can somehow process the results of these, and ignore the fact that `host asdjhasd.com` is an NXDOMAIN output with an exist status of 1.

**Comment by jonathandturner** [comment]
If you're up for it, I think we should give it a try.  I agree that the logic of using && may not give you what you want (great example by the way)

Are you interested in refactoring and removing that assumption?  Seems like we could generally have a better experience using the more relaxed approach you're suggesting

**Comment by thegedge** [comment]
I'm up for it, if there's no urgency. I generally only have a little time on the weekends to work, and this weekend I won't have any 😅 

Arguably, we could use `;` instead of `&&` to get a similar effect, but it's probably worth exploring doing all of this ourselves. I assume there's a long term goal to not have to shell out for these kinds of things?

**Comment by andrasio** [comment]
@thegedge How are we doing? Got any updates?

**Comment by thegedge** [comment]
Been a little busy lately, but I should have some free time this weekend to give it a shot. If it's out of my reach, we can hand it off. How does that sound?

**Comment by thegedge** [comment]
So, after digging into this problem and sharing in Discord, it looks like @jonathandturner and I came to similar conclusions.

This is actually much more difficult than expected when we introduce `$it` to an external command. If we want nushell to be the orchestrator for each separate process, we'll have a separate `stdout` for every process. A naive approach to this would be to return a stream/vec of `ClassifiedInputStream` instances from `ExternalCommand`, but this also means a much larger refactor that perhaps doesn't make sense in the longer term.

I'll continue thinking about this but, as it stands, I don't have any immediate ideas of the best way to approach this. I may try to do some smaller refactors that will help me better understand how everything connects here. If we're lucky, maybe those refactors will help us get closer to where we want to be.

**Comment by thegedge** [comment]
After digging around a ton, I think we need an abstraction of a pipe. That's really all that's happening when you do `foo | bar`, and I think we'll just need to manage this ourselves in nushell. Going to keep chipping away at this. I encourage others to take alternative approaches, but hopefully I can have a working prototype within a week 🤞
