### ISSUE TITLE
 [RFC] Structured data for non-built in commands

### ISSUE THREAD

**Issue by KoviRobi** [nushell/nushell#8285]
### Related problem

Hi,

I am looking at coming up with a portable way to tell programs that they can output structured data, and telling the shell that the said data is structured according to the given format. For this I have a draft proposal write-up at https://github.com/KoviRobi/structured-shell-stdio but I would like some feedback.

Thanks,
Robert
Proposed technical implementation details (optional)

### Describe the solution you'd like

Programs should be able to tell they are being called from a shell that supports JSON, and the shell should know the output is JSON without guessing. So the following
```
ip --json addr | from json
```
could become just
```
ip addr
```

### Describe alternatives you've considered

Setting an alias for each program (or in some cases each subcommand). This would be tedious, and might be fragile.

**Comment by hgkamath** [comment]
>Programs should be able to tell they are being called from a shell that supports JSON, and the shell should know the output is JSON without guessing. 

For the time being is isn't going to happen. The program presently just don't because they aren't coded that way. This would require every single program out-there, which could be a gazillion on them, to comply with a command invocation argument specification.  (just like how X-client programs comply with ```--display``` and other Xorg arguments)
Presently, its not even possible to probe a unix/linux-command to see if it supports an argument, without trying it out.   
The only way currently seems to be to maintain an exhaustive-as-possible-expert-table.

Just a user here making speculations (pseudocode, may not be actual working nushell code) :   

Create an special json alias table of all commands that already take some form of ```--json``` argument.
Regular alias lookup happens only in the repl, and don't expand when run as a script. 
So this special json alias lookup needs to be consulted even when run as a script. 
ex pseudocode : ```jalias ip=`ip --json` ```
But then, if the default is to lookup the json alias-table first, then you need a way to not lookup alias
ex pseudocode :  ```"ip"``` double quotes (or maybe an initial backspace) around command inhibits alias lookup. 
What if command prefix ```nojson_ip``` indicate to explicitly not do json aliasing.
Another question would be, how does one compose both types on aliasing in the repl.

Another possibility is to always use a variable to refer to binaries, that splits on substitution :
```pseudocode : IPBIN="ip --json"```
```pseudocode : $IPBIN addr```

What if the text-json is replaced by BSON or someother data-exchange-format?

**Comment by rgwood** [comment]
Cool idea, thanks for sharing it with us and I hope it goes well. Closing because this is a little outside the scope of Nushell right now.
