### ISSUE TITLE
Setting up nushell on Mac fails

### ISSUE THREAD

**Issue by kajen3** [nushell/nushell#8383]
### Describe the bug

I'm not able to use `nushell` on Mac. Installation via `homebrew` and setting `nushell` as default shell as described [here](https://www.nushell.sh/book/default_shell.html) raised the following error message ```login: -nushell: Permission denied```.  (Path is `/opt/homebrew/opt/nushell`).

As described [here](https://smallsharpsoftwaretools.com/tutorials/use_modern_bash_on_macos/) I also tried to modify `env/shells`  via ```echo "$(brew --prefix nushell)" | sudo tee -a /etc/shells;``` which successfully added `nushell` to the list of shells, however the same error message appears after opening a new window.

### How to reproduce

1. Run ```brew install nushell```
2. Run ```brew --prefix nushell``` for the path and follow the instructions for Terminal.app (macOS) from [here](https://www.nushell.sh/book/default_shell.html#setting-nu-as-default-shell-on-your-terminal) 
3. Open a new terminal window

### Expected behavior

I expected to be able to use `nushell`.

### Screenshots

<img width="479" alt="Screenshot 2023-03-10 at 10 24 45" src="https://user-images.githubusercontent.com/82041909/224277410-6b81405a-3aba-4ee4-adca-ec97b17a0e2d.png">
<img width="530" alt="Screenshot 2023-03-10 at 10 25 02" src="https://user-images.githubusercontent.com/82041909/224277427-b1180f75-4579-4af5-a916-ba3ff638998e.png">

### Configuration

Arm64 M1 Max
System Version: macOS 13.1 (22C65)
Kernel Version: Darwin 22.2.0
Terminal Version: 2.13 (447)

### Additional context

Same issue appears on a mac with Intel chip.

**Comment by remmycat** [comment]
I think the issue here is that you are using `brew --prefix nushell` (=`/opt/homebrew/opt/nushell`) everywhere.
This is brew's installation folder for nushell, but not the actual executable. The executable is also just called `nu`, not `nushell`.

Assuming that homebrew is correctly configured for you in your existing shell, you can get the path to the `nu` executable with `which nu` instead.
For your installation, this should resolve to `/opt/homebrew/bin/nu`.

**Comment by kajen3** [comment]
Thanks!
