### ISSUE TITLE
New optional cell-path make use of variables harder

### ISSUE THREAD

**Issue by Jan9103** [nushell/nushell#8480]
### Related problem

**This is related to the merged unreleased [MR 8379](https://github.com/nushell/nushell/pull/8379)**

Previous to this change i could do the following:
```
$ let b = "b"
$ {"a": 1} | get -i $b
```

With this change i cant find a way (expect for using a `try`-block) to do this:
```
$ let b = "b"
$ {"a": 1} | get $b?
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #3:1:1]
 1 │ {"a": 1} | get $b?
   ·                  ┬
   ·                  ╰── expected .
   ╰────

$ {"a": 1} | get ($b)?
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #5:1:1]
 1 │ {"a": 1} | get ($b)?
   ·                    ┬
   ·                    ╰── expected .
   ╰────

$ {"a": 1} | get $"($b)"?
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #17:1:1]
 1 │ {"a": 1} | get $"($b)"?
   · ────┬───       ────┬───
   ·     │              ╰── cannot find column 'b"?'
   ·     ╰── value originates here
   ╰────
```

### Describe the solution you'd like

I would appreciate it if one of the following would work:
- `get $b?`
- `get ($b)?`

### Describe alternatives you've considered

`{"a": 1} | try {get ($b)} catch {null}` works, but is a bit chunky in my opinion.

**Comment by rgwood** [comment]
Another option would be to just bring back the `-i` flag. I was thinking it wouldn't be needed after the `?` change, but I wasn't considering the use of variables.

**Comment by rgwood** [comment]
Say the `b` variable is a cell path with multiple members, `foo.bar.baz` (this can't be done right now because the relationship between strings and cell paths is only half baked, but let's pretend it can). In that case, what behaviour do you expect for `get $b?`? Do you expect it to make every path member optional, i.e. something equivalent to `get foo?.bar?.baz?`?

> having `-i` and `?` feels a bit wrong.

I initially thought so, but I've come around to the view that it's useful to have a quick way to make every member in the cell path optional. i.e. `get foo?.bar?.baz?` would be equivalent to `get -i foo.bar.baz`.

**Comment by rgwood** [comment]
Fixed in https://github.com/nushell/nushell/pull/8488
