### ISSUE TITLE
Declaring an unknown external command

### ISSUE THREAD

**Issue by francoisthire** [nushell/nushell#8643]
### Describe the bug

Run the following command:

```nu
export extern "foo" [ ]
```

and then try to run the command `foo`.

You get:

```bash
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #6:1:1]
 1 │ bar
   · ─┬─
   ·  ╰── did you mean 'bar'?
   ╰────
  help: No such file or directory (os error 2)
```

### How to reproduce

Repeat the description above.

### Expected behavior

An error message such as command `foo` unknown or not found.

### Configuration

> version | transpose key value | to md --pretty                                                                     03/27/2023 10:03:48 pm
| key                | value                                      |
| ------------------ | ------------------------------------------ |
| version            | 0.77.1                                     |
| branch             |                                            |
| commit_hash        |                                            |
| build_os           | linux-x86_64                               |
| build_target       | x86_64-unknown-linux-gnu                   |
| rust_version       | rustc 1.69.0-beta.2 (2602aa81a 2023-03-17) |
| rust_channel       | beta-x86_64-unknown-linux-gnu              |
| cargo_version      | cargo 1.69.0-beta.2 (9880b408a 2023-02-28) |
| build_time         | 2023-03-26 19:39:11 +02:00                 |
| build_rust_channel | release                                    |
| features           | default, zip                               |
| installed_plugins  |                                            |

**Comment by stellarpower** [comment]
I have just downloaded 0.79.0. Might be slightly different, but related:

I am brand new to nu, and without realising it was trying to use `join` when this was not installed on my system. the error I get back traces back to the line where I initialised a variable, and does not spit out the name of the external command, which led to quite a confusing scenario:

```nu
let  left = (open  '/tmp/left.csv'  )                                  
let right = (open  '/tmp/right.csv' )                               
$left | join $right columnName columnName
Error: nu::shell::external_command (link)
  × External command failed
   ╭─[entry #23:1:1]
 1 │ let right = (open  '/tmp/right.csv' )  
   ·               ──┬─
   ·                 ╰── Cannot convert record<bus: int, device: int, id: string, description: string, vendorID: string, productID: int> to a string
   ╰────
  help: All arguments to an external command need to be string-compatible  
```

The real problem here is that it is calling e.g. `/bin/join` and thus needs arguments in string form. But nothing is mentioned that tells me this external command is `join`, and the "backtrace" back to the place I opened the file and assigned my variable is rather confusing, implying (to a newcomer) the compiler is somehow trying to go back and run the full set of statements again (I believe nu compiles scripts before executing; some REPLs I have used do not fully interpret and instead recompile over and over).

So perhaps this needs looking at again(?). I think `× External command 'name' failed` would suffice, for example.
