### ISSUE TITLE
Feature: extend nth to take multiple arguments

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#878]
Right now `nth` lets you select a single row to return. I was thinking it would be handy to extend `nth` to work more like `pick`. The `pick` command lets  you pick the columns you want, we could let you pick the rows (rather than a single row) that you want with `nth`.

Eg) `ls | nth 1 2 5`

**Comment by andrasio** [comment]
#900

**Comment by notryanb** [comment]
@jonathandturner I was playing around with creating a `range` command where the user could express something like ` ls | range 3 6` instead of `ls | skip 3 | first 7` (I'm thinking this would be inclusive or have a flag to control that behavior). Would this be better included in the `nth` command where the user writes `ls | nth 3 6 --range` ?

It might be awkward to interpret when you have > 2 parameters as shown in your example.

**Comment by jonathandturner** [comment]
@notryanb - I wonder if we might want to update the parser to support ranges.  I think something like: `ls | nth 3..6` would read a bit better and also let you pass multiple ranges more easily.

cc @wycats for thoughts on parsing

**Comment by notryanb** [comment]
I think a range type would be a better solution from a UI perspective. 

One of the issue I ran up against was error handling, which would be nice to handle at the parser level instead of in the command/plugin. This way we wouldn't have to keep re-implementing checks for negative ranges.
