### ISSUE TITLE
stdlib: complete the test framework

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8819]
waiting for
- https://github.com/nushell/nushell/pull/8815
- https://github.com/nushell/nushell/pull/8776

resolved by
- https://github.com/nushell/nushell/pull/8776
- https://github.com/nushell/nushell/pull/8850
- https://github.com/nushell/nushell.github.io/pull/868

### Related problem
cc/ @presidento 

time to wrap up the testing framework, am i right? :yum: 

> **Note**
> comes from https://github.com/nushell/nushell/issues/8815#issuecomment-1500940506

### Describe the solution you'd like

- make the test runner a part of `std`
- maybe use the following structure?
```
crates/nu-std/lib/
├── testing
│   ├── assert.nu
│   ├── run.nu
│   └── setup.nu
├── dirs.nu
├── ...
└── xml.nu
```

**Comment by presidento** [comment]
I think it is important to be able to load everything from a submodule, I mean something like `use asserts *` to get every `assert` command. (Or similarly, `use logger *`.)

I would rename the `assert` module to `asserts`. (It was its original name, too.) And put the `run` module there with a describing name, like... hm... since Nushell has a [`run-external`](https://www.nushell.sh/commands/docs/run-external.html) command, I would name it `run-tests`. (Although I like more `run external` and `run tests`, but the consistency has more value.)

**Comment by amtoine** [comment]
> I think it is important to be able to load everything from a submodule, I mean something like `use asserts *` to get every `assert` command. (Or similarly, `use logger *`.)
> 
i think it's not possible right now with how the modules are nested :thinking: 
and it was not possible before as everything was in a single module :open_mouth: 

if you try to `use std dirs`, that would give 
```bash
Error: nu::parser::export_not_found

  × Export not found.
   ╭─[entry #1:1:1]
 1 │ use std dirs
   ·         ──┬─
   ·           ╰── could not find imports
   ╰────
```
for instance

**Comment by presidento** [comment]
They had to be in a single module since bb8949f2b27666cf77a8b7b4412b162fed61c49e. I am glad that now they can be again in submodules. (Although they cannot be imported directly.) I agree that in current implementation it is not possible, also I think it would be preferable. Because we are going to have a standard _library_, not a standard _book_. 

I do not want to expand the scope of this issue, you can create another one for discussing how to organize stdlib submodules.

For now I think we have to agree at least in the name of the test runner command.

**Comment by amtoine** [comment]
> They had to be in a single module since [bb8949f](https://github.com/nushell/nushell/commit/bb8949f2b27666cf77a8b7b4412b162fed61c49e). I am glad that now they can be again in submodules. (Although they cannot be imported directly.) I agree that in current implementation it is not possible, also I think it would be preferable. Because we are going to have a standard _library_, not a standard _book_.
> 
:+1: 

> I do not want to expand the scope of this issue, you can create another one for discussing how to organize stdlib submodules.
> 
it's already in the [roadmap](https://github.com/nushell/nushell/issues/8450) under "structuring the library" :wink: 

> For now I think we have to agree at least in the name of the test runner command.
>
`run-tests` is ok for now :+1: 
that's a simple `mv` call and minor find/replace to change this to some other name, so the structure is the main focus :yum:

**Comment by amtoine** [comment]
> Okay. I'll create a PR after #8776 to move the runner into stdlib, named `run-tests`, and I'll update the documentation about testing.
>
coool, looking forward to seing this then :yum:

**Comment by amtoine** [comment]
@presidento 
do you think that this issue will be addressed once https://github.com/nushell/nushell/pull/8850 lands? :yum: 

if you want to work more on the test framework, i can add a task to the description above and we can let this open :wink:

**Comment by presidento** [comment]
Almost, just documentation is needed: https://github.com/nushell/nushell.github.io/pull/868
Then we reach the MVP,  so this will be addressed IMHO.

**Comment by amtoine** [comment]
gotcha, that's great :ok_hand:
