### ISSUE TITLE
Add "traditional" function call syntax

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#9116]
### Related problem

Add "traditional" function call syntax as a solution to the "flag-passing" problem:
```
def func [--bar: int, --flag] { }

def spam [--bar: int, --flag] {
    func  # How to pass --bar and --flag forward?
}
```

Currently, the only solution is to use `if` or `match` to go through all the combinations which quickly gets out of hand with growing number of parameters.

### Describe the solution you'd like

Allow "traditional" function call syntax known from other languages:
```
func(bar: $bar, flag: $flag)
```
If the parameters are named the same, you could use the following shorthand (inspired by https://github.com/SerenityOS/jakt):
```
func($bar, $flag)
```

### Describe alternatives you've considered

This solution intentionally does not provides fully dynamic variable-length arguments in the style of `kwargs` known from Python. "kwargs"-like functionality would bypass signature type checking and it also tends to produce less readable APIs turning the signature into a black box. If you need a fully dynamic parameter, you can pass a record.

For externals, you can use newly allowed blocks to `extern` (https://github.com/nushell/nushell/pull/8956). The variable-length args are stored as strings under `$rest` which makes creating custom wrappers around externals much easier.

We could also use `=` instead of `:`:
```
func(bar: $bar, flag: $flag)
```
vs.
```
func(bar = $bar, flag = $flag)
```
I might lean towards `:` here.

A possible caveat:
```
func($bar, $flag)
```
vs.
```
func ($bar, $flag)
```
In the second case, it would try to call `func` with one subexpression arg which might produce strange errors.

### Additional context and details

The function call syntax also allows nice inlining of calls into expressions: `3 + add-ten(7) + 20` vs. `3 + (add-ten 7) + 20`

Related issues: https://github.com/nushell/nushell/issues/7758 https://github.com/nushell/nushell/issues/7260 https://github.com/nushell/nushell/issues/7033

**Comment by cumber** [comment]
Given that nushell generally does whitespace-separated arguments rather than C-like arguments, using C-like syntax for this one thing feels a little "off" to me. The `func($bar, $flag)` vs `func ($bar, $flag)` caveat is a manifestation of this infelicity.

In a way the `(bar: $bar, flag: $flag)` part of the syntax looks rather like a funny way of writing a record: `{ bar: $bar, flag: $flag }`. So maybe a more fitting way of doing this would be to have special syntax for applying a command to a record. Something like:

```
func @ { bar: $bar, flag: $flag }
```

Some sort of special syntax (like `@`) would be required to distinguish this apply-to-record feature from applying `func` to a single positional argument which happened to be a record. If the "special syntax" we use is to swap the braces for parentheses, we get back to the "traditional function call syntax".

But I wonder, if we see this as an ability to apply a command to a record, rather than merely as unusual syntax required for passing flags, would it be possible to do this with a runtime record value rather than only a record-literal? E.g. would it be possible to implement a feature that would allow:

```
let args = { bar: $bar, flag: $flag }
func @ $args
```

Or even:

```
def wrapper [args] {
  func @ $args
}
```

I would expect the fields accessed in `$args` to be determined by the signature for `func`, and a runtime error if `$args` turns out not to have the required fields (or not to be a record). Much like the behaviour of this:

```
def extract-some-fields [args] {
  [ $args.bar, $args.flag ]
}
```

So if it's possible to tell the signature of `func` at parse time, this wouldn't even necessarily require any more runtime type checking than things like `extract-some-fields` already does.

But if only a static version with record-literals would be possible, then maybe the "traditional-function-call" idea is indeed better, as looking like "real" records could mislead people into trying to use it more dynamically.

**Comment by kubouch** [comment]
These are good points. A problematic aspect of the proposed syntax are:
1. Multi-word commands:
```
spam func(bar: $bar, flag: $flag)
```
or
```
`spam func`(bar: $bar, flag: $flag
```
???
2. Space being significant: `func(bar: $bar, flag: $flag)` vs `func (bar: $bar, flag: $flag)` being two completely different things.

The applying record method is interesting. One important part of the design is to be able to shorten `func(bar: $bar, flag: $flag)` to `func($bar, $flag)` BUT WHAT IF we allowed this shortening for records in general, e.g., `let record = { $bar, $flag }`?

**Comment by cumber** [comment]
@kubouch I would definitely use such shorthand syntax for records in general, yes!

**Comment by cumber** [comment]
@kubouch I suppose using an operator rather than parentheses to indicate that the command is being applied to an argument list rather than normal arguments (whether it's a record or special-purpose argument list syntax) would help the multi-word command case as well? At least I think I would be less confused to see

    spam func @ { bar: $bar, flag: $flag }

than

    spam func(bar: $bar, flag: $flag)

(Especially if there is no permitted space between the `func` and the `(`). My brain just has an easier time reading the operator as "lower precedence" than the grouping of `spam` and `func`.

I don't know whether it would be possible to extend that to allow partially applying a command to some arguments normally and then filling in the rest from a record, but that would be useful too. e.g.

    def func [foo: int, --bar: int, --flag] { }

    let result = func 17 @ { $bar: 29, $flag: false }

I'd imagine that would be added implementation complexity that shouldn't be in the first draft, but it would be cool if it eventually developed that way. It's still all theoretically determinable what it means just from knowledge of the signature of `func`, I think. Maybe some tricky spots with `$rest` arguments. The other way around (partially applying to a record and then filling in more arguments via normal application) would be more problematic, as you'd have to also know the contents of the record to tell how to interpret any following positional arguments.

**Comment by kubouch** [comment]
I think it could all be a record because all signature parameters are named. For example:
```
def foo [x: int, --foo, --bar(b): string, ...rest] { ... }
```
would be called as 
```
foo(x, $foo, bar: ''foo", 1, 2, 4)
# or
foo($x, $foo, bar: ''foo", rest: [ 1 2 4 ])
```
with the traditional syntax or
```
foo @ { $x, $foo, bar: $bar, rest: [ 1 2 4 ] }
```
with your proposed syntax.

The problem with the `@` syntax is that it might not be obvious what it means. Imagine seeing this when you just learned about Nushell:
```
spam @ { $bar, flag: $x }
```
Is it clear enough? To me, definitely less clear than `spam($bar, flag: $x)` . Maybe we could find something more intuitive? For example @pingiun proposed `apply` command some time ago in https://github.com/nushell/nushell/issues/7758#issuecomment-1506840343 that would look like this:
```
apply spam { $bar, flag: $x }
```

**Comment by amtoine** [comment]
i think i like the more *shell*-like feeling of
```
foo @ { $x, $foo, bar: $bar, rest: [ 1 2 4 ] }
spam @ { $bar, flag: $x }
```
or
```
apply foo { $x, $foo, bar: $bar, rest: [ 1 2 4 ] }
apply spam { $bar, flag: $x }
```
compared to the *standard* calling syntax
```
foo($x, $foo, bar: $bar, rest: [ 1 2 4 ])
spam($bar, flag: $x)
```
:thinking:

**Comment by amtoine** [comment]
other ideas to replace `@`
- `foo <- { ... }`
- `foo ^ { ... }`
- `foo % { ... }`

(i prefer `@` :confused:)

**Comment by kubouch** [comment]
One benefit of the functional syntax is also being able to use it directly in expressions without wrapping into `()`:
```
10 + add(3, 7) + 20
```

**Comment by kubouch** [comment]
If we allow "traditional namespace syntax" then, we could write
```
spam::foo($bar, flag: $x)
```
which would solve the subcommand naming problem.

Just throwing ideas here.

**Comment by amtoine** [comment]
these are also nice :thinking:

**Comment by cumber** [comment]
Yeah, `@` was a suggestion with very little thought behind it. It could be a different operator, or a keyword (like `apply`), or any other syntax.

The meat of my idea was to encode the argument list as a standard record, so that the argument list as a whole is a first-class value and you can use any existing tools for working with records to assemble an argument list. That's the main downside of the traditional call syntax; it's dedicated syntax for associating parameter names with argument values, instead of piggy-backing on the syntactic structures we already have for associating names and values.

Also, I think it's easy to overestimate how intuitive the traditional call syntax. It only seems that way because it's common elsewhere, so a lot of people already know it. That's not really inherently intuitive though, it's relying on users already having memorised the notation; *everything* is intuitive once you've memorised it. It wouldn't be obvious to anyone for whom nushell is their *first* programming language. A keyword like `apply` has a claim that the *word* "apply" communicates some of the idea, but using symbols like `(` `)` (or `@`) doesn't; it's just something you have to learn about and memorise.

There's even an argument to be made that the parenthesis-based syntax might be less intuitive than some other arbitrary symbol, since nushell already uses parentheses for other purposes. It's easier for users to learn what syntactic structures do if they always do the same thing (and it prevents issues like needing to use whitespace to distinguish `func ($bar)` from `func($bar)`).

**Comment by cumber** [comment]
> One benefit of the functional syntax we'd lose with is being able to use it directly in expressions without wrapping into `()`:
> 
> ```
> 10 + add(3, 7) + 20
> ```

Why couldn't that work with an operator? It's just a matter of giving it a high enough precedence isn't it?

    10 + add @ { x: 3, y: 7 } + 20

**Comment by kubouch** [comment]
>... because it's common elsewhere, so a lot of people already know it.

This is a very important factor that is easy to underestimate :-D . For a Python beginner who just finished their first tutorial something like `foo(1, 2)` is immediately understandable. Sometimes, not following the common path gives us more leverage -- Nushell is not POSIX after all -- but at the same time following the "rule of least surprise" we try to put as little roadblocks for users as possible.

> Why couldn't that work with an operator? It's just a matter of giving it a high enough precedence isn't it?
> ```
> 10 + add @ { x: 3, y: 7 } + 20
> ```

In this case, `add` would be interpreted as a string value and the rest would fail because it expects an operator after the value. Changing this would cause a ripple effect to the rest of the syntax and we'd have to require all strings to be quoted.

**Comment by kubouch** [comment]
`func x y --flag` is again obvious to anyone who has ever interacted with a CLI tool :-).

If you have a command `printfoo` that takes no parameters, then in `10 + printfoo + 20`  the "printfoo" is still interpreted as a string. That's how the language currently works that bare words in value positions are interpreted as strings. You could enforce a command call with `10 + printfoo() + 20` with the "traditional" syntax. The `@` syntax would need something similar: `10 + printfoo @ {} + 20`. Maybe would be clearer without the spaces: `10 + printfoo@{} + 20`, not sure.

Also, going back to your original message, the records would need to be record literals, or maybe `const`, but you wouldn't have the full flexibility of Python's kwargs. Even having `const` record could create confusing situations:
```
const args = { bar: $bar, flag: $flag }

# ... 100 lines later:

func @ $args  # what is args, I forgot...
```
It could make the code less readable. Fully dynamic kwargs were recently dismissed as they can create very confusing APIs. If you need a full Python-like kwargs, you could just pass the record itself as a parameter.

It's an interesting idea, though. The traditional call syntax still suffers from the space problem (`foo($bar)` vs `foo ($bar)`), so no solution is without drawbacks.

**Comment by cumber** [comment]
"100 lines later, what is $foo I forgot" goes for *any* variable, it has nothing to do with this specific usage. You can't avoid confusion for users by denying them any features that could possibly be confusing! Not unless you give them a system that does nothing.

I saw that having a kwargs-style parameter for **receiving** arguments had already been discussed and rejected, but that's not what I'm proposing. Python has **two** syntactic features you might call "kwargs" and they're actually independent; don't confuse them.

Receiving kwargs would mean the function is *defined* like `def foo [**kwargs] {...}` and then called with the ordinary `foo --x=13 --y=hello` syntax, and inside `foo` you would have `$kwargs` bound to `{ x: 13, y: "hello" }`. I agree this would be a bad idea; it means any call has to be closely coupled to the implementation of the command (because that's what determines which parameters it will examine in the `$kwargs` record, which is its actual interface), basically requiring fragile and hard-to-understand code. And as you point out, taking an untyped record parameter is equivalent anyway. Any API that **needs** this flexibility can already be written in Nushell today. Receiving kwargs would only provide the minor syntactic shortcut of letting you fill a dynamic structure (a record) from a static argument list. `--foo=1 --bar=$whatever` contains the exact same information as `{ foo: 1, bar: $whatever }`, and it's only 3 characters shorter!

What I'm proposing is the other way around. I want kwargs-style specification of arguments I'm *passing*, not ones I'm receiving. I want to work with things defined like `def foo [x : int, y : string] {...}` where the arguments it takes are fully specified as normal, with no confusing dynamic API. I just want call `foo` as `foo @ $args` if `$arg` is of type `record<x: int, y: string>`. This would give me flexibility to dynamically assemble a call to an ordinary pre-defined command, something that *is* a new capability (unlike receiving kwargs). The alternative is writing a wrapper for every command I want to call this way that takes all the same parameters as fields of a single record and then properly extracts them and passes them as normal arguments; this can be a *lot* of extra boiler plate if the command has a lot of parameters, and it has to be updated to stay in sync. Passing kwargs allows us to *avoid* this extra fragile code.

Note you can already do this in Nushell today:

```
def foo [rec : record<x: int, y: string>] { echo $rec }

let kwargs = { x: 13, y: hello }

foo $kwargs
```

So it clearly **is** possible for Nushell to check a dynamic record against the signature of a command, without it being a const. All that is required is a way to say "match a command's signature against the fields of a record instead of a hard-coded list of arguments". That would give the ability to use this flexibility on all existing commands, instead of requiring them all to be rewritten to take a single record.

The traditional-style function call syntax is just another way of writing a static list of arguments. If it weren't for the fact that the CLI style way of writing a static list of arguments doesn't provide any way to pass the value of a boolean flag from a variable, then implementing the traditional syntax would gain absolutely no capability. (Even the ability to avoid parentheses around a call in the middle of an expression isn't really a benefit, since you need to add parentheses around the argument list in the call instead! `10 + printfoo() + 20` is exactly the same characters as `10 + (printfoo) + 20`, just in a different order). If that very minor capability is all we're getting, I personally would prefer we just fixed it so that `--flag=$var` worked, instead of boolean flags ignoring an explicitly passed value. That would be a much smaller change, no dual-syntax to confuse users, no space issue, no drawbacks that I can think of at all.

**Comment by dedebenui** [comment]
I'm on board with the `@` syntax. It's a bit tricky to work with positional arguments though since users are not expected to know their internal names. How about flipping the `@` syntax to work more like a pipe?

```
let result = { $bar: 29, $flag: false } @ func 17
```

This has two benefits in my view:

1. the pipe-like syntax is already familiar. It's easy to learn.
2. positional arguments still come after the piped function, as is the case with normal pipes

If `@` takes precedence over `|`, working in conjunction with normal pipes is fine too. Putting all together:

```
let flags = { $bar: 29, $flag: false }
glob * | $flags @ func 17
```

**Comment by amtoine** [comment]
@bew 
i just tried and the following already works without the spread operator :yum:
```nushell
let global_opts = [--no-pager]
let rest = [--graph --oneline --decorate]

git $global_opts log $rest
```

**Comment by bew** [comment]
> the following already works without the spread operator 😋
> 
> ```nushell
> let global_opts = [--no-pager]
> let rest = [--graph --oneline --decorate]
> 
> git $global_opts log $rest
> ```

Well that would be a solution for the first part 🤔
Why does it work? Does the parser detects if the target command is an external one?

Although to me this is not something that should happen automagically.

From a readability point of view it doesn't feel right, because the implicit spread is not predictable, unless you know that the command you're passing this into is an external command.
Having to explicitly spread the args would be more predictable and easy to read and understand.

**Comment by bew** [comment]
Allright 👌
What about the rest of my brain dump, do you have thoughts on this kind of mini-framework to define and manipulate args in a structured way? 🤔

**Comment by amtoine** [comment]
> Allright 👌 What about the rest of my brain dump, do you have thoughts on this kind of mini-framework to define and manipulate args in a structured way? 🤔
>
not sure i see what you mean :confused: 

ohh, the big post of yours above?! let me have another look :wink:

**Comment by amtoine** [comment]
@bew 
interesting idea but i'm not sure what hole in the current arg syntax these new types would fill :confused: 
i must have missed it but it looks to me like all the more complex examples using `arg flag` can already be done natively?

**Comment by kubouch** [comment]
Because the `()` syntax looks too much like a subexpression, I think adding this would add too much confusion. The “flag-passing” problem is largely solved by allowing flags to take boolean parameters, like `--flag=$value`.

Let's try not to have two ways to do the same thing, I think we can close it for now.
