### ISSUE TITLE
Requesting a Matrix group.

### ISSUE THREAD

**Issue by Absinthe8383** [nushell/nushell#9367]
I am requesting a matrix group for the folks who don't use discord and might want to ask question. It is easy to bridge, so won't have any problem.

**Comment by fdncred** [comment]
has been ask for before and we decided against it because it meant the people supporting nushell would have to live in both communities. it's hard enough to get volunteers to support people in one community (actually 2, discord and github), but adding another is just kind of a lot of work and perhaps too much to ask people for.

interested how others feel

**Comment by fdncred** [comment]
We may have been on matrix originally like 2019-ish. I don't know. We also tried zulip. I'm on matrix right now looking around.

**Comment by Absinthe8383** [comment]
> We may have been on matrix originally like 2019-ish. I don't know. We also tried zulip. I'm on matrix right now looking around.

matrix has grown ever since, so It might be good to give it a try again.

**Comment by jntrnr** [comment]
Going to close this - discord is really our main effort. We've tried doing discord + <something else> in the past and it just doesn't work well. Until we have a good reason to leave discord, let's stick with it and focus on growing the community there.
