### ISSUE TITLE
Should `rm` recycle by default?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#941]
from reddit:

"Wouldn't it be prudent to invert the behavior, rm sends to the trash by default and rm --no-backsies does a non-recoverable delete?"

**Comment by alteous** [comment]
From the Art of Unix Programming, 'file deletion is irrevocable' is listed under the 'What Unix Gets Wrong' section:

http://catb.org/~esr/writings/taoup/html/ch01s04.html

**Comment by t-hart** [comment]
Hmm, so `rm`  would send to a recoverable trash can by default? 

In my opinion, that'd be surprising in a bad way. I can't remember the last time I wanted to move anything to the trash upon deletion and it's a very different practice from what I'm used to. 

Naturally, that it's different isn't a bad thing, though the principle of least surprise is a thing. That said, for people used to how it works through the GUI on Windows and macOS might find it surprising that it's irrevocable.

Having the option is nice, but making it the default feels strange to me.

**Comment by Aloso** [comment]
I'd like to have a global configuration option.

- If it's enabled, `rm` moves the file to trash, and `rm --permanent` deletes it
- If it's disabled, `rm` deletes the file, and `rm --trash` moves it to the trash

**Comment by thegedge** [comment]
Config value sounds 👍

**Comment by Kelli314** [comment]
I'd like to work on this.

**Comment by filalex77** [comment]
Hey @Kelli314, sorry - I didn't see your comment when I started working on #1869.
Please feel free to add any input on my PR - I'd be more than happy to add you as a co-author.
Sorry once again, didn't mean to steal it from you 😅

**Comment by thegedge** [comment]
I've thought about this more, and I don't think we should do this. Should we add a config value so that `ls` is always `--full` by default? Maybe `which` should always have `--all`? You can see where I'm going with this. By adding a config value here, we're setting a precedent, which I think is the wrong one.

So what _should_ we do?

What I'd really love to be able to do is alias an builtin command. If we supported that, and "rest args", we wouldn't need a config value here, but could rather do this:

```
alias rm [$args] { rm --trash $args }
```

I do this a ton in my bash and zsh configuration. The reason I have a preference for this over config is because it a) keeps the codebase as simple as possible by building on simpler "units", b) is one less thing one has to remember, and c) once you know you can do this, you can apply this to every command.

**Comment by thegedge** [comment]
I've created https://github.com/nushell/nushell/issues/1884 and https://github.com/nushell/nushell/issues/1885 to work towards the suggestion above. I think those are the key pieces that are currently missing.
