### ISSUE TITLE
scripts do not take `$in` as input

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#9460]
### Describe the bug

it appears a Nushell script cannot have input data being piped in :thinking: 

### How to reproduce

1. save the following in `foo.nu`
```nushell
#!/usr/bin/env nu

def main [arg?: any] {
    print $"in: ($in)"
    print $"arg: ($arg)"
}
```
2. make it executable with something like `chmod +x foo.nu`
3. run `"foo" | ./foo.nu "bar"`

see the output is 
```bash
in:
arg: bar
```

### Expected behavior

i expect the output to be
```bash
in: foo
arg: bar
```

> **Note**
> this works fine in the REPL
> ```nushell
> def foo [arg?: any] {
>     print $"in: ($in)"
>     print $"arg: ($arg)"
> }
> ```
> and then
> ```nu
> > "foo" | foo "bar"
> in: foo
> arg: bar
> ```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.81.1                                   |
| branch             | main                                     |
| commit_hash        | a5dd93d1543da1b5ea47b93591c41a8997b20bb4 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)      |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)      |
| build_time         | 2023-06-08 20:55:16 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I think you're right.

Just sharing these things below, although it's not what you want.
```
❯ source foo.nu
❯ "foo" | main bar
in: foo
arg: bar
```
This also works, which I've always found it a bit odd syntax.
```
❯ cat foo.nu
#!/usr/bin/env nu

def main [] {
    | str upcase
}
❯ source foo.nu
❯ "foo" | main
FOO
```
So, it looks like custom commands can handle data piped into them, but that information isn't getting passed or heard when doing it the way your issue describes.

**Comment by amtoine** [comment]
> So, it looks like custom commands can handle data piped into them, but that information isn't getting passed or heard when doing it the way your issue describes.
>
yup something like this :open_mouth:

**Comment by dev-cyprium** [comment]
This seems to be a bug inside the `parse` function in the `nu-parser` crate. I'm afraid I wasn't able to track issue more precisely, but these are my findings for someone to tackle this problem.

https://github.com/nushell/nushell/blob/main/src/main.rs#L283

`run_file` is being called, but getting `None` as the `input` passed. Which means, no `stdin` data was parsed. 
Tracing the problem further:

https://github.com/nushell/nushell/blob/main/src/main.rs#L244
```rust
let input = if let Some(redirect_stdin) = &parsed_nu_cli_args.redirect_stdin {
        let stdin = std::io::stdin();
        let buf_reader = BufReader::new(stdin);

        PipelineData::ExternalStream {
        ...
        }
    } else {
        PipelineData::empty()
    };
```

And going beyond that, simply it all falls on this line: https://github.com/nushell/nushell/blob/main/src/command.rs#L93
```rust
let redirect_stdin = call.get_named_arg("stdin");
```

But, the `call` itself is being generated by the `parse` function like I mentioned which is beyond my understanding of the logic, as that is the most complex code that deals with AST. 

One way I was able to roughly "fix" this bug is by hard-coding `stdin` flag getting, which fixes the issue, but it's not a long term solution. The proper fix would require to find a proper place and populate this flag correctly. (Which is where `stdin` is flag is being set, which I wasn't able to find)

I suggest looking in here for this: https://github.com/nushell/nushell/tree/main/crates/nu-parser

**Comment by amtoine** [comment]
thanks for compiling all this and where the culprit looks to be :pray:

**Comment by tv42** [comment]
This might be a duplicate of #9373: "scripts can't operate as part of a pipeline"

**Comment by amtoine** [comment]
another episode of my duplicating my own issues when i'm annoyed by something :laughing: 
closing in favor of #9373 which was there before :+1:
